BMLT Root Server: c_comdef_formats Class Reference
c_comdef_formats Class Reference
Include the format class.
Public Member Functions
__construct ($in_parent_obj, $in_array)
Constructor. Sets the parent object.
GetFormatsArray ()
Accessor -Get the format object array.
GetFormatByKeyAndLanguage ($in_format_key, $in_lang_enum=null)
Return a reference to a single object, by format key and language.
GetFormatBySharedIDCodeAndLanguage ($in_shared_id_bigint, $in_lang_enum=null)
Return a reference to a single object, by shared ID and language.
GetFormatsBySharedIDCode ($in_shared_id_bigint)
Return all the formats that share a given shared ID code.
GetFormatsByLanguage ($in_lang_enum=null)
Return all the formats that share a given language.
GetFormatsByString ($in_string, $in_lang_enum=null)
Return all the formats that contain the given string.
SetParentObj ($in_parent_obj)
Set the parent object of this instance.
GetParentObj ()
Return a reference to the parent object of this instance.
Private Attributes
$_local_id_parent_obj = null
This is the parent (container) object that holds this instance.
$_local_copy_of_array = null
Detailed Description
Include the format class.
A Class for Aggregating Format Codes
This class acts as an array aggregator for c_comdef_format objects. It is a class unto itself, because we want to have a couple of additional filtering options (like the ability to get a bunch of formats that share a _shared_id_bigint code).
The formats are kept in a simple two-dimensional array:
$_local_copy_of_array = array[$lang_enum][$shared_id_bigint]
The combination of shared ID and language needs to be unique. This is how we match formats to languages. The same shared ID is used throughout the system, and we use the localization to return its key and description in the appropriate language.
Definition at line 50 of file c_comdef_formats.class.php.
Constructor & Destructor Documentation
__construct()
__construct ($in_parent_obj, $in_array)
Constructor. Sets the parent object.
Definition at line 66 of file c_comdef_formats.class.php.
       {
         $this->SetParentObj($in_parent_obj);
         $this->_local_copy_of_array = $in_array;
     }
Member Function Documentation
GetFormatByKeyAndLanguage()
GetFormatByKeyAndLanguage ($in_format_key, $in_lang_enum = null)
Return a reference to a single object, by format key and language.
You do not need to provide a language, in which case, the server's local language is used.
Returns
A reference to the single selected object.
If no language is given, we use the server's native language.
Parameters
$in_format_key This is the shared ID code.
$in_lang_enum This is the code for the desired language. If not given, the server localization will be used.
Definition at line 96 of file c_comdef_formats.class.php.
References c_comdef_server\GetServer().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         /// If no language is given, we use the server's native language.
         if (null == $in_lang_enum) {
             $in_lang_enum = $this->GetParentObj()->GetLocalLang();
         }
         if (!$in_lang_enum) {
             $in_lang_enum = c_comdef_server::GetServer()->GetLocalLang();
         }
         // Should never happen.
         if (!$in_lang_enum) {
             $in_lang_enum = "en";
         }
         if (isset($this->_local_copy_of_array[$in_lang_enum]) && is_array($this->_local_copy_of_array[$in_lang_enum]) && count($this->_local_copy_of_array[$in_lang_enum])) {
             foreach ($this->_local_copy_of_array[$in_lang_enum] as &$format) {
                 if ($in_format_key == $format->GetKey()) {
                     return $format;
                 };
             }
         }
         return null;
     }
GetFormatBySharedIDCodeAndLanguage()
GetFormatBySharedIDCodeAndLanguage ($in_shared_id_bigint, $in_lang_enum = null)
Return a reference to a single object, by shared ID and language.
You do not need to provide a language, in which case, the server's local language is used.
Returns
A reference to the single selected object.
If no language is given, we use the server's native language.
Parameters
$in_shared_id_bigint This is the shared ID code.
$in_lang_enum This is the code for the desired language. If not given, the server localization will be used.
Definition at line 136 of file c_comdef_formats.class.php.
References c_comdef_server\GetServer().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         /// If no language is given, we use the server's native language.
         if (null == $in_lang_enum) {
             $in_lang_enum = $this->GetParentObj()->GetLocalLang();
         }
         if (!$in_lang_enum) {
             $in_lang_enum = c_comdef_server::GetServer()->GetLocalLang();
         }
         // Should never happen.
         if (!$in_lang_enum) {
             $in_lang_enum = "en";
         }
         if (isset($this->_local_copy_of_array[$in_lang_enum][$in_shared_id_bigint])) {
             return $this->_local_copy_of_array[$in_lang_enum][$in_shared_id_bigint];
         }
     }
GetFormatsArray()
GetFormatsArray ()
Accessor -Get the format object array.
Returns
a reference to an array of c_comdef_format objects.
Definition at line 80 of file c_comdef_formats.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_local_copy_of_array;
     }
GetFormatsByLanguage()
GetFormatsByLanguage ($in_lang_enum = null)
Return all the formats that share a given language.
You do not need to provide a language, in which case, the server's local language is used.
Returns
A simple array of references to the objects for the formats in the given language. Null if no formats fit the language.
If no language is given, we use the server's native language.
Parameters
$in_lang_enum This is the code for the desired language. If not given, the server localization will be used.
Definition at line 194 of file c_comdef_formats.class.php.
References $ret.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         /// If no language is given, we use the server's native language.
         if (null == $in_lang_enum) {
             $in_lang_enum = $this->GetParentObj()->GetLocalLang();
         }
         if (isset($this->_local_copy_of_array) && is_array($this->_local_copy_of_array) && isset($this->_local_copy_of_array[$in_lang_enum]) && is_array($this->_local_copy_of_array)) {
             $ret = $this->_local_copy_of_array[$in_lang_enum];
         }
         return $ret;
     }
GetFormatsBySharedIDCode()
GetFormatsBySharedIDCode ($in_shared_id_bigint)
Return all the formats that share a given shared ID code.
Returns
A simple array of references to the objects for the formats in all languages for the given shared ID. Null if no formats fit the language.
Parameters
$in_shared_id_bigint This is the shared ID code.
Definition at line 167 of file c_comdef_formats.class.php.
References $ret.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         foreach ($this->_local_copy_of_array as $lang) {
             foreach ($lang as $id) {
                 if ($id->GetSharedID() == $in_shared_id_bigint) {
                     $ret[$id->GetLocalLang()] = $id;
                 }
             }
         }
         return $ret;
     }
GetFormatsByString()
GetFormatsByString ($in_string, $in_lang_enum = null)
Return all the formats that contain the given string.
If the language is English or Spanish, this does a metaphone search of all all the strings in the "en" or "es" formats. If it is any other language, then a simple string search is performed.
Returns
A simple array of references to the objects for the formats in all languages for the given string. Null if no formats fit.
If no language is given, we use the server's native language.
We force the search to happen in lowercase. This is a very basic search.
If we will use metaphone, we convert our search criteria to metaphone keys.
We will look in each of the text fields for our string.
Parameters
$in_string This is the string to search for.
$in_lang_enum This is the code for the desired language. If not given, the server localization will be used.
Definition at line 223 of file c_comdef_formats.class.php.
References $ret, and SplitIntoMetaphone().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         /// If no language is given, we use the server's native language.
         if (null == $in_lang_enum) {
             $in_lang_enum = $this->GetParentObj()->GetLocalLang();
         }
         /// We force the search to happen in lowercase. This is a very basic search.
         $in_string = strtolower($in_string);
         /// If we will use metaphone, we convert our search criteria to metaphone keys.
         $in_string_comp = SplitIntoMetaphone($in_string, $in_lang_enum);
         $count = 0;
         $iterating_target = $this->GetFormatsByLanguage($in_lang_enum);
         foreach ($iterating_target as $id) {
             $found = false;
             /// We will look in each of the text fields for our string.
             $string = $id->GetKey();
             $comp = SplitIntoMetaphone($string, $in_lang_enum);
             foreach ($in_string_comp as $test) {
                 if (array_search($test, $comp)) {
                     $found = true;
                     break;
                 }
             }
             if (!$found) {
                 $string = $id->GetLocalName();
                 $comp = SplitIntoMetaphone($string, $in_lang_enum);
                 foreach ($in_string_comp as $test) {
                     if (array_search($test, $comp)) {
                         $found = true;
                         break;
                     }
                 }
             }
             if (!$found) {
                 $string = $id->GetLocalDescription();
                 $comp = SplitIntoMetaphone($string, $in_lang_enum);
                 foreach ($in_string_comp as $test) {
                     if (array_search($test, $comp)) {
                         $found = true;
                         break;
                     }
                 }
             }
             if ($found) {
                 $ret[$count++] = $id;
             }
         }
         return $ret;
     }
GetParentObj()
GetParentObj ()
Return a reference to the parent object of this instance.
Returns
a reference to the parent instance of the object.
Implements i_comdef_has_parent.
Definition at line 310 of file c_comdef_formats.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_local_id_parent_obj;
     }
SetParentObj()
SetParentObj ($in_parent_obj)
Set the parent object of this instance.
Parameters
$in_parent_obj A reference to the parent object.
Implements i_comdef_has_parent.
Definition at line 296 of file c_comdef_formats.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_local_id_parent_obj = null;
         $this->_local_id_parent_obj = $in_parent_obj;
     }
Member Data Documentation
$_local_copy_of_array
$_local_copy_of_array = null private
We keep a local copy of the simple array, because we can instantly access it, as opposed to having to instantiate iterators.
Definition at line 61 of file c_comdef_formats.class.php.
$_local_id_parent_obj
$_local_id_parent_obj = null private
This is the parent (container) object that holds this instance.
Definition at line 55 of file c_comdef_formats.class.php.
The documentation for this class was generated from the following file:
/Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/server/classes/c_comdef_formats.class.php