BMLT Root Server: /home/travis/build/bmlt-enabled/bmlt-root-server/main_server/server/shared/Array2Json.php File Reference
Array2Json.php File Reference
Functions
array2json ($arr)
Encodes a given associative array into a JSON object string.
Function Documentation
array2json ($arr)
Encodes a given associative array into a JSON object string.
Returns
a JSON object, as a string.
Parameters
$arr An associative string, to be encoded as JSON.
Definition at line 41 of file Array2Json.php.
Referenced by c_comdef_admin_ajax_handler\HandleAccountChange(), parse_redirect(), c_comdef_admin_ajax_handler\TranslateToJSON(), TranslateToJSON(), and whitespace_warnings().
   {
     $parts = array();
     // See if we are an associative array.
     $is_list = (count(array_filter(array_keys($arr), 'is_numeric')) == count($arr)) && (array_keys($arr) === range(0, count($arr) - 1));
     foreach ($arr as $key => $value) {
         if (is_array($value) && count($value)) { //Custom handling for arrays
             if ($is_list) {
                 $parts[] = array2json($value); /* :RECURSION: */
             } else {
                 $parts[] = '"' . $key . '":' . array2json($value); /* :RECURSION: */
             }
         } else {
             $str = '';
             if ($key === 'json_data') {  // JSON data is passed through without any vetting or modification (so it can easily bork the stream).
                 $str = '"'.$key.'":'.$value;
             } else {
                 if (!$is_list) {
                     $str = '"' . $key . '":';
                 }
                 //Custom handling for multiple data types
                 if (isset($value)) {
                     if (is_integer($value)) {
                         $str .= $value;
                     } elseif (is_bool($value)) {
                         $str .= $value ? 'true': 'false';
                     } else {
                         $str .= '"' . trim(json_encode(str_replace('"', '&quot;', $value), JSON_UNESCAPED_SLASHES), '"') . '"'; //All other things
                     }
                 } else {
                     $str .= '""'; //All other things
                 }
             }
             // :TODO: Is there any more datatype we should be in the lookout for? (Object?)
             $parts[] = $str;
         }
     }
     $json = implode(',', $parts);
     if ($is_list) {
         return '[' . $json . ']'; //Return numerical JSON
     } else {
         return '{' . $json . '}'; //Return associative JSON
     }
 }