BMLT Root Server: c_comdef_format Class Reference
c_comdef_format Class Reference
A Class for Format Codes.
Public Member Functions
UpdateToDB ($is_rollback=false)
Updates the DB to the current values of this instance. (replacing current values of the DB).
DeleteFromDB_NoRecord ()
Deletes this instance from the database without recording it.
DeleteFromDB ()
Deletes this instance from the database.
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
__construct ($in_parent_obj, $in_shared_id_bigint=null, $in_format_type_string=null, $in_key_string=null, $in_icon_blob=null, $in_worldid_mixed=null, $in_lang_enum=null, $in_name_string=null, $in_description_string=null)
The initial setup call for the class. If you send in values, the object will set itself up to use them.
SetSharedID ($in_shared_id_bigint)
Accessor -Set the shared ID.
GetSharedID ()
Accessor -Get a reference to the shared ID.
SetFormatType ($in_format_type_string)
Accessor -Sets the format type code.
& GetFormatType ()
Accessor -Returns a reference to the format type code.
SetKey ($in_key_string)
Accessor -Sets the format key (the 1-3 letter code that represents the format).
& GetKey ()
Accessor -Returns a reference to the _key_string data member.
SetIcon ($in_icon_blob)
Accessor -Sets a 64-pixel-square image (as a GIF), to be used to indicate the format.
& GetIcon ()
Accessor -Returns a reference to the _icon_blob data member.
SetFormatCodes ($in_format_code_array)
Accessor -Sets a brief description string for the format, in whatever language has been selected.
& GetFormatCodes ()
Accessor -Returns a reference to the _format_codes data member.
SerializeObject ()
Returns a storable serialization of the object, as a string.
UserCanEdit ($in_user_object=null)
Test to see if a user is allowed to edit an instance (change the data).
Public Member Functions inherited from t_comdef_world_type
SetWorldID ($in_worldid_mixed)
Accessor -Sets the _world_type_worldid_mixed data member.
GetWorldID ()
Accessor -Returns a reference to the _world_type_worldid_mixed data member.
Public Member Functions inherited from t_comdef_local_type
SetLocalLang ($in_lang_enum=null)
Sets the language.
GetLocalLang ()
Returns a reference to the local language setting.
SetLocalName ($in_name_string)
Accessor -Sets the _local_type_name_string data member.
GetLocalName ()
Accessor -Returns a reference to the _local_type_name_string data member.
SetLocalDescription ($in_description_string)
Accessor -Sets the _local_type_desc_string data member.
GetLocalDescription ()
Accessor -Returns a reference to the _local_type_desc_string data member.
Public Member Functions inherited from t_local_id_class
SetParentObj ($in_parent_obj)
Sets the object's "parent" (Container) object, as a reference.
GetParentObj ()
Returns a reference to the object's container.
Public Member Functions inherited from i_comdef_db_stored
UpdateToDB ()
This causes the object to update the database to its current state.
Static Public Member Functions
static UnserializeObject ($in_parent, $serialized_array)
This takes the serialized data, and instantiates a new object from it.
Public Attributes
$_shared_id_bigint = null
The shared ID (for multiple instances of the same format code).
$_format_type_string = null
This is the type of format.
$_key_string = null
The Format Key, in Text Form.
$_icon_blob = null
The Format Icon, as a 64-pixel-square Icon, in GIF format.
$_format_codes = null
This will be an array of the format types (localized).
Detailed Description
A Class for Format Codes.
This class handles the model for the NA Meeting Format Codes. The codes are stored one code per language per instance of this class. If codes are related (Same code, different languages), then you should give them all the same shared ID.
Definition at line 37 of file c_comdef_format.class.php.
Constructor & Destructor Documentation
__construct()
__construct ($in_parent_obj, $in_shared_id_bigint = null, $in_format_type_string = null, $in_key_string = null, $in_icon_blob = null, $in_worldid_mixed = null, $in_lang_enum = null, $in_name_string = null, $in_description_string = null)
The initial setup call for the class. If you send in values, the object will set itself up to use them.
This is the server language.
Should never be necessary.
This gets us the format codes, with their localized descriptions.
Parameters
$in_parent_obj The object that "owns" this instance.
$in_shared_id_bigint The shared ID (If this is the same as other formats -used for different languages).
$in_key_string The format Key, as a text string (1-3 Characters).
$in_icon_blob The format icon, as 64-pixel-square GIF image data.
$in_worldid_mixed The t_comdef_world_type Class: The NAWS ID for this format (can be the same as other format IDs)
$in_lang_enum The t_comdef_local_type Class The language to be used for this instance (if null, the server language is used).
$in_name_string The name of this instance
$in_description_string A verbose description
Definition at line 280 of file c_comdef_format.class.php.
References $comdef_global_language.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         global  $comdef_global_language;
         /// This is the server language.
         if (null == $in_lang_enum) {
             $in_lang_enum = $comdef_global_language;
         }
         /// Should never be necessary.
         if (null == $in_lang_enum) {
             $in_lang_enum = "en";
         }
         $this->SetSharedID($in_shared_id_bigint);
         $this->SetFormatType($in_format_type_string);
         $this->SetKey($in_key_string);
         $this->SetIcon($in_icon_blob);
         $this->SetParentObj($in_parent_obj);
         $this->SetLocalLang($in_lang_enum);
         $this->SetLocalName($in_name_string);
         $this->SetLocalDescription($in_description_string);
         $this->SetWorldID($in_worldid_mixed);
         /// This gets us the format codes, with their localized descriptions.
 //      $file_path = dirname ( __FILE__ ).'/../../local_server/server_admin/lang/'.$in_lang_enum.'/format_codes.inc.php';
 //
 //      require ( $file_path );
 //
 //      $this->SetFormatCodes ( $comdef_format_types );
     }
Member Function Documentation
DeleteFromDB()
DeleteFromDB ()
Deletes this instance from the database.
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 197 of file c_comdef_format.class.php.
References $ret, c_comdef_server\AddNewChange(), c_comdef_server\GetCurrentUserObj(), and c_comdef_server\GetOneFormat().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             // We take a snapshot of the user as it currently sits in the database as a "before" image.
             $before = null;
             $before_id = null;
             $before_lang = null;
             $before_obj = c_comdef_server::GetOneFormat($this->GetSharedID(), $this->GetLocalLang());
             if ($before_obj instanceof c_comdef_format) {
                 $before = $before_obj->SerializeObject();
                 $before_id = $before_obj->GetSharedID();
                 $before_lang = $before_obj->GetLocalLang();
                 $before_obj = null;
             }
             $ret = $this->DeleteFromDB_NoRecord();
             if ($ret) {
                 c_comdef_server::AddNewChange($user->GetID(), 'comdef_change_type_delete', $this->GetSharedID(), $before, null, 'c_comdef_format', $before_id, null, $before_lang, null);
             }
         }
         return $ret;
     }
DeleteFromDB_NoRecord()
DeleteFromDB_NoRecord ()
Deletes this instance from the database without recording it.
Returns
true, if the delete was successful. False, otherwise.
Exceptions
a PDOException if there is a problem.
Definition at line 167 of file c_comdef_format.class.php.
References $_COMDEF_DEBUG, $ret, and c_comdef_dbsingleton\preparedExec().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         if ($this->UserCanEdit()) {
             try {
                 $sql = "DELETE FROM `".c_comdef_server::GetFormatTableName_obj()."` WHERE shared_id_bigint=? AND lang_enum=?";
                 c_comdef_dbsingleton::preparedExec($sql, array ( $this->GetSharedID(), $this->GetLocalLang() ));
                 $ret = true;
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_format::DeleteFromDB_NoRecord()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
GetFormatCodes()
& GetFormatCodes ()
Accessor -Returns a reference to the _format_codes data member.
Returns
The _format_codes data member, as a reference.
Definition at line 453 of file c_comdef_format.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_format_codes;
     }
GetFormatType()
& GetFormatType ()
Accessor -Returns a reference to the format type code.
Returns
The _format_type_string data member, as a reference.
Definition at line 381 of file c_comdef_format.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_format_type_string;
     }
GetIcon()
& GetIcon ()
Accessor -Returns a reference to the _icon_blob data member.
Returns
The _icon_blob data member, as a reference.
Definition at line 429 of file c_comdef_format.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_icon_blob;
     }
GetKey()
& GetKey ()
Accessor -Returns a reference to the _key_string data member.
Returns
The _key_string data member, as a reference.
Definition at line 405 of file c_comdef_format.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_key_string;
     }
GetSharedID()
GetSharedID ()
Accessor -Get a reference to the shared ID.
Returns
The _shared_id_bigint data member, as a reference.
Definition at line 353 of file c_comdef_format.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_shared_id_bigint;
     }
RestoreFromDB()
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 235 of file c_comdef_format.class.php.
References $_COMDEF_DEBUG, and c_comdef_dbsingleton\preparedQuery().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         try {
             $sql = "SELECT * FROM `".c_comdef_server::GetFormatTableName_obj()."` WHERE shared_id_bigint=? AND lang_enum=?";
             $vals = array ( intval($this->GetLocalID(), $this->GetLocalLang()) );
             $rows = c_comdef_dbsingleton::preparedQuery($sql, $vals);
             if (is_array($rows) && count($rows)) {
                 $this->SetSharedID($rs['shared_id_bigint']);
                 $this->SetFormatType($rs['format_type_enum']);
                 $this->SetKey($rs['key_string']);
                 $this->SetIcon($rs['icon_blob']);
                 $this->SetWorldID($rs['worldid_mixed']);
                 $this->SetLocalLang($rs['lang_enum']);
                 $this->SetLocalName($rs['name_string']);
                 $this->SetLocalDescription($rs['description_string']);
             } else {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_format::RestoreFromDB()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_format::RestoreFromDB()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
     }
SerializeObject()
SerializeObject ()
Returns a storable serialization of the object, as a string.
This is only used for the changes, as the serialized string may not be easily searched.
Returns
an array, containing the object in serialized form.
Implements i_comdef_serialized.
Definition at line 468 of file c_comdef_format.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $s_array['shared_id_bigint'] = $this->GetSharedID();
         $s_array['format_type_string'] = $this->GetFormatType();
         $s_array['key_string'] = $this->GetKey();
         $s_array['icon_blob'] = $this->GetIcon();
         $s_array['worldid_mixed'] = $this->GetWorldID();
         $s_array['lang_enum'] = $this->GetLocalLang();
         $s_array['name_string'] = $this->GetLocalName();
         $s_array['description_string'] = $this->GetLocalDescription();
         return serialize($s_array);
     }
SetFormatCodes()
SetFormatCodes ($in_format_code_array)
Accessor -Sets a brief description string for the format, in whatever language has been selected.
< Make sure we copy it.
Parameters
$in_format_code_array An associative array, with the format codes.
Definition at line 439 of file c_comdef_format.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_format_codes = null;
         $this->_format_codes = $in_format_code_array;   ///< Make sure we copy it.
     }
SetFormatType()
SetFormatType ($in_format_type_string)
Accessor -Sets the format type code.
Definition at line 363 of file c_comdef_format.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_format_type_string = null;
         $this->_format_type_string = $in_format_type_string;
     }
SetIcon()
SetIcon ($in_icon_blob)
Accessor -Sets a 64-pixel-square image (as a GIF), to be used to indicate the format.
Parameters
$in_icon_blob The GIF image, as a stream of binary data.
Definition at line 415 of file c_comdef_format.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_icon_blob = null;
         $this->_icon_blob = $in_icon_blob;
     }
SetKey()
SetKey ($in_key_string)
Accessor -Sets the format key (the 1-3 letter code that represents the format).
Parameters
$in_key_string The format Key, as a text string (1-3 Characters)
Definition at line 391 of file c_comdef_format.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_key_string = null;
         $this->_key_string = $in_key_string;
     }
SetSharedID()
SetSharedID ($in_shared_id_bigint)
Accessor -Set the shared ID.
The shared ID may be the same for a number of different instances. It is how we link different language versions of the same format together.
Parameters
$in_shared_id_bigint The shared ID (If this is the same as other formats -used for different languages).
Definition at line 339 of file c_comdef_format.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_shared_id_bigint = null;
         $this->_shared_id_bigint = $in_shared_id_bigint;
     }
UnserializeObject()
static UnserializeObject ($in_parent, $serialized_array) static
This takes the serialized data, and instantiates a new object from it.
Returns
a new instance of c_comdef_format, set up according to the serialized data passed in.
Parameters
$in_parent The parent object.
$serialized_array An array containing the serialized data.
Implements i_comdef_serialized.
Definition at line 491 of file c_comdef_format.class.php.
Referenced by c_comdef_change\GetAfterObject(), and c_comdef_change\GetBeforeObject().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $s_array = unserialize($serialized_array);
         return new c_comdef_format(
             $in_parent,
             $s_array['shared_id_bigint'],
             $s_array['format_type_string'],
             $s_array['key_string'],
             $s_array['icon_blob'],
             $s_array['worldid_mixed'],
             $s_array['lang_enum'],
             $s_array['name_string'],
             $s_array['description_string']
         );
     }
UpdateToDB()
UpdateToDB ($is_rollback = false)
Updates the DB to the current values of this instance. (replacing current values of the DB).
Exceptions
a PDOException if there is a problem.
Set the values for this instance, to be stored in the database.
< This is used to keep track of the first iteration, to prevent a comma before it.
< This is the prepared statement value array.
Create a new entry.
We give the prepared statement a token, that will be filled by a value.
We give the value by declaring an associative array element with the token name.
Parameters
$is_rollback If true, this is a rollback operation.
Definition at line 67 of file c_comdef_format.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\AddNewChange(), c_comdef_server\GetCurrentUserObj(), c_comdef_server\GetOneFormat(), and c_comdef_dbsingleton\preparedExec().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             // We take a snapshot of the format as it currently sits in the database as a "before" image.
             $before = null;
             $before_id = null;
             $before_lang = null;
             $before_obj = c_comdef_server::GetOneFormat($this->GetSharedID(), $this->GetLocalLang());
             if ($before_obj instanceof c_comdef_format) {
                 $before = $before_obj->SerializeObject();
                 $before_id = $before_obj->GetSharedID();
                 $before_lang = $before_obj->GetLocalLang();
                 $before_obj = null;
             }
             try {
                 $this->DeleteFromDB_NoRecord();
                 /// Set the values for this instance, to be stored in the database.
                 $record = array();
                 $record['shared_id_bigint'] = intval($this->GetSharedID());
                 $record['format_type_enum'] = $this->GetFormatType();
                 $record['key_string'] = $this->GetKey();
                 $record['icon_blob'] = $this->GetIcon();
                 $record['worldid_mixed'] = $this->GetWorldID();
                 $record['lang_enum'] = $this->GetLocalLang();
                 $record['name_string'] = $this->GetLocalName();
                 $record['description_string'] = $this->GetLocalDescription();
                 $first = true;  ///< This is used to keep track of the first iteration, to prevent a comma before it.
                 $vals = array();    ///< This is the prepared statement value array.
                 /// Create a new entry.
                 $updateSQL = "INSERT INTO `".c_comdef_server::GetFormatTableName_obj()."` (";
                 while (list ( $key, $value ) = each($record)) {
                     if (!$first) {
                         $updateSQL .= ",";
                     } else {
                         $first = false;
                     }
                     $updateSQL .= "`".$key."`";
                 }
                 reset($record);
                 $updateSQL .= ") VALUES (";
                 $first = true;
                 while (list ( $key, $value ) = each($record)) {
                     if (!$first) {
                         $updateSQL .= ",";
                     } else {
                         $first = false;
                     }
                     /// We give the prepared statement a token, that will be filled by a value.
                     $updateSQL .= ":$key";
                     /// We give the value by declaring an associative array element with the token name.
                     $vals[':'.$key] = $value;
                 }
                 $updateSQL .= ")";
                 c_comdef_dbsingleton::preparedExec($updateSQL, $vals);
                 $after = $this->SerializeObject();
                 $after_id = $this->GetSharedID();
                 $after_lang = $this->GetLocalLang();
                 $cType = (true == $is_rollback) ? 'comdef_change_type_rollback' : ((null != $before) ? 'comdef_change_type_change' : 'comdef_change_type_new');
                 c_comdef_server::AddNewChange($user->GetID(), $cType, null, $before, $after, 'c_comdef_format', $before_id, $after_id, $before_lang, $after_lang);
                 $ret = true;
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_format::UpdateToDB()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
UserCanEdit()
UserCanEdit ($in_user_object = null)
Test to see if a user is allowed to edit an instance (change the data).
Returns
true, if the user is allowed to edit, false, otherwise.
Parameters
$in_user_object A reference to a c_comdef_user object, for the user to be validated. If null, or not supplied, the server current user is tested.
Implements i_comdef_auth.
Definition at line 517 of file c_comdef_format.class.php.
References $ret, c_comdef_server\GetCurrentUserObj(), and c_comdef_server\IsUserServerAdmin().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         // We load the server user if one wasn't supplied.
         if (null == $in_user_object) {
             $in_user_object = c_comdef_server::GetCurrentUserObj();
         }
         // If it isn't a user object, we fail right there.
         if ($in_user_object instanceof c_comdef_user) {
             $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
             // Only the server admin can edit formats.
             if (c_comdef_server::IsUserServerAdmin()) {
                 $ret = true;
             }
         }
         return $ret;
     }
Member Data Documentation
$_format_codes
$_format_codes = null
This will be an array of the format types (localized).
Definition at line 58 of file c_comdef_format.class.php.
$_format_type_string
$_format_type_string = null
This is the type of format.
An enumerated string value, representing the classification of the format:
"FC1" -Meeting Format (Speaker, Book Study, etc.)
"FC2" -Location Code (Wheelchair Accessible, Limited Parking, etc.)
"FC3" -Attendance Restriction (Men Only, Closed, Open, No Children, etc.)
Definition at line 49 of file c_comdef_format.class.php.
$_icon_blob
$_icon_blob = null
The Format Icon, as a 64-pixel-square Icon, in GIF format.
Definition at line 55 of file c_comdef_format.class.php.
$_key_string
$_key_string = null
The Format Key, in Text Form.
Definition at line 52 of file c_comdef_format.class.php.
$_shared_id_bigint
$_shared_id_bigint = null
The shared ID (for multiple instances of the same format code).
Definition at line 42 of file c_comdef_format.class.php.
The documentation for this class was generated from the following file:
/Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/server/classes/c_comdef_format.class.php