BMLT Root Server: /home/travis/build/bmlt-enabled/bmlt-root-server/main_server/local_server/install_wizard/installer.js File Reference
installer.js File Reference
Functions
function BMLTInstaller (in_prefs)
function convertFormatLangsToJSON (v)
if (!this.m_installer_state)
function reactToEmailCheckbox ()
A global context callback for the email checkboxes being selected. *.
function gmScriptLoadCompletion ()
A global context callback for the script load completion. *.
function BMLT_Installer_AjaxPostRequest (url, callback, data, extra_data)
A simple, generic AJAX request function. * *.
function sprintf ()
Variables
this reactToMapClick
This is the callback for a map click or drag end. *.
this buttonTestForDatabaseSetup
this buttonTestForDatabaseSetupCallback
this testForDatabaseSetup
this testForDatabaseSetupCallback
this initializeRootServer
this initializeRootServerCallback
this geMinPasswordLength
Returns the minimum password length *.
this gatherInstallerState
This gathers the installer state. *.
this createFileData
Creates the text for the file *.
this testMapsApiKey
Triggered by the TEST KEY button. When no callback is provided, result is * displayed in an alert box. *.
this m_installer_wrapper_object = document.getElementById('installer_wrapper')
Function Documentation
function BMLT_Installer_AjaxPostRequest (url, callback, data, extra_data)
A simple, generic AJAX request function. * *.
Returns
a new XMLHTTPRequest object. *
Create a generic XMLHTTPObject. *
This will account for the various flavors imposed by different browsers. *
Returns
a new XMLHTTPRequest object. *
Parameters
url The URI to be called
callback The success callback
data FormData object
extra_data If supplied, extra data to be delivered to the callback.
Definition at line 763 of file installer.js.
References e, and i.
   {
     /************************************************************************************//**
     *   \brief Create a generic XMLHTTPObject.                                              *
     *                                                                                       *
     *   This will account for the various flavors imposed by different browsers.            *
     *                                                                                       *
     *   \returns a new XMLHTTPRequest object.                                               *
     ****************************************************************************************/
     function createXMLHTTPObject() {
         var XMLHttpArray = [
             function () {return new XMLHttpRequest()},
             function () {return new ActiveXObject("Msxml2.XMLHTTP")},
             function () {return new ActiveXObject("Msxml2.XMLHTTP")},
             function () {return new ActiveXObject("Microsoft.XMLHTTP")}
         ];
         var xmlhttp = false;
         for (var i=0; i < XMLHttpArray.length; i++) {
             try {
                 xmlhttp = XMLHttpArray[i]();
             } catch (e) {
                 continue;
             }
             break;
         }
         return xmlhttp;
     }
     var req = createXMLHTTPObject();
     req.finalCallback = callback;
     if (extra_data != null) {
         req.extra_data = extra_data;
     }
     req.open("POST", url, true);
     req.onreadystatechange = function () {
         if (req.readyState !== 4) {
             return;
         }
         if (req.status !== 200) {
             return;
         }
         callback(req, req.extra_data);
         req = null;
     }
     req.send(data);
     return req;
 }
function BMLTInstaller (in_prefs)
Shows Page 1 of the installer wizard. It does this by setting the wrapper * className to the first page, which uses CSS to hide the other two pages. *
Shows Page 2 of the installer wizard. It does this by setting the wrapper * className to the first page, which uses CSS to hide the other two pages. *
Shows Page 3 of the installer wizard. It does this by setting the wrapper * className to the first page, which uses CSS to hide the other two pages. *
Shows Page 4 of the installer wizard. It does this by setting the wrapper * className to the first page, which uses CSS to hide the other two pages. *
When a text input (either <input> or <textarea> is initialized, we can set * up a default text value that is displayed when the item is empty and not in * focus. If we don't send in a specific value, then the current value of the * text item is considered to be the default. *
This just makes sure that the className is correct. *
< This is the text item to check.
< true, if the item is in focus
When a text item receives focus, we clear any default text. *
When a text item loses focus, we restore any default text, if the item was * left empty. *
This creates the map for the location tab. *
Parameters
in_prefs A JSON object with the initial prefs.
Definition at line 17 of file installer.js.
References createFileData, m_installer_wrapper_object, testForDatabaseSetup, and testMapsApiKey.
 {
     var m_installer_wrapper_object;
     var m_map_object;
     var m_map_center;
     var m_installer_state;
     var m_ajax_uri;
     var m_ajax_request_in_progress;
     var m_google_api_key = "";
     var m_google_maps_script = null;
     var m_google_api_key_is_good = false;
     var m_database_credentials_are_good = false;
     var m_server_admin_password_is_good = false;
     // #mark -
     // #mark Page Selection Handlers
     // #mark -
     /************************************************************************************//**
     *   \brief Shows Page 1 of the installer wizard. It does this by setting the wrapper    *
     *          className to the first page, which uses CSS to hide the other two pages.     *
     ****************************************************************************************/
     this.selectPage1 = function () {
         if ( this.m_installer_wrapper_object.className != 'page_1_wrapper' ) {
             this.m_installer_wrapper_object.className = 'page_1_wrapper';
         };
     };
     /************************************************************************************//**
     *   \brief Shows Page 2 of the installer wizard. It does this by setting the wrapper    *
     *          className to the first page, which uses CSS to hide the other two pages.     *
     ****************************************************************************************/
     this.selectPage2 = function () {
         if ( this.m_installer_wrapper_object.className != 'page_2_wrapper' ) {
             this.m_installer_wrapper_object.className = 'page_2_wrapper';
         };
     };
     /************************************************************************************//**
     *   \brief Shows Page 3 of the installer wizard. It does this by setting the wrapper    *
     *          className to the first page, which uses CSS to hide the other two pages.     *
     ****************************************************************************************/
     this.selectPage3 = function () {
         if ( this.m_installer_wrapper_object.className != 'page_3_wrapper' ) {
             this.m_installer_wrapper_object.className = 'page_3_wrapper';
             this.testForDatabaseSetup();
         };
     };
     /************************************************************************************//**
     *   \brief Shows Page 4 of the installer wizard. It does this by setting the wrapper    *
     *          className to the first page, which uses CSS to hide the other two pages.     *
     ****************************************************************************************/
     this.selectPage4 = function () {
         if ( this.m_installer_wrapper_object.className != 'page_4_wrapper' ) {
             this.m_installer_wrapper_object.className = 'page_4_wrapper';
             document.getElementById('database_install_stuff_div').className = 'item_hidden';
             document.getElementById('file_text_pre').innerHTML = this.createFileData();
             var apiKeyWarningDiv = document.getElementById('admin_google_api_key_warning');
             var testForDatabaseSetup = this.testForDatabaseSetup;
             if (apiKeyWarningDiv) {
                 this.testMapsApiKey(function (message) {
                     if (message) {
                         apiKeyWarningDiv.innerHTML = g_maps_api_key_warning + ' ' + message + '<br><a href="javascript:g_installer_object.selectPage2()">' + g_maps_api_key_click_here + '</a>';
                         this.m_google_api_key_is_good = false;
                     } else {
                         apiKeyWarningDiv.innerHTML = '';
                         this.m_google_api_key_is_good = true;
                     }
                     testForDatabaseSetup.call(g_installer_object);
                 });
             }
         }
     };
     // #mark -
     // #mark Text Item Handlers
     // #mark -
     /************************************************************************************//**
     *   \brief When a text input (either <input> or <textarea> is initialized, we can set   *
     *          up a default text value that is displayed when the item is empty and not in  *
     *          focus. If we don't send in a specific value, then the current value of the   *
     *          text item is considered to be the default.                                   *
     ****************************************************************************************/
     this.handleTextInputLoad = function (
         in_text_item,
         in_default_value,
         in_size
     ) {
         if ( in_text_item ) {
             in_text_item.original_value = in_text_item.value;
             in_text_item.small = false;
             in_text_item.med = false;
             in_text_item.tiny = false;
             if ( in_size ) {
                 if ( in_size == 'tiny' ) {
                     in_text_item.tiny = true;
                 } else if ( in_size == 'small' ) {
                     in_text_item.small = true;
                 } else if ( in_size == 'med' ) {
                     in_text_item.med = true;
                 };
             };
             if ( in_default_value != null ) {
                 in_text_item.defaultValue = in_default_value;
             } else {
                 in_text_item.defaultValue = in_text_item.value;
             };
             in_text_item.value = in_text_item.original_value;
             if ( !in_text_item.value || (in_text_item.value == in_text_item.defaultValue) ) {
                 in_text_item.value = in_text_item.defaultValue;
                 in_text_item.className = 'bmlt_text_item' + (in_text_item.small ? '_small' : (in_text_item.med ? '_med' : (in_text_item.tiny ? '_tiny' : ''))) + ' bmlt_text_item_dimmed';
             } else {
                 in_text_item.className = 'bmlt_text_item' + (in_text_item.small ? '_small' : (in_text_item.med ? '_med' : (in_text_item.tiny ? '_tiny' : '')));
             };
             in_text_item.onfocus = function () {
                 g_installer_object.handleTextInputFocus(this); };
             in_text_item.onblur = function () {
                 g_installer_object.handleTextInputBlur(this); };
             this.setTextItemClass(in_text_item, false);
         };
     };
     /************************************************************************************//**
     *   \brief This just makes sure that the className is correct.                          *
     ****************************************************************************************/
     this.setTextItemClass = function (
         in_text_item,   ///< This is the text item to check.
         is_focused      ///< true, if the item is in focus
     ) {
         if ( in_text_item ) {
             if ( !is_focused && ((in_text_item.value == null) || (in_text_item.value == in_text_item.defaultValue)) ) {
                 in_text_item.className = 'bmlt_text_item' + (in_text_item.small ? '_small' : (in_text_item.med ? '_med' : (in_text_item.tiny ? '_tiny' : ''))) + ' bmlt_text_item_dimmed';
             } else {
                 in_text_item.className = 'bmlt_text_item' + (in_text_item.small ? '_small' : (in_text_item.med ? '_med' : (in_text_item.tiny ? '_tiny' : '')));
             };
         };
     };
     /************************************************************************************//**
     *   \brief When a text item receives focus, we clear any default text.                  *
     ****************************************************************************************/
     this.handleTextInputFocus = function (   in_text_item
                                         ) {
         if ( in_text_item ) {
             if ( in_text_item.value == in_text_item.defaultValue ) {
                 in_text_item.value = '';
             };
             this.setTextItemClass(in_text_item, true);
         };
     };
     /************************************************************************************//**
     *   \brief When a text item loses focus, we restore any default text, if the item was   *
     *          left empty.                                                                  *
     ****************************************************************************************/
     this.handleTextInputBlur = function (    in_text_item
                                         ) {
         if ( in_text_item ) {
             if ( !in_text_item.value ) {
                 in_text_item.value = in_text_item.defaultValue;
             };
             this.setTextItemClass(in_text_item, false);
         };
     };
     /************************************************************************************//**
     *   \brief This creates the map for the location tab.                                   *
     ****************************************************************************************/
     this.createLocationMap = function ( ) {
         if ( !this.m_map_object ) {
             var myOptions = {
                 'center': new google.maps.LatLng(this.m_installer_state.search_spec_map_center.latitude, this.m_installer_state.search_spec_map_center.longitude),
                 'zoom': parseInt(this.m_installer_state.search_spec_map_center.zoom),
                 'mapTypeId': google.maps.MapTypeId.ROADMAP,
                 'mapTypeControlOptions': { 'style': google.maps.MapTypeControlStyle.DROPDOWN_MENU },
                 'zoomControl': true,
                 'mapTypeControl': true,
                 'disableDoubleClickZoom' : true,
                 'draggableCursor': "crosshair",
                 'scaleControl' : true,
                 'scrollwheel' : false
             };
             myOptions.zoomControlOptions = { 'style': google.maps.ZoomControlStyle.LARGE };
             parent_div = document.getElementById('installer_map_display_div');
             parent_div.innerHTML = '';
             this.m_map_object = new google.maps.Map(parent_div, myOptions);
             google.maps.event.addListener(this.m_map_object, 'click', g_installer_object.reactToMapClick);
             this.m_map_object.setOptions(myOptions);
             m_icon_image = new google.maps.MarkerImage("./local_server/server_admin/style/images/NACenterMarker.png", new google.maps.Size(21, 36), new google.maps.Point(0,0), new google.maps.Point(11, 36));
             m_icon_shadow = new google.maps.MarkerImage("./local_server/server_admin/style/images/NACenterMarkerS.png", new google.maps.Size(43, 36), new google.maps.Point(0,0), new google.maps.Point(11, 36));
             this.m_map_object.main_marker = new google.maps.Marker({
                 'position':     this.m_map_object.getCenter(),
                 'map':          this.m_map_object,
                 'icon':         m_icon_image,
                 'shadow':       m_icon_shadow,
                 'clickable':    false,
                 'cursor':       'pointer',
                 'draggable':    true
                                                                 });
             google.maps.event.addListener(this.m_map_object.main_marker, 'dragend', g_installer_object.reactToMapClick);
         };
     };
function convertFormatLangsToJSON (v)
Definition at line 586 of file installer.js.
References g, and v.
{
         var ret = {};
         var langs = v.match(/\S+/g);
         if (!Array.isArray(langs)) {
             return JSON.stringify(ret);
         }
         langs.forEach(function(lang) {
             var parts = lang.split(':');
             if (parts.length == 2) {
                 parts[0] = parts[0].trim();
                 parts[1] = parts[1].trim();
                 if (parts[0]==="" || parts[1]==="") {
                     alert("Could not parse format languages");
                 }
                 ret[parts[0].trim()] = parts[1];
             } else {
                 alert("Could not parse format languages");
             }
         });
         return JSON.stringify(ret);
     };
function gmScriptLoadCompletion ()
A global context callback for the script load completion. *.
Definition at line 748 of file installer.js.
 {
     g_installer_object.createLocationMap();
 };
if (!this. m_installer_state)
Definition at line 717 of file installer.js.
{
         this.m_installer_state = in_prefs;
     };
function reactToEmailCheckbox ()
A global context callback for the email checkboxes being selected. *.
Definition at line 727 of file installer.js.
 {
     var enableEmailObject = document.getElementById('installer_admin_email_contact_checkbox');
     var sbAdminEmailObject = document.getElementById('installer_admin_email_sba_contact_checkbox');
     var allAdminsEmailCheckbox = document.getElementById('installer_admin_email_all_admins_checkbox');
     if ( !enableEmailObject.checked ) {
         sbAdminEmailObject.checked = false;
     };
     if ( !sbAdminEmailObject.checked ) {
         allAdminsEmailCheckbox.checked = false;
     };
     sbAdminEmailObject.disabled = !enableEmailObject.checked;
     allAdminsEmailCheckbox.disabled = !sbAdminEmailObject.checked;
 };
function sprintf ()
sprintf() for JavaScript 0.6
Copyright (c) Alexandru Marasteanu <alexaholic [at) gmail (dot] com> All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met: Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution. Neither the name of sprintf() for JavaScript nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Alexandru Marasteanu BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Changelog: 2007.04.03 - 0.1:
initial release 2007.09.11 - 0.2:
feature: added argument swapping 2007.09.17 - 0.3:
bug fix: no longer throws exception on empty paramenters (Hans Pufal) 2007.10.21 - 0.4:
unit test and patch (David Baird) 2010.05.09 - 0.5:
bug fix: 0 is now preceeded with a + sign
bug fix: the sign was not at the right position on padded results (Kamal Abdali)
switched from GPL to BSD license 2010.05.22 - 0.6:
reverted to 0.4 and fixed the bug regarding the sign of the number 0 Note: Thanks to Raphael Pigulla <raph (at] n3rd [dot) org> (http://www.n3rd.org/) who warned me about a bug in 0.5, I discovered that the last update was a regress. I appologize for that.
Definition at line 873 of file installer.js.
References a, b, c, d(), e, f, i, m, o, s, u, and x.
Referenced by BMLT_FuncNAWSReturnMeetingServiceBodyNAWSID(), NAWSImport::createMeetings(), DB_Connect_and_Upgrade(), bdfProfiler::html_output(), bdfProfiler::output(), and whitespace_warnings().
 {
     function str_repeat(i, m)
     {
         for (var o = []; m > 0; o[--m] = i) {
         }
         return o.join('');
     };
     var i = 0, a, f = arguments[i++], o = [], m, p, c, x, s = '';
     while (f) {
         if (m = /^[^\x25]+/.exec(f)) {
             o.push(m[0]);
         } else if (m = /^\x25{2}/.exec(f)) {
             o.push('%');
         } else if (m = /^\x25(?:(\d+)\$)?(\+)?(0|'[^$])?(-)?(\d+)?(?:\.(\d+))?([b-fosuxX])/.exec(f)) {
             if (((a = arguments[m[1] || i++]) == null) || (a == undefined)) {
                 throw('Too few arguments.');
             };
             if (/[^s]/.test(m[7]) && (typeof(a) != 'number')) {
                 throw('Expecting number but found ' + typeof(a));
             };
             switch (m[7]) {
                 case 'b': a = a.toString(2); break;
                 case 'c': a = String.fromCharCode(a); break;
                 case 'd': a = parseInt(a,10); break;
                 case 'e': a = m[6] ? a.toExponential(m[6]) : a.toExponential(); break;
                 case 'f': a = m[6] ? parseFloat(a).toFixed(m[6]) : parseFloat(a); break;
                 case 'o': a = a.toString(8); break;
                 case 's': a = ((a = String(a)) && m[6] ? a.substring(0, m[6]) : a); break;
                 case 'u': a = Math.abs(a); break;
                 case 'x': a = a.toString(16); break;
                 case 'X': a = a.toString(16).toUpperCase(); break;
             };
             a = (/[def]/.test(m[7]) && m[2] && a >= 0 ? '+'+ a : a);
             c = m[3] ? m[3] == '0' ? '0' : m[3].charAt(1) : ' ';
             x = m[5] - String(a).length - s.length;
             p = m[5] ? str_repeat(c, x) : '';
             o.push(s + (m[4] ? a + p : p + a));
         } else {
             throw('Huh ?!');
         };
         f = f.substring(m[0].length);
     };
     return o.join('');
 };
Variable Documentation
this buttonTestForDatabaseSetup
Initial value:
= function () {
        var uri = this.m_ajax_uri;
        this.gatherInstallerState();
        if ( this.m_ajax_request_in_progress ) {
            this.m_ajax_request_in_progress.abort();
            this.m_ajax_request_in_progress = null;
        };
        uri += 'test_comprehensive';
        var formData = new FormData();
        formData.append('dbType', this.m_installer_state.dbType);
        formData.append('dbName', this.m_installer_state.dbName);
        formData.append('dbUser', this.m_installer_state.dbUser);
        formData.append('dbPassword', this.m_installer_state.dbPassword);
        formData.append('dbServer', this.m_installer_state.dbServer);
        formData.append('dbPrefix', this.m_installer_state.dbPrefix);
        var salt = new Date();
        uri += '&salt=' + salt.getTime();
        this.m_ajax_request_in_progress = BMLT_Installer_AjaxPostRequest(uri, function (in_req) {
            g_installer_object.buttonTestForDatabaseSetupCallback(in_req); }, formData);
    }
Definition at line 251 of file installer.js.
this buttonTestForDatabaseSetupCallback
Initial value:
= function (in_http_request
                                                        ) {
        this.m_ajax_request_in_progress = null;
        if ( in_http_request.responseText ) {
            eval('var json_object = ' + in_http_request.responseText + ';');
            if ( json_object ) {
                alert(json_object.message);
            };
        } else
            {
        };
    }
Definition at line 280 of file installer.js.
this createFileData
Creates the text for the file *.
Returns
The PHP code for the auto-config.inc.php file. *
Definition at line 612 of file installer.js.
Referenced by BMLTInstaller().
this gatherInstallerState
This gathers the installer state. *.
Definition at line 484 of file installer.js.
this geMinPasswordLength
Initial value:
= function () {
        var pw_length_object = document.getElementById('installer_pw_length_select');
        this.m_installer_state.min_pw_len = pw_length_object.options[pw_length_object.selectedIndex].value;
        return parseInt(this.m_installer_state.min_pw_len, 10);
    }
Returns the minimum password length *.
Returns
an integer, with the password length. *
Definition at line 473 of file installer.js.
this initializeRootServer
Definition at line 354 of file installer.js.
this initializeRootServerCallback
Definition at line 429 of file installer.js.
this m_installer_wrapper_object = document.getElementById('installer_wrapper')
Definition at line 721 of file installer.js.
Referenced by BMLTInstaller().
this reactToMapClick
Initial value:
= function (in_gMap_event
                                    ) {
        var map_center = in_gMap_event.latLng;
        g_installer_object.m_map_object.panTo(map_center);
        g_installer_object.m_map_object.main_marker.setPosition(map_center);
    }
This is the callback for a map click or drag end. *.
Definition at line 241 of file installer.js.
this testForDatabaseSetup
Initial value:
= function () {
        var uri = this.m_ajax_uri;
        this.gatherInstallerState();
        if ( this.m_ajax_request_in_progress ) {
            this.m_ajax_request_in_progress.abort();
            this.m_ajax_request_in_progress = null;
        };
        uri += 'test';
        var formData = new FormData();
        formData.append('dbType', this.m_installer_state.dbType);
        formData.append('dbName', this.m_installer_state.dbName);
        formData.append('dbUser', this.m_installer_state.dbUser);
        formData.append('dbPassword', this.m_installer_state.dbPassword);
        formData.append('dbServer', this.m_installer_state.dbServer);
        formData.append('dbPrefix', this.m_installer_state.dbPrefix);
        var salt = new Date();
        uri += '&salt=' + salt.getTime();
        this.m_ajax_request_in_progress = BMLT_Installer_AjaxPostRequest(uri, function (in_req) {
            g_installer_object.testForDatabaseSetupCallback(in_req); }, formData);
    }
Definition at line 298 of file installer.js.
Referenced by BMLTInstaller().
this testForDatabaseSetupCallback
Initial value:
= function (in_http_request
                                                ) {
        this.m_ajax_request_in_progress = null;
        this.m_database_credentials_are_good = false;
        if (in_http_request.responseText) {
            eval('var ret_val = parseInt ( ' + in_http_request.responseText + ', 10 );');
            document.getElementById('admin_db_items_warning').innerHTML = '';
            document.getElementById('admin_pw_warning_div_2').className = 'item_hidden';
            if (ret_val == 0) {
                document.getElementById('admin_login_stuff_fieldset').className = 'item_hidden';
                document.getElementById('admin_pw_warning_div_2').className = 'extra_text_div red_char';
                document.getElementById('admin_db_items_warning').innerHTML = g_db_init_db_set_warning_text + '<br><a href="javascript:g_installer_object.selectPage1()">' + g_db_init_db_click_here + '</a>';
            } else if (ret_val == -1) {
                document.getElementById('admin_login_stuff_fieldset').className = '';
                document.getElementById('admin_db_items_warning').innerHTML = g_db_init_db_generic_db_error_text + '<br><a href="javascript:g_installer_object.selectPage1()">' + g_db_init_db_click_here + '</a>';
            } else {
                document.getElementById('admin_login_stuff_fieldset').className = '';
                this.m_database_credentials_are_good = true;
                this.gatherInstallerState();
            }
        }
    }
Definition at line 327 of file installer.js.
this testMapsApiKey
Triggered by the TEST KEY button. When no callback is provided, result is * displayed in an alert box. *.
Definition at line 675 of file installer.js.
Referenced by BMLTInstaller().