BMLT Root Server: c_comdef_dbsingleton Class Reference
c_comdef_dbsingleton Class Reference
This class provides a genericized interface to the PHP PDO toolkit. It is a completely static class.
Static Public Member Functions
static init ($driver, $host, $database, $user=null, $password=null, $charset=null)
Initializes connection param class members.
static connect ()
Create internal PDO object thus connecting to database using connection param class members (passed in from previous call to c_comdef_dbsingleton::init())
static isConnected ()
Returns whether internal PDO object is instantiated and thus connected.
static pdoInstance ($do_connect=false)
Provides access to internal PDO object in case this classes functionality is not enough.
static preparedQuery ($sql, $params=array(), $fetchKeyPair=false)
Wrapper for preparing and executing a PDOStatement that returns a resultset e.g. SELECT SQL statements.
static preparedExec ($sql, $params=array())
Wrapper for preparing and executing a PDOStatement that does not return a resultset e.g. INSERT or UPDATE SQL statements.
static lastInsertId ()
Wrapper for PDO::lastInsertId()
static beginTransaction ()
static rollBack ()
static commit ()
Private Member Functions
__construct ()
Private constructor (prevents direct creation of object)
Static Private Attributes
static $pdo = null
Internal PDO object.
static $driver = null
Connection database driver type param.
static $host = null
Connection host param.
static $database = null
Connection database param.
static $user = null
Connection user param.
static $password = null
Connection password param.
static $charset = null
Connection charset param.
static $fetchMode = PDO::FETCH_ASSOC
Default fetch mode for internal PDOStatements.
Detailed Description
This class provides a genericized interface to the PHP PDO toolkit. It is a completely static class.
Definition at line 69 of file c_comdef_dbsingleton.class.php.
Constructor & Destructor Documentation
__construct()
__construct () private
Private constructor (prevents direct creation of object)
Definition at line 100 of file c_comdef_dbsingleton.class.php.
     {
     }
Member Function Documentation
beginTransaction()
static beginTransaction () static
Definition at line 299 of file c_comdef_dbsingleton.class.php.
Referenced by DB_Connect_and_Upgrade().
     {
         if (!self::$pdo instanceof PDO) {
             self::connect();
         }
         return self::$pdo->beginTransaction();
     }
commit()
static commit () static
Definition at line 313 of file c_comdef_dbsingleton.class.php.
Referenced by DB_Connect_and_Upgrade().
     {
         return self::$pdo->commit();
     }
connect()
static connect () static
Create internal PDO object thus connecting to database using connection param class members (passed in from previous call to c_comdef_dbsingleton::init())
Will destroy previous connection (if one exists) before reconnecting
Exceptions
Exception thrown if internal PDO object cannot be created e.g. wrong connection param(s)
For security purposes, once we connect, we get rid of all the info, and a new init needs to be called.
Definition at line 150 of file c_comdef_dbsingleton.class.php.
     {
         if (self::$pdo instanceof pdo) {
             self::$pdo = null;
         }
         try {
             $dsn = self::$driver . ':host=' . self::$host . ';dbname=' . self::$database;
             self::$pdo = new PDO($dsn, self::$user, self::$password, array(PDO::MYSQL_ATTR_INIT_COMMAND => "SET NAMES 'utf8'"));
             self::$pdo->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
             self::$pdo->setAttribute(PDO::ATTR_CASE, PDO::CASE_LOWER);
             self::$pdo->setAttribute(PDO::ATTR_EMULATE_PREPARES, true);
             if (strlen(self::$charset) > 0) {
                 self::preparedExec('SET NAMES :charset', array(':charset' => self::$charset));
             }
             /// For security purposes, once we connect, we get rid of all the info, and a new init needs to be called.
             self::$driver = null;
             self::$host = null;
             self::$database = null;
             self::$user = null;
             self::$password = null;
             self::$charset = null;
         } catch (PDOException $exception) {
             throw new Exception(__METHOD__ . '() ' . $exception->getMessage());
         }
     }
init()
static init ($driver, $host, $database, $user = null, $password = null, $charset = null) static
Initializes connection param class members.
Must be called BEFORE any attempts to connect to or query a database.
Will destroy previous connection (if one exists).
Parameters
$driver database server type (ex: 'mysql')
$host database server host
$database database name
$user user, optional
$password password, optional
$charset connection charset, optional
Definition at line 111 of file c_comdef_dbsingleton.class.php.
Referenced by c_comdef_server\__construct(), and DB_Connect_and_Upgrade().
       {
         if (self::$pdo instanceof pdo) {
             self::$pdo = null;
         }
         self::$driver = (string) $driver;
         self::$host = (string) $host;
         self::$database = (string) $database;
         if (!is_null($user)) {
             self::$user = (string) $user;
         }
         if (!is_null($password)) {
             self::$password = (string) $password;
         }
         if (!is_null($charset)) {
             self::$charset = $charset;
         }
     }
isConnected()
static isConnected () static
Returns whether internal PDO object is instantiated and thus connected.
Returns
true if connected.
Definition at line 184 of file c_comdef_dbsingleton.class.php.
     {
         if (self::$pdo instanceof PDO) {
             return true;
         } else {
             return false;
         }
     }
lastInsertId()
static lastInsertId () static
Wrapper for PDO::lastInsertId()
Returns
the ID of the last INSERT
Exceptions
Exception thrown if internal PDO object not instantiated
Definition at line 290 of file c_comdef_dbsingleton.class.php.
     {
         if (!self::$pdo instanceof PDO) {
             throw new Exception(__METHOD__ . '() internal PDO object not instantiated');
         }
         return self::$pdo->lastInsertId();
     }
pdoInstance()
static pdoInstance ($do_connect = false) static
Provides access to internal PDO object in case this classes functionality is not enough.
Returns
the PDO object
Exceptions
Exception thrown if internal PDO object not instantiated
Parameters
$do_connect Set this to true to force a connection if one does not yet exist. Default is false.
Definition at line 200 of file c_comdef_dbsingleton.class.php.
Referenced by c_comdef_server\GetMeetings().
       {
         if (!self::isConnected() && $do_connect) {
             self::connect();
         }
         if (self::$pdo instanceof PDO) {
             return self::$pdo;
         } else {
             throw new Exception(__METHOD__ . '() internal PDO object not instantiated');
         }
     }
preparedExec()
static preparedExec ($sql, $params = array()) static
Wrapper for preparing and executing a PDOStatement that does not return a resultset e.g. INSERT or UPDATE SQL statements.
See PDO documentation about prepared queries.
If there isn't already a database connection, it will "lazy load" the connection.
Exceptions
Exception thrown if internal PDO exception is thrown
Returns
true if execution is successful.
Parameters
$sql same as kind provided to PDO::prepare()
$params same as kind provided to PDO::prepare()
Definition at line 267 of file c_comdef_dbsingleton.class.php.
Referenced by c_comdef_data_importer\AddOneMeeting(), DB_Connect_and_Upgrade(), c_comdef_data_importer\DeleteAllOldMeetings(), c_comdef_change\DeleteFromDB(), c_comdef_format\DeleteFromDB_NoRecord(), c_comdef_service_body\DeleteFromDB_NoRecord(), c_comdef_user\DeleteFromDB_NoRecord(), c_comdef_meeting\DeleteFromDB_NoRecord(), c_comdef_server\GetNewMeetingID(), c_comdef_user\ResetChildUsers(), c_comdef_format\UpdateToDB(), c_comdef_change\UpdateToDB(), c_comdef_service_body\UpdateToDB(), c_comdef_user\UpdateToDB(), and c_comdef_meeting\UpdateToDB().
       {
         if (!self::$pdo instanceof PDO) {
             self::connect();
         }
         try {
             $stmt = self::$pdo->prepare($sql);
             return $stmt->execute($params);
         } catch (PDOException $exception) {
             throw new Exception(__METHOD__ . '() ' . $exception->getMessage());
         }
     }
preparedQuery()
static preparedQuery ($sql, $params = array(), $fetchKeyPair = false) static
Wrapper for preparing and executing a PDOStatement that returns a resultset e.g. SELECT SQL statements.
Returns a multidimensional array depending on internal fetch mode setting (self::$fetchMode) See PDO documentation about prepared queries.
If there isn't already a database connection, it will "lazy load" the connection.
Fetching key pairs- when $fetchKeyPair is set to TRUE, it will force the returned array to be a one-dimensional array indexed on the first column in the query. Note- query may contain only two columns or an exception/error is thrown. See PDO::PDO::FETCH_KEY_PAIR for more details
Returns
associative array of results.
Exceptions
Exception thrown if internal PDO exception is thrown
Parameters
$sql same as kind provided to PDO::prepare()
$params same as kind provided to PDO::prepare()
$fetchKeyPair See description in method documentation
Definition at line 231 of file c_comdef_dbsingleton.class.php.
Referenced by c_comdef_data_importer\AddOneMeeting(), DB_Connect_and_Upgrade(), c_comdef_data_importer\DeleteAllOldMeetings(), c_comdef_server\DoesMeetingExist(), c_comdef_data_importer\extract_service_bodies(), c_comdef_data_importer\FetchTemplates(), c_comdef_meeting\GetAllMeetingKeys(), c_comdef_meeting\GetAllValuesForKey(), c_comdef_server\GetChangesFromSQL(), c_comdef_server\GetCoverageArea(), c_comdef_server\GetDatabaseVersion(), c_comdef_meeting\GetDataTableTemplate(), c_comdef_meeting\GetLongDataTableTemplate(), c_comdef_server\GetMeetingsFromSQL(), c_comdef_server\GetNewMeetingID(), c_comdef_server\GetOneFormat(), c_comdef_server\GetOneMeeting(), c_comdef_server\GetOneUser(), c_comdef_server\HuntForRadius(), c_comdef_server\IsFormatKeyUnique(), c_comdef_meeting\process_meeting_row(), c_comdef_server\ReadFormats(), c_comdef_server\ReadServiceBodies(), c_comdef_server\ReadServiceIDs(), c_comdef_server\ReadUsers(), c_comdef_change\RestoreFromDB(), c_comdef_format\RestoreFromDB(), c_comdef_service_body\RestoreFromDB(), c_comdef_user\RestoreFromDB(), c_comdef_meeting\RestoreFromDB(), c_comdef_change\UpdateToDB(), c_comdef_user\UpdateToDB(), and c_comdef_service_body\UpdateToDB().
       {
         if (!self::$pdo instanceof PDO) {
             self::connect();
         }
         try {
             $stmt = self::$pdo->prepare($sql);
             $stmt->setFetchMode(self::$fetchMode);
             $stmt->execute($params);
             if ($fetchKeyPair) {
                 return $stmt->fetchAll(PDO::FETCH_KEY_PAIR);
             } else {
                 return $stmt->fetchAll();
             }
         } catch (PDOException $exception) {
             throw new Exception(__METHOD__ . '() ' . $exception->getMessage());
         }
     }
rollBack()
static rollBack () static
Definition at line 308 of file c_comdef_dbsingleton.class.php.
Referenced by DB_Connect_and_Upgrade().
     {
         return self::$pdo->rollBack();
     }
Member Data Documentation
$charset
$charset = null static private
Connection charset param.
Definition at line 92 of file c_comdef_dbsingleton.class.php.
$database
$database = null static private
Connection database param.
Definition at line 83 of file c_comdef_dbsingleton.class.php.
$driver
$driver = null static private
Connection database driver type param.
Definition at line 77 of file c_comdef_dbsingleton.class.php.
$fetchMode
$fetchMode = PDO::FETCH_ASSOC static private
Default fetch mode for internal PDOStatements.
Definition at line 95 of file c_comdef_dbsingleton.class.php.
$host
$host = null static private
Connection host param.
Definition at line 80 of file c_comdef_dbsingleton.class.php.
$password
$password = null static private
Connection password param.
Definition at line 89 of file c_comdef_dbsingleton.class.php.
$pdo
$pdo = null static private
Internal PDO object.
Definition at line 74 of file c_comdef_dbsingleton.class.php.
$user
$user = null static private
Connection user param.
Definition at line 86 of file c_comdef_dbsingleton.class.php.
The documentation for this class was generated from the following file:
/Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/server/classes/c_comdef_dbsingleton.class.php