CREATE TABLE IF NOT EXISTS `na_comdef_changes` (
  `id_bigint` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id_bigint` bigint(20) unsigned NOT NULL,
  `service_body_id_bigint` bigint(20) unsigned NOT NULL,
  `lang_enum` varchar(7) NOT NULL,
  `change_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `object_class_string` varchar(64) NOT NULL,
  `change_name_string` tinytext,
  `change_description_text` text,
  `before_id_bigint` bigint(20) unsigned DEFAULT NULL,
  `before_lang_enum` varchar(7) DEFAULT NULL,
  `after_id_bigint` bigint(20) unsigned DEFAULT NULL,
  `after_lang_enum` varchar(7) DEFAULT NULL,
  `change_type_enum` varchar(32) NOT NULL,
  `before_object` blob,
  `after_object` blob,
  PRIMARY KEY (`id_bigint`),
  KEY `user_id_bigint` (`user_id_bigint`),
  KEY `service_body_id_bigint` (`service_body_id_bigint`),
  KEY `lang_enum` (`lang_enum`),
  KEY `change_type_enum` (`change_type_enum`),
  KEY `change_date` (`change_date`),
  KEY `before_id_bigint` (`before_id_bigint`),
  KEY `after_id_bigint` (`after_id_bigint`),
  KEY `before_lang_enum` (`before_lang_enum`),
  KEY `after_lang_enum` (`after_lang_enum`),
  KEY `object_class_string` (`object_class_string`),
  FULLTEXT KEY `change_name_string` (`change_name_string`),
  FULLTEXT KEY `change_description_text` (`change_description_text`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `na_comdef_formats` (
  `shared_id_bigint` bigint(20) unsigned NOT NULL,
  `key_string` varchar(255) DEFAULT NULL,
  `icon_blob` longblob,
  `worldid_mixed` varchar(255) DEFAULT NULL,
  `lang_enum` varchar(7) NOT NULL DEFAULT 'en',
  `name_string` tinytext,
  `description_string` text,
  `format_type_enum` varchar(7) DEFAULT NULL,
  KEY `shared_id_bigint` (`shared_id_bigint`),
  KEY `worldid_mixed` (`worldid_mixed`),
  KEY `format_type_enum` (`format_type_enum`),
  KEY `lang_enum` (`lang_enum`),
  KEY `key_string` (`key_string`),
  FULLTEXT KEY `description_string` (`description_string`),
  FULLTEXT KEY `name_string` (`name_string`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO `na_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'B', NULL, NULL, 'en', 'Beginners', 'This meeting is focused on the needs of new members of NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'en', 'Bi-Lingual', 'This Meeting can be attended by speakers of English and another language.', 'FC3'),
(3, 'BT', NULL, NULL, 'en', 'Basic Text', 'This meeting is focused on discussion of the Basic Text of Narcotics Anonymous.', 'FC1'),
(4, 'C', NULL, NULL, 'en', 'Closed', 'This meeting is closed to non-addicts. You should attend only if you believe that you may have a problem with substance abuse.', 'FC3'),
(5, 'CH', NULL, NULL, 'en', 'Closed Holidays', 'This meeting gathers in a facility that is usually closed on holidays.', 'FC3'),
(6, 'CL', NULL, NULL, 'en', 'Candlelight', 'This meeting is held by candlelight.', 'FC2'),
(7, 'CS', NULL, NULL, 'en', 'Children under Supervision', 'Well-behaved, supervised children are welcome.', 'FC3'),
(8, 'D', NULL, NULL, 'en', 'Discussion', 'This meeting invites participation by all attendees.', 'FC1'),
(9, 'ES', NULL, NULL, 'en', 'Espanol', 'This meeting can be attended by speakers of Spanish.', 'FC3'),
(10, 'GL', NULL, NULL, 'en', 'Gay/Lesbian', 'This meeting is focused on the needs of gay and lesbian members of NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'en', 'Illness', 'This meeting is focused on the needs of NA members with chronic illness.', 'FC1'),
(12, 'IP', NULL, NULL, 'en', 'Informational Pamphlet', 'This meeting is focused on discussion of one or more Informational Pamphlets.', 'FC1'),
(13, 'IW', NULL, NULL, 'en', 'It Works -How and Why', 'This meeting is focused on discussion of the It Works -How and Why text.', 'FC1'),
(14, 'JT', NULL, NULL, 'en', 'Just for Today', 'This meeting is focused on discussion of the Just For Today text.', 'FC1'),
(15, 'M', NULL, NULL, 'en', 'Men', 'This meeting is meant to be attended by men only.', 'FC3'),
(16, 'NC', NULL, NULL, 'en', 'No Children', 'Please do not bring children to this meeting.', 'FC3'),
(17, 'O', NULL, NULL, 'en', 'Open', 'This meeting is open to addicts and non-addicts alike. All are welcome.', 'FC3'),
(18, 'Pi', NULL, NULL, 'en', 'Pitch', 'This meeting has a format that consists of each person who shares picking the next person.', 'FC1'),
(19, 'RF', NULL, NULL, 'en', 'Rotating Format', 'This meeting has a format that changes for each meeting.', 'FC1'),
(20, 'Rr', NULL, NULL, 'en', 'Round Robin', 'This meeting has a fixed sharing order (usually a circle.)', 'FC1'),
(21, 'SC', NULL, NULL, 'en', 'Surveillance Cameras', 'This meeting is held in a facility that has surveillance cameras.', 'FC2'),
(22, 'SD', NULL, NULL, 'en', 'Speaker/Discussion', 'This meeting is lead by a speaker, then opened for participation by attendees.', 'FC1'),
(23, 'SG', NULL, NULL, 'en', 'Step Working Guide', 'This meeting is focused on discussion of the Step Working Guide text.', 'FC1'),
(24, 'SL', NULL, NULL, 'en', 'ASL', 'This meeting provides an American Sign Language (ASL) interpreter for the deaf.', 'FC2'),
(25, 'Sm', NULL, NULL, 'en', 'Smoking Permitted', 'Smoking (of tobacco) is permitted at this meeting.', 'FC2'),
(26, 'So', NULL, NULL, 'en', 'Speaker Only', 'This meeting is a speaker-only meeting. Other attendees do not participate in the discussion.', 'FC1'),
(27, 'St', NULL, NULL, 'en', 'Step', 'This meeting is focused on discussion of the Twelve Steps of NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'en', 'Timer', 'This meeting has sharing time limited by a timer.', 'FC1'),
(29, 'To', NULL, NULL, 'en', 'Topic', 'This meeting is based upon a topic chosen by a speaker or by group conscience.', 'FC1'),
(30, 'Tr', NULL, NULL, 'en', 'Tradition', 'This meeting is focused on discussion of the Twelve Traditions of NA.', 'FC1'),
(31, 'TW', NULL, NULL, 'en', 'Traditions Workshop', 'This meeting engages in detailed discussion of one or more of the Twelve Traditions of N.A.', 'FC1'),
(32, 'W', NULL, NULL, 'en', 'Women', 'This meeting is meant to be attended by women only.', 'FC3'),
(33, 'WC', NULL, NULL, 'en', 'Wheelchair', 'This meeting is wheelchair accessible.', 'FC2'),
(34, 'YP', NULL, NULL, 'en', 'Young People', 'This meeting is focused on the needs of younger members of NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'en', 'Open-Ended', 'No fixed duration. The meeting continues until everyone present has had a chance to share.', 'FC1'),
(36, 'BK', NULL, NULL, 'en', 'Book Study', 'Approved N.A. Books', 'FC1'),
(37, 'NS', NULL, NULL, 'en', 'No Smoking', 'Smoking is not allowed at this meeting.', 'FC1'),
(39, 'FD', NULL, NULL, 'en', 'Five and Dime', 'Discussion of the Fifth Step and the Tenth Step', 'FC1'),
(40, 'AB', NULL, NULL, 'en', 'Ask-It-Basket', 'A topic is chosen from suggestions placed into a basket.', 'FC1'),
(41, 'ME', NULL, NULL, 'en', 'Meditation', 'This meeting encourages its participants to engage in quiet meditation.', 'FC1'),
(42, 'RA', NULL, NULL, 'en', 'Restricted Attendance', 'This facility places restrictions on attendees.', 'FC3'),
(43, 'QA', NULL, NULL, 'en', 'Question and Answer', 'Attendees may ask questions and expect answers from Group members.', 'FC1'),
(44, 'CW', NULL, NULL, 'en', 'Children Welcome', 'Children are welcome at this meeting.', 'FC3'),
(45, 'CP', NULL, NULL, 'en', 'Concepts', 'This meeting is focused on discussion of the twelve concepts of NA.', 'FC1'),
(1, 'B', NULL, NULL, 'es', 'Para el recién llegado', 'Esta reunión se centra en las necesidades de los nuevos miembros de NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'es', 'Bilingüe', 'Esta reunión se pueden asistir personas de que hablen inglés y otro idioma.', 'FC3'),
(3, 'BT', NULL, NULL, 'es', 'Texto Básico', 'Esta reunión se centra en la discusión del texto básico de Narcóticos Anónimos.', 'FC1'),
(4, 'C', NULL, NULL, 'es', 'Cerrado', 'Esta reunión está cerrada a los no adictos. Usted debe asistir solamente si cree que puede tener un problema con abuso de drogas.', 'FC3'),
(5, 'CH', NULL, NULL, 'es', 'Cerrado en Días de fiesta', 'Esta reunión tiene lugar en una localidad que esta generalmente cerrada los días de fiesta.', 'FC3'),
(6, 'CL', NULL, NULL, 'es', 'Luz de vela', 'Esta reunión se celebra a luz de vela.', 'FC2'),
(7, 'CS', NULL, NULL, 'es', 'Niños bajo Supervisión', 'Los niños de buen comportamiento y supervisados son bienvenidos.', 'FC3'),
(8, 'D', NULL, NULL, 'es', 'Discusión', 'Esta reunión invita la participación de todos los asistentes.', 'FC1'),
(9, 'ES', NULL, NULL, 'es', 'Español', 'A esta reunión pueden asistir personas que hablen español.', 'FC3'),
(10, 'GL', NULL, NULL, 'es', 'Gay/Lesbiana', 'Esta reunión se centra en las necesidades de miembros gay y lesbianas de NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'es', 'Enfermedad', 'Esta reunión se centra en las necesidades de los miembros de NA con enfermedades crónicas.', 'FC1'),
(12, 'IP', NULL, NULL, 'es', 'Folleto Informativo', 'Esta reunión se centra en la discusión de unos o más folletos informativos.', 'FC1'),
(13, 'IW', NULL, NULL, 'es', 'Functiona - Cómo y Porqué', 'Esta reunión se centra en la discusión del texto Funciona - Cómo y Porqué.', 'FC1'),
(14, 'JT', NULL, NULL, 'es', 'Solo por Hoy', 'Esta reunión se centra en la discusión del texto Solo por Hoy.', 'FC1'),
(15, 'M', NULL, NULL, 'es', 'Hombres', 'A esta reunión se supone que aistan hombres solamente.', 'FC3'),
(16, 'NC', NULL, NULL, 'es', 'No niños', 'Por favor no traer niños a esta reunión.', 'FC3'),
(17, 'O', NULL, NULL, 'es', 'Abierta', 'Esta reunión está abierta a los adictos y a los no adictos por igual. Todos son bienvenidos.', 'FC3'),
(18, 'Pi', NULL, NULL, 'es', 'Echada', 'Esta reunión tiene un formato que consiste en que cada persona que comparta escoja a la persona siguiente.', 'FC1'),
(19, 'RF', NULL, NULL, 'es', 'Formato que Rota', 'Esta reunión tiene un formato que cambia para cada reunión.', 'FC1'),
(20, 'Rr', NULL, NULL, 'es', 'Round Robin', 'Esta reunión tiene un orden fijo de compartir (generalmente un círculo).', 'FC1'),
(21, 'SC', NULL, NULL, 'es', 'Cámaras de Vigilancia', 'Esta reunión se celebra en una localidad que tenga cámaras de vigilancia.', 'FC2'),
(22, 'SD', NULL, NULL, 'es', 'Orador/Discusión', 'Esta reunión es conducida por un orador, después es abierta para la participación de los asistentes.', 'FC1'),
(23, 'SG', NULL, NULL, 'es', 'Guia Para Trabajar los Pasos', 'Esta reunión se centra en la discusión del texto Guia Para Trabajar los Pasos.', 'FC1'),
(24, 'SL', NULL, NULL, 'es', 'ASL', 'Esta reunión proporciona intérprete (ASL) para los sordos.', 'FC2'),
(25, 'Sm', NULL, NULL, 'es', 'Permitido Fumar', 'El fumar (tabaco) es permitido en esta reunión.', 'FC2'),
(26, 'So', NULL, NULL, 'es', 'Solamente Orador', 'Esta reunión es de orador solamente. Otros asistentes no participan en la discusión.', 'FC1'),
(27, 'St', NULL, NULL, 'es', 'Paso', 'Esta reunión se centra en la discusión de los doce pasos de NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'es', 'Contador de Tiempo', 'Esta reunión tiene el tiempo de compartir limitado por un contador de tiempo.', 'FC1'),
(29, 'To', NULL, NULL, 'es', 'Tema', 'Esta reunión se basa en un tema elegido por el orador o por la conciencia del grupo.', 'FC1'),
(30, 'Tr', NULL, NULL, 'es', 'Tradición', 'Esta reunión se centra en la discusión de las Doce Tradiciones de NA.', 'FC1'),
(31, 'TW', NULL, NULL, 'es', 'Taller de las Tradiciones', 'Esta reunión consiste en la discusión detallada de una o más de las Doce Tradiciones de N.A.', 'FC1'),
(32, 'W', NULL, NULL, 'es', 'Mujeres', 'A esta reunión se supone que asistan mujeres solamente.', 'FC3'),
(33, 'WC', NULL, NULL, 'es', 'Silla de Ruedas', 'Esta reunión es accesible por silla de ruedas.', 'FC2'),
(34, 'YP', NULL, NULL, 'es', 'Jovenes', 'Esta reunión se centra en las necesidades de los miembros más jóvenes de NA.', 'FC1'),
(35, 'OE', NULL, NULL, 'es', 'Sin Tiempo Fijo', 'No tiene tiempo fijo. Esta reunión continua hasta que cada miembro haya tenido la oportunidad de compartir.', 'FC1');
CREATE TABLE IF NOT EXISTS `na_comdef_meetings_data` (
  `meetingid_bigint` bigint(20) unsigned NOT NULL,
  `key` varchar(32) NOT NULL,
  `field_prompt` tinytext,
  `lang_enum` varchar(7) DEFAULT NULL,
  `visibility` int(1) DEFAULT NULL,
  `data_string` tinytext,
  `data_bigint` bigint(20) DEFAULT NULL,
  `data_double` double DEFAULT NULL,
  KEY `data_bigint` (`data_bigint`),
  KEY `data_double` (`data_double`),
  KEY `meetingid_bigint` (`meetingid_bigint`),
  KEY `lang_enum` (`lang_enum`),
  KEY `key` (`key`),
  KEY `visibility` (`visibility`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
INSERT INTO `na_comdef_meetings_data` (`meetingid_bigint`, `key`, `field_prompt`, `lang_enum`, `visibility`, `data_string`, `data_bigint`, `data_double`) VALUES
(0, 'meeting_name', 'Meeting Name', 'en', NULL, 'Meeting Name', NULL, NULL),
(0, 'location_text', 'Location Name', 'en', NULL, 'Location Name', NULL, NULL),
(0, 'location_info', 'Additional Location Information', 'en', NULL, 'Additional Location Information', NULL, NULL),
(0, 'location_street', 'Street Address', 'en', NULL, 'Street Address', NULL, NULL),
(0, 'location_city_subsection', 'Borough', 'en', NULL, 'Borough', NULL, NULL),
(0, 'location_neighborhood', 'Neighborhood', 'en', NULL, 'Neighborhood', NULL, NULL),
(0, 'location_municipality', 'Town', 'en', NULL, 'Town', NULL, NULL),
(0, 'location_sub_province', 'County', 'en', NULL, 'County', NULL, NULL),
(0, 'location_province', 'State', 'en', NULL, 'State', NULL, NULL),
(0, 'location_postal_code_1', 'Zip Code', 'en', NULL, NULL, 0, NULL),
(0, 'location_nation', 'Nation', 'en', NULL, 'Nation', NULL, NULL),
(0, 'comments', 'Comments', 'en', NULL, 'Comments', NULL, NULL),
(0, 'train_lines', 'Train Lines', 'en', NULL, NULL, NULL, NULL),
(0, 'bus_lines', 'Bus Lines', 'en', NULL, NULL, NULL, NULL),
(0, 'contact_phone_2', 'Contact 2 Phone', 'en', 1, 'Contact 2 Phone', NULL, NULL),
(0, 'contact_email_2', 'Contact 2 Email', 'en', 1, 'Contact 2 Email', NULL, NULL),
(0, 'contact_name_2', 'Contact 2 Name', 'en', 1, 'Contact 2 Name', NULL, NULL),
(0, 'contact_phone_1', 'Contact 1 Phone', 'en', 1, 'Contact 1 Phone', NULL, NULL),
(0, 'contact_email_1', 'Contact 1 Email', 'en', 1, 'Contact 1 Email', NULL, NULL),
(0, 'contact_name_1', 'Contact 1 Name', 'en', 1, 'Contact 1 Name', NULL, NULL);
CREATE TABLE IF NOT EXISTS `na_comdef_meetings_longdata` (
  `meetingid_bigint` bigint(20) unsigned NOT NULL,
  `key` varchar(32) NOT NULL,
  `field_prompt` varchar(255) DEFAULT NULL,
  `lang_enum` varchar(7) DEFAULT NULL,
  `visibility` int(1) DEFAULT NULL,
  `data_longtext` text,
  `data_blob` blob,
  KEY `meetingid_bigint` (`meetingid_bigint`),
  KEY `lang_enum` (`lang_enum`),
  KEY `field_prompt` (`field_prompt`),
  KEY `key` (`key`),
  KEY `visibility` (`visibility`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
CREATE TABLE IF NOT EXISTS `na_comdef_meetings_main` (
  `id_bigint` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `worldid_mixed` varchar(255) DEFAULT NULL,
  `shared_group_id_bigint` bigint(20) DEFAULT NULL,
  `service_body_bigint` bigint(20) unsigned NOT NULL,
  `weekday_tinyint` tinyint(4) unsigned DEFAULT NULL,
  `start_time` time DEFAULT NULL,
  `duration_time` time DEFAULT NULL,
  `formats` varchar(255) DEFAULT NULL,
  `lang_enum` varchar(7) DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `published` tinyint(4) NOT NULL DEFAULT '0',
  `email_contact` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id_bigint`),
  KEY `weekday_tinyint` (`weekday_tinyint`),
  KEY `service_body_bigint` (`service_body_bigint`),
  KEY `start_time` (`start_time`),
  KEY `duration_time` (`duration_time`),
  KEY `formats` (`formats`),
  KEY `lang_enum` (`lang_enum`),
  KEY `worldid_mixed` (`worldid_mixed`),
  KEY `shared_group_id_bigint` (`shared_group_id_bigint`),
  KEY `longitude` (`longitude`),
  KEY `latitude` (`latitude`),
  KEY `published` (`published`),
  KEY `email_contact` (`email_contact`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;
CREATE TABLE IF NOT EXISTS `na_comdef_service_bodies` (
  `id_bigint` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name_string` tinytext NOT NULL,
  `description_string` text NOT NULL,
  `lang_enum` varchar(7) NOT NULL DEFAULT 'en',
  `worldid_mixed` varchar(255) DEFAULT NULL,
  `kml_file_uri_string` varchar(255) DEFAULT NULL,
  `principal_user_bigint` bigint(20) unsigned DEFAULT NULL,
  `editors_string` varchar(255) DEFAULT NULL,
  `uri_string` varchar(255) DEFAULT NULL,
  `sb_type` varchar(32) DEFAULT NULL,
  `sb_owner` bigint(20) unsigned DEFAULT NULL,
  `sb_owner_2` bigint(20) unsigned DEFAULT NULL,
  `sb_meeting_email` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`id_bigint`),
  KEY `worldid_mixed` (`worldid_mixed`),
  KEY `kml_file_uri_string` (`kml_file_uri_string`),
  KEY `principal_user_bigint` (`principal_user_bigint`),
  KEY `editors_string` (`editors_string`),
  KEY `lang_enum` (`lang_enum`),
  KEY `uri_string` (`uri_string`),
  KEY `sb_type` (`sb_type`),
  KEY `sb_owner` (`sb_owner`),
  KEY `sb_owner_2` (`sb_owner_2`),
  KEY `sb_meeting_email` (`sb_meeting_email`),
  FULLTEXT KEY `name_string` (`name_string`),
  FULLTEXT KEY `description_string` (`description_string`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1047 ;
INSERT INTO `na_comdef_service_bodies` (`id_bigint`, `name_string`, `description_string`, `lang_enum`, `worldid_mixed`, `kml_file_uri_string`, `principal_user_bigint`, `editors_string`, `uri_string`, `sb_type`, `sb_owner`, `sb_owner_2`, `sb_meeting_email`) VALUES
(1, 'Initial Service Body', '', 'en', '', '', 2, '0', '', 'RS', 0, 0, '');
CREATE TABLE IF NOT EXISTS `na_comdef_users` (
  `id_bigint` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_level_tinyint` tinyint(4) unsigned NOT NULL DEFAULT '0',
  `name_string` tinytext NOT NULL,
  `description_string` text NOT NULL,
  `email_address_string` varchar(255) NOT NULL,
  `login_string` varchar(255) NOT NULL,
  `password_string` varchar(255) NOT NULL,
  `last_access_datetime` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `lang_enum` varchar(7) NOT NULL DEFAULT 'en',
  PRIMARY KEY (`id_bigint`),
  UNIQUE KEY `login_string` (`login_string`),
  KEY `user_level_tinyint` (`user_level_tinyint`),
  KEY `email_address_string` (`email_address_string`),
  KEY `last_access_datetime` (`last_access_datetime`),
  KEY `lang_enum` (`lang_enum`),
  FULLTEXT KEY `name_string` (`name_string`),
  FULLTEXT KEY `description_string` (`description_string`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=58 ;
INSERT INTO `na_comdef_users` (`id_bigint`, `user_level_tinyint`, `name_string`, `description_string`, `email_address_string`, `login_string`, `password_string`, `last_access_datetime`, `lang_enum`) VALUES
(1, 1, 'Server Administrator', '', '', '%ADMIN-LOGIN%', '%ADMIN-PW%', '0000-00-00 00:00:00', 'en'),
(2, 2, 'First Service Body Admin', '', '', 'sb_admin', '%SB-ADMIN-PW%', '0000-00-00 00:00:00', 'en');
