BMLT Root Server: PhpJsonXmlArrayStringInterchanger Class Reference
PhpJsonXmlArrayStringInterchanger Class Reference
Public Member Functions
displayLastError ()
displayErrorLog ()
convertXmlToArray ($xmlContent)
convertArrayToXML ($array)
convertJsonToXML ($json)
convertJsonToArray ($json)
convertStringToArray ($string, &$myarray="")
convertXmltoString ($xml)
Private Member Functions
parseXml ($ret)
parseArray ($array)
convertArrayToString ($myarray, &$output="", &$parentkey="")
Private Attributes
$errorLog =array()
Detailed Description
Definition at line 14 of file PhpJsonXmlArrayStringInterchanger.inc.php.
Member Function Documentation
convertArrayToString()
convertArrayToString ($myarray, & $output = "", & $parentkey = "") private
Function to parse Array and convert it into string
Parameters
array $array private
Returns
string on success and false on failure
Definition at line 236 of file PhpJsonXmlArrayStringInterchanger.inc.php.
References LINE_SEPERATOR.
Referenced by convertXmltoString().
     {
         if (is_array($myarray)) {
             if (trim($parentkey)=="") {
                 $parentkey=LINE_SEPERATOR;
             }
             foreach ($myarray as $key => $value) {
                 if (is_array($value)) {
                     $parentkey .= $key.NODE_SEPERATOR;
                     $this->convertArrayToString($value, $output, $parentkey);
                     $parentkey = "";
                 } else {
                     $output .= $parentkey.$key.NODE_SEPERATOR.$value.LINE_SEPERATOR;
                 }
             }
         } else {
             $this->errorLog[]="Invalid array in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
             return false;
         }
         return $output;
     }
convertArrayToXML()
convertArrayToXML ($array)
Function to convert an associative array into XML
Parameters
string $array public
Returns
string(xml) on success and false on failure
Definition at line 144 of file PhpJsonXmlArrayStringInterchanger.inc.php.
References parseArray().
Referenced by convertJsonToXML().
     {
         $return="<?xml version='1.0' encoding='ISO-8859-1'?><PhpJsonXmlArrayStringInterchanger>";
         $return.=$this->parseArray($array);
         $return.="</PhpJsonXmlArrayStringInterchanger>";
         return $return;
     }
convertJsonToArray()
convertJsonToArray ($json)
Function to convert an JSON into array
Parameters
string $json public
Returns
array on success and false on failure
Definition at line 181 of file PhpJsonXmlArrayStringInterchanger.inc.php.
     {
         if (!is_string($json)) {
             $this->errorLog[]="The first parameter should to be string in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
             return false;
         }
         $json=str_replace("\\'", "'", $json);
         $json=str_replace('\\"', '"', $json);
         $array=json_decode($json, true);
         if ($array===false) {
             $this->errorLog[]="Failed to decode JSON in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
             return false;
         } else {
             return $array;
         }
     }
convertJsonToXML()
convertJsonToXML ($json)
Function to convert an JSON into XML
Parameters
string $json public
Returns
string(xml) on success and false on failure
Definition at line 159 of file PhpJsonXmlArrayStringInterchanger.inc.php.
References convertArrayToXML().
     {
         if (!is_string($json)) {
             $this->errorLog[]="The first parameter should to be string in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
             return false;
         }
         $array=json_decode($json, true);
         if ($array===false) {
             $this->errorLog[]="Failed to decode JSON in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
             return false;
         } else {
             return $this->convertArrayToXML($array);
         }
     }
convertStringToArray()
convertStringToArray ($string, & $myarray = "")
Function to parse String and convert it into array
Parameters
array $array public
Returns
array on success and false on failure
Definition at line 207 of file PhpJsonXmlArrayStringInterchanger.inc.php.
References LINE_SEPERATOR, and NODE_SEPERATOR.
     {
         $lines = explode(LINE_SEPERATOR, $string);
         foreach ($lines as $value) {
             $items = explode(NODE_SEPERATOR, $value);
             if (sizeof($items) == 2) {
                 $myarray[$items[0]] = $items[1];
             } elseif (sizeof($items) == 3) {
                 $myarray[$items[0]][$items[1]] = $items[2];
             } elseif (sizeof($items) == 4) {
                 $myarray[$items[0]][$items[1]] [$items[2]] = $items[3];
             } elseif (sizeof($items) == 5) {
                 $myarray[$items[0]][$items[1]] [$items[2]][$items[3]] = $items[4];
             } elseif (sizeof($items) == 6) {
                 $myarray[$items[0]][$items[1]] [$items[2]][$items[3]][$items[4]] = $items[5];
             } elseif (sizeof($items) == 7) {
                 $myarray[$items[0]][$items[1]] [$items[2]][$items[3]][$items[4]][$items[5]] = $items[6];
             }
         }
         return $myarray;
     }
convertXmlToArray()
convertXmlToArray ($xmlContent)
Function to convert XML into Array
Parameters
string $xmlContent public
Returns
array on success and false on failure
Definition at line 88 of file PhpJsonXmlArrayStringInterchanger.inc.php.
References $ret, and parseXml().
Referenced by convertXmltoString().
     {
         $return=false;
         $ret=simplexml_load_string($xmlContent);
         if ($ret===false) {
             $this->errorLog[]="Invalid XML content: $xmlContent in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
             return false;
         } else {
             $return=$this->parseXml($ret);
             if ($return===false) {
                 $this->errorLog[]="Failed to parse XML content in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
                 return false;
             }
         }
         return $return;
     }
convertXmltoString()
convertXmltoString ($xml)
Function to convert XML into string
Parameters
string $xml
Returns
string on success and false on failure
Definition at line 264 of file PhpJsonXmlArrayStringInterchanger.inc.php.
References convertArrayToString(), and convertXmlToArray().
     {
         $array=$this->convertXmlToArray($xml);
         if ($array===false) {
             return false;
         } else {
             return $this->convertArrayToString($array);
         }
     }
displayErrorLog()
displayErrorLog ()
Function to display complete error log for debugging purpose
public
Returns
string
Definition at line 42 of file PhpJsonXmlArrayStringInterchanger.inc.php.
     {
         $return="No errors were encountered.";
         $c=count($this->errorLog);
         if ($c>0) {
             $return="";
             for ($i=0; $i<$c; $i++) {
                 $return.="<div style='".ERROR_STYLE."'>".$this->errorLog[$i]."</div>";
             }
         }
         echo $return;
     }
displayLastError()
displayLastError ()
Function to display last error for debugging purpose
public
Returns
string
Definition at line 25 of file PhpJsonXmlArrayStringInterchanger.inc.php.
     {
         $return="No errors were encountered.";
         $c=count($this->errorLog);
         if ($c>0) {
             $i=$c-1;
             $return="<div style='".ERROR_STYLE."'>".$this->errorLog[$i]."</div>";
         }
         echo $return;
     }
parseArray()
parseArray ($array) private
Function to recursivly parse Array Content
Parameters
mixed $ret private
Returns
string(xml) on success and false on failure
Definition at line 112 of file PhpJsonXmlArrayStringInterchanger.inc.php.
Referenced by convertArrayToXML().
     {
         if (is_array($array)) {
             foreach ($array as $k => $v) {
                 if (trim($k)=="") {
                     $this->errorLog[]="Array needs to be associative as parameter in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
                     return false;
                 } else {
                     if (is_numeric($k)) {
                         $k="nodeValue$k";
                     }
                     if (is_array($v)) {
                         $return.="<$k>".$this->parseArray($v)."</$k>";
                     } else {
                         $return.="<$k>$v</$k>";
                     }
                 }
             }
         } else {
             $this->errorLog[]="Invalid array in function: ".__FUNCTION__." on line: ".__LINE__." in filename= ".__FILE__;
             return false;
         }
         return $return;
     }
parseXml()
parseXml ($ret) private
Function to recursivly parse Xml Content
Parameters
mixed $ret private
Returns
array on success and false on failure
Definition at line 62 of file PhpJsonXmlArrayStringInterchanger.inc.php.
References $ret.
Referenced by convertXmlToArray().
     {
         $return=false;
         if (is_object($ret)) {
             $ret=(array)$ret;
             $this->parseXml($ret);
         }
         if (is_array($ret)) {
             foreach ($ret as $k => $v) {
                 if (is_object($v)) {
                     $return[$k]=$this->parseXml($v);
                 } else {
                     $return[$k]=$v  ;
                 }
             }
         }
         return $return;
     }
Member Data Documentation
$errorLog
$errorLog =array() private
Definition at line 17 of file PhpJsonXmlArrayStringInterchanger.inc.php.
The documentation for this class was generated from the following file:
/Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/local_server/server_admin/PhpJsonXmlArrayStringInterchanger.inc.php