BMLT Root Server: /home/travis/build/bmlt-enabled/bmlt-root-server/main_server/client_interface/csv/search_results_csv.php File Reference
search_results_csv.php File Reference
This file represents a View layer of the BMLT MVC pattern. It will do a meeting search, and return the results as comma-separated values (CSV). It is not an object-oriented file, and is quite simple to use. For many people, the procedural View Layer files may be all they need to see. The object-oriented stuff is encapsulated within.
Functions
if(!isset($g_format_dictionary)||!is_array($g_format_dictionary)||!count($g_format_dictionary)) bmlt_populate_format_dictionary ()
This reads in the server format codes, and populates the format dictionary with the NAWS IDs.
DisplaySearchResultsCSV ($in_http_vars, &$return_array=null, &$return_geocode=null, &$return_results=null, $in_supress_hidden_concat=false, $in_editor_only=false)
This function does a search, then builds a CSV result, with each row being a meeting. The first row is a row of keys.
ReturnNAWSFormatCSV ($in_http_vars, &$server)
Returns the CSV file in NAWS format.
ReturnNAWSDeletedMeetings (&$server, $in_transfer_dictionary, $in_services)
Returns deleted meetings with NAWS IDs.
BMLT_FuncNAWSReturnPublishedStatus ($in_meeting_id, &$server)
Returns '' or '1', if the meeting is unpublished or not (used for the NAWS format)
BMLT_FuncNAWSReturnOpenOrClosed ($in_meeting_id, &$server)
Returns 'OPEN' or 'CLOSED', if the meeting is open or closed (used for the NAWS format)
BMLT_FuncNAWSReturnWheelchair ($in_meeting_id, &$server)
Returns 'TRUE' or 'FALSE', if the meeting is or is not wheelchair-accessible (used for the NAWS format)
BMLT_FuncNAWSReturnInst ($in_meeting_id, &$server)
Returns 'TRUE' or 'FALSE', if the meeting is or is not an institution meeting (used for the NAWS format)
BMLT_FuncNAWSReturnWeekday ($in_meeting_id, &$server)
Returns the string for the weekday the meeting gathers (used for the NAWS format)
BMLT_FuncNAWSReturnTime ($in_meeting_id, &$server)
Returns the string for the weekday the meeting gathers (used for the NAWS format)
BMLT_FuncNAWSReturnLanguage1 ($in_meeting_id, &$server)
Returns the string for the first alternative language (if any)
BMLT_FuncNAWSReturnMeetingNAWSID ($in_meeting_id, &$server)
Returns the string for the NAWS ID for the meeting (used for the NAWS format)
BMLT_FuncNAWSReturnMeetingTown ($in_meeting_id, &$server)
Returns the string for the town field the meeting (used for the NAWS format). This may use the borough name, instead.
BMLT_FuncNAWSReturnLastMeetingChangeTime ($in_meeting_id, &$server)
Returns the latest changed date for the given meeting.
BMLT_FuncNAWSReturnMeetingServiceBodyNAWSID ($in_meeting_id, &$server)
Returns the string for the NAWS ID for the meeting's Service Body (used for the NAWS format)
BMLT_FuncNAWSReturnNonNawsFormats ($in_meeting_id, &$server)
Returns a string of all formats that don't map to NAWS codes.
BMLT_FuncNAWSReturnDirections ($in_meeting_id, &$server)
Returns a string of location_info and comments fields.
BMLT_FuncNAWSReturnFormat1 ($in_meeting_id, &$server)
Returns the string for the first format (used for the NAWS format)
BMLT_FuncNAWSReturnFormat2 ($in_meeting_id, &$server)
Returns the string for the second format (used for the NAWS format)
BMLT_FuncNAWSReturnFormat3 ($in_meeting_id, &$server)
Returns the string for the third format (used for the NAWS format)
BMLT_FuncNAWSReturnFormat4 ($in_meeting_id, &$server)
Returns the string for the fourth format (used for the NAWS format)
BMLT_FuncNAWSReturnFormat5 ($in_meeting_id, &$server)
Returns the string for the fifth format (used for the NAWS format)
BMLT_FuncNAWSReturnFormat ($n, $in_meeting_id, &$server)
Returns the string for the n-th format (used for the NAWS format)
BMLT_FuncNAWSReturnMeetingServiceBodyName ($in_meeting_id, &$server)
Returns the string for the name for the meeting's Service Body (used for the NAWS format)
Variables
global $g_format_dictionary
This is a dictionary used to translate formats to NAWS format. It uses the format shared IDs in the server's language.
Detailed Description
This file represents a View layer of the BMLT MVC pattern. It will do a meeting search, and return the results as comma-separated values (CSV). It is not an object-oriented file, and is quite simple to use. For many people, the procedural View Layer files may be all they need to see. The object-oriented stuff is encapsulated within.
The way you use this file is to call DisplaySearchResultsCSV with an array that contains values that specify the search.
This file is part of the Basic Meeting List Toolbox (BMLT).
Find out more at: https://bmlt.app
BMLT is free software: you can redistribute it and/or modify it under the terms of the MIT License.
BMLT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the MIT License for more details.
You should have received a copy of the MIT License along with this code. If not, see https://opensource.org/licenses/MIT.
Definition in file search_results_csv.php.
Function Documentation
BMLT_FuncNAWSReturnDirections ($in_meeting_id, & $server)
Returns a string of location_info and comments fields.
Returns
A string The location_info and comments fields.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1181 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = "";
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $ret = trim($the_meeting->GetMeetingDataValue('location_info'));
         if ($the_meeting->GetMeetingDataValue('comments')) {
             if ($ret) {
                 $ret .= ", ";
             }
             $ret .= trim($the_meeting->GetMeetingDataValue('comments'));
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnFormat ($n, $in_meeting_id, & $server)
Returns the string for the n-th format (used for the NAWS format)
Returns
A string The format code, in NAWS form.
Parameters
$n which format
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1279 of file search_results_csv.php.
References $g_format_dictionary, and $server.
Referenced by BMLT_FuncNAWSReturnFormat1(), BMLT_FuncNAWSReturnFormat2(), BMLT_FuncNAWSReturnFormat3(), BMLT_FuncNAWSReturnFormat4(), and BMLT_FuncNAWSReturnFormat5().
   {
     global $g_format_dictionary;
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         // $formats is an array of the formats for this meeting as they are stored in the BMLT database.
         // $naws_formats is an array of the NAWS versions of these formats - note that not everything in $formats
         // will have a corresponding NAWS versions.  Also there can also be several BMLT formats that map
         // to the same NAWS format -- in this case, only include one NAWS format.
         // This function is a bit stupid, since it gets called up to 5 times for the 5 possible NAWS formats --
         // more aesthetic (and slightly more efficient) would be to just call it once.  However, efficiency is not
         // terribly important here since this just gets called when producing an export spreadsheet.
         $formats = $the_meeting->GetMeetingDataValue('formats');
         $naws_formats = [];
         if (is_array($formats) && count($formats)) {
             foreach ($g_format_dictionary as $n_format => $b_formats) {
                 if (($n_format != 'OPEN') && ($n_format != 'CLOSED') && ($n_format != 'WCHR')) {
                     foreach ($b_formats as $b_format) {
                         if (isset($formats[$b_format]) && !in_array($n_format, $naws_formats)) {
                             array_push($naws_formats, $n_format);
                         }
                     }
                 }
             }
         }
         if ($n > count($naws_formats)) {
             return null;
         } else {
             return $naws_formats[$n-1];
         }
     }
 }
BMLT_FuncNAWSReturnFormat1 ($in_meeting_id, & $server)
Returns the string for the first format (used for the NAWS format)
Returns
A string The format code, in NAWS form.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1214 of file search_results_csv.php.
References $server, and BMLT_FuncNAWSReturnFormat().
   {
     return BMLT_FuncNAWSReturnFormat(1, $in_meeting_id, $server);
 }
BMLT_FuncNAWSReturnFormat2 ($in_meeting_id, & $server)
Returns the string for the second format (used for the NAWS format)
Returns
A string The format code, in NAWS form.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1227 of file search_results_csv.php.
References $server, and BMLT_FuncNAWSReturnFormat().
   {
     return BMLT_FuncNAWSReturnFormat(2, $in_meeting_id, $server);
 }
BMLT_FuncNAWSReturnFormat3 ($in_meeting_id, & $server)
Returns the string for the third format (used for the NAWS format)
Returns
A string The format code, in NAWS form.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1240 of file search_results_csv.php.
References $server, and BMLT_FuncNAWSReturnFormat().
   {
     return BMLT_FuncNAWSReturnFormat(3, $in_meeting_id, $server);
 }
BMLT_FuncNAWSReturnFormat4 ($in_meeting_id, & $server)
Returns the string for the fourth format (used for the NAWS format)
Returns
A string The format code, in NAWS form.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1253 of file search_results_csv.php.
References $server, and BMLT_FuncNAWSReturnFormat().
   {
     return BMLT_FuncNAWSReturnFormat(4, $in_meeting_id, $server);
 }
BMLT_FuncNAWSReturnFormat5 ($in_meeting_id, & $server)
Returns the string for the fifth format (used for the NAWS format)
Returns
A string The format code, in NAWS form.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1266 of file search_results_csv.php.
References $server, and BMLT_FuncNAWSReturnFormat().
   {
     return BMLT_FuncNAWSReturnFormat(5, $in_meeting_id, $server);
 }
BMLT_FuncNAWSReturnInst ($in_meeting_id, & $server)
Returns 'TRUE' or 'FALSE', if the meeting is or is not an institution meeting (used for the NAWS format)
Returns
A string, 'TRUE' or 'FALSE' (It will always be FALSE).
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 908 of file search_results_csv.php.
References $ret.
   {
     $ret = 'FALSE';
     return $ret;
 }
BMLT_FuncNAWSReturnLanguage1 ($in_meeting_id, & $server)
Returns the string for the first alternative language (if any)
Returns
A string.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 978 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = '';
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $formats = $the_meeting->GetMeetingDataValue('formats');
         $lang = $server->GetLocalLang();
         if (is_array($formats) && count($formats)) {
             foreach ($formats as $format) {
                 if ($format instanceof c_comdef_format) {
                     if ('LANG' == $format->GetWorldID()) {
                         $ret = strtoupper(trim($format->GetKey()));
                         break;
                     }
                 }
             }
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnLastMeetingChangeTime ($in_meeting_id, & $server)
Returns the latest changed date for the given meeting.
Returns
a date in ISO form ('2013-01-31').
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1073 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = null;
     $changes_obj = $server->GetChangesFromIDAndType('c_comdef_meeting', $in_meeting_id);
     if ($changes_obj instanceof c_comdef_changes) {
         $changes_objects = $changes_obj->GetChangesObjects();
         if (is_array($changes_objects) && count($changes_objects)) {
             $last_date = 0;
             foreach ($changes_objects as $change) {
                 $last_date = max($last_date, $change->GetChangeDate());
             }
             if ($last_date) {
                 $ret = date('n/j/y', $last_date);
             }
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnMeetingNAWSID ($in_meeting_id, & $server)
Returns the string for the NAWS ID for the meeting (used for the NAWS format)
Returns
A string The meeting ID, in NAWS form (G0000000).
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1015 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = null;
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $ret = trim($the_meeting->GetMeetingDataValue('worldid_mixed'));
     }
     return $ret;
 }
BMLT_FuncNAWSReturnMeetingServiceBodyName ($in_meeting_id, & $server)
Returns the string for the name for the meeting's Service Body (used for the NAWS format)
Returns
A string The Service Body name.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1325 of file search_results_csv.php.
References $ret, $server, c_comdef_service_body__ASC__, and c_comdef_service_body__RSC__.
   {
     $ret = null;
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $service_body = $the_meeting->GetServiceBodyObj();
         while (!$ret && ($service_body instanceof c_comdef_service_body)) {
             if (($service_body->GetSBType() == c_comdef_service_body__ASC__) || ($service_body->GetSBType() == c_comdef_service_body__RSC__)) {
                 $ret = $service_body->GetLocalName();
             } else {
                 $service_body = $service_body->GetOwnerIDObject();
             }
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnMeetingServiceBodyNAWSID ($in_meeting_id, & $server)
Returns the string for the NAWS ID for the meeting's Service Body (used for the NAWS format)
Returns
A string The Service Body ID, in NAWS form (RG/AR0000000).
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1105 of file search_results_csv.php.
References $ret, $server, c_comdef_service_body__ASC__, c_comdef_service_body__RSC__, and sprintf().
   {
     $ret = null;
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $service_body = $the_meeting->GetServiceBodyObj();
         $ret2 = intval(preg_replace('|\D*?|', '', trim($service_body->GetWorldID())));
         if ($service_body instanceof c_comdef_service_body) {
             if ($service_body->GetSBType() == c_comdef_service_body__ASC__) {
                 if ($ret2) {
                     $ret = sprintf('AR%05d', $ret2);
                 }
             } elseif ($service_body->GetSBType() == c_comdef_service_body__RSC__) {
                 if ($ret2) {
                     $ret = sprintf('RG%03d', $ret2);
                 }
             }
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnMeetingTown ($in_meeting_id, & $server)
Returns the string for the town field the meeting (used for the NAWS format). This may use the borough name, instead.
Returns
A string The meeting town.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1039 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = null;
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         // Our first choice is the borough/ku.
         $ret = trim($the_meeting->GetMeetingDataValue('location_city_subsection'));
         if (!$ret) {
             $ret = trim($the_meeting->GetMeetingDataValue('location_municipality'));
         }
         // If all else fails, we use the neighborhood.
         if (!$ret) {
             $ret = trim($the_meeting->GetMeetingDataValue('location_neighborhood'));
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnNonNawsFormats ($in_meeting_id, & $server)
Returns a string of all formats that don't map to NAWS codes.
Returns
A string The format codes name_string.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 1144 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = "";
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $formats = $the_meeting->GetMeetingDataValue('formats');
         if (is_array($formats) && count($formats)) {
             foreach ($formats as $format) {
                 if ($format != null && !$format->GetWorldID()) {
                     $ret .= $format->GetLocalName();
                     $ret .= ',';
                 }
             }
             $ret = rtrim($ret, ',');
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnOpenOrClosed ($in_meeting_id, & $server)
Returns 'OPEN' or 'CLOSED', if the meeting is open or closed (used for the NAWS format)
Returns
A string, 'OPEN' or 'CLOSED'.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID). This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 829 of file search_results_csv.php.
References $g_format_dictionary, $ret, $server, and c_comdef_server\GetLocalStrings().
   {
     global $g_format_dictionary;
     $localized_strings = c_comdef_server::GetLocalStrings();
     $ret = $localized_strings['default_closed_status'] ? 'CLOSED' : 'OPEN'; // This is the default closed/open status.
     $opposite = $localized_strings['default_closed_status'] ? 'OPEN' : 'CLOSED';
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     $ids = $g_format_dictionary[$opposite];
     if ($the_meeting instanceof c_comdef_meeting) {
         $formats = $the_meeting->GetMeetingDataValue('formats');
         if (is_array($formats) && count($formats) && is_array($ids)) {
             foreach ($ids as $id) {
                 if (isset($formats[$id])) {
                     $ret = $opposite;
                     break;
                 }
             }
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnPublishedStatus ($in_meeting_id, & $server)
Returns '' or '1', if the meeting is unpublished or not (used for the NAWS format)
Returns
A string, '' or '1'.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID). This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 804 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = '';
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $ret = $the_meeting->IsPublished() ? '' : '1';
     }
     return $ret;
 }
BMLT_FuncNAWSReturnTime ($in_meeting_id, & $server)
Returns the string for the weekday the meeting gathers (used for the NAWS format)
Returns
A string (the time, in pure military time - no seconds).
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 950 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = null;
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $ret = explode(':', $the_meeting->GetMeetingDataValue('start_time'));
         if (is_array($ret) && count($ret) > 1) {
             $ret = $ret[0].$ret[1];
         }
     }
     return $ret;
 }
BMLT_FuncNAWSReturnWeekday ($in_meeting_id, & $server)
Returns the string for the weekday the meeting gathers (used for the NAWS format)
Returns
A string ('Monday' - 'Friday').
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 923 of file search_results_csv.php.
References $ret, and $server.
   {
     $ret = null;
     $weekdays = array ( null, 'Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday' );
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     if ($the_meeting instanceof c_comdef_meeting) {
         $ret = $weekdays[$the_meeting->GetMeetingDataValue('weekday_tinyint')];
     }
     return $ret;
 }
BMLT_FuncNAWSReturnWheelchair ($in_meeting_id, & $server)
Returns 'TRUE' or 'FALSE', if the meeting is or is not wheelchair-accessible (used for the NAWS format)
Returns
A string, 'TRUE' or 'FALSE'.
Parameters
$in_meeting_id The ID of the meeting (internal DB ID) This can also be a meeting object.
$server A reference to an instance of c_comdef_server
Definition at line 870 of file search_results_csv.php.
References $g_format_dictionary, $ret, and $server.
   {
     global $g_format_dictionary;
     $ret = 'FALSE';
     if ($in_meeting_id instanceof c_comdef_meeting) {
         $the_meeting = $in_meeting_id;
     } else {
         $the_meeting = $server->GetOneMeeting($in_meeting_id);
     }
     $ids = $g_format_dictionary['WCHR'];
     if ($the_meeting instanceof c_comdef_meeting) {
         $formats = $the_meeting->GetMeetingDataValue('formats');
         if (is_array($formats) && count($formats) && is_array($ids)) {
             foreach ($ids as $id) {
                 if (isset($formats[$id])) {
                     $ret = 'TRUE';
                     break;
                 }
             }
         }
     }
     return $ret;
 }
if (!isset($g_format_dictionary)||!is_array($g_format_dictionary)||!count($g_format_dictionary)) bmlt_populate_format_dictionary ()
This reads in the server format codes, and populates the format dictionary with the NAWS IDs.
If you wish to override this, simply set this up in your /get-config.php file. That will supersede this. Actually... this block of code never, ever gets hit because the above call to bmlt_populate_format_dictionary will always set $g_format_dictionary. We should... probably remove it?
< This is a dictionary used to translate formats to NAWS format. It uses the format shared IDs in the server's language.
Definition at line 84 of file search_results_csv.php.
References $g_format_dictionary, $local_strings, $server, c_comdef_server\GetLocalStrings(), c_comdef_server\GetServer(), and c_comdef_server\MakeServer().
 {
     global $g_format_dictionary;    ///< This is a dictionary used to translate formats to NAWS format. It uses the format shared IDs in the server's language.
     // first accumulate a local array of formats in $dict
     $dict = [];
     $server = c_comdef_server::MakeServer();
     $localized_strings = c_comdef_server::GetLocalStrings();
     $formats_array = c_comdef_server::GetServer()->GetFormatsObj()->GetFormatsArray();
     foreach ($formats_array['en'] as $format) {
         if ($format instanceof c_comdef_format) {
             $world_id = $format->GetWorldID();
             $shared_id = $format->GetSharedID();
             if ($world_id && $shared_id) {
                 if (array_key_exists($world_id, $dict)) {
                     array_push($dict[$world_id], $shared_id);
                 } else {
                     $dict[$world_id] = array( $shared_id );
                 }
             }
         }
     }
     // add all the formats in $dict to $g_format_dictionary, putting the preferred formats first (in the same
     // order as in naws_export_formats_at_front)
     $g_format_dictionary = [];
     $local_strings = c_comdef_server::GetLocalStrings();
     $preferred = $local_strings['naws_export_formats_at_front'];
     foreach ($preferred as $id) {
         if (array_key_exists($id, $dict)) {
             $g_format_dictionary[$id] = $dict[$id];
         }
     }
     foreach ($dict as $id => $val) {
         if (!in_array($id, $preferred)) {
             $g_format_dictionary[$id] = $dict[$id];
         }
     }
 }
DisplaySearchResultsCSV ($in_http_vars, & $return_array = null, & $return_geocode = null, & $return_results = null, $in_supress_hidden_concat = false, $in_editor_only = false)
This function does a search, then builds a CSV result, with each row being a meeting. The first row is a row of keys.
Returns
a string, containing CSV data, with the first row a key header.
Parameters
$return_array If this is supplied, then the result will be saved in this as an array. It must be an empty array, supplied by reference.
$return_results If supplied, should point to an array that will be filled with the actual meeting objects that comprise the result.
$in_supress_hidden_concat If true, then hidden fields will not have their prompts encoded
$in_editor_only If true, then only meetings for which the current logged-in user can edit/observe are returned.
Definition at line 130 of file search_results_csv.php.
References $lang_enum, $ret, c_comdef_meeting\GetAllMeetingKeys(), c_comdef_server\GetLocalStrings(), c_comdef_server\GetServer(), GetURLToMainServerDirectory(), and SetUpSearch().
Referenced by GetSearchResults(), c_comdef_admin_ajax_handler\GetSearchResults(), c_comdef_admin_xml_handler\process_meeting_search(), and ReturnNAWSFormatCSV().
   {
     $ret = null;
     require_once(dirname(__FILE__).'/c_comdef_meeting_search_manager.class.php');
     $search_manager = new c_comdef_meeting_search_manager;
     if ($search_manager instanceof c_comdef_meeting_search_manager) {
         $localized_strings = c_comdef_server::GetLocalStrings();
         $lang_enum = c_comdef_server::GetServer()->GetLocalLang();
         // This can be changed in the auto config.
         include(dirname(__FILE__).'/../../server/config/get-config.php');
         if (isset($in_http_vars['lang_enum']) && $in_http_vars['lang_enum']) {
             $lang_enum = $in_http_vars['lang_enum'];
         }
         if (!isset($in_http_vars['results_per_page'])) {
             $in_http_vars['results_per_page'] = 0;
         }
         if (isset($default_sort_key) && !isset($in_http_vars['sort_key']) && !isset($in_http_vars['sort_keys'])) {
             $in_http_vars['sort_key'] = $default_sort_key;
         }
         if ((!isset($in_http_vars['sort_dir']) || ( ($in_http_vars['sort_dir'] != 'desc') && ($in_http_vars['sort_dir'] != 'asc') ) ) && !isset($in_http_vars['sort_keys'])) {
             $in_http_vars['sort_dir'] = 'asc';
         }
         SetUpSearch($search_manager, $in_http_vars);
         if (isset($in_http_vars['page_size'])) {
             $search_manager->SetResultsPerPage($in_http_vars['page_size']);
         }
         if (isset($in_http_vars['sort_dir'])) {
             $sort_dir_desc = ($in_http_vars['sort_dir'] == "desc") ? true : false;
             if (isset($localized_strings['default_sorts']) && isset($in_http_vars['sort_key']) && isset($sort_dir_desc) && !isset($in_http_vars['sort_keys'])) {
                 $search_manager->SetSort($localized_strings['default_sorts'][$in_http_vars['sort_key']], $sort_dir_desc, 0);
             }
         }
         $search_manager->DoSearch();
         $long = null;
         $lat = null;
         if (isset($in_http_vars['long_val'])) {
             $long = $in_http_vars['long_val'];
         }
         if (isset($in_http_vars['lat_val'])) {
             $lat = $in_http_vars['lat_val'];
         }
         if (isset($in_http_vars['geo_width'])) {
             $my_radius = $in_http_vars['geo_width'];
         } elseif (isset($in_http_vars['geo_width_km'])) {
             $my_radius = $in_http_vars['geo_width_km'];
         }
         if (isset($my_radius) && ($my_radius < 0)) {
             $my_radius = $search_manager->GetRadius($localized_strings['dist_units'] == 'mi');
         }
         if (isset($return_geocode)) {
             $return_geocode = nil;
             if ($search_manager->GetRadius(false)) {
                 $return_geocode['radius'] = $search_manager->GetRadius(false);
                 $return_geocode['longitude'] = $search_manager->GetLongitude();
                 $return_geocode['latitude'] = $search_manager->GetLatitude();
             }
         }
         $num_pages = $search_manager->GetNumberOfPages();
         $num_results = $search_manager->GetNumberOfResults();
         $page_no = 1;
         if (isset($in_http_vars['page_num']) && (0 < intval($in_http_vars['page_num']))) {
             $page_no = intval($in_http_vars['page_num']);
         }
         if (1 > intval($page_no)) {
             $page_no = 1;
         }
         if ($page_no > $num_pages) {
             $page_no = $num_pages;
         }
         $page_data = $search_manager->GetPageOfResults($page_no);
         if ($page_data instanceof c_comdef_meeting_search_manager) {
             $keys = c_comdef_meeting::GetAllMeetingKeys();
             // This is a required one for data export.
             if (!in_array('meeting_name', $keys)) {
                 $keys[] = 'meeting_name';
             }
             $keys[] = 'root_server_uri';
             $keys[] = 'format_shared_id_list';
             $ret = '"'.join('","', $keys).'"';
             $formats = c_comdef_server::GetServer()->GetFormatsObj();
             $formats_keys = array();
             $formats_keys_header = array();
             $ret .= "\n";
             $in_ar = $page_data->GetSearchResultsAsArray();
             if (isset($return_results) && is_array($return_results)) {
                 $return_results = $in_ar;
             }
             foreach ($in_ar as &$mtg_obj) {
                 $line = array();
                 $formats_ar = $formats_keys;
                 if ($mtg_obj instanceof c_comdef_meeting) {
                     if (!$in_editor_only || $mtg_obj->UserCanObserve()) {
                         $format_shared_id_list = array();
                         $first = true;
                         foreach ($keys as $key) {
                             if (trim($key)) {
                                 $val = $mtg_obj->GetMeetingDataValue($key);
                                 if (($key == 'meeting_name') && !$val) {    // No meeting name results in a generic "NA Meeting" as the name.
                                     $val = $localized_strings['comdef_server_admin_strings']['Value_Prompts']['generic'];
                                 }
                                 if ($key == 'lang_enum' && isset($in_http_vars['lang_enum']) && $in_http_vars['lang_enum']) {
                                     // Override the native lang_enum for the meeting with the requested language if present in http_vars
                                     // (Does this ever matter??)
                                     $val = $in_http_vars['lang_enum'];
                                 }
                                 if (isset($val)) {
                                     if (($key == 'formats')) {
                                         if (is_array($val) && count($val)) {
                                             $v_ar = array();
                                             foreach ($val as $format) {
                                                 if ($format instanceof c_comdef_format) {
                                                     // $format will be one of the meeting's formats in the native server language.  If it's already
                                                     // in the correct language, just add its key to $v_ar and its id to $format_shared_id_list.
                                                     // Otherwise see if there is a version of the format in the other language (stored in $lang_enum).  If there is,
                                                     // push the key for the format in the other language onto $v_ar instead.  Note that the key might be different
                                                     // in different languages.  If there isn't a version of the format in the other language, just skip it.
                                                     $id = $format->GetSharedID();
                                                     if ($format->GetLocalLang() == $lang_enum) {
                                                         array_push($v_ar, $format->GetKey());
                                                         array_push($format_shared_id_list, $id);
                                                     } else {
                                                         $fs = $formats->GetFormatsBySharedIDCode($id);
                                                         if (array_key_exists($lang_enum, $fs)) {
                                                             $localized_format = $fs[$lang_enum];
                                                             array_push($v_ar, $localized_format->GetKey());
                                                             array_push($format_shared_id_list, $id);
                                                         }
                                                     }
                                                 }
                                             }
                                             $val = join(',', $v_ar);
                                             $val = preg_replace('|"|', '\\"', preg_replace('|[\r\n\t]+|', ' ', $val));
                                         } elseif (is_string($val)) {
                                             $val = preg_replace('|"|', '\\"', preg_replace('|[\r\n\t]+|', ' ', $val));
                                         }
                                     }
                                     if (($key == 'formats') && $val) {
                                         $f_list = explode(',', $val);
                                         if (is_array($f_list) && count($f_list)) {
                                             foreach ($f_list as $format) {
                                                 $formats_ar[$format] = 1;
                                             }
                                         }
                                     }
                                     if ($val) {
                                         if ($mtg_obj->IsItemHidden($key)) {
                                             if ($mtg_obj->UserCanObserve()) {
                                                 if (!$in_supress_hidden_concat && !isset($in_http_vars['simple_other_fields'])) {
                                                     $val = preg_replace('|.*?\#\@\-\@\#|', '', $mtg_obj->GetMeetingDataValue($key));    // Strip out any old accidentally introduced separators.
                                                     $val = 'observer_only#@-@#'.$mtg_obj->GetMeetingDataPrompt($key).'#@-@#'.$val;
                                                 }
                                             } else {
                                                 $val = '';
                                             }
                                         } else {
                                             switch ($key) {
                                                 // We don't do anything for the standard fields.
                                                 case 'distance_in_miles':
                                                 case 'distance_in_km':
                                                 case 'id_bigint':
                                                 case 'worldid_mixed':
                                                 case 'shared_group_id_bigint':
                                                 case 'service_body_bigint':
                                                 case 'weekday_tinyint':
                                                 case 'start_time':
                                                 case 'duration_time':
                                                 case 'time_zone':
                                                 case 'formats':
                                                 case 'lang_enum':
                                                 case 'longitude':
                                                 case 'latitude':
                                                 case 'published':
                                                 case 'email_contact':
                                                 case 'meeting_name':
                                                 case 'location_text':
                                                 case 'location_info':
                                                 case 'location_street':
                                                 case 'location_city_subsection':
                                                 case 'location_neighborhood':
                                                 case 'location_municipality':
                                                 case 'location_sub_province':
                                                 case 'location_province':
                                                 case 'location_postal_code_1':
                                                 case 'location_nation':
                                                 case 'comments':
                                                 case 'virtual_meeting_link':
                                                 case 'virtual_meeting_additional_info':
                                                 case 'phone_meeting_number':
                                                     break;
                                                 // The rest get the prompt/value treatment, unless otherwise requested.
                                                 default:
                                                     if ($val && !isset($in_http_vars['simple_other_fields'])) {
                                                         $val = preg_replace('|.*?\#\@\-\@\#|', '', $val);    // Strip out any old accidentally introduced separators.
                                                         $val = $mtg_obj->GetMeetingDataPrompt($key).'#@-@#'.$val;
                                                     }
                                                     break;
                                             }
                                         }
                                     }
                                 } else {
                                     $val = '';
                                 }
                                 $val = trim(preg_replace("|[\n\r]+|", "; ", $val));
                                 $line[$key] = $val;
                             }
                         }
                         if (!isset($line['duration_time']) || !$line['duration_time'] || ($line['duration_time'] == '00:00:00')) {
                             $line['duration_time'] = $localized_strings['default_duration_time'];
                         }
                         if (isset($format_shared_id_list) && is_array($format_shared_id_list) && count($format_shared_id_list)) {
                             sort($format_shared_id_list);
                             $line['format_shared_id_list'] = implode(',', $format_shared_id_list);
                         }
                         $line['root_server_uri'] = dirname(dirname(GetURLToMainServerDirectory(true)));
                         if (is_array($line) && count($line)) {
                             if (is_array($return_array)) {
                                 array_push($return_array, $line);
                             }
                             $ret .= '"'.join('","', $line).'"';
                             $ret .= "\n";
                         }
                     }
                 }
             }
         }
     }
     return $ret;
 }
ReturnNAWSDeletedMeetings (& $server, $in_transfer_dictionary, $in_services)
Returns deleted meetings with NAWS IDs.
This queries every deleted meeting. The meetings returned are not restricted to the search parameters, and may repeat from previous dumps. Only meetings that had World IDs, and that don't have the World ID 'deleted' in their most recent change record, are returned. (The special World ID 'deleted' indicates a meeting that NAWS has already processed, and so they don't need to see it again.)
Returns
An array of World IDs and change dates. These each represent deleted meetings.
Parameters
$server A reference to an instance of c_comdef_server
$in_transfer_dictionary The transfer dictionary
$in_services Any Service body IDs
Definition at line 720 of file search_results_csv.php.
References $ret, and $server.
Referenced by ReturnNAWSFormatCSV().
   {
     $ret = null;
     $ids_to_ignore = [];   // these are the IDs of meetings that NAWS has already processed, and so we don't output them
     // We start by getting all the meetings that have been deleted (Could be quite a few).
     // These are returned in reverse chronological order, with the most recent change first.
     $changes = $server->GetChangesFromOTypeAndCType('c_comdef_meeting', 'comdef_change_type_delete');
     if ($changes instanceof c_comdef_changes) {
         $ret = array();
         $c_array = $changes->GetChangesObjects();
         if (is_array($c_array) && count($c_array)) {
             foreach ($c_array as &$change) {
                 $b_obj = $change->GetBeforeObject();
                 if ($b_obj instanceof c_comdef_meeting) {
                     $line = null;
                     if (!$server->GetOneMeeting($b_obj->GetID())) {  // Must be currently deleted.
                         if (is_array($in_services) && count($in_services)) {
                             $found = false;
                             reset($in_services);
                             foreach ($in_services as $sb_id) {
                                 if (!$found) {
                                     if (intval($b_obj->GetServiceBodyID()) == intval($sb_id)) {
                                         $found = true;
                                     }
                                 }
                             }
                         }
                         // If the meeting's ID is in $ids_to_ignore, we don't output it (not surprisingly).
                         // If the world_id for the meeting is 'deleted', that means that NAWS has already processed it,
                         // and we don't output it either; in addition, we add it to the $ids_to_ignore so that any earlier
                         // deletion change records for this meeting don't have anything output either.
                         if (in_array($b_obj->GetID(), $ids_to_ignore)) {
                             $value = false;
                         } else if ($b_obj->GetMeetingDataValue('worldid_mixed') === 'deleted') {
                             array_push($ids_to_ignore, $b_obj->GetID());
                             $value = false;
                         } else {
                             $value = intval(preg_replace('|\D*?|', '', $b_obj->GetMeetingDataValue('worldid_mixed')));
                         }
                         if ($value && $found) {
                             foreach ($in_transfer_dictionary as $key => $value2) {
                                 if (($key != 'Delete')) {
                                     $value1 = null;
                                     // See if this is a function.
                                     if (function_exists($value2) && is_callable($value2) && preg_match('|^BMLT_FuncNAWSReturn|', $value2)) {
                                         if ($value2 == 'BMLT_FuncNAWSReturnLastMeetingChangeTime') {
                                             $value1 =  date('n/j/y', $change->GetChangeDate());
                                         } else {
                                             $value1 = $value2($b_obj, $server);
                                         }
                                     } else // See if we just transfer the value with no change.
{
                                         $value1 = $b_obj->GetMeetingDataValue($value2);
                                     }
                                 } else {
                                     $value1 = 'D';
                                 }
                                 $line[$key] = $value1;
                             }
                         }
                     }
                     array_push($ret, $line);
                 }
             }
         }
     }
     return $ret;
 }
ReturnNAWSFormatCSV ($in_http_vars, & $server)
Returns the CSV file in NAWS format.
Returns
A string, consisting of a CSV file, in the format required by NAWS.
Parameters
$in_http_vars The HTTP GET and POST parameters.
$server A reference to an instance of c_comdef_server
Definition at line 600 of file search_results_csv.php.
References $ret, $server, DisplaySearchResultsCSV(), and ReturnNAWSDeletedMeetings().
Referenced by CSVHandleNawsDump().
   {
     // This is a dictionary that is used to translate the meeting data from the BMLT format to the NAWS format.
     $transfer_dictionary = array(   'Committee'          => 'BMLT_FuncNAWSReturnMeetingNAWSID',
                                     'CommitteeName'      => 'meeting_name',
                                     'AddDate'            => null,
                                     'AreaRegion'         => 'BMLT_FuncNAWSReturnMeetingServiceBodyNAWSID',
                                     'ParentName'         => 'BMLT_FuncNAWSReturnMeetingServiceBodyName',
                                     'ComemID'            => null,
                                     'ContactID'          => null,
                                     'ContactName'        => null,
                                     'CompanyName'        => null,
                                     'ContactAddrID'      => null,
                                     'ContactAddress1'    => null,
                                     'ContactAddress2'    => null,
                                     'ContactCity'        => null,
                                     'ContactState'       => null,
                                     'ContactZip'         => null,
                                     'ContactCountry'     => null,
                                     'ContactPhone'       => null,
                                     'MeetingID'          => null,
                                     'Room'               => 'BMLT_FuncNAWSReturnNonNawsFormats',
                                     'Closed'             => 'BMLT_FuncNAWSReturnOpenOrClosed',
                                     'WheelChr'           => 'BMLT_FuncNAWSReturnWheelchair',
                                     'Day'                => 'BMLT_FuncNAWSReturnWeekday',
                                     'Time'               => 'BMLT_FuncNAWSReturnTime',
                                     'Language1'          => 'BMLT_FuncNAWSReturnLanguage1',
                                     'Language2'          => null,
                                     'Language3'          => null,
                                     'LocationId'         => null,
                                     'Place'              => 'location_text',
                                     'Address'            => 'location_street',
                                     'City'               => 'BMLT_FuncNAWSReturnMeetingTown',
                                     'LocBorough'         => 'location_neighborhood',
                                     'State'              => 'location_province',
                                     'Zip'                => 'location_postal_code_1',
                                     'Country'            => 'location_nation',
                                     'Directions'         => 'BMLT_FuncNAWSReturnDirections',
                                     'Institutional'      => 'BMLT_FuncNAWSReturnInst',
                                     'Format1'            => 'BMLT_FuncNAWSReturnFormat1',
                                     'Format2'            => 'BMLT_FuncNAWSReturnFormat2',
                                     'Format3'            => 'BMLT_FuncNAWSReturnFormat3',
                                     'Format4'            => 'BMLT_FuncNAWSReturnFormat4',
                                     'Format5'            => 'BMLT_FuncNAWSReturnFormat5',
                                     'Delete'             => null,
                                     'LastChanged'        => 'BMLT_FuncNAWSReturnLastMeetingChangeTime',
                                     'Longitude'          => 'longitude',
                                     'Latitude'           => 'latitude',
                                     'ContactGP'          => null,
                                     'PhoneMeetingNumber' => 'phone_meeting_number',
                                     'VirtualMeetingLink' => 'virtual_meeting_link',
                                     'VirtualMeetingInfo' => 'virtual_meeting_additional_info',
                                     'TimeZone'           => 'time_zone',
                                     'bmlt_id'            => 'id_bigint',
                                     'unpublished'        => 'BMLT_FuncNAWSReturnPublishedStatus'
                                 );
     $ret = null;
     if (!( isset($in_http_vars['geo_width']) && $in_http_vars['geo_width'] ) && isset($in_http_vars['bmlt_search_type']) && ($in_http_vars['bmlt_search_type'] == 'advanced') && isset($in_http_vars['advanced_radius']) && isset($in_http_vars['advanced_mapmode']) && $in_http_vars['advanced_mapmode'] && ( floatval($in_http_vars['advanced_radius'] != 0.0) ) && isset($in_http_vars['lat_val']) &&  isset($in_http_vars['long_val']) && ( (floatval($in_http_vars['lat_val']) != 0.0) || (floatval($in_http_vars['long_val']) != 0.0) )) {
         $in_http_vars['geo_width'] = $in_http_vars['advanced_radius'];
     } elseif (!( isset($in_http_vars['geo_width']) && $in_http_vars['geo_width'] ) && isset($in_http_vars['bmlt_search_type']) && ($in_http_vars['bmlt_search_type'] == 'advanced')) {
         $in_http_vars['lat_val'] = null;
         $in_http_vars['long_val'] = null;
     } elseif (!isset($in_http_vars['geo_loc']) || $in_http_vars['geo_loc'] != 'yes') {
         if (!isset($in_http_vars['geo_width'])) {
             $in_http_vars['geo_width'] = 0;
         }
     }
     $ret_array = array ();  // If we supply an array as a second parameter, we will get the dump returned in a two-dimensional array.
     DisplaySearchResultsCSV($in_http_vars, $ret_array);  // Start off by getting the CSV dump in the same manner as the normal CSV dump.
     if (is_array($ret_array) && count($ret_array)) {
         $ret = '"'.join('","', array_keys($transfer_dictionary)).'"'; // This is the header line.
         foreach ($ret_array as $one_meeting) {
             if (is_array($one_meeting) && count($one_meeting)) {
                 $line = array();
                 foreach ($transfer_dictionary as $key => $value) {
                     // See if this is a function.
                     if (function_exists($value) && is_callable($value) && preg_match('|^BMLT_FuncNAWSReturn|', $value)) {
                         $value = $value($one_meeting['id_bigint'], $server);
                     } elseif (isset($one_meeting[$value])) {   // See if we just transfer the value with no change.
                         $value = $one_meeting[$value];
                     }
                     array_push($line, $value);
                 }
                 if (is_array($line) && count($line)) {
                     $ret .= "\n".'"'.join('","', $line).'"';
                 }
             }
         }
     }
     $del_meetings = ReturnNAWSDeletedMeetings($server, $transfer_dictionary, $in_http_vars['services']); // We append deleted meetings to the end.
     if (is_array($del_meetings) && count($del_meetings)) {
         foreach ($del_meetings as $one_meeting) {
             if (is_array($one_meeting) && count($one_meeting)) {
                 $ret .= "\n".'"'.join('","', $one_meeting).'"';
             }
         }
     }
     return $ret;
 }
Variable Documentation
global $g_format_dictionary
This is a dictionary used to translate formats to NAWS format. It uses the format shared IDs in the server's language.
Definition at line 32 of file search_results_csv.php.
Referenced by BMLT_FuncNAWSReturnFormat(), BMLT_FuncNAWSReturnOpenOrClosed(), BMLT_FuncNAWSReturnWheelchair(), and bmlt_populate_format_dictionary().