BMLT Root Server: /Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/local_server/install_wizard/installer.php File Reference
installer.php File Reference
Variables
if(isset($http_vars['ajax_req']) && $http_vars['ajax_req']) else
global $prefs_array
global $comdef_install_wizard_strings
$https = (!empty($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] !== 'off') || ($port == 443)))
$url_path = 'http'.($https ? 's' : '').'://'.$_SERVER['SERVER_NAME'].((($_SERVER['SERVER_PORT'] != 80) && ($_SERVER['SERVER_PORT'] != 443)) ? ':'.$_SERVER['SERVER_PORT'] : '').'/'.dirname($_SERVER['PHP_SELF'])
$shortcut_icon = "$url_path/local_server/server_admin/style/images/shortcut.png"
$stylesheet = "$url_path/local_server/server_admin/style/install_wizard_styles.css?v=". time()
Variable Documentation
$comdef_install_wizard_strings
global $comdef_install_wizard_strings
Definition at line 32 of file installer.php.
Referenced by bmlt_create_next_prev_buttons().
$https
$https = (!empty($_SERVER['HTTPS']) && (($_SERVER['HTTPS'] !== 'off') || ($port == 443)))
Definition at line 72 of file installer.php.
Referenced by bmlt_basic\get_ajax_base_uri(), GetURLToMainServerDirectory(), and parse_redirect().
$prefs_array
$prefs_array
Initial value:
= array ('dbName'                        =>  '',
                            'dbUser'                        =>  '',
                            'dbPassword'                    =>  '',
                            'dbType'                        =>  'mysql',
                            'dbServer'                      =>  'localhost',
                            'dbPrefix'                      =>  'na',
                            'comdef_global_language'        =>  $lang,
                            'min_pw_len'                    =>  $comdef_install_wizard_strings['DefaultPasswordLength'],
                            'number_of_meetings_for_auto'   =>  $comdef_install_wizard_strings['DefaultMeetingCount'],
                            'change_depth_for_meetings'     =>  $comdef_install_wizard_strings['DefaultChangeDepth'],
                            'region_bias'                   =>  $comdef_install_wizard_strings['DefaultRegionBias'],
                            'search_spec_map_center'        =>  $comdef_install_wizard_strings['search_spec_map_center'],
                            'bmlt_title'                    =>  $comdef_install_wizard_strings['TitleTextInitialText'],
                            'banner_text'                   =>  $comdef_install_wizard_strings['BannerTextInitialText'],
                            'comdef_distance_units'         =>  $comdef_install_wizard_strings['DefaultDistanceUnits'],
                            'default_duration_time'         =>  $comdef_install_wizard_strings['DefaultDurationTime'],
                            'enable_language_selector'      =>  false,
                            'default_duration'              =>  $comdef_install_wizard_strings['DurationTextInitialText'],
                            'time_format'                   =>  $comdef_install_wizard_strings['time_format'],
                            'change_date_format'            =>  $comdef_install_wizard_strings['change_date_format'],
                            'admin_session_name'            =>  'BMLT_Admin'
                            )
Definition at line 32 of file installer.php.
Referenced by bmlt_create_pdo_driver_select(), and bmlt_create_region_bias_select().
$shortcut_icon
$shortcut_icon = "$url_path/local_server/server_admin/style/images/shortcut.png"
Definition at line 74 of file installer.php.
$stylesheet
$stylesheet = "$url_path/local_server/server_admin/style/install_wizard_styles.css?v=". time()
Definition at line 75 of file installer.php.
$url_path
$url_path = 'http'.($https ? 's' : '').'://'.$_SERVER['SERVER_NAME'].((($_SERVER['SERVER_PORT'] != 80) && ($_SERVER['SERVER_PORT'] != 443)) ? ':'.$_SERVER['SERVER_PORT'] : '').'/'.dirname($_SERVER['PHP_SELF'])
Definition at line 73 of file installer.php.
else
if (file_exists(dirname(__FILE__).'/../server_admin/lang/'. $lang.'/install_wizard_strings.php')) else
Initial value:
{
    require_once(dirname(__FILE__).'/../../server/shared/Array2Json.php')
Definition at line 22 of file installer.php.