BMLT Root Server: bmlt_basic Class Reference
bmlt_basic Class Reference
Public Member Functions
output_head ($in_shortcode='')
Outputs the head HTML, CSS and JavaScript. *.
output_body ()
Outputs the body HTML and JavaScript. *.
process_text ($in_string)
This uses the CMS text processor (t) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
standard_head ($in_text=null)
returns any necessary head content. *
admin_head ()
No admin in this implementation. * *.
admin_page ()
Prevents the admin page from being shown. *.
Public Attributes
$my_shortcode = null
This will hold the given shortcode.
$m_is_logged_in_user = null
This will be true, if the user is logged in.
Protected Member Functions
get_ajax_base_uri ()
Return an HTTP path to the AJAX callback target. * *.
get_plugin_path ()
Return an HTTP path to the plugin directory. * *.
geDefaultBMLTOptions ()
This gets the default admin options from the object (not the DB). * *.
cms_get_option ($in_option_key)
This gets the admin options from the config file. * *.
cms_get_page_settings_id ($in_text, $in_check_mobile=false)
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
get_admin_ajax_base_uri ()
We don't do admin in this variant, so this makes that clear. * *.
get_admin_form_uri ()
We don't do admin in this variant, so this makes that clear. * *.
cms_set_option ($in_option_key, $in_option_value)
You cannot set options in this implementation. * *.
cms_delete_option ($in_option_key)
You cannot delete options in this implementation. * *.
cms_get_post_meta ($in_page_id, $in_settings_id)
This is declared to make it clear that we don't do post meta. * *.
Detailed Description
Definition at line 43 of file bmlt_basic.class.php.
Member Function Documentation
admin_head()
admin_head ()
No admin in this implementation. * *.
Returns
null *
Definition at line 396 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
admin_page()
admin_page ()
Prevents the admin page from being shown. *.
Definition at line 406 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
     }
cms_delete_option()
cms_delete_option ($in_option_key) protected
You cannot delete options in this implementation. * *.
Returns
false *
Parameters
$in_option_key The name of the option
Definition at line 369 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return false;
     }
cms_get_option()
cms_get_option ($in_option_key) protected
This gets the admin options from the config file. * *.
Returns
an associative array, with the option settings. *
Parameters
$in_option_key The name of the option
Definition at line 162 of file bmlt_basic.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         global $bmlt_basic_configuration;
         global $bmlt_basic_configuration_index;
         $ret = null;
         if ($in_option_key != self::$admin2OptionsName) {
             $index = intval(max($bmlt_basic_configuration_index - 1, intval(str_replace(self::$adminOptionsName.'_', '', $in_option_key))));
             $ret = $bmlt_basic_configuration[$index];
         } else {
             $ret = array ( 'num_servers' => $bmlt_basic_configuration_index );
         }
         return $ret;
     }
cms_get_page_settings_id()
cms_get_page_settings_id ($in_text, $in_check_mobile = false) protected
This function fetches the settings ID for a page (if there is one). *
If $in_check_mobile is set to true, then ONLY a check for mobile support will be * made, and no other shortcodes will be checked. * *.
Returns
a mixed type, with the settings ID. *
Parameters
$in_text Required (for the base version) content to check.
$in_check_mobile True if this includes a check for mobile. Default is false.
Definition at line 191 of file bmlt_basic.class.php.
Referenced by standard_head().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $my_option_id = 0;
         if (!$in_check_mobile && isset($this->my_http_vars['bmlt_settings_id']) && is_array($this->getBMLTOptions($this->my_http_vars['bmlt_settings_id']))) {
             $my_option_id = $this->my_http_vars['bmlt_settings_id'];
         } else {
             $support_mobile = self::get_shortcode($in_text, 'bmlt_mobile');
             if ($support_mobile === true) {
                 $options = $this->getBMLTOptions(1);
                 $support_mobile = (!isset($options['id']) || !$options['id'] ) ? "" : strval($options['id']);
             }
             if ($in_check_mobile && $support_mobile && !isset($this->my_http_vars['BMLTPlugin_mobile']) && (self::mobile_sniff_ua($this->my_http_vars) != 'xhtml')) {
                 $my_option_id = $support_mobile;
             } elseif (!$in_check_mobile) {
                 if (isset($this->my_http_vars['bmlt_settings_id']) && intval($this->my_http_vars['bmlt_settings_id'])) {
                     $my_option_id = intval($this->my_http_vars['bmlt_settings_id']);
                 } elseif ($in_text) {
                     $my_option_id_content = parent::cms_get_page_settings_id($in_text, $in_check_mobile);
                     $my_option_id = $my_option_id_content ? $my_option_id_content : $my_option_id;
                 }
                 if (!$my_option_id) {   // If nothing else gives, we go for the default (first) settings.
                     $options = $this->getBMLTOptions(1);
                     $my_option_id = (!isset($options['id']) || !$options['id'] ) ? "" : $options['id'];
                 }
             }
         }
         return $my_option_id;
     }
cms_get_post_meta()
cms_get_post_meta ($in_page_id, $in_settings_id) protected
This is declared to make it clear that we don't do post meta. * *.
Returns
null *
Parameters
$in_page_id The ID of the page/post
$in_settings_id The ID of the meta tag to fetch
Definition at line 382 of file bmlt_basic.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
cms_set_option()
cms_set_option ($in_option_key, $in_option_value) protected
You cannot set options in this implementation. * *.
Returns
false *
Parameters
$in_option_key The name of the option
$in_option_value the values to be set (associative array)
Definition at line 355 of file bmlt_basic.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return false;
     }
geDefaultBMLTOptions()
geDefaultBMLTOptions () protected
This gets the default admin options from the object (not the DB). * *.
Returns
an associative array, with the default option settings. *
Definition at line 148 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         global $bmlt_basic_configuration;
         // These are the defaults. If the saved option has a different value, it replaces the ones in here.
         return $bmlt_basic_configuration[0];
     }
get_admin_ajax_base_uri()
get_admin_ajax_base_uri () protected
We don't do admin in this variant, so this makes that clear. * *.
THESE ARE ALL DISABLED IN THE BASIC SATELLITE *
Returns
null *
Definition at line 331 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
get_admin_form_uri()
get_admin_form_uri () protected
We don't do admin in this variant, so this makes that clear. * *.
Returns
null *
Definition at line 343 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return null;
     }
get_ajax_base_uri()
get_ajax_base_uri () protected
Return an HTTP path to the AJAX callback target. * *.
INTERNAL FUNCTIONS (NOT CALLED BY CLIENT) *
Returns
a string, containing the path. *
Definition at line 86 of file bmlt_basic.class.php.
References $https.
Referenced by get_plugin_path().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $from_proxy = array_key_exists("HTTP_X_FORWARDED_PROTO", $_SERVER);
         if ($from_proxy) {
             $https = $_SERVER['HTTP_X_FORWARDED_PROTO'] == 'https';
             if (array_key_exists("HTTP_X_FORWARDED_PORT", $_SERVER)) {
                 $port = intval($_SERVER['HTTP_X_FORWARDED_PORT']);
             } elseif ($https) {
                 $port = 443;
             } else {
                 $port = 80;
             }
         } else {
             $port = intval($_SERVER['SERVER_PORT']);
             $https = !empty($_SERVER['HTTPS']) && ($_SERVER['HTTPS'] !== 'off' || $port == 443) ? true : false;
         }
         $server_path = $_SERVER['SERVER_NAME'];
         $my_path = $_SERVER['PHP_SELF'];
         $server_path .= trim((($https && ($port != 443)) || (!$https && ($port != 80))) ? ':'.$port : '', '/');
         $server_path = 'http'.($https ? 's' : '').'://'.$server_path.$my_path;
         return $server_path;
     }
get_plugin_path()
get_plugin_path () protected
Return an HTTP path to the plugin directory. * *.
Returns
a string, containing the path. *
Definition at line 118 of file bmlt_basic.class.php.
References get_ajax_base_uri().
Referenced by standard_head().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return dirname($this->get_ajax_base_uri()).'/../../vendor/bmlt/bmlt-satellite-base-class/';
     }
output_body()
output_body ()
Outputs the body HTML and JavaScript. *.
Definition at line 70 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         echo $this->content_filter($this->my_shortcode);
     }
output_head()
output_head ($in_shortcode = '')
Outputs the head HTML, CSS and JavaScript. *.
CLIENT FUNCTIONS *
Parameters
$in_shortcode You need to provide a shortcode, if you want something other than the default.
Definition at line 58 of file bmlt_basic.class.php.
References standard_head().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->my_shortcode = $in_shortcode;  // Save this.
         echo $this->standard_head($this->my_shortcode);
     }
process_text()
process_text ($in_string)
This uses the CMS text processor (t) to process the given string. *
This allows easier translation of displayed strings. All strings displayed by the * plugin should go through this function. * *.
Returns
a string, processed by WP. *
Parameters
$in_string The string to be processed.
Definition at line 133 of file bmlt_basic.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $in_string = htmlspecialchars($in_string);
         return $in_string;
     }
standard_head()
standard_head ($in_text = null)
returns any necessary head content. *
Parameters
$in_text This is the page content text.
Definition at line 233 of file bmlt_basic.class.php.
References cms_get_page_settings_id(), defined, and get_plugin_path().
Referenced by output_head().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->ajax_router();
         $load_head = false;   // This is a throwback. It prevents the GM JS from being loaded if there is no directly specified settings ID.
         $head_content = "<!-- Added by the BMLT plugin 3.0. -->\n<meta http-equiv=\"X-UA-Compatible\" content=\"IE=EmulateIE7\" />\n<meta http-equiv=\"Content-Style-Type\" content=\"text/css\" />\n<meta http-equiv=\"Content-Script-Type\" content=\"text/javascript\" />\n";
         $support_mobile = $this->cms_get_page_settings_id($in_text, true);
         if ($support_mobile) {
             $mobile_options = $this->getBMLTOptions_by_id($support_mobile);
         } else {
             $support_mobile = null;
         }
         $options = $this->getBMLTOptions_by_id($this->cms_get_page_settings_id($in_text));
         if ($support_mobile && is_array($mobile_options) && count($mobile_options)) {
             $mobile_url = $_SERVER['PHP_SELF'].'?BMLTPlugin_mobile&bmlt_settings_id='.$support_mobile;
             if (isset($this->my_http_vars['WML'])) {
                 $mobile_url .= '&WML='.intval($this->my_http_vars['WML']);
             }
             if (isset($this->my_http_vars['simulate_smartphone'])) {
                 $mobile_url .= '&simulate_smartphone';
             }
             ob_end_clean();
             header("location: $mobile_url");
             die();
         }
         $load_server_header = $this->get_shortcode($in_text, 'bmlt');   // No GMAP API key or no "bmlt" shortcode, no BMLT window.
         $this->my_http_vars['start_view'] = (!isset($options['bmlt_initial_view']) || !$options['bmlt_initial_view'] ) ? "" : $options['bmlt_initial_view'];
         $this->load_params();
         $root_server_root = (!isset($options['root_server']) || !$options['root_server'] ) ? "" : $options['root_server'];
         $head_content .= '<link rel="stylesheet" type="text/css" href="';
         $url = trim($this->get_plugin_path());
         if ($url) {
             $head_content .= (!isset($options['theme']) || !$options['theme'] ) ? $url."themes/default/" : htmlspecialchars($url.'themes/'.$options['theme'].'/');
             $head_content .= 'styles.css?v=' . time() . '" />';
             $head_content .= '<link rel="stylesheet" type="text/css" href="';
             $head_content .= (!isset($options['theme']) || !$options['theme'] ) ? $url."themes/default/" : htmlspecialchars($url.'themes/'.$options['theme'].'/');
             $head_content .= 'nouveau_map_styles.css?v=' . time() . '" />';
         }
         if ($root_server_root) {
             $additional_css = '.bmlt_container * {margin:0;padding:0;text-align:center }';
             if (isset($options['additional_css']) && $options['additional_css']) {
                 $additional_css .= $options['additional_css'];
             }
             if ($additional_css) {
                 $head_content .= '<style type="text/css">'.preg_replace("|\s+|", " ", $additional_css).'</style>';
             }
         }
         $head_content .= '<script type="text/javascript">';
         $head_content .= self::stripFile('javascript.js');
         if ($this->get_shortcode($in_text, 'bmlt_quicksearch')) {
             $head_content .= self::stripFile('quicksearch.js') . (defined('_DEBUG_MODE_') ? "\n" : '');
         }
         if ($this->get_shortcode($in_text, 'bmlt_map')) {
             $head_content .= self::stripFile('map_search.js');
         }
         if ($this->get_shortcode($in_text, 'bmlt_mobile')) {
             $head_content .= self::stripFile('fast_mobile_lookup.js');
         }
         $head_content .= '</script>';
         return $head_content;
     }
Member Data Documentation
$m_is_logged_in_user
$m_is_logged_in_user = null
This will be true, if the user is logged in.
Definition at line 48 of file bmlt_basic.class.php.
$my_shortcode
$my_shortcode = null
This will hold the given shortcode.
Definition at line 47 of file bmlt_basic.class.php.
The documentation for this class was generated from the following file:
/Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/client_interface/html/bmlt-basic/bmlt_basic.class.php