BMLT Root Server: c_comdef_service_body Class Reference
c_comdef_service_body Class Reference
A Class for Service Body Objects.
Public Member Functions
UpdateToDB ($is_rollback=false)
Updates or adds this instance to the database.
DeleteFromDB_NoRecord ()
Deletes this instance from the database without creating a change record.
DeleteFromDB ()
Deletes this instance from the database, and creates a change record.
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
__construct ($in_parent_obj=null, $in_id_bigint=null, $in_principal_user_bigint=null, $in_editors_string=null, $in_kml_file_uri_string=null, $in_uri_string=null, $in_name_string=null, $in_description_string=null, $in_lang_enum=null, $in_world_id_mixed=null, $in_sb_type=null, $in_sb_owner=null, $in_sb_owner_2=null, $in_sb_meeting_email=null)
The initial setup call for the class. If you send in values, the object will set itself up to use them.
GetID ()
Accessor - Returns the service body ID as an integer.
SetID ($in_service_body_id_bigint)
Accessor - Sets the service body ID as an integer.
GetPrincipalUserID ()
Accessor - Returns the principal user for this service body.
& GetPrincipalUserObj ()
Accessor - Returns the principal user for this service body.
SetPrincipalUserID ($in_principal_user_id_bigint)
Accessor - Sets the principal user for this service body.
GetSBType ()
Accessor - Returns the Service Body Type.
SetSBType ($in_sb_type)
Accessor - Sets the URI of the KML file for the Service Boundaries.
GetOwnerID ()
Accessor - Returns the ID of the 'owner' of this object.
GetOwner2ID ()
Accessor - Returns the ID of the 'secondary owner' of this object.
& GetOwnerIDObject ()
Accessor - Returns the 'owner' of this object as a reference to an object.
& GetOwner2IDObject ()
Accessor - Returns the 'secondary owner' of this object as a reference to an object.
SetOwnerID ($in_sb_owner)
Accessor - Sets the ID of the 'owner' of this object.
SetOwner2ID ($in_sb_owner)
Accessor - Sets the ID of the 'secondary owner' of this object.
SetOwnerObj (&$in_sb_owner_obj)
Accessor - Sets the ID of the 'owner' of this object by sending in an object reference.
SetOwner2Obj (&$in_sb_owner_obj)
Accessor - Sets the ID of the 'secondary owner' of this object by sending in an object reference.
GetHelpline ()
Accessor - Returns the helpline, as a string.
SetHelpline ($in_helpline_string)
Accessor - Sets the URI of the KML file for the Service Boundaries.
GetURI ()
Accessor - Returns the URI of a site with more information on the Service Body.
SetURI ($in_uri_string)
Accessor - Sets the URI of a site with more information on the Service Body.
SetContactEmail ($in_email)
Accessor - set the contact email string.
GetContactEmail ($in_recursive=false)
Get the contact email for this Service Body. If $in_recursive is false, then it simply looks at this Service Body. This first looks at the Service Body Meeting Email. If that is not there, it gets the email for the principal admin. If that is not there, it percolates to the parent, recursively (if $in_recursive is true).
GetEditors ()
Accessor - Returns IDs for all the editors.
GetEditorsAsObjects ()
Accessor - Returns user objects for all the editors.
IsUserInServiceBody ($in_user_object=null)
Accessor - Returns true if the current user is an editor for the Service Body, or if the user is an owner.
IsUserInServiceBodyHierarchy ($in_user_object=null)
Accessor - Returns true if the current user is an editor for the Service Body. Checks up the hierarchy recursively.
SetEditors ($in_editor_id_array)
Accessor - Sets the editors by ID.
SerializeObject ()
Returns a storable serialization of the object, as a string.
UserCanEditMeetings ($in_user_object=null)
Test to see if a user is allowed to edit meetings in this Service body.
UserCanObserve ($in_user_object=null)
Test to see if a user is allowed to observe in this Service body.
UserCanEdit ($in_user_object=null)
Test to see if a user is allowed to edit an instance (change the data). Service Body Administrators that are Editors in parent, or secondary parent Service bodies can edit the Service body.
IsOwnedBy ($in_sb_id, $in_direct=false)
Check to see if a given Service Body ID is anywhere in the "direct parent" hierarchy of this Service Body.
Public Member Functions inherited from t_comdef_world_type
SetWorldID ($in_worldid_mixed)
Accessor -Sets the _world_type_worldid_mixed data member.
GetWorldID ()
Accessor -Returns a reference to the _world_type_worldid_mixed data member.
Public Member Functions inherited from t_comdef_local_type
SetLocalLang ($in_lang_enum=null)
Sets the language.
GetLocalLang ()
Returns a reference to the local language setting.
SetLocalName ($in_name_string)
Accessor -Sets the _local_type_name_string data member.
GetLocalName ()
Accessor -Returns a reference to the _local_type_name_string data member.
SetLocalDescription ($in_description_string)
Accessor -Sets the _local_type_desc_string data member.
GetLocalDescription ()
Accessor -Returns a reference to the _local_type_desc_string data member.
Public Member Functions inherited from t_local_id_class
SetParentObj ($in_parent_obj)
Sets the object's "parent" (Container) object, as a reference.
GetParentObj ()
Returns a reference to the object's container.
Public Member Functions inherited from i_comdef_db_stored
UpdateToDB ()
This causes the object to update the database to its current state.
Static Public Member Functions
static UnserializeObject ($in_parent, $serialized_string)
This takes the serialized table, and instantiates a new object from it.
Private Attributes
$_id_bigint = null
An integer, containing the unique ID of this service body.
$_principal_user_bigint = null
An integer, with the ID of the principal administrator for this Service Body.
$_editors_string = null
A string, containing a CSV list of integers, each an ID for a user that has editor privileges for meetings for this Service Body.
$_kml_file_uri_string = null
A string, containing the helpline (re-used KML file URI).
$_uri_string = null
A string, containing a URI to a site that gives further information about the Service Body.
$_sb_type = null
$_sb_owner = null
An integer. The ID of the Service Body that "owns" this one.
$_sb_owner_2 = null
An integer. Some Service Bodies can have "unofficial" "owners" (like Zonal Forums or Metro Areas).
$_sb_meeting_email = null
A string that contains the meeting contact email address.
Detailed Description
A Class for Service Body Objects.
The BMLT doesn't really care that much about the Service role of any given Service Body. Indicators of such are provided so that clients of the BMLT can keep track of them.
The BMLT is more interested in the hierarchy of a Service Body. If a Service Body has an owner or a secondary owner, then any member of the owner or secondary owner can edit any meetings in the Service Body, and and Service Body Administrators in an owner or secondary owner can administer the Service Body itself.
Definition at line 58 of file c_comdef_service_body.class.php.
Constructor & Destructor Documentation
__construct()
__construct ($in_parent_obj = null, $in_id_bigint = null, $in_principal_user_bigint = null, $in_editors_string = null, $in_kml_file_uri_string = null, $in_uri_string = null, $in_name_string = null, $in_description_string = null, $in_lang_enum = null, $in_world_id_mixed = null, $in_sb_type = null, $in_sb_owner = null, $in_sb_owner_2 = null, $in_sb_meeting_email = null)
The initial setup call for the class. If you send in values, the object will set itself up to use them.
This is the server language.
Should never be necessary.
Parameters
$in_parent_obj A reference to the parent object for this Service Body Object.
$in_id_bigint An integer, containing the ID of the object. If null or 0, then the object is new.
$in_principal_user_bigint An integer with the ID of the principal user for this Service Body.
$in_editors_string A string containing a CSV array of integers with editor user IDs
$in_kml_file_uri_string A string containing a URI to the KML file that displays this Service Body's boundaries.
$in_uri_string A string containing a URI to a site that has more information about the Service Body.
$in_name_string The local name of the Service Body as a string.
$in_description_string The local description of the Service Body as a string.
$in_lang_enum A string, with the language code for this Service Body.
$in_world_id_mixed A string, containing the World ID for this Service Body.
$in_sb_owner An integer. The ID of the Service Body that "owns" this Service Body.
$in_sb_owner_2 An integer. The ID of the "secondary" Service Body that "owns" this Service Body.
$in_sb_meeting_email A string, containing any email address that is to be used for meeting contacts.
Definition at line 301 of file c_comdef_service_body.class.php.
References $comdef_global_language.
       {
         global  $comdef_global_language;
         /// This is the server language.
         if (null == $in_lang_enum) {
             $in_lang_enum = $comdef_global_language;
         }
         /// Should never be necessary.
         if (null == $in_lang_enum) {
             $in_lang_enum = "en";
         }
         // Set the five inherited values.
         $this->SetParentObj($in_parent_obj);
         $this->SetLocalLang($in_lang_enum);
         $this->SetLocalName($in_name_string);
         $this->SetWorldID($in_world_id_mixed);
         $this->SetLocalDescription($in_description_string);
         // Set the local values.
         $this->_id_bigint = $in_id_bigint;
         $this->_principal_user_bigint = $in_principal_user_bigint;
         $this->_editors_string = $in_editors_string;
         $this->_kml_file_uri_string = $in_kml_file_uri_string;
         $this->_uri_string = $in_uri_string;
         $this->_sb_type = $in_sb_type;
         $this->SetOwnerID($in_sb_owner);
         $this->SetOwner2ID($in_sb_owner_2);
         $this->SetContactEmail($in_sb_meeting_email);
     }
Member Function Documentation
DeleteFromDB()
DeleteFromDB ()
Deletes this instance from the database, and creates a change record.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 226 of file c_comdef_service_body.class.php.
References $ret, c_comdef_server\AddNewChange(), c_comdef_server\GetCurrentUserObj(), and c_comdef_server\GetServiceBodyByIDObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             // We take a snapshot of the service body as it currently sits in the database as a "before" image.
             $before = null;
             $before_id = null;
             $before_lang = null;
             $before_obj = c_comdef_server::GetServiceBodyByIDObj($this->GetID());
             if ($before_obj instanceof c_comdef_service_body) {
                 $before = $before_obj->SerializeObject();
                 $before_id = $before_obj->GetID();
                 $before_lang = $before_obj->GetLocalLang();
                 $before_obj = null;
             }
             $ret = $this->DeleteFromDB_NoRecord();
             if ($ret) {
                 c_comdef_server::AddNewChange($user->GetID(), 'comdef_change_type_delete', $this->GetID(), $before, null, 'c_comdef_service_body', $before_id, null, $before_lang, null);
             }
         }
         return $ret;
     }
DeleteFromDB_NoRecord()
DeleteFromDB_NoRecord ()
Deletes this instance from the database without creating a change record.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Definition at line 194 of file c_comdef_service_body.class.php.
References $_COMDEF_DEBUG, $ret, and c_comdef_dbsingleton\preparedExec().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         if ($this->UserCanEdit()) {
             try {
                 $sql = "DELETE FROM `".c_comdef_server::GetServiceBodiesTableName_obj()."` WHERE id_bigint=?";
                 c_comdef_dbsingleton::preparedExec($sql, array ( $this->GetID() ));
                 $ret = true;
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_service_body::DeleteFromDB_NoRecord()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
GetContactEmail()
GetContactEmail ($in_recursive = false)
Get the contact email for this Service Body. If $in_recursive is false, then it simply looks at this Service Body. This first looks at the Service Body Meeting Email. If that is not there, it gets the email for the principal admin. If that is not there, it percolates to the parent, recursively (if $in_recursive is true).
Returns
a string, which is the contact email for this Service Body
Parameters
$in_recursive If this is true, then the function will return a recursive result. Default is false.
Definition at line 639 of file c_comdef_service_body.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = trim($this->_sb_meeting_email);
         if (!$ret && $in_recursive) {
             $owner = $this->GetOwnerIDObject();
             if ($owner instanceof c_comdef_service_body) {
                 $ret = $owner->GetContactEmail($in_recursive);
             }
         }
         return $ret;
     }
GetEditors()
GetEditors ()
Accessor - Returns IDs for all the editors.
Returns
an array of integers, containing the editor IDs.
Definition at line 662 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret_array = array();
         $editor_ids = explode(",", $this->_editors_string);
         foreach ($editor_ids as $id) {
             $id = intval($id);
             array_push($ret_array, $id);
         }
         return $ret_array;
     }
GetEditorsAsObjects()
GetEditorsAsObjects ()
Accessor - Returns user objects for all the editors.
Returns
an array of references to c_comdef_user objects. The associative key for each user will the ID for that user.
Definition at line 683 of file c_comdef_service_body.class.php.
References c_comdef_server\GetUserByIDObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret_array = array();
         $editor_ids = $this->GetEditors();
         foreach ($editor_ids as $id) {
             $ret_array[$id] = c_comdef_server::GetUserByIDObj($id);
         }
         return $ret_array;
     }
GetHelpline()
GetHelpline ()
Accessor - Returns the helpline, as a string.
Returns
a string, containing the URI.
Definition at line 578 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_kml_file_uri_string;
     }
GetID()
GetID ()
Accessor - Returns the service body ID as an integer.
Returns
an integer, containing the service body ID.
Definition at line 364 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_id_bigint;
     }
GetOwner2ID()
GetOwner2ID ()
Accessor - Returns the ID of the 'secondary owner' of this object.
Returns
an integer, containing the owner ID of the secondary "owner."
Definition at line 476 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_sb_owner_2;
     }
GetOwner2IDObject()
& GetOwner2IDObject ()
Accessor - Returns the 'secondary owner' of this object as a reference to an object.
Returns
a reference to the internal c_comdef_service_body object for the service body. Null if not found.
Definition at line 502 of file c_comdef_service_body.class.php.
References c_comdef_server\GetServiceBodyByIDObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return c_comdef_server::GetServiceBodyByIDObj($this->GetOwner2ID());
     }
GetOwnerID()
GetOwnerID ()
Accessor - Returns the ID of the 'owner' of this object.
Returns
an integer, containing the owner ID.
Definition at line 464 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_sb_owner;
     }
GetOwnerIDObject()
& GetOwnerIDObject ()
Accessor - Returns the 'owner' of this object as a reference to an object.
Returns
a reference to the internal c_comdef_service_body object for the service body. Null if not found.
Definition at line 488 of file c_comdef_service_body.class.php.
References $ret, and c_comdef_server\GetServiceBodyByIDObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $owner_id = $this->GetOwnerID();
         $ret = c_comdef_server::GetServiceBodyByIDObj($owner_id);
         return $ret;
     }
GetPrincipalUserID()
GetPrincipalUserID ()
Accessor - Returns the principal user for this service body.
Returns
an integer, containing the user ID.
Definition at line 387 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_principal_user_bigint;
     }
GetPrincipalUserObj()
& GetPrincipalUserObj ()
Accessor - Returns the principal user for this service body.
Returns
a reference to a c_comdef_user object of the principal user.
Definition at line 399 of file c_comdef_service_body.class.php.
References c_comdef_server\GetUserByIDObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return c_comdef_server::GetUserByIDObj($this->_principal_user_bigint);
     }
GetSBType()
GetSBType ()
Accessor - Returns the Service Body Type.
Returns
a string, containing the Type. It can be one of the following:
c_comdef_service_body__GRP__ Individual NA Group
c_comdef_service_body__ASC__ Area Service Committee
c_comdef_service_body__RSC__ Regional Service Committee
c_comdef_service_body__WSC__ World Service Committee
c_comdef_service_body__MAS__ Metro Area
c_comdef_service_body__ZFM__ Zonal Forum
c_comdef_service_body__GSU__ Group Service Unit
c_comdef_service_body__LSU__ Local Service Unit
Definition at line 431 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_sb_type;
     }
GetURI()
GetURI ()
Accessor - Returns the URI of a site with more information on the Service Body.
Returns
a string, containing the URI.
Definition at line 601 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_uri_string;
     }
IsOwnedBy()
IsOwnedBy ($in_sb_id, $in_direct = false)
Check to see if a given Service Body ID is anywhere in the "direct parent" hierarchy of this Service Body.
Returns
a boolean. True if the given Service Body appears in the hierarchy above it.
Parameters
$in_sb_id The ID of a potential owner.
$in_direct If this is set to true, then only the immediate parent is checked. Default is false.
Definition at line 1035 of file c_comdef_service_body.class.php.
References $ret, $server, and c_comdef_server\GetServer().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $server = c_comdef_server::GetServer();
         if ($server instanceof c_comdef_server) {
             $sb_to_check = $server->GetServiceBodyByIDObj($in_sb_id);
             $parent = $this->GetOwnerID();
             if ($parent == $in_sb_id) {
                 $ret = true;
             } elseif (!$in_direct) {
                 if ($parent) {
                     $sb_to_check = $server->GetServiceBodyByIDObj($parent);
                     if ($sb_to_check instanceof c_comdef_service_body) {
                         $ret = IsSBRecursive($in_sb_id, $sb_to_check->GetID(), $in_direct);
                     }
                 }
             }
         }
         return $ret;
     }
IsUserInServiceBody()
IsUserInServiceBody ($in_user_object = null)
Accessor - Returns true if the current user is an editor for the Service Body, or if the user is an owner.
Returns
a boolean. True if the user is an editor or principal user.
Parameters
$in_user_object A reference to an instance of c_comdef_user. If null, the current user is checked.
Definition at line 704 of file c_comdef_service_body.class.php.
References $ret, and c_comdef_server\GetCurrentUserObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         // We load the server user if one wasn't supplied.
         if (null == $in_user_object) {
             $in_user_object = c_comdef_server::GetCurrentUserObj();
         }
         // If it isn't a user object, we fail right there.
         if ($in_user_object instanceof c_comdef_user) {
             $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
             $user_id = intval($in_user_object->GetID());
             $in_user_object = null;
             if (intval($this->GetPrincipalUserID()) == $user_id) {
                 $ret = true;
             } else {
                 $editors = $this->GetEditors();
                 foreach ($editors as $editor) {
                     if ($user_id == intval($editor)) {
                         $ret = true;
                         break;
                     }
                 }
             }
         }
         return $ret;
     }
IsUserInServiceBodyHierarchy()
IsUserInServiceBodyHierarchy ($in_user_object = null)
Accessor - Returns true if the current user is an editor for the Service Body. Checks up the hierarchy recursively.
Returns
a boolean. True if the user is in the hierarchy (going up) of the Service Body.
Parameters
$in_user_object A reference to an instance of c_comdef_user. If null, the current user is checked.
Definition at line 743 of file c_comdef_service_body.class.php.
References $ret, c_comdef_server\GetCurrentUserObj(), and c_comdef_server\GetServer().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         // We load the server user if one wasn't supplied.
         if (null == $in_user_object) {
             $in_user_object = c_comdef_server::GetCurrentUserObj();
         }
         // If it isn't a user object, we fail right there.
         if ($in_user_object instanceof c_comdef_user) {
             $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
             // First, see if the user is in this Service Body.
             $ret = $this->IsUserInServiceBody($in_user_object);
             if (!$ret && $this->GetOwnerID()) {
                 $parent = c_comdef_server::GetServer()->GetServiceBodyByIDObj($this->GetOwnerID());
                 // Check the primary "parent" Service Body's hierarchy.
                 if ($parent instanceof c_comdef_service_body) {
                     if ($parent->IsUserInServiceBody($in_user_object)) {
                         $ret = true;
                     } else {
                         $ret = $parent->IsUserInServiceBodyHierarchy($in_user_object);
                     }
                 }
             }
             if (!$ret && $this->GetOwner2ID()) {
                 $parent = c_comdef_server::GetServer()->GetServiceBodyByIDObj($this->GetOwner2ID());
                 // Check the secondary "parent" Service Body's hierarchy.
                 if ($parent instanceof c_comdef_service_body) {
                     if ($parent->IsUserInServiceBody($in_user_object)) {
                         $ret = true;
                     } else {
                         $ret = $parent->IsUserInServiceBodyHierarchy($in_user_object);
                     }
                 }
             }
         }
         return $ret;
     }
RestoreFromDB()
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 264 of file c_comdef_service_body.class.php.
References $_COMDEF_DEBUG, and c_comdef_dbsingleton\preparedQuery().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         try {
             if ($this->GetID()) {
                 $sql = "SELECT * FROM `".c_comdef_server::GetServiceBodiesTableName_obj()."` WHERE id_bigint=? LIMIT 1";
                 $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $this->GetID() ));
                 if (is_array($rows) && count($rows)) {
                     $this->_principal_user_bigint = $rows[0]['principal_user_bigint'];
                     $this->_editors_string = $rows[0]['editors_string'];
                     $this->_kml_file_uri_string = $rows[0]['kml_file_uri_string'];
                     $this->_uri_string = $rows[0]['uri_string'];
                     $this->SetLocalName($rows[0]['name_string']);
                     $this->SetLocalDescription($rows[0]['description_string']);
                     $this->SetLocalLang($rows[0]['lang_enum']);
                     $this->_sb_type = $rows[0]['sb_type'];
                     $this->SetOwnerID($rows[0]['sb_owner']);
                     $this->SetOwner2ID($rows[0]['sb_owner_2']);
                     $this->SetContactEmail($rows[0]['sb_meeting_email']);
                 }
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_service_body::RestoreFromDB()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
     }
SerializeObject()
SerializeObject ()
Returns a storable serialization of the object, as a string.
This is only used for the changes, as the serialized string may not be easily searched.
Returns
a string, containing the table array, in serialized form.
Implements i_comdef_serialized.
Definition at line 827 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $serialize_array = array(
                                 $this->_id_bigint,
                                 $this->_principal_user_bigint,
                                 $this->_editors_string,
                                 $this->_kml_file_uri_string,
                                 $this->_uri_string,
                                 $this->GetWorldID(),
                                 $this->GetLocalName(),
                                 $this->GetLocalDescription(),
                                 $this->GetLocalLang(),
                                 $this->_sb_type,
                                 $this->_sb_owner,
                                 $this->_sb_owner_2,
                                 $this->GetContactEmail()
                                 );
         return serialize($serialize_array);
     }
SetContactEmail()
SetContactEmail ($in_email)
Accessor - set the contact email string.
Parameters
$in_email A string. The email address to be set.
Definition at line 622 of file c_comdef_service_body.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_sb_meeting_email = $in_email;
     }
SetEditors()
SetEditors ($in_editor_id_array)
Accessor - Sets the editors by ID.
Returns
the processed string.
Parameters
$in_editor_id_array An array of integers, containing the user IDs.
Definition at line 795 of file c_comdef_service_body.class.php.
References _USER_LEVEL_SERVER_ADMIN, and c_comdef_server\GetOneUser().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         foreach ($in_editor_id_array as &$id) {
             // We need valid, non-server admin IDs.
             if ($id == $this->GetPrincipalUserID()) {
                 unset($id);
             } else {
                 $user = c_comdef_server::GetOneUser($id);
                 if (($user instanceof c_comdef_user) && ($user->GetUserLevel() != _USER_LEVEL_SERVER_ADMIN)) {
                     unset($id);
                 } else {
                     $id = intval($id);   // Just to be tinfoil...
                 }
             }
         }
         $this->_editors_string = implode(",", $in_editor_id_array);
         return $this->_editors_string;
     }
SetHelpline()
SetHelpline ($in_helpline_string)
Accessor - Sets the URI of the KML file for the Service Boundaries.
Parameters
$in_helpline_string A string, containing the helpline number
Definition at line 588 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_kml_file_uri_string = $in_helpline_string;
     }
SetID()
SetID ($in_service_body_id_bigint)
Accessor - Sets the service body ID as an integer.
Parameters
$in_service_body_id_bigint An integer, with the service body ID.
Definition at line 374 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_id_bigint = $in_service_body_id_bigint;
     }
SetOwner2ID()
SetOwner2ID ($in_sb_owner)
Accessor - Sets the ID of the 'secondary owner' of this object.
Parameters
$in_sb_owner An integer, containing the owner of the object.
Definition at line 523 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_sb_owner_2 = intval($in_sb_owner);
     }
SetOwner2Obj()
SetOwner2Obj (& $in_sb_owner_obj)
Accessor - Sets the ID of the 'secondary owner' of this object by sending in an object reference.
This will test, to ensure that a loop will not occur. The function will return false if it determines that the hierarchy would result in this object being its own ancestor.
Returns
true, if successful, false, if the ID would cause a loop.
Parameters
$in_sb_owner_obj An integer, containing the secondary owner of the object.
Definition at line 561 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if ($in_sb_owner_obj instanceof c_comdef_service_body) {
             return $this->SetOwner2ID($in_sb_owner_obj->GetID());
         }
         return false;
     }
SetOwnerID()
SetOwnerID ($in_sb_owner)
Accessor - Sets the ID of the 'owner' of this object.
Parameters
$in_sb_owner An integer, containing the owner of the object.
Definition at line 512 of file c_comdef_service_body.class.php.
Referenced by c_comdef_admin_ajax_handler\HandleServiceBodyCreate().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_sb_owner = intval($in_sb_owner);
     }
SetOwnerObj()
SetOwnerObj (& $in_sb_owner_obj)
Accessor - Sets the ID of the 'owner' of this object by sending in an object reference.
This will test, to ensure that a loop will not occur. The function will return false if it determines that the hierarchy would result in this object being its own ancestor.
Returns
true, if successful, false, if the ID would cause a loop.
Parameters
$in_sb_owner_obj An integer, containing the owner of the object.
Definition at line 540 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if ($in_sb_owner_obj instanceof c_comdef_service_body) {
             return $this->SetOwnerID($in_sb_owner_obj->GetID());
         }
         return false;
     }
SetPrincipalUserID()
SetPrincipalUserID ($in_principal_user_id_bigint)
Accessor - Sets the principal user for this service body.
Parameters
$in_principal_user_id_bigint Integer, the principal user ID.
Definition at line 409 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_principal_user_bigint = $in_principal_user_id_bigint;
     }
SetSBType()
SetSBType ($in_sb_type)
Accessor - Sets the URI of the KML file for the Service Boundaries.
Definition at line 441 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_sb_type = $in_sb_type;
     }
SetURI()
SetURI ($in_uri_string)
Accessor - Sets the URI of a site with more information on the Service Body.
Parameters
$in_uri_string A string, containing the URI
Definition at line 611 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_uri_string = $in_uri_string;
     }
UnserializeObject()
static UnserializeObject ($in_parent, $serialized_string) static
This takes the serialized table, and instantiates a new object from it.
Returns
a new instance of c_comdef_service_body, set up according to the serialized data passed in.
Parameters
$in_parent The parent object.
$serialized_string A string containing the serialized data.
Implements i_comdef_serialized.
Definition at line 857 of file c_comdef_service_body.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         list (  $_id_bigint,
                 $_principal_user_bigint,
                 $_editors_string,
                 $_kml_file_uri_string,
                 $_uri_string,
                 $_worldid_mixed,
                 $_name_string,
                 $_description_string,
                 $_lang_enum,
                 $sb_type,
                 $sb_owner,
                 $sb_owner_2,
                 $sb_meeting_email ) = unserialize($serialized_string);
         return new c_comdef_service_body($in_parent, $_id_bigint, $_principal_user_bigint, $_editors_string, $_kml_file_uri_string, $_uri_string, $_name_string, $_description_string, $_lang_enum, $_worldid_mixed, $sb_type, $sb_owner, $sb_owner_2, $sb_meeting_email);
     }
UpdateToDB()
UpdateToDB ($is_rollback = false)
Updates or adds this instance to the database.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Parameters
$is_rollback If true, this is a rollback operation.
Definition at line 99 of file c_comdef_service_body.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\AddNewChange(), c_comdef_server\GetCurrentUserObj(), c_comdef_server\GetServiceBodyByIDObj(), c_comdef_dbsingleton\preparedExec(), and c_comdef_dbsingleton\preparedQuery().
       {
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             // We take a snapshot of the service body as it currently sits in the database as a "before" image.
             $before = null;
             $before_id = null;
             $before_lang = null;
             $before_obj = c_comdef_server::GetServiceBodyByIDObj($this->GetID());
             if ($before_obj instanceof c_comdef_service_body) {
                 $before_obj = clone $before_obj;
                 if ($before_obj instanceof c_comdef_service_body) {
                     $before_obj->RestoreFromDB();
                     $before = $before_obj->SerializeObject();
                     $before_id = $before_obj->GetID();
                     $before_lang = $before_obj->GetLocalLang();
                     $before_obj = null;
                 }
             }
             $this->DeleteFromDB_NoRecord();
             try {
                 $update = array();
                 if ($this->_id_bigint) {
                     array_push($update, $this->_id_bigint);
                 }
                 array_push($update, $this->_principal_user_bigint);
                 array_push($update, $this->_editors_string);
                 array_push($update, $this->_kml_file_uri_string);
                 array_push($update, $this->_uri_string);
                 array_push($update, $this->GetLocalName());
                 array_push($update, $this->GetLocalDescription());
                 array_push($update, $this->GetLocalLang());
                 array_push($update, $this->GetWorldID());
                 array_push($update, $this->GetSBType());
                 array_push($update, $this->GeTOwnerID());
                 array_push($update, $this->GeTOwner2ID());
                 array_push($update, $this->GetContactEmail());
                 $sql = "INSERT INTO `".c_comdef_server::GetServiceBodiesTableName_obj()."` (";
                 if ($this->_id_bigint) {
                     $sql .= "`id_bigint`,";
                 }
                 $sql .= "`principal_user_bigint`,`editors_string`,`kml_file_uri_string`,`uri_string`,`name_string`,`description_string`,`lang_enum`,`worldid_mixed`,`sb_type`,`sb_owner`,`sb_owner_2`,`sb_meeting_email`) VALUES (";
                 if ($this->_id_bigint) {
                     $sql .= "?,";
                 }
                 $sql .= "?,?,?,?,?,?,?,?,?,?,?,?)";
                 c_comdef_dbsingleton::preparedExec($sql, $update);
                 // If this is a new user, then we'll need to fetch the ID.
                 if (!$this->_id_bigint) {
                     $sql = "SELECT LAST_INSERT_ID()";
                     $rows = c_comdef_dbsingleton::preparedQuery($sql);
                     if (is_array($rows) && count($rows)) {
                         $this->_id_bigint = intval($rows[0]['last_insert_id()']);
                     }
                 }
                 $after = $this->SerializeObject();
                 $after_id = $this->GetID();
                 $after_lang = $this->GetLocalLang();
                 $cType = (true == $is_rollback) ? 'comdef_change_type_rollback' : ((null != $before) ? 'comdef_change_type_change' : 'comdef_change_type_new');
                 c_comdef_server::AddNewChange($user->GetID(), $cType, $after_id, $before, $after, 'c_comdef_service_body', $before_id, $after_id, $before_lang, $after_lang);
                 $ret = true;
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_service_body::UpdateToDB()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
UserCanEdit()
UserCanEdit ($in_user_object = null)
Test to see if a user is allowed to edit an instance (change the data). Service Body Administrators that are Editors in parent, or secondary parent Service bodies can edit the Service body.
Returns
true, if the user is allowed to edit, false, otherwise.
Parameters
$in_user_object A reference to a c_comdef_user object, for the user to be validated. If null, or not supplied, the server current user is tested.
Implements i_comdef_auth.
Definition at line 977 of file c_comdef_service_body.class.php.
References $ret, _USER_LEVEL_SERVICE_BODY_ADMIN, c_comdef_server\GetCurrentUserObj(), c_comdef_server\GetServiceBodyByIDObj(), and c_comdef_server\IsUserServerAdmin().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         // We load the server user if one wasn't supplied.
         if (null == $in_user_object) {
             $in_user_object = c_comdef_server::GetCurrentUserObj();
         }
         // If it isn't a user object, we fail right there.
         if ($in_user_object instanceof c_comdef_user) {
             $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
             // User must be a Service Body Admin
             if ($in_user_object->GetUserLevel() == _USER_LEVEL_SERVICE_BODY_ADMIN) {
                 // If there is an existing object, then we can't make changes unless it's allowed in the existing object.
                 $current_obj = c_comdef_server::GetServiceBodyByIDObj($this->GetID());
                 $new_obj = false;
                 // If there is no current object, then we are a new service body. Otherwise, block dope fiends by reloading.
                 if ($current_obj instanceof c_comdef_service_body) {
                     // We clone, in case changes have been made, and we don't want to screw them up.
                     $current_obj = clone $current_obj;
                     $current_obj->RestoreFromDB();
                 } else {
                     $current_obj = $this;
                 }
                 if ($current_obj instanceof c_comdef_service_body) {
                     if (intval($current_obj->GetPrincipalUserID()) == intval($in_user_object->GetID())) {
                         $ret = true;
                     } else if ($this->GetOwnerID()) {
                         $parent = c_comdef_server::GetServiceBodyByIDObj($this->GetOwnerID());
                         if ($parent instanceof c_comdef_service_body) {
                             $ret = $parent->UserCanEdit($in_user_object);
                         }
                     }
                 }
             } elseif (c_comdef_server::IsUserServerAdmin()) { // The server admin can edit anything.
                 $ret = true;
             }
         }
         return $ret;
     }
UserCanEditMeetings()
UserCanEditMeetings ($in_user_object = null)
Test to see if a user is allowed to edit meetings in this Service body.
Returns
true, if the user is allowed to edit, false, otherwise.
Parameters
$in_user_object A reference to a c_comdef_user object, for the user to be validated. If null, or not supplied, the server current user is tested.
Definition at line 886 of file c_comdef_service_body.class.php.
References $ret, _USER_LEVEL_SERVICE_BODY_ADMIN, c_comdef_server\GetCurrentUserObj(), and c_comdef_server\GetServiceBodyByIDObj().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = $this->UserCanEdit($in_user_object);  // First, see if we are able to edit this Service body. If so, then we're golden.
         if (!$ret) {    // If not, then see if we are able to edit as a "guest."
             if (null == $in_user_object) {
                 $in_user_object = c_comdef_server::GetCurrentUserObj();
             }
             if ($in_user_object instanceof c_comdef_user) {
                 $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
                 $editors = $this->GetEditors();
                 foreach ($editors as $id) {
                     if (($in_user_object->GetID() == $id) && ($in_user_object->GetUserLevel() == _USER_LEVEL_SERVICE_BODY_ADMIN)) {
                         $ret = true;
                         break;
                     }
                 }
                 if (!$ret) {
                     if ($this->GetOwnerID()) {
                         $parent = c_comdef_server::GetServiceBodyByIDObj($this->GetOwnerID());
                         if ($parent instanceof c_comdef_service_body) {
                             $ret = $parent->UserCanEditMeetings($in_user_object);
                         }
                     }
                 }
             }
         }
         return $ret;
     }
UserCanObserve()
UserCanObserve ($in_user_object = null)
Test to see if a user is allowed to observe in this Service body.
Returns
true, if the user is allowed to observe, false, otherwise.
Parameters
$in_user_object A reference to a c_comdef_user object, for the user to be validated. If null, or not supplied, the server current user is tested.
Definition at line 931 of file c_comdef_service_body.class.php.
References $ret, _USER_LEVEL_OBSERVER, _USER_LEVEL_SERVICE_BODY_ADMIN, c_comdef_server\GetCurrentUserObj(), and c_comdef_server\GetServiceBodyByIDObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = $this->UserCanEdit($in_user_object);  // First, see if we are able to edit this Service body. If so, then we're golden.
         if (!$ret) {    // If not, then see if we are able to edit as a "guest."
             if (null == $in_user_object) {
                 $in_user_object = c_comdef_server::GetCurrentUserObj();
             }
             if ($in_user_object instanceof c_comdef_user) {
                 $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
                 $editors = $this->GetEditors();
                 foreach ($editors as $id) {
                     if (($in_user_object->GetID() == $id) && (($in_user_object->GetUserLevel() == _USER_LEVEL_SERVICE_BODY_ADMIN) || ($in_user_object->GetUserLevel() == _USER_LEVEL_OBSERVER))) {
                         $ret = true;
                         break;
                     }
                 }
                 if (!$ret) {
                     if ($this->GetOwnerID()) {
                         $parent = c_comdef_server::GetServiceBodyByIDObj($this->GetOwnerID());
                         if ($parent instanceof c_comdef_service_body) {
                             $ret = $parent->UserCanObserve($in_user_object);
                         }
                     }
                 }
             }
         }
         return $ret;
     }
Member Data Documentation
$_editors_string
$_editors_string = null private
A string, containing a CSV list of integers, each an ID for a user that has editor privileges for meetings for this Service Body.
Definition at line 67 of file c_comdef_service_body.class.php.
$_id_bigint
$_id_bigint = null private
An integer, containing the unique ID of this service body.
Definition at line 63 of file c_comdef_service_body.class.php.
$_kml_file_uri_string
$_kml_file_uri_string = null private
A string, containing the helpline (re-used KML file URI).
Definition at line 69 of file c_comdef_service_body.class.php.
$_principal_user_bigint
$_principal_user_bigint = null private
An integer, with the ID of the principal administrator for this Service Body.
Definition at line 65 of file c_comdef_service_body.class.php.
$_sb_meeting_email
$_sb_meeting_email = null private
A string that contains the meeting contact email address.
Definition at line 89 of file c_comdef_service_body.class.php.
$_sb_owner
$_sb_owner = null private
An integer. The ID of the Service Body that "owns" this one.
Definition at line 85 of file c_comdef_service_body.class.php.
$_sb_owner_2
$_sb_owner_2 = null private
An integer. Some Service Bodies can have "unofficial" "owners" (like Zonal Forums or Metro Areas).
Definition at line 87 of file c_comdef_service_body.class.php.
$_sb_type
$_sb_type = null private
An enum string, containing the Service Body type. It can be one of the following:
c_comdef_service_body__GRP__ Individual NA Group
c_comdef_service_body__ASC__ Area Service Committee
c_comdef_service_body__RSC__ Regional Service Committee
c_comdef_service_body__WSC__ World Service Committee
c_comdef_service_body__MAS__ Metro Area
c_comdef_service_body__ZFM__ Zonal Forum
c_comdef_service_body__GSU__ Group Service Unit
c_comdef_service_body__LSU__ Local Service Unit
Definition at line 83 of file c_comdef_service_body.class.php.
$_uri_string
$_uri_string = null private
A string, containing a URI to a site that gives further information about the Service Body.
Definition at line 71 of file c_comdef_service_body.class.php.
The documentation for this class was generated from the following file:
/Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/server/classes/c_comdef_service_body.class.php