FROM ubuntu:jammy

# Install packages
ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update \
    && apt-get -yqq install \
        software-properties-common \
        apache2 \
        curl \
        libapache2-mod-php \
        libcurl4-gnutls-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        mcrypt \
        unzip

# Install older php
RUN apt-get update \
    && apt-get -yqq install \
        php \
        php-curl \
        php-dev \
        php-gd \
        php-mbstring \
        php-mysql \
        php-pdo \
        php-xdebug \
        php-xml \
        php-zip \
        php-intl

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    HASH=$(curl -s https://composer.github.io/installer.sig) \
    && echo "$HASH composer-setup.php" | sha384sum -c - \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

# Configure apache
ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data
ENV APACHE_RUN_DIR www-data
ENV APACHE_LOG_DIR /var/log/apache2
ENV APACHE_LOCK_DIR /var/lock/apache2
ENV APACHE_PID_FILE /var/run/apache2.pid
RUN /bin/bash -c "source /etc/apache2/envvars"
RUN chown -R www-data: /var/www
RUN sed -i 's/Listen 80/Listen 8000/' /etc/apache2/ports.conf
RUN sed -i 's/^\tOptions Indexes FollowSymLinks/\tOptions FollowSymLinks/' /etc/apache2/apache2.conf
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
COPY auto-config.inc.php /var/www/html/auto-config.inc.php
RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
    ln -sf /proc/self/fd/1 /var/log/apache2/error.log
RUN a2enmod rewrite

# PHP memory limits
RUN sed -i 's/^memory_limit.*$/memory_limit = 256M/' /etc/php/8.1/apache2/php.ini
RUN sed -i 's/^memory_limit.*$/memory_limit = 320M/' /etc/php/8.1/cli/php.ini

EXPOSE 8000
