FROM ubuntu:jammy

ARG PHP_VERSION=8.2

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt-get update \
    && apt-get -yqq install \
        software-properties-common \
        apache2 \
        curl \
        libapache2-mod-php \
        libcurl4-gnutls-dev \
        libmcrypt-dev \
        libpng-dev \
        libxml2-dev \
        mcrypt \
        unzip

RUN add-apt-repository ppa:ondrej/php -y && apt-get update
RUN apt-get -yqq install \
        php${PHP_VERSION} \
        php${PHP_VERSION}-curl \
        php${PHP_VERSION}-dev \
        php${PHP_VERSION}-gd \
        php${PHP_VERSION}-mbstring \
        php${PHP_VERSION}-mysql \
        php${PHP_VERSION}-pdo \
        php${PHP_VERSION}-xdebug \
        php${PHP_VERSION}-xml \
        php${PHP_VERSION}-zip \
        php${PHP_VERSION}-intl \
        libapache2-mod-php${PHP_VERSION}

RUN update-alternatives --set php /usr/bin/php${PHP_VERSION}

# Install composer
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" && \
    HASH=$(curl -s https://composer.github.io/installer.sig) \
    && echo "$HASH composer-setup.php" | sha384sum -c - \
    && php composer-setup.php --install-dir=/usr/local/bin --filename=composer \
    && rm composer-setup.php

# Configure apache
ENV APACHE_RUN_USER=www-data
ENV APACHE_RUN_GROUP=www-data
ENV APACHE_RUN_DIR=www-data
ENV APACHE_LOG_DIR=/var/log/apache2
ENV APACHE_LOCK_DIR=/var/lock/apache2
ENV APACHE_PID_FILE=/var/run/apache2.pid
RUN /bin/bash -c "source /etc/apache2/envvars"
RUN chown -R www-data: /var/www
RUN sed -i 's/Listen 80/Listen 8000/' /etc/apache2/ports.conf
RUN sed -i 's/^\tOptions Indexes FollowSymLinks/\tOptions FollowSymLinks/' /etc/apache2/apache2.conf
COPY 000-default.conf /etc/apache2/sites-available/000-default.conf
COPY auto-config.inc.php /var/www/html/auto-config.inc.php
RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
    ln -sf /proc/self/fd/1 /var/log/apache2/error.log

RUN a2enmod rewrite

# Disable default PHP modules
RUN for ver in 7.4 8.0 8.1 8.2 8.3 8.4; do \
        if [ -f "/etc/apache2/mods-enabled/php$ver.conf" ] && [ "$ver" != "${PHP_VERSION}" ]; then \
            a2dismod php$ver; \
        fi; \
    done

# Enable the specified PHP version
RUN a2enmod php${PHP_VERSION}

# PHP memory limits
RUN sed -i 's/^memory_limit.*$/memory_limit = 256M/' /etc/php/${PHP_VERSION}/apache2/php.ini
RUN sed -i 's/^memory_limit.*$/memory_limit = 320M/' /etc/php/${PHP_VERSION}/cli/php.ini

EXPOSE 8000
