FROM public.ecr.aws/t5y4k5q3/bmlt-root-server:latest

ENV PHP_INI_PATH /etc/php/8.1/apache2/php.ini
ENV PHP_XDEBUG_ENABLED: 1

RUN apt-get update \
    && apt-get -yqq install \
    php-dev \
    php-xdebug

RUN echo "zend_extension=$(find /usr/lib/php/ -name xdebug.so)" >> ${PHP_INI_PATH} \
    && echo "xdebug.mode=debug" >> ${PHP_INI_PATH} \
    && echo "xdebug.client_port=9003" >> ${PHP_INI_PATH} \
    && echo "xdebug.client_host=host.docker.internal" >> ${PHP_INI_PATH} \
    && echo "xdebug.start_with_request=1" >> ${PHP_INI_PATH} \
    && echo "xdebug.log=/tmp/xdebug.log" >> ${PHP_INI_PATH} \
    && echo "xdebug.idekey=ROOT_SERVER_DEBUG" >> ${PHP_INI_PATH}
