FROM public.ecr.aws/t5y4k5q3/bmlt-root-server:latest

ENV PHP_INI_PATH /etc/php/7.4/apache2/php.ini
ENV PHP_XDEBUG_ENABLED: 1

RUN apt-get update \
    && apt-get -yqq install \
    php-dev \
    php-xdebug

RUN echo "zend_extension=$(find /usr/lib/php/ -name xdebug.so)" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_port=10000" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_enable=1" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_connect_back=0" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_host=docker.for.mac.localhost" >> ${PHP_INI_PATH} \
    && echo "xdebug.idekey=ROOT_SERVER_DEBUG" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_autostart=1" >> ${PHP_INI_PATH} \
    && echo "xdebug.remote_log=/tmp/xdebug.log" >> ${PHP_INI_PATH}
