BMLT Root Server: /Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/local_server/index.php File Reference
index.php File Reference
Variables
const _LANG_COOKIE_NAME 'bmlt_admin_lang_pref'
global $http_vars = array_merge($_GET, $_POST)
$lang_enum = ''
if(isset($_COOKIE) &&isset($_COOKIE[_LANG_COOKIE_NAME]) && $_COOKIE[_LANG_COOKIE_NAME]) if(isset($http_vars['lang_enum']) && $http_vars['lang_enum']) $http_vars ['lang_enum'] = $lang_enum
$file_loc = dirname(__FILE__).'/install_wizard/index.php'
if(isset($g_enable_language_selector) && $g_enable_language_selector) if(isset($http_vars ['bmlt_data_transfer'])) elseif(isset($http_vars ['bmlt_ajax_callback'])) else {
$config_file_path = dirname(dirname(__FILE__)).'/server/config/get-config.php'
if(file_exists($config_file_path)) $url_path = GetURLToMainServerDirectory()
$shortcut_icon = $url_path."local_server/server_admin/style/images/shortcut.png"
$stylesheet = $url_path."local_server/server_admin/style/styles.css?v=" . time()
$server = c_comdef_server::MakeServer()
Variable Documentation
$config_file_path
$config_file_path = dirname(dirname(__FILE__)).'/server/config/get-config.php'
Definition at line 60 of file index.php.
$file_loc
$file_loc = dirname(__FILE__).'/install_wizard/index.php'
Definition at line 36 of file index.php.
$http_vars [1/2]
$http_vars = array_merge($_GET, $_POST)
Definition at line 21 of file index.php.
Referenced by c_comdef_server\__construct(), c_comdef_admin_bar(), c_comdef_LoginForm(), parse_redirect(), and c_comdef_admin_xml_handler\process_meeting_search().
$http_vars [2/2]
if (isset($_COOKIE) &&isset($_COOKIE[_LANG_COOKIE_NAME]) &&$_COOKIE[_LANG_COOKIE_NAME]) if (isset($http_vars[ 'lang_enum']) &&$http_vars[ 'lang_enum']) $http_vars[ 'lang_enum'] = $lang_enum
Definition at line 34 of file index.php.
$lang_enum
$lang_enum = ''
Definition at line 23 of file index.php.
Referenced by c_comdef_data_importer\__construct(), c_comdef_admin_bar(), DisplaySearchResultsCSV(), c_comdef_server\GetLocalLang(), and c_comdef_server\GetLocalStrings().
$server
$server = c_comdef_server::MakeServer()
Definition at line 75 of file index.php.
$shortcut_icon
$shortcut_icon = $url_path."local_server/server_admin/style/images/shortcut.png"
Definition at line 67 of file index.php.
$stylesheet
$stylesheet = $url_path."local_server/server_admin/style/styles.css?v=" . time()
Definition at line 68 of file index.php.
$url_path
if (file_exists($config_file_path)) $url_path = GetURLToMainServerDirectory()
Definition at line 66 of file index.php.
Referenced by c_comdef_admin_main_console\__construct(), and GetURLToMainServerDirectory().
_LANG_COOKIE_NAME
const _LANG_COOKIE_NAME 'bmlt_admin_lang_pref'
Definition at line 19 of file index.php.
else
if (isset($g_enable_language_selector) &&$g_enable_language_selector) if (isset($http_vars [ 'bmlt_data_transfer'])) elseif (isset($http_vars [ 'bmlt_ajax_callback'])) else {
Definition at line 49 of file index.php.