/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorUnauthorized
 */
export interface ErrorUnauthorized {
    /**
     * 
     * @type {string}
     * @memberof ErrorUnauthorized
     */
    message?: string;
}

/**
 * Check if a given object implements the ErrorUnauthorized interface.
 */
export function instanceOfErrorUnauthorized(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ErrorUnauthorizedFromJSON(json: any): ErrorUnauthorized {
    return ErrorUnauthorizedFromJSONTyped(json, false);
}

export function ErrorUnauthorizedFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorUnauthorized {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function ErrorUnauthorizedToJSON(value?: ErrorUnauthorized | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

