/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FormatAllOf
 */
export interface FormatAllOf {
    /**
     * 
     * @type {number}
     * @memberof FormatAllOf
     */
    id?: number;
}

/**
 * Check if a given object implements the FormatAllOf interface.
 */
export function instanceOfFormatAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FormatAllOfFromJSON(json: any): FormatAllOf {
    return FormatAllOfFromJSONTyped(json, false);
}

export function FormatAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormatAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
    };
}

export function FormatAllOfToJSON(value?: FormatAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
    };
}

