/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FormatTranslation } from './FormatTranslation';
import {
    FormatTranslationFromJSON,
    FormatTranslationFromJSONTyped,
    FormatTranslationToJSON,
} from './FormatTranslation';

/**
 * 
 * @export
 * @interface FormatBase
 */
export interface FormatBase {
    /**
     * 
     * @type {string}
     * @memberof FormatBase
     */
    worldId?: string;
    /**
     * 
     * @type {string}
     * @memberof FormatBase
     */
    type?: string;
    /**
     * 
     * @type {Array<FormatTranslation>}
     * @memberof FormatBase
     */
    translations?: Array<FormatTranslation>;
}

/**
 * Check if a given object implements the FormatBase interface.
 */
export function instanceOfFormatBase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FormatBaseFromJSON(json: any): FormatBase {
    return FormatBaseFromJSONTyped(json, false);
}

export function FormatBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): FormatBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'worldId': !exists(json, 'worldId') ? undefined : json['worldId'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'translations': !exists(json, 'translations') ? undefined : ((json['translations'] as Array<any>).map(FormatTranslationFromJSON)),
    };
}

export function FormatBaseToJSON(value?: FormatBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'worldId': value.worldId,
        'type': value.type,
        'translations': value.translations === undefined ? undefined : ((value.translations as Array<any>).map(FormatTranslationToJSON)),
    };
}

