/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Returns when no format exists.
 * @export
 * @interface NoFormatExists
 */
export interface NoFormatExists {
    /**
     * 
     * @type {string}
     * @memberof NoFormatExists
     */
    message?: string;
}

/**
 * Check if a given object implements the NoFormatExists interface.
 */
export function instanceOfNoFormatExists(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NoFormatExistsFromJSON(json: any): NoFormatExists {
    return NoFormatExistsFromJSONTyped(json, false);
}

export function NoFormatExistsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoFormatExists {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function NoFormatExistsToJSON(value?: NoFormatExists | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

