/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Returns when no Meeting exists.
 * @export
 * @interface NoMeetingExists
 */
export interface NoMeetingExists {
    /**
     * 
     * @type {string}
     * @memberof NoMeetingExists
     */
    message?: string;
}

/**
 * Check if a given object implements the NoMeetingExists interface.
 */
export function instanceOfNoMeetingExists(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NoMeetingExistsFromJSON(json: any): NoMeetingExists {
    return NoMeetingExistsFromJSONTyped(json, false);
}

export function NoMeetingExistsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoMeetingExists {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function NoMeetingExistsToJSON(value?: NoMeetingExists | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

