/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * Returns when no user exists.
 * @export
 * @interface NoServiceBodyExists
 */
export interface NoServiceBodyExists {
    /**
     * 
     * @type {string}
     * @memberof NoServiceBodyExists
     */
    message?: string;
}

/**
 * Check if a given object implements the NoServiceBodyExists interface.
 */
export function instanceOfNoServiceBodyExists(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function NoServiceBodyExistsFromJSON(json: any): NoServiceBodyExists {
    return NoServiceBodyExistsFromJSONTyped(json, false);
}

export function NoServiceBodyExistsFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoServiceBodyExists {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'message': !exists(json, 'message') ? undefined : json['message'],
    };
}

export function NoServiceBodyExistsToJSON(value?: NoServiceBodyExists | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'message': value.message,
    };
}

