/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ServiceBodyBase
 */
export interface ServiceBodyBase {
    /**
     * 
     * @type {number}
     * @memberof ServiceBodyBase
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyBase
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyBase
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyBase
     */
    type?: string;
    /**
     * 
     * @type {number}
     * @memberof ServiceBodyBase
     */
    adminUserId?: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof ServiceBodyBase
     */
    assignedUserIds?: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyBase
     */
    url?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyBase
     */
    helpline?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyBase
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof ServiceBodyBase
     */
    worldId?: string;
}

/**
 * Check if a given object implements the ServiceBodyBase interface.
 */
export function instanceOfServiceBodyBase(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ServiceBodyBaseFromJSON(json: any): ServiceBodyBase {
    return ServiceBodyBaseFromJSONTyped(json, false);
}

export function ServiceBodyBaseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ServiceBodyBase {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'parentId': !exists(json, 'parentId') ? undefined : json['parentId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'adminUserId': !exists(json, 'adminUserId') ? undefined : json['adminUserId'],
        'assignedUserIds': !exists(json, 'assignedUserIds') ? undefined : json['assignedUserIds'],
        'url': !exists(json, 'url') ? undefined : json['url'],
        'helpline': !exists(json, 'helpline') ? undefined : json['helpline'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'worldId': !exists(json, 'worldId') ? undefined : json['worldId'],
    };
}

export function ServiceBodyBaseToJSON(value?: ServiceBodyBase | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'parentId': value.parentId,
        'name': value.name,
        'description': value.description,
        'type': value.type,
        'adminUserId': value.adminUserId,
        'assignedUserIds': value.assignedUserIds,
        'url': value.url,
        'helpline': value.helpline,
        'email': value.email,
        'worldId': value.worldId,
    };
}

