/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserPartialUpdate
 */
export interface UserPartialUpdate {
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdate
     */
    username?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdate
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdate
     */
    displayName?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdate
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdate
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdate
     */
    ownerId?: string;
    /**
     * 
     * @type {string}
     * @memberof UserPartialUpdate
     */
    password?: string;
}

/**
 * Check if a given object implements the UserPartialUpdate interface.
 */
export function instanceOfUserPartialUpdate(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserPartialUpdateFromJSON(json: any): UserPartialUpdate {
    return UserPartialUpdateFromJSONTyped(json, false);
}

export function UserPartialUpdateFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserPartialUpdate {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'username': !exists(json, 'username') ? undefined : json['username'],
        'type': !exists(json, 'type') ? undefined : json['type'],
        'displayName': !exists(json, 'displayName') ? undefined : json['displayName'],
        'description': !exists(json, 'description') ? undefined : json['description'],
        'email': !exists(json, 'email') ? undefined : json['email'],
        'ownerId': !exists(json, 'ownerId') ? undefined : json['ownerId'],
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function UserPartialUpdateToJSON(value?: UserPartialUpdate | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'username': value.username,
        'type': value.type,
        'displayName': value.displayName,
        'description': value.description,
        'email': value.email,
        'ownerId': value.ownerId,
        'password': value.password,
    };
}

