/* tslint:disable */
/* eslint-disable */
/**
 * BMLT
 * BMLT Admin API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserCreateAllOf
 */
export interface UserCreateAllOf {
    /**
     * 
     * @type {string}
     * @memberof UserCreateAllOf
     */
    password?: string;
}

/**
 * Check if a given object implements the UserCreateAllOf interface.
 */
export function instanceOfUserCreateAllOf(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UserCreateAllOfFromJSON(json: any): UserCreateAllOf {
    return UserCreateAllOfFromJSONTyped(json, false);
}

export function UserCreateAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserCreateAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'password': !exists(json, 'password') ? undefined : json['password'],
    };
}

export function UserCreateAllOfToJSON(value?: UserCreateAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'password': value.password,
    };
}

