BMLT Root Server: /Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/server/shared/spanish_metaphone.php File Reference
spanish_metaphone.php File Reference
Functions
spanish_metaphone ($string)
This is a Spanish version of the standard double metaphone tokenizer.
spanish_metaphone_string_at ($string, $start, $string_length, $list)
Search a string for the presence of substrings.
spanish_metaphone_is_vowel ($string, $pos)
See if the character at a given string position is a vowel.
Function Documentation
spanish_metaphone()
spanish_metaphone ($string)
This is a Spanish version of the standard double metaphone tokenizer.
Metaphone allows matching of strings phonetically, but is very language- dependent. The standard metaphone algorithm is for English, and misses a few rules for Spanish. This is a version that takes Spanish pronunciation into account when generating tokens.
Returns
a metaphone token for the given Spanish string.
Parameters
$string The string to tokenize.
Definition at line 52 of file spanish_metaphone.php.
References spanish_metaphone_is_vowel(), and spanish_metaphone_string_at().
Referenced by SplitIntoMetaphone().
   {
     //initialize metaphone key string
     $meta_key = "";
     //set maximum metaphone key size
     $key_length = 6;
     //set current position to the beginning
     $current_pos =  0;
     //get string  length
     $string_length = strlen($string);
     //set to  the end of the string
     $end_of_string_pos = $string_length - 1;
     $original_string = $string. "    ";
     //Let's replace some spanish characters  easily confused
     $original_string = strtr($original_string, 'bz', 'AEIOUNUVS');
     //convert string to uppercase
     $original_string = strtoupper($original_string);
     // main loop
     while (strlen($meta_key) < $key_length) {
         //break out of the loop if greater or equal than the length
         if ($current_pos >= $string_length) {
             break;
         }
         //get character from the string
         $current_char = substr($original_string, $current_pos, 1);
         //if it is a vowel, and it is at the begining of the string,
         //set it as part of the meta key
         if (spanish_metaphone_is_vowel($original_string, $current_pos)
                                   && ($current_pos == 0)) {
             $meta_key   .= $current_char;
             $current_pos += 1;
         } elseif (spanish_metaphone_string_at(
             $original_string,
             $current_pos,
             1,
             array('D','F','J','K','M','N','P','R','S','T','V')
         )) {
             //Let's check for consonants  that have a single sound
             //or already have been replaced  because they share the same
             //sound like 'B' for 'V' and 'S' for 'Z'
             $meta_key   .= $current_char;
             //increment by two if a repeated letter is found
             if (substr($original_string, $current_pos + 1, 1) == $current_char) {
                 $current_pos += 2;
             }
             //else increment only by one
             $current_pos += 1;
         } else //check consonants with similar confusing sounds
             {
             switch ($current_char) {
                 case 'C':
                     //special case 'macho', chato,etc.
                     if (substr($original_string, $current_pos + 1, 1)== 'H') {
                         $current_pos += 2;
                     } elseif (substr($original_string, $current_pos + 1, 1)== 'C') {
                         //special case 'accin', 'reaccin',etc.
                         $meta_key   .= 'X';
                         $current_pos += 2;
                         break;
                     } elseif (spanish_metaphone_string_at($original_string, $current_pos, 2, array('CE','CI'))) {
                         // special case 'cesar', 'cien', 'cid', 'conciencia'
                         $meta_key   .= 'S';
                         $current_pos += 2;
                         break;
                     } // else
                     $meta_key   .= 'K';
                     $current_pos += 1;
                     break;
                 case 'G':
                     // special case 'gente', 'ecologia',etc
                     if (spanish_metaphone_string_at(
                         $original_string,
                         $current_pos,
                         2,
                         array('GE','GI')
                     )) {
                         $meta_key   .= 'J';
                         $current_pos += 2;
                         break;
                     } // else
                     $meta_key   .= 'G';
                     $current_pos += 1;
                     break;
                 //since the letter 'h' is silent in spanish,
                 //let's set the meta key to the vowel after the letter 'h'
                 case 'H':
                     if (spanish_metaphone_is_vowel($original_string, $current_pos + 1)) {
                         $meta_key .= $original_string[$current_pos + 1];
                         $current_pos += 2;
                         break;
                     }
                     // else
                     $meta_key   .= 'H';
                     $current_pos += 1;
                     break;
                 case 'Q':
                     if (substr($original_string, $current_pos + 1, 1) == 'U') {
                         $current_pos += 2;
                     } else {
                         $current_pos += 1;
                     }
                     $meta_key   .= 'K';
                     break;
                 case 'W':
                     $meta_key   .= 'U';
                     $current_pos += 2;
                     break;
                 case 'X':
                     //some mexican spanish words like'Xochimilco','xochitl'
                     if ($current_pos == 0) {
                         $meta_key   .= 'S';
                         $current_pos += 2;
                         break;
                     }
                     $meta_key   .= 'X';
                     $current_pos += 1;
                     break;
                 default:
                     $current_pos += 1;
             } // end of switch
         }//end else
             //Commented code *** for debugging purposes only ***
             /*
             printf("<br>ORIGINAL STRING:    '%s'\n", $original_string);
             printf("<br>CURRENT POSITION:   '%s'\n", $current_pos);
             intf("<br>META KEY STRING:    '%s'\n", $meta_key);
             */
     } // end of while loop
     //trim any blank characters
     $meta_key = trim($meta_key) ;
     //return the final meta key string
     return $meta_key;
 }
spanish_metaphone_is_vowel()
spanish_metaphone_is_vowel ($string, $pos)
See if the character at a given string position is a vowel.
Returns
true if the character is a vowel.
Parameters
$string The string to search.
$pos The position of the character to test.
Definition at line 254 of file spanish_metaphone.php.
Referenced by spanish_metaphone().
   {
     return preg_match("/[AEIOU]/", substr($string, $pos, 1));
 }
spanish_metaphone_string_at()
spanish_metaphone_string_at ($string, $start, $string_length, $list)
Search a string for the presence of substrings.
Returns
true if the string contains any of the given substrings.
Parameters
$string The main string to search.
$start The position within the main string to start the search.
$string_length The length of the substrings to test.
$list An array of substrings.
Definition at line 225 of file spanish_metaphone.php.
Referenced by spanish_metaphone().
   {
     if (($start <0) || ($start >= strlen($string))) {
         return 0;
     }
     for ($i=0; $i<count($list); $i++) {
         if ($list[$i] == substr($string, $start, $string_length)) {
             return 1;
         }
     }
     return 0;
 }