BMLT Root Server: /Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/client_interface/csv/common_search.inc.php File Reference
common_search.inc.php File Reference
This file contains a routine that allows a search to be established with an existing c_comdef_search_manager object.
Functions
SetUpSearch (&$in_search_manager, &$in_http_vars)
This function sets up the search manager to do the specified search. It does not actually do the search.
GetAllContainedServiceBodyIDs ($in_parent_id=0)
This gets all the Service bodies, and returns a one-dimensional arry, containing its ID, and the IDs of all the Service bodies that are contained in the array.
BuildFormats ($in_mtg_obj, $lite=false)
This displays the format keys, along with abbreviations to display when the cursor is over them.
BuildTown ($in_mtg_obj)
Combines the town, borough and neighborhood into one string.
BuildTime ($in_time, $in_integer=false)
This creates a time string to be displayed for the meeting. The display is done in non-military time, and "midnight" and "noon" are substituted for 12:59:00, 00:00:00 and 12:00:00.
BuildLocation ($in_mtg_obj)
This combines the location and street address fields.
GetGeocodeFromString ($in_string, $in_weekday_tinyint_array)
This function uses the server-level Google Maps API to try to geocode an address from the string passed in. A instance of c_comdef_server needs to have been instantiated by the time this is called.
Detailed Description
This file contains a routine that allows a search to be established with an existing c_comdef_search_manager object.
This file is part of the Basic Meeting List Toolbox (BMLT).
Find out more at: https://bmlt.app
BMLT is free software: you can redistribute it and/or modify it under the terms of the MIT License.
BMLT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the MIT License for more details.
You should have received a copy of the MIT License along with this code. If not, see https://opensource.org/licenses/MIT.
Definition in file common_search.inc.php.
Function Documentation
BuildFormats()
BuildFormats ($in_mtg_obj, $lite = false)
This displays the format keys, along with abbreviations to display when the cursor is over them.
Returns
a string, containing the HTML rendered by the function, or, if the $lite parameter is set to true, an associative, multidimensional array, containing the information.
Parameters
$in_mtg_obj A reference to an instance of c_comdef_meeting.
$lite If this is set to true, then the formats will be returned in an associative array, instead of as HTML. Default is false.
Definition at line 566 of file common_search.inc.php.
References c_comdef_htmlspecialchars().
   {
     $formats = "";
     $formats_obj = $in_mtg_obj->GetMeetingDataValue('formats');
     if (is_array($formats_obj) && count($formats_obj)) {
         foreach ($formats_obj as $format) {
             if ($format instanceof c_comdef_format) {
                 $key = htmlspecialchars($format->GetKey());
                 $name = c_comdef_htmlspecialchars($format->GetLocalName());
                 $desc = c_comdef_htmlspecialchars($format->GetLocalDescription());
                 if ($lite) {
                     $formats[$key]['name'] = $name;
                     $formats[$key]['desc'] = $desc;
                 } else {
                     $formatspacer = '';
                     if ($formats) {
                         $formatspacer = ' ';
                     }
                     $formats .= "<span class=\"c_comdef_search_results_single_format\"><abbr title=\"$desc\">$formatspacer$key</abbr></span>";
                 }
             }
         }
     }
     return $formats;
 }
BuildLocation()
BuildLocation ($in_mtg_obj)
This combines the location and street address fields.
Returns
a string, containing the HTML rendered by the function.
Parameters
$in_mtg_obj A reference to an instance of c_comdef_meeting.
Definition at line 661 of file common_search.inc.php.
References $ret, and c_comdef_htmlspecialchars().
 {
     $ret = "";
     if ($in_mtg_obj instanceof c_comdef_meeting) {
         $location_text = c_comdef_htmlspecialchars(trim(stripslashes($in_mtg_obj->GetMeetingDataValue('location_text'))));
         $street = c_comdef_htmlspecialchars(trim(stripslashes($in_mtg_obj->GetMeetingDataValue('location_street'))));
         $info = c_comdef_htmlspecialchars(trim(stripslashes($in_mtg_obj->GetMeetingDataValue('location_info'))));
         if ($location_text) {
             $ret .= $location_text;
         }
         if ($street) {
             if ($ret) {
                 $ret .= ", ";
             }
             $ret .= $street;
         }
         if ($info) {
             if ($ret) {
                 $ret .= " ";
             }
             $ret .= "($info)";
         }
     }
     return $ret;
 }
BuildTime()
BuildTime ($in_time, $in_integer = false)
This creates a time string to be displayed for the meeting. The display is done in non-military time, and "midnight" and "noon" are substituted for 12:59:00, 00:00:00 and 12:00:00.
Returns
a string, containing the HTML rendered by the function.
Parameters
$in_time A string. The value of the time field.
$in_integer If true, the time is returned as an integer (Military time).
Definition at line 633 of file common_search.inc.php.
References c_comdef_htmlspecialchars(), and c_comdef_server\GetLocalStrings().
   {
     $localized_strings = c_comdef_server::GetLocalStrings();
     $time = null;
     if ($in_integer) {
         $time = intval(str_replace(':', '', $in_time)) / 100;
     } else {
         if (($in_time == "00:00:00") || ($in_time == "23:59:00")) {
             $time = c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['meeting_editor_screen_meeting_noon_label']);
         } elseif ($in_time == "12:00:00") {
             $time = c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['meeting_editor_screen_meeting_midnight_label']);
         } else {
             $time = c_comdef_htmlspecialchars(date($localized_strings['time_format'], strtotime($in_time)));
         }
     }
     return $time;
 }
BuildTown()
BuildTown ($in_mtg_obj)
Combines the town, borough and neighborhood into one string.
Returns
a string, containing the HTML rendered by the function.
Parameters
$in_mtg_obj A reference to an instance of c_comdef_meeting.
Definition at line 603 of file common_search.inc.php.
References c_comdef_htmlspecialchars().
 {
     $location_borough = c_comdef_htmlspecialchars(trim(stripslashes($in_mtg_obj->GetMeetingDataValue('location_city_subsection'))));
     $location_town = c_comdef_htmlspecialchars(trim(stripslashes($in_mtg_obj->GetMeetingDataValue('location_municipality'))));
     $location_neighborhood = c_comdef_htmlspecialchars(trim(stripslashes($in_mtg_obj->GetMeetingDataValue('location_neighborhood'))));
     $location_province = c_comdef_htmlspecialchars(trim(stripslashes($in_mtg_obj->GetMeetingDataValue('location_province'))));
     if ($location_province) {
         $location_town .= ', '.$location_province;
     }
     if ($location_borough) {
         $location_town = "<span class=\"c_comdef_search_results_town\">$location_borough</span>, <span class=\"c_comdef_search_results_town\">$location_town</span>";
     }
     if ($location_neighborhood) {
         $location_town = "$location_town <span class=\"c_comdef_search_results_neighborhood\">($location_neighborhood)</span>";
     }
     return $location_town;
 }
GetAllContainedServiceBodyIDs()
GetAllContainedServiceBodyIDs ($in_parent_id = 0)
This gets all the Service bodies, and returns a one-dimensional arry, containing its ID, and the IDs of all the Service bodies that are contained in the array.
Returns
an array of integers.
Parameters
$in_parent_id This is the ID of the top Service body (will not be included in the reponse).
Definition at line 537 of file common_search.inc.php.
References $ret, and c_comdef_server\GetServer().
Referenced by SetUpSearch().
 {
     $in_parent_id = intval($in_parent_id);
     $ret = array( $in_parent_id );
     $service_bodies = c_comdef_server::GetServer()->GetServiceBodyArray();
     foreach ($service_bodies as $service_body) {
         $sb_id = intval($service_body->GetID());
         $parent_id = intval($service_body->GetOwnerID());
         if ($in_parent_id == $parent_id) {
             $ret2 = GetAllContainedServiceBodyIDs($sb_id);
             $ret = array_merge($ret, $ret2);
         }
     }
     return $ret;
 }
GetGeocodeFromString()
GetGeocodeFromString ($in_string, $in_weekday_tinyint_array)
This function uses the server-level Google Maps API to try to geocode an address from the string passed in. A instance of c_comdef_server needs to have been instantiated by the time this is called.
Returns
an associative array of two floating-point numbers, representing the longitude and latitude, in degrees, of any geocoded result. Null, if no valid result was returned.
Parameters
$in_string The string to be checked.
$in_weekday_tinyint_array An array of weekdays in which to filter for.
Definition at line 704 of file common_search.inc.php.
References $ret, c_comdef_server\GetLocalStrings(), and c_comdef_server\HuntForRadius().
Referenced by SetUpSearch().
   {
     $ret = null;
     $localized_strings = c_comdef_server::GetLocalStrings();
     $geo_uri = $localized_strings['comdef_server_admin_strings']['ServerMapsURL'];
     if ($localized_strings['region_bias']) {
         $geo_uri .= '&region='.$localized_strings['region_bias'];
     }
     if ($localized_strings['google_api_key']) {
         $geo_uri .= '&key='.$localized_strings['google_api_key'];
     }
     // Bit of a kludge. If the string is just a number (a postcode), then we add the region bias directly to it.
     if (is_numeric($in_string) && $localized_strings['region_bias']) {
         $in_string .= " ".$localized_strings['region_bias'];
     }
     $geo_uri = str_replace('##SEARCH_STRING##', urlencode($in_string), $geo_uri);
     // We set up a 200-mile bounds, in order to encourage Google to look in the proper place.
     $m_p_deg = 100 / (111.321 * cos(deg2rad($localized_strings['search_spec_map_center']['latitude'])) * 1.609344);  // Degrees for 100 miles.
     $bounds_ar = strval($localized_strings['search_spec_map_center']['latitude'] - $m_p_deg).",". strval($localized_strings['search_spec_map_center']['longitude'] - $m_p_deg);       // Southwest corner
     $bounds_ar .= "|";
     $bounds_ar .= strval($localized_strings['search_spec_map_center']['latitude'] + $m_p_deg).",".strval($localized_strings['search_spec_map_center']['longitude'] + $m_p_deg);       // Northeast corner
     $xml = simplexml_load_file($geo_uri);
     if ($xml->status == 'OK') {
         $ret['longitude'] = floatval($xml->result->geometry->location->lng);
         $ret['latitude'] = floatval($xml->result->geometry->location->lat);
         $radius = c_comdef_server::HuntForRadius($localized_strings['number_of_meetings_for_auto'], $ret['longitude'], $ret['latitude'], $in_weekday_tinyint_array);
         if ($radius) {
             // The native units for the radius search is km. We need to convert to miles, if we are in miles.
             if ($localized_strings['dist_units'] == 'mi') {
                 $radius /= 1.609344;
             }
             $ret['radius'] = $radius;
         } else {
             $ret = null;
         }
     }
     return $ret;
 }
SetUpSearch()
SetUpSearch (& $in_search_manager, & $in_http_vars)
This function sets up the search manager to do the specified search. It does not actually do the search.
Parameters
$in_search_manager A reference to an instance of c_comdef_search_manager. The search manager to set up.
Definition at line 30 of file common_search.inc.php.
References GetAllContainedServiceBodyIDs(), c_comdef_server\GetCurrentUserObj(), c_comdef_meeting\GetDataTableTemplate(), GetGeocodeFromString(), c_comdef_server\GetLocalStrings(), and true.
Referenced by DisplaySearchResultsCSV().
   {
     $search_string = isset($in_http_vars['SearchString']) ? trim($in_http_vars['SearchString']) : '';
     if ($search_string && !(isset($in_http_vars['StringSearchIsAnAddress']) && $in_http_vars['StringSearchIsAnAddress']) && intval($search_string) && (preg_match('|\d+|', $search_string) || preg_match('(|\d+|,)+', $search_string))) {
         $temp_ids = explode(',', $search_string);
         if (is_array($temp_ids) && count($temp_ids)) {
             $first = true;
             foreach ($temp_ids as $id) {
                 $id = intval(trim($id));
                 if ($id) {
                     if ($first) {
                         $in_http_vars['meeting_ids'] = null;
                         $first = false;
                     }
                     $in_http_vars['meeting_ids'][] = $id;
                 }
             }
         } else {
             $id = intval($search_string);
             if ($id) {
                 $in_http_vars['meeting_ids'] = array ( intval($id) );
             }
         }
     }
     // If we have a meeting ID array, then that defines the entire search. We ignore everything else
     if (isset($in_http_vars['meeting_ids']) && is_array($in_http_vars['meeting_ids']) && count($in_http_vars['meeting_ids'])) {
         $in_search_manager->SetMeetingIDArray($in_http_vars['meeting_ids']);
     } else {
         if (isset($in_http_vars['sort_results_by_distance'])) {
             $in_search_manager->SetSortByDistance($in_http_vars['sort_results_by_distance']);
         } elseif (isset($in_http_vars['sort_keys']) && $in_http_vars['sort_keys']) {
             $sort_fields = array();
             $keys = explode(',', $in_http_vars['sort_keys']);
             $dir = 'asc';
             foreach ($keys as $key) {
                 if (strtolower(trim($key)) == 'desc') {
                     $dir = 'desc';
                 } else {
                     $templates = c_comdef_meeting::GetDataTableTemplate();
                     if ($templates && count($templates)) {
                         $additional = array ();
                         foreach ($templates as $template) {
                             $value = $template['key'];
                             array_push($additional, $value);
                         }
                         $standards = array ( 'weekday_tinyint', 'id_bigint', 'worldid_mixed', 'service_body_bigint', 'lang_enum', 'duration_time', 'start_time', 'longitude', 'latitude' );
                         $templates = array_merge($standards, $additional);
                         if (in_array($key, $templates)) {
                             array_push($sort_fields, $key);
                         }
                     }
                 }
             }
             $in_search_manager->SetSort($sort_fields, $dir == 'desc', count($sort_fields));
         }
         // The first thing we do is try to resolve any address lookups.
         if ($search_string && isset($in_http_vars['StringSearchIsAnAddress']) && $in_http_vars['StringSearchIsAnAddress']) {
             $geo_search = (isset($in_http_vars['geo_width']) && $in_http_vars['geo_width']) ? true : ((isset($in_http_vars['geo_width_km']) && $in_http_vars['geo_width_km']) ? true : false);
             // We do a geocode to find out if this is an address.
             if (!$geo_search) {
                 $search_string = preg_replace('|,(\s*?)|', ', ', $search_string);    // This works around a bug caused by too-tight commas.
                 $geo = GetGeocodeFromString($search_string, $in_http_vars['advanced_weekdays']);
                 if (is_array($geo) && count($geo)) {
                     $localized_strings = c_comdef_server::GetLocalStrings();
                     $in_http_vars['long_val'] = $geo['longitude'];
                     $in_http_vars['lat_val'] = $geo['latitude'];
                     if (isset($in_http_vars['SearchStringRadius']) && floatval($in_http_vars['SearchStringRadius']) != 0.0) {
                         if (intval($in_http_vars['SearchStringRadius']) < 0) {
                             $geo['radius'] = intval($in_http_vars['SearchStringRadius']);
                         } else {
                             $geo['radius'] = floatval($in_http_vars['SearchStringRadius']);
                         }
                     }
                     if ($localized_strings['dist_units'] == 'mi') {
                         if (isset($in_http_vars['geo_width_km'])) {
                             unset($in_http_vars['geo_width_km']);
                         }
                         $in_http_vars['geo_width'] = $geo['radius'];
                     } else {
                         unset($in_http_vars['geo_width']);
                         $in_http_vars['geo_width_km'] = $geo['radius'];
                     }
                     /* We need to undef these, because they can step on the long/lat. */
                     unset($search_string);
                     unset($in_http_vars['StringSearchIsAnAddress']);
                     unset($in_http_vars['SearchStringRadius']);
                 }
             }
         }
         // First, set up the services.
         if (isset($in_http_vars['bmlt_search_type']) && ($in_http_vars['bmlt_search_type'] == 'advanced') && isset($in_http_vars['advanced_service_bodies']) && is_array($in_http_vars['advanced_service_bodies']) && count($in_http_vars['advanced_service_bodies'])) {
             $in_http_vars['services'] = $in_http_vars['advanced_service_bodies'];
         }
         if (isset($in_http_vars['services']) && !is_array($in_http_vars['services'])) {
             $in_http_vars['services'] = array ( $in_http_vars['services'] );
         }
         // Look for Service bodies.
         if (isset($in_http_vars['services']) && is_array($in_http_vars['services']) && count($in_http_vars['services'])) {
             $services = array();
             if (isset($in_http_vars['recursive']) && $in_http_vars['recursive']) {
                 foreach ($in_http_vars['services'] as $service) {
                     $nested = GetAllContainedServiceBodyIDs(intval($service));
                     if (isset($nested) && is_array($nested) && count($nested)) {
                         foreach ($nested as $sb_i) {
                             $sb_i = intval($sb_i);
                             $services[$sb_i] = $sb_i;
                         }
                     }
                 }
             } else {
                 $services = $in_http_vars['services'];
             }
             $sb =& $in_search_manager->GetServiceBodies();
             foreach ($services as $service) {
                 $sb[intval($service)] = 1;
             }
         } else {
             unset($in_http_vars['services']);
         }
         if (!( isset($in_http_vars['geo_width_km']) && $in_http_vars['geo_width_km'] )
             && !( isset($in_http_vars['geo_width']) && $in_http_vars['geo_width'] )
             && isset($in_http_vars['bmlt_search_type'])
             && ($in_http_vars['bmlt_search_type'] == 'advanced')
             && isset($in_http_vars['advanced_radius'])
             && isset($in_http_vars['advanced_mapmode'])
             && $in_http_vars['advanced_mapmode']
             && ( floatval($in_http_vars['advanced_radius'] != 0.0) )
             && isset($in_http_vars['lat_val'])
             && isset($in_http_vars['long_val'])
             && ( (floatval($in_http_vars['lat_val']) != 0.0) || (floatval($in_http_vars['long_val']) != 0.0) )
             ) {
             if ($localized_strings['dist_units'] == 'mi') {
                 $in_http_vars['geo_width'] = $in_http_vars['advanced_radius'];
                 unset($in_http_vars['geo_width_km']);
             } else {
                 $in_http_vars['geo_width_km'] = $in_http_vars['advanced_radius'];
                 unset($in_http_vars['geo_width']);
             }
         }
         // If we aren't doing any geographic searches, then we won't have a search center.
         if (!( isset($in_http_vars['geo_width']) && $in_http_vars['geo_width'] ) && !( isset($in_http_vars['geo_width_km']) && $in_http_vars['geo_width_km'] )) {
             unset($in_http_vars['lat_val']);
             unset($in_http_vars['long_val']);
         }
         // Next, set up the weekdays.
         if (isset($in_http_vars['bmlt_search_type']) && ($in_http_vars['bmlt_search_type'] == 'advanced') && isset($in_http_vars['advanced_weekdays']) && ((is_array($in_http_vars['advanced_weekdays']) && count($in_http_vars['advanced_weekdays'])) || isset($in_http_vars['advanced_weekdays']))) {
             $in_http_vars['weekdays'] = $in_http_vars['advanced_weekdays'];
         }
         if (isset($in_http_vars['weekdays']) && !is_array($in_http_vars['weekdays']) && (intval(abs($in_http_vars['weekdays'])) > 0) && (intval(abs($in_http_vars['weekdays'])) < 8)) {
             $in_http_vars['weekdays'] = array ( intval($in_http_vars['weekdays']) );
         }
         if (isset($in_http_vars['weekdays']) && is_array($in_http_vars['weekdays']) && count($in_http_vars['weekdays'])) {
             $wd =& $in_search_manager->GetWeekdays();
             foreach ($in_http_vars['weekdays'] as $weekday) {
                 $wd[abs(intval($weekday))] = intval($weekday) > 0 ? 1 : -1;
             }
         } elseif (isset($in_http_vars['weekdays'])) {
             $wd =& $in_search_manager->GetWeekdays();
             $wd[abs(intval($in_http_vars['weekdays']))] = intval(intval($in_http_vars['weekdays'])) > 0 ? 1 : -1;
         }
         // Next, set up the formats.
         if (isset($in_http_vars['bmlt_search_type']) && ($in_http_vars['bmlt_search_type'] == 'advanced') && isset($in_http_vars['advanced_formats']) && is_array($in_http_vars['advanced_formats']) && count($in_http_vars['advanced_formats'])) {
             $in_http_vars['formats'] = $in_http_vars['advanced_formats'];
         }
         if (isset($in_http_vars['formats'])) {
             if (!is_array($in_http_vars['formats'])) {
                 $in_http_vars['formats'] = array ( intval($in_http_vars['formats']) );
             }
             $fm =& $in_search_manager->GetFormats();
             foreach ($in_http_vars['formats'] as $format) {
                 $key = abs(intval($format));
                 $fm[$key] = (intval($format) > 0) ? 1 : -1;
             }
         }
         // Next, set up the languages.
         if (isset($in_http_vars['langs']) && is_array($in_http_vars['langs']) && count($in_http_vars['langs'])) {
             $lan =& $in_search_manager->GetLanguages();
             foreach ($in_http_vars['langs'] as $lng) {
                 $lan[$lng] = 1;
             }
         }
         // Next, set up the advanced published option.
         if (isset($in_http_vars['advanced_published']) && (c_comdef_server::GetCurrentUserObj() instanceof c_comdef_user)) {
             $in_search_manager->SetPublished(intval($in_http_vars['advanced_published']));
         } else {
             $in_search_manager->SetPublished(1);
         }
         // Set the start window.
         $start_time = null;
         $end_time = null;
         // Next, the minimum start time..
         if (isset($in_http_vars['StartsAfterH']) || isset($in_http_vars['StartsAfterM'])) {
             $start_hour = min(23, max(0, intval($in_http_vars['StartsAfterH'])));
             $start_minute = min(59, max(0, intval($in_http_vars['StartsAfterM'])));
             $start_time = mktime($start_hour, $start_minute);
         }
         // Next, the maximum start time..
         if (isset($in_http_vars['StartsBeforeH']) || isset($in_http_vars['StartsBeforeM'])) {
             $end_hour = min(23, max(0, intval($in_http_vars['StartsBeforeH'])));
             $end_minute = min(59, max(0, intval($in_http_vars['StartsBeforeM'])));
             $end_time = mktime($end_hour, $end_minute);
         }
         $in_search_manager->SetStartTime($start_time, $end_time);
         $end_time = null;
         // Next, the maximum end time..
         if (isset($in_http_vars['EndsBeforeH']) || isset($in_http_vars['EndsBeforeM'])) {
             $end_hour = min(23, max(0, intval($in_http_vars['EndsBeforeH'])));
             $end_minute = min(59, max(0, intval($in_http_vars['EndsBeforeM'])));
             $end_time = ($end_hour * 3600) + ($end_minute * 60);
         }
         $in_search_manager->SetEndTime($end_time);
         // Set the duration window.
         $max_duration_time = null;
         $min_duration_time = null;
         // Next, the minimum start time..
         if (isset($in_http_vars['MaxDurationH']) || isset($in_http_vars['MaxDurationM'])) {
             $max_duration_hour = min(23, max(0, intval($in_http_vars['MaxDurationH'])));
             $max_duration_minute = min(59, max(0, intval($in_http_vars['MaxDurationM'])));
             $max_duration_time = mktime($max_duration_hour, $max_duration_minute);
         }
         // Next, the maximum start time..
         if (isset($in_http_vars['MinDurationH']) || isset($in_http_vars['MinDurationM'])) {
             $min_duration_hour = min(23, max(0, intval($in_http_vars['MinDurationH'])));
             $min_duration_minute = min(59, max(0, intval($in_http_vars['MinDurationM'])));
             $min_duration_time = mktime($min_duration_hour, $min_duration_minute);
         }
         $in_search_manager->SetDuration($max_duration_time, $min_duration_time);
         // Next, we deal with a geolocated search radius.
         if ((isset($in_http_vars['geo_width']) && ($in_http_vars['geo_width'] != 0))
             ||  (isset($in_http_vars['geo_width_km']) && ($in_http_vars['geo_width_km'] != 0) ) ) {
             $long = isset($in_http_vars['long_val']) ? floatval($in_http_vars['long_val']) : 0;
             $lat = isset($in_http_vars['lat_val']) ? floatval($in_http_vars['lat_val']) : 0;
             $radius_in_miles = 0;
             $radius_in_km = 0;
             $local_strings = c_comdef_server::GetLocalStrings();
             $radius_auto = $local_strings['number_of_meetings_for_auto'];
             if (isset($in_http_vars['geo_width']) && ( $in_http_vars['geo_width'] != 0 )) {
                 if ($in_http_vars['geo_width'] < 0) {
                     $radius_auto = 0 - intval($in_http_vars['geo_width']);
                 } else {
                     $radius_in_miles = floatval($in_http_vars['geo_width']);
                 }
             } elseif (isset($in_http_vars['geo_width_km']) && ( $in_http_vars['geo_width_km'] != 0 )) {
                 if ($in_http_vars['geo_width_km'] < 0) {
                     $radius_auto = 0 - intval($in_http_vars['geo_width_km']);
                 } else {
                     $radius_in_km = floatval($in_http_vars['geo_width_km']);
                 }
             }
             if ($radius_in_miles > 0) {
                 $in_search_manager->SetSearchRadiusAndCenterInMiles($radius_in_miles, $long, $lat);
             } elseif ($radius_in_km > 0) {
                 $in_search_manager->SetSearchRadiusAndCenterInKm($radius_in_km, $long, $lat);
             } elseif ($radius_auto > 0) {
                 $in_search_manager->SetSearchRadiusAndCenterAuto($radius_auto, $long, $lat);
             }
         }
         if ($search_string && (!isset($in_http_vars['meeting_key']) || !(is_array($in_http_vars['meeting_key']) && count($in_http_vars['meeting_key'])))) {
             // And last, but not least, a string search:
             $find_all = (isset($in_http_vars['SearchStringAll']) && $in_http_vars['SearchStringAll']) ? true :false;
             $literal = (isset($in_http_vars['SearchStringExact']) && $in_http_vars['SearchStringExact']) ? true :false;
             $in_search_manager->SetSearchString($search_string, $find_all, $literal);
         }
         if (isset($in_http_vars['meeting_key']) && $in_http_vars['meeting_key']) {
             // This is true by default.
             if (!isset($in_http_vars['meeting_key_contains'])) {
                 $in_http_vars['meeting_key_contains'] = false;
             }
             // This is false by default.
             if (!isset($in_http_vars['meeting_key_match_case'])) {
                 $in_http_vars['meeting_key_match_case'] = false;
             }
             $in_search_manager->SetKeyValueSearch($in_http_vars['meeting_key'], $in_http_vars['meeting_key_value'], $in_http_vars['meeting_key_match_case'], $in_http_vars['meeting_key_contains']);
         }
     }
 }