BMLT Root Server: /Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/local_server/server_admin/c_comdef_login.php File Reference
c_comdef_login.php File Reference
This presents a login dialog to the user, vets the login, and establishes a session.
Functions
url_origin ($s, $use_forwarded_host=false)
Copied verbatim from here: http://stackoverflow.com/questions/6768793/get-the-full-url-in-php.
full_url ($s, $use_forwarded_host=false)
Copied verbatim from here: http://stackoverflow.com/questions/6768793/get-the-full-url-in-php.
GetServerInfo ()
This function parses the main server version from the XML file.
c_comdef_LoginForm (&$in_server)
Returns HTML for the login form. If the user is not logged in, then they get the form. Otherwise, the login is processed, or the user is vetted.
Variables
$t_server = c_comdef_server::MakeServer()
$lang_enum = $t_server->GetServer()->GetLocalLang()
if(isset($_COOKIE) &&isset($_COOKIE['bmlt_admin_lang_pref']) && $_COOKIE['bmlt_admin_lang_pref']) if(isset($http_vars['lang_enum']) && $http_vars['lang_enum']) if(isset($g_enable_language_selector) && $g_enable_language_selector) if(!isset($_SESSION)) if((isset($_GET['admin_action']) &&($_GET['admin_action']=='logout'))||(isset($_POST['admin_action']) &&($_POST['admin_action']=='logout'))||(isset($_POST['admin_action']) &&($_POST['admin_action']=='login'))) if(isset($_SESSION[$admin_session_name])) else
Detailed Description
This presents a login dialog to the user, vets the login, and establishes a session.
We track admin logins through the use of PHP sessions. This allows the login data to remain on the server. It also allows the login data to be carried into AJAX calls.
We're pretty anal about checking user credentials. We don't allow any changes to happen to the DB unless the user has been vetted at the time the DB access is made, but we do a lot of checking along the way.
If you include this file at the top of any file that does admin, it will check the session. If the session is not there, it will replace the output with a login form, and will continue along the way, once the user has logged in. If the session is set, it simply makes sure that the session reflects a user that has a system login (it does not check the user level), and stays out of the way.
If the user authentication fails, then it does a PHP die(), and scrags the whole thing. This prevents execution of any code beyond the bare minimum necessary to authenticate.
Cookies and JavaScript (and AJAX) are required to administer the server (but not to use it as a regular site visitor). This form checks to see if JavaScript is enabled, and if cookies are enabled.
You should link to the c_comdef_login.css file for this form.
This file is part of the Basic Meeting List Toolbox (BMLT).
Find out more at: https://bmlt.app
BMLT is free software: you can redistribute it and/or modify it under the terms of the MIT License.
BMLT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the MIT License for more details.
You should have received a copy of the MIT License along with this code. If not, see https://opensource.org/licenses/MIT.
Definition in file c_comdef_login.php.
Function Documentation
c_comdef_LoginForm()
c_comdef_LoginForm (& $in_server)
Returns HTML for the login form. If the user is not logged in, then they get the form. Otherwise, the login is processed, or the user is vetted.
Returns
a string, containing the form HTML.
Parameters
$in_server A reference to an instance of c_comdef_server
Definition at line 234 of file c_comdef_login.php.
References $_GET, $comdef_global_language, $http_vars, $ret, c_comdef_htmlspecialchars(), defined, full_url(), c_comdef_server\GetLocalStrings(), c_comdef_server\GetServer(), and GetServerInfo().
 {
     include(dirname(dirname(dirname(__FILE__))).'/server/config/get-config.php');
     $http_vars = array_merge($_GET, $_POST);
     $localized_strings = c_comdef_server::GetLocalStrings();
     $server_info = GetServerInfo();
     global  $comdef_global_language;
     if (isset($http_vars) && is_array($http_vars) && count($http_vars) && isset($http_vars['lang_enum'])) {
         $lang_name = $http_vars['lang_enum'];
         if (file_exists(dirname(__FILE__)."/lang/".$lang_name."/name.txt")) {
             $comdef_global_language = $lang_name;
         }
     } elseif (isset($_SESSION) && is_array($_SESSION) && isset($_SESSION['lang_enum'])) {
         $lang_name = $_SESSION['lang_enum'];
         if (file_exists(dirname(__FILE__)."/lang/".$lang_name."/name.txt")) {
             $comdef_global_language = $lang_name;
         }
     }
     if (isset($_SESSION) && is_array($_SESSION)) {
         $_SESSION['lang_enum'] = $comdef_global_language;
     }
     $ret = '<div class="c_comdef_admin_login_form_container_div">';
         // If there is no JavaScript, then this message is displayed, and the form will not be revealed.
         $ret .= '<noscript><h1>'.c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['noscript']).'</h1></noscript>';
         $ret .= '<h1 class="login_form_main_banner_h1">'.c_comdef_htmlspecialchars($server_info['title']).'</h1>';
         $ret .= '<h2 class="login_form_secondary_banner_h2">'.c_comdef_htmlspecialchars($server_info['banner_text']).'</h2>';
         $ret .= '<form method="post" class="c_comdef_admin_login_form" id="c_comdef_admin_login_form" action="'.c_comdef_htmlspecialchars($_SERVER['SCRIPT_NAME']);
         $ret_temp = '';
     foreach ($http_vars as $key => $value) {
         switch ($key) {
             // Skip these.
             case 'c_comdef_admin_login':
             case 'c_comdef_admin_password':
             case 'admin_action':
             case 'login':
                 break;
             default:
                 // Arrays need to be concatenated strings.
                 if (is_array($value)) {
                     $value = join(",", $value);
                 }
                 if ($ret_temp) {
                     $ret_temp .= '&amp;';
                 } else {
                     $ret_temp = '?';
                 }
                 $ret_temp .= c_comdef_htmlspecialchars($key).'='.c_comdef_htmlspecialchars($value);
                 break;
         }
     }
         $ret .= '">';   // Only the login will go through post.
             $ret .= '<input id="admin_action" type="hidden" name="admin_action" value="login" />';
             $attempted_url = full_url($_SERVER);
     if (!preg_match('|logout|', $attempted_url)) {
         $ret .= '<input id="attemptedurl" type="hidden" name="attemptedurl" value="'.c_comdef_htmlspecialchars($attempted_url).'" />';
     }
             $ret .= '<div style="display:none" id="c_comdef_admin_login_form_inner_container_div" class="c_comdef_admin_login_form_inner_container_div">';
                 $ret .= '<div class="c_comdef_admin_login_form_line_div">';
                 $ret .= '<div class="c_comdef_admin_login_form_prompt">'.c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['title']).'</div>';
                     $ret .= '<label for="c_comdef_admin_login">'.c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['login']).$localized_strings['prompt_delimiter'].'</label>';
                     $ret .= '<input id="c_comdef_admin_login" type="text" name="c_comdef_admin_login" value="" />';
                 $ret .= '</div>';
                 $ret .= '<div class="c_comdef_admin_login_form_line_div">';
                     $ret .= '<label for="c_comdef_admin_password">'.c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['password']).$localized_strings['prompt_delimiter'].'</label>';
                     $ret .= '<input type="password" id="c_comdef_admin_password" name="c_comdef_admin_password" value="" />';
                 $ret .= '</div>';
     if (isset($g_enable_language_selector) && $g_enable_language_selector) {
         $ret .= '<div id="lang_enum_select_div" class="c_comdef_admin_login_form_line_div">';
             $ret .= '<select id="lang_enum_select" name="lang_enum">'.(defined('__DEBUG_MODE__') ? "\n" : '');
             $lang_array = c_comdef_server::GetServer()->GetServerLangs();
         foreach ($lang_array as $id => $name) {
             if ($id && $name) {
                 $ret .= '<option value="'.c_comdef_htmlspecialchars($id).'"';
                 if ($comdef_global_language == $id) {
                         $ret .= ' selected="selected"';
                 }
                 $ret.= '>'.c_comdef_htmlspecialchars($name).'</option>'.(defined('__DEBUG_MODE__') ? "\n" : '');
             }
         }
             $ret .= '</select>'.(defined('__DEBUG_MODE__') ? "\n" : '');
             $ret .= '<div id="cookie_notice_div" class="bmlt_cookie_notice_div">'.c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['cookie_monster']).'</div>';
                     $ret .= '</div>';
     }
                 $ret .= '<div class="c_comdef_admin_login_form_submit_div">';
                     $ret .= '<input type="submit" value="'.c_comdef_htmlspecialchars($localized_strings['comdef_server_admin_strings']['button']).'" />';
                 $ret .= '</div>';
                 $ret .= '<div class="server_version_display_login">';
                     $ret .= htmlspecialchars($server_info['version']);
                 $ret .= '</div>';
             $ret .= '</div>';
         // This is how we check for JavaScript availability and enabled cookies (Cookies are required for sessions).
         // We reveal the form using JavaScript (It stays invisible if no JS), and we set a transitory cookie with JS to be read upon login.
         $ret .= '</form>
         <script type="text/javascript">
             document.getElementById(\'c_comdef_admin_login_form_inner_container_div\').style.display=\'block\';
             document.getElementById(\'c_comdef_admin_login\').focus();
             document.cookie=\'comdef_test=test\';
         </script>';
     $ret .= '</div>';
     return $ret;
 }
full_url()
full_url ($s, $use_forwarded_host = false)
Copied verbatim from here: http://stackoverflow.com/questions/6768793/get-the-full-url-in-php.
Returns
a string, with the full URI.
Definition at line 181 of file c_comdef_login.php.
References url_origin().
Referenced by c_comdef_LoginForm().
 {
     return url_origin($s, $use_forwarded_host) . $s['REQUEST_URI'];
 }
GetServerInfo()
GetServerInfo ()
This function parses the main server version from the XML file.
Returns
a string, containing the version info and banner.
Definition at line 190 of file c_comdef_login.php.
References $config_file_path, $ret, and c_comdef_server\GetLocalStrings().
Referenced by c_comdef_LoginForm().
 {
     $ret = null;
     if (file_exists(dirname(dirname(dirname(__FILE__))).'/client_interface/serverInfo.xml')) {
         $info_file = new DOMDocument;
         if ($info_file instanceof DOMDocument) {
             if (@$info_file->load(dirname(dirname(dirname(__FILE__))).'/client_interface/serverInfo.xml')) {
                 $has_info = $info_file->getElementsByTagName("bmltInfo");
                 if (($has_info instanceof domnodelist) && $has_info->length) {
                     $ret['version'] = $has_info->item(0)->nodeValue;
                 }
             }
         }
     }
     $config_file_path = dirname(dirname(dirname(__FILE__))).'/server/config/get-config.php';
     if (file_exists($config_file_path)) {
         include($config_file_path);
         $localized_strings = c_comdef_server::GetLocalStrings();
         if (isset($bmlt_title) && trim($bmlt_title)) {
             $ret['title'] = trim($bmlt_title);
         } else {
             $ret['title'] = $localized_strings['comdef_server_admin_strings']['login_banner'];
         }
         if (isset($banner_text) && trim($banner_text)) {
             $ret['banner_text'] = trim($banner_text);
         } else {
             $ret['banner_text'] = $localized_strings['comdef_server_admin_strings']['login_underbanner'];
         }
     }
     return $ret;
 }
url_origin()
url_origin ($s, $use_forwarded_host = false)
Copied verbatim from here: http://stackoverflow.com/questions/6768793/get-the-full-url-in-php.
Returns
a string, with the full URI.
Definition at line 165 of file c_comdef_login.php.
Referenced by full_url().
 {
     $ssl = ( !empty($s['HTTPS']) && $s['HTTPS'] == 'on' ) ? true:false;
     $sp = strtolower($s['SERVER_PROTOCOL']);
     $protocol = substr($sp, 0, strpos($sp, '/')) . ( ( $ssl ) ? 's' : '' );
     $port = $s['SERVER_PORT'];
     $port = ( (!$ssl && $port=='80') || ($ssl && $port=='443') ) ? '' : ':'.$port;
     $host = ( $use_forwarded_host && isset($s['HTTP_X_FORWARDED_HOST']) ) ? $s['HTTP_X_FORWARDED_HOST'] : (isset($s['HTTP_HOST']) ? $s['HTTP_HOST'] : null);
     $host = isset($host) ? $host : $s['SERVER_NAME'] . $port;
     return $protocol . '://' . $host;
 }
Variable Documentation
$lang_enum
$lang_enum = $t_server->GetServer()->GetLocalLang()
Definition at line 57 of file c_comdef_login.php.
$t_server
$t_server = c_comdef_server::MakeServer()
Definition at line 55 of file c_comdef_login.php.
else
if (isset($_COOKIE) &&isset($_COOKIE[ 'bmlt_admin_lang_pref']) &&$_COOKIE[ 'bmlt_admin_lang_pref']) if (isset($http_vars[ 'lang_enum']) &&$http_vars[ 'lang_enum']) if (isset($g_enable_language_selector) &&$g_enable_language_selector) if (!isset($_SESSION)) if ((isset($_GET[ 'admin_action']) &&($_GET[ 'admin_action']=='logout'))||(isset($_POST[ 'admin_action']) &&($_POST[ 'admin_action']=='logout'))||(isset($_POST[ 'admin_action']) &&($_POST[ 'admin_action']=='login'))) if (isset($_SESSION[ $admin_session_name])) else
Initial value:
{
    echo c_comdef_LoginForm($t_server)
Definition at line 155 of file c_comdef_login.php.