BMLT Root Server: /home/travis/build/bmlt-enabled/bmlt-root-server/main_server/client_interface/html/index.php File Reference
index.php File Reference
Variables
const ROOTPATH __DIR__ . '/../..'
defined ('BMLT_EXEC') or define('BMLT_EXEC'
$console_object = new c_comdef_admin_main_console($_REQUEST)
$local_strings = $console_object->my_server->GetLocalStrings()
$user_obj = $console_object->my_server->GetCurrentUserObj()
Variable Documentation
$console_object = new c_comdef_admin_main_console($_REQUEST)
Definition at line 5 of file index.php.
$local_strings = $console_object->my_server->GetLocalStrings()
Definition at line 6 of file index.php.
Referenced by bmlt_populate_format_dictionary(), c_comdef_htmlspecialchars(), c_comdef_meeting\GetAddressDataItemBuilder(), c_comdef_meeting\GetAddressDataItemKeys(), and SetUpSearch().
$user_obj = $console_object->my_server->GetCurrentUserObj()
Definition at line 7 of file index.php.
Referenced by c_comdef_server\AddNewUser(), c_comdef_admin_xml_handler\basic_user_validation(), c_comdef_admin_bar(), c_comdef_server\GetUsersByLevelObj(), c_comdef_admin_xml_handler\process_capabilities_request(), c_comdef_admin_xml_handler\process_meeting_modify(), and c_comdef_admin_xml_handler\process_user_info().
defined('BMLT_EXEC') or define('BMLT_EXEC'
Definition at line 3 of file index.php.
Referenced by c_comdef_admin_main_console\__construct(), c_comdef_LoginForm(), bmlt_semantic\get_wizard_page_html(), c_comdef_server\GetLocalStrings(), c_comdef_admin_main_console\return_main_console_html(), and bmlt_semantic\strip_script().
const ROOTPATH __DIR__ . '/../..'
Definition at line 2 of file index.php.