BMLT Root Server: c_comdef_meeting Class Reference
c_comdef_meeting Class Reference
A class to hold a single meeting object.
Public Member Functions
ReduceToArrays ()
Returns the object, in 3 storable arrays.
UpdateToDB ($is_rollback=false)
Updates the DB to the current values of this instance. (replacing current values of the DB).
DeleteFromDB_NoRecord ()
Deletes this instance from the database.
DeleteFromDB ()
Deletes this instance from the database.
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
__construct ($in_parent_obj, $inMeetingData)
Constructor.
& GetMeetingData ()
Returns a reference to the internal meeting data.
GetMeetingDataKeys ()
Returns a list of the available keys in this meeting.
GetMeetingDataValue ($in_key)
Returns a reference to the internal meeting data.
IsItemHidden ($in_key)
Returns whether or not a data item is hidden.
GetMeetingDataPrompt ($in_key)
Returns the internal meeting data string prompt.
IsValidMeeting ()
Accessor - Returns true if the meeting data is valid.
IsCopy ()
Accessor - Reflects the meeting's status as a duplicate of another.
IsCopyOf ()
Accessor - Reflects the meeting's status as a duplicate of another.
IsPublished ()
Accessor - Reflects the meeting's published status.
SetPublished ($in_published)
Accessor - Sets the meeting's published status.
GetID ()
Accessor - Returns the user ID as an integer.
SetMeetingID ($in_meeting_id_bigint)
Set this meeting's ID.
GetWorldID ()
Get this meeting's world_id.
SetWorldID ($new_world_id)
Set this meeting's world_id.
GetEmailContact ()
Get this meeting's Email Contact Address.
SetEmailContact ($in_email_contact)
Set this meeting's Email Contact Address This "vets" the email address, to ensure it has the appropriate structure. It won't set the address if it is not the appropriate structure.
GetServiceBodyID ()
Get this meeting's Service Body ID.
SetServiceBodyID ($in_service_body_id)
Set this meeting's Service Body ID.
GetServiceBodyObj ()
Get this meeting's Service Body, as a reference to an object.
GetServiceBodyName ()
Get this meeting's Service Body name, as a string.
AddDataField ($in_key_enum, $in_field_prompt_string, $in_value_mixed, $in_lang_enum=null, $in_visibility=null, $in_force=false)
Add a new data field to the object. If the field already exists, then the existing field is changed to match the new data.
DeleteDataField ($in_key_enum)
Deletes a data field. Will not delete a principal field.
GetMeetingLang ()
Get this meeting's Language Enum.
GetMeetingAddressString ($in_list=false)
Get this meeting's Address in the string format specified for this server.
AddFormat ($in_format)
Add a format to the meeting (by code).
RemoveFormat ($in_format)
Remove a format from the meeting (by code).
SerializeObject ()
Returns a storable serialization of the object, as a string.
GetContactEmail ($in_recursive=false)
Get the contact email for this meeting. If $in_recursive is false, then it simply looks at this meeting's Service Body.
UserCanEdit ($in_user_object=null)
Test to see if a user is allowed to edit an instance (change the data).
UserCanObserve ($in_user_object=null)
Test to see if a user is allowed to observe an instance (view the data).
Public Member Functions inherited from t_comdef_world_type
SetWorldID ($in_worldid_mixed)
Accessor -Sets the _world_type_worldid_mixed data member.
GetWorldID ()
Accessor -Returns a reference to the _world_type_worldid_mixed data member.
Public Member Functions inherited from t_comdef_local_type
SetLocalLang ($in_lang_enum=null)
Sets the language.
GetLocalLang ()
Returns a reference to the local language setting.
SetLocalName ($in_name_string)
Accessor -Sets the _local_type_name_string data member.
GetLocalName ()
Accessor -Returns a reference to the _local_type_name_string data member.
SetLocalDescription ($in_description_string)
Accessor -Sets the _local_type_desc_string data member.
GetLocalDescription ()
Accessor -Returns a reference to the _local_type_desc_string data member.
Public Member Functions inherited from t_local_id_class
SetParentObj ($in_parent_obj)
Sets the object's "parent" (Container) object, as a reference.
GetParentObj ()
Returns a reference to the object's container.
Public Member Functions inherited from i_comdef_db_stored
UpdateToDB ()
This causes the object to update the database to its current state.
Static Public Member Functions
static GetAddressDataItemKeys ($in_list=false)
Return an array of data item keys that are used to build an address.
static GetAddressDataItemBuilder ($in_list=false)
Return an array of data item keys, as well as their prefixes and suffixes, that are used to build an address.
static GetAllMeetingKeys ()
Returns an array of strings, containing the keys (table columns) used for all meetings (specified in ID 0 table rows).
static GetAllValuesForKey ($inKey)
Returns an array of values for the given key.
static GetFullTemplate ()
Returns an array that provides a template for all tables.
static GetMainDataTemplate ()
Returns an array that provides a template for the main table values (the standard values).
static GetDataTableTemplate ()
Returns an array that provides a template for the data table values (the optional/additional values).
static GetLongDataTableTemplate ($in_lang_enum=null)
Returns an array that provides a template for the long data table values (the optional/additional values).
static format_sorter_preference ($a, $b)
Determines which format goes first (used in sorting).
static format_sorter_simple ($a, $b)
Determines which format goes first (used in sorting). Very simple version, with no preferences.
static UnserializeObject ($in_parent, $serialized_array)
This takes a serialized object, and instantiates a new object from it.
static process_meeting_row ($row, $data_rows=null, $longdata_rows=null)
This processes the data retrieved from a single main table meeting. It will look up the corollary data in the data and longdata tables, and will consolidate it into an atomic array. It will also return c_comdef_format objects for the formats in the server language.
Private Attributes
$_my_meeting_data = null
This is the data for this meeting.
Detailed Description
A class to hold a single meeting object.
Definition at line 50 of file c_comdef_meeting.class.php.
Constructor & Destructor Documentation
__construct ($in_parent_obj, $inMeetingData)
Constructor.
This sets the local ID and the parent object.
Definition at line 1001 of file c_comdef_meeting.class.php.
       {
         $this->SetParentObj($in_parent_obj);
         $this->_my_meeting_data = $inMeetingData;
         if (isset($this->_my_meeting_data) && isset($this->_my_meeting_data['formats']) && is_array($this->_my_meeting_data['formats']) && count($this->_my_meeting_data['formats'])) {
             uksort($this->_my_meeting_data['formats'], array('c_comdef_meeting','format_sorter_preference'));
         }
         // Set these inherited characteristics.
         $this->SetLocalLang($this->_my_meeting_data['lang_enum']);
         if (isset($this->_my_meeting_data['meeting_name']) && $this->_my_meeting_data['meeting_name'] && $this->_my_meeting_data['meeting_name']['value']) {
             $this->SetLocalName($this->_my_meeting_data['meeting_name']['value']);
         }
     }
Member Function Documentation
AddDataField ($in_key_enum, $in_field_prompt_string, $in_value_mixed, $in_lang_enum = null, $in_visibility = null, $in_force = false)
Add a new data field to the object. If the field already exists, then the existing field is changed to match the new data.
Returns
a bool that is true, if the operation was successful.
Parameters
$in_key_enum The data field key, which is a string enum for the field.
$in_field_prompt_string A string, containing the field prompt.
$in_value_mixed The value of the data field, which can be passed by reference.
$in_lang_enum The language enum. Optional. If not specified, the meeting value will be used.
$in_force If this is set to true, then the value is written, regardless of whether or not it is already set. Default is false.
Definition at line 1336 of file c_comdef_meeting.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         // We will not operate on the principal elements.
         $_meeting_data_value = array_key_exists($in_key_enum, $this->_my_meeting_data) ? $this->_my_meeting_data[$in_key_enum] : null;
         if (($in_force && !isset($_meeting_data_value)) || ($in_force && is_array($_meeting_data_value)) || !is_array($_meeting_data_value)) {
             if (!$in_lang_enum) {
                 $in_lang_enum = $this->_my_meeting_data['lang_enum'];
             }
             $this->_my_meeting_data[$in_key_enum]['key'] = strval($in_key_enum);
             if ($in_field_prompt_string !== null) {
                 $this->_my_meeting_data[$in_key_enum]['prompt'] = $in_field_prompt_string;
             }
             // Hack to make sure there's no such thing as "pure" midnight.
             if ($in_key_enum == 'start_time') {
                 if (($in_value_mixed == '00:00:00') || ($in_value_mixed == '00:00') || ($in_value_mixed == '24:00:00') || ($in_value_mixed == '24:00')) {
                     $in_value_mixed == '23:59:00';
                 }
             }
             $this->_my_meeting_data[$in_key_enum]['value'] = null;  // Just in case of memory leaks.
             $this->_my_meeting_data[$in_key_enum]['value'] = $in_value_mixed;
             $this->_my_meeting_data[$in_key_enum]['lang_enum'] = $in_lang_enum;
             $this->_my_meeting_data[$in_key_enum]['visibility'] = ( $in_visibility === null ) ? ((isset($this->_my_meeting_data[$in_key_enum]) && isset($this->_my_meeting_data[$in_key_enum]['visibility'])) ? intval($this->_my_meeting_data[$in_key_enum]['visibility']) : 0) : intval($in_visibility);
             return true;
         }
         return false;
     }
AddFormat ($in_format)
Add a format to the meeting (by code).
Given an integer, representing the format code, it will add it to the meeting, and will reference the object for the meeting's language for that format.
Returns
true if the format was not already there, and false if the format was there.
Parameters
$in_format An integer, containing the format to be added.
Definition at line 1459 of file c_comdef_meeting.class.php.
References c_comdef_server\GetServer().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $myData = $this->GetMeetingData();
         $my_formats = c_comdef_server::GetServer()->GetFormatsObj();
         // If we already have the format, we don't add it, but there's no error.
         if (!isset($myData['formats'][$in_format])) {
             $myData['formats'][$in_format] = $my_formats->GetFormatBySharedIDCodeAndLanguage($in_format, $this->GetMeetingLang());
             uksort($myData['formats'], array('c_comdef_meeting','format_sorter_preference'));
             return true;
         }
         return false;
     }
DeleteDataField ($in_key_enum)
Deletes a data field. Will not delete a principal field.
Returns
a bool that is true, if the operation was successful.
Parameters
$in_key_enum The data field key, which is a string enum for the field.
Definition at line 1386 of file c_comdef_meeting.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         // We will not operate on the principal elements.
         if (is_array($this->_my_meeting_data[$in_key_enum])) {
             // We do this, just so there's no possibility of memory leaks and hanging references.
             if (isset($this->_my_meeting_data[$in_key_enum]['prompt'])) {
                 $this->_my_meeting_data[$in_key_enum]['prompt'] = null;
                 unset($this->_my_meeting_data[$in_key_enum]['prompt']);
             }
             if (isset($this->_my_meeting_data[$in_key_enum]['value'])) {
                 $this->_my_meeting_data[$in_key_enum]['value'] = null;
                 unset($this->_my_meeting_data[$in_key_enum]['value']);
             }
             $this->_my_meeting_data[$in_key_enum] = null;
             unset($this->_my_meeting_data[$in_key_enum]);
             return true;
         }
         return false;
     }
DeleteFromDB ()
Deletes this instance from the database.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 461 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\AddNewChange(), and c_comdef_server\GetCurrentUserObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             // We take a snapshot of the meeting as it currently sits in the database as a "before" image.
             $service_body_id = $this->GetServiceBodyID();
             $id = $this->GetID();
             $lang = $this->GetLocalLang();
             $before = $this->SerializeObject();
             try {
                 $ret = $this->DeleteFromDB_NoRecord();
                 c_comdef_server::AddNewChange($user->GetID(), 'comdef_change_type_delete', $service_body_id, $before, '', 'c_comdef_meeting', $id, null, $lang, null);
                 $ret = true;
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_meeting::DeleteFromDB()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
DeleteFromDB_NoRecord ()
Deletes this instance from the database.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Definition at line 423 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\GetCurrentUserObj(), and c_comdef_dbsingleton\preparedExec().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             try {
                 $sql = "DELETE FROM `".c_comdef_server::GetMeetingTableName_obj()."_main` WHERE `id_bigint`=?";
                 c_comdef_dbsingleton::preparedExec($sql, array ( $this->_my_meeting_data['id_bigint'] ));
                 $sql = "DELETE FROM `".c_comdef_server::GetMeetingTableName_obj()."_data` WHERE `meetingid_bigint`=?";
                 c_comdef_dbsingleton::preparedExec($sql, array ( $this->_my_meeting_data['id_bigint'] ));
                 $sql = "DELETE FROM `".c_comdef_server::GetMeetingTableName_obj()."_longdata` WHERE `meetingid_bigint`=?";
                 c_comdef_dbsingleton::preparedExec($sql, array ( $this->_my_meeting_data['id_bigint'] ));
                 $ret = true;
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_meeting::DeleteFromDB()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
static format_sorter_preference ($a, $b) static
Determines which format goes first (used in sorting).
Format 4 (Closed) and format 17 (Open) are always in front. Otherwise, it's a simple numeric sort.
Returns
-1 if $a is 4, 17, or less than $b, 0 if they are equal, and 1 if $b is 4, 17 or less than $a
Parameters
$a The first value to check
$b The second value to check
Definition at line 1508 of file c_comdef_meeting.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $a = intval($a);
         $b = intval($b);
         if (($a == 4) || ($a == 17)) {
             return -1;
         } elseif (($b == 4) || ($b == 17)) {
             return 1;
         } elseif ($a == $b) {
             return 0;
         } else {
             return ( $a < $b ) ? -1 : 1;
         }
     }
static format_sorter_simple ($a, $b) static
Determines which format goes first (used in sorting). Very simple version, with no preferences.
Returns
-1 if $a is less than $b, 0 if they are equal, and 1 if $b is less than $a
Parameters
$a The first value to check
$b The second value to check
Definition at line 1534 of file c_comdef_meeting.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $a = intval($a);
         $b = intval($b);
         if ($a == $b) {
             return 0;
         } else {
             return ( $a < $b ) ? -1 : 1;
         }
     }
static GetAddressDataItemBuilder ($in_list = false) static
Return an array of data item keys, as well as their prefixes and suffixes, that are used to build an address.
Returns
an array of strings, containing the data item field keys.
Exceptions
an exception if there is a problem.
Parameters
$in_list If this is true, then the return is for the list view. If false, for the "More Details" screen.
Definition at line 579 of file c_comdef_meeting.class.php.
References $local_strings, $ret, GetAllMeetingKeys(), and c_comdef_server\GetLocalStrings().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         $local_strings = c_comdef_server::GetLocalStrings();
         // At this point, we have the format strings. We mow parse them to get the keys used for address display.
         // The data item keys are surrounded by sets of double percent signs (%%_key_%%).
         $string_to_parse = $local_strings['comdef_global_more_details_address'];
         if ($in_list) {
             $string_to_parse = $local_strings['comdef_global_list_address'];
         }
         $matches = array();
         $parse_targets = explode('@@', $string_to_parse);
         if (is_array($parse_targets) && count($parse_targets)) {
             $ret = array ();
             $keys = c_comdef_meeting::GetAllMeetingKeys();
             if (is_array($keys) && count($keys)) {
                 foreach ($parse_targets as $target) {
                     $r['prefix'] = preg_replace('#(.*?)\%(.*)#', "$1", $target);
                     $r['key'] = preg_replace('#(.*?)\%\%(.*?)\%\%(.*)#', "$2", $target);
                     $r['suffix'] = preg_replace('#(.*)\%(.*?)$#', "$2", $target);
                     if (in_array($r['key'], $keys)) {
                         array_push($ret, $r);
                     }
                 }
             }
         }
         return $ret;
     }
static GetAddressDataItemKeys ($in_list = false) static
Return an array of data item keys that are used to build an address.
Returns
an array of strings, containing the data item field keys.
Exceptions
an exception if there is a problem.
Parameters
$in_list If this is true, then the return is for the list view. If false, for the "More Details" screen.
Definition at line 537 of file c_comdef_meeting.class.php.
References $local_strings, $ret, GetAllMeetingKeys(), and c_comdef_server\GetLocalStrings().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         $local_strings = c_comdef_server::GetLocalStrings();
         // At this point, we have the format strings. We mow parse them to get the keys used for address display.
         // The data item keys are surrounded by sets of double percent signs (%%_key_%%).
         $string_to_parse = $local_strings['comdef_global_more_details_address'];
         if ($in_list) {
             $string_to_parse = $local_strings['comdef_global_list_address'];
         }
         $matches = array();
         if (preg_match_all('#\%\%(.*?)\%\%#', $string_to_parse, $matches)) {
             $keys = c_comdef_meeting::GetAllMeetingKeys();
             if (is_array($keys) && count($keys)) {
                 $ret = array();
                 while ($elem = array_shift($matches[1])) {
                     if (in_array($elem, $keys)) {
                         array_push($ret, $elem);
                     }
                 }
             }
         }
         return $ret;
     }
static GetAllMeetingKeys () static
Returns an array of strings, containing the keys (table columns) used for all meetings (specified in ID 0 table rows).
Returns
an array of strings, with the key being the same as the value. NOTE: This contains ALL possible keys.
Exceptions
a PDOException if there is a problem.
Definition at line 629 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $ret, and c_comdef_dbsingleton\preparedQuery().
Referenced by DisplaySearchResultsCSV(), GetAddressDataItemBuilder(), GetAddressDataItemKeys(), c_comdef_meeting_search_manager\GetAllAvailableSortKeys(), and c_comdef_admin_xml_handler\process_meeting_modify().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         try {
             // The main table always has these keys.
             $ret['id_bigint'] = 'id_bigint';
             $ret['worldid_mixed'] = 'worldid_mixed';
             $ret['shared_group_id_bigint'] = 'shared_group_id_bigint';
             $ret['service_body_bigint'] = 'service_body_bigint';
             $ret['weekday_tinyint'] = 'weekday_tinyint';
             $ret['start_time'] = 'start_time';
             $ret['duration_time'] = 'duration_time';
             $ret['time_zone'] = 'time_zone';
             $ret['formats'] = 'formats';
             $ret['lang_enum'] = 'lang_enum';
             $ret['longitude'] = 'longitude';
             $ret['latitude'] = 'latitude';
             $ret['distance_in_km'] = 'distance_in_km';
             $ret['distance_in_miles'] = 'distance_in_miles';
             $ret['email_contact'] = 'email_contact';
             // For the data and longdata tables, the keys can be dynamic, and we create a "0" ID version of them to establish the possibilities.
             $sql = "SELECT * FROM `".c_comdef_server::GetMeetingTableName_obj()."_data` WHERE meetingid_bigint=0";
             $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( ));
             if (is_array($rows) && count($rows)) {
                 foreach ($rows as $row) {
                     $key = $row['key'];
                     $ret[$key] = $key;
                 }
             }
             $sql = "SELECT * FROM `".c_comdef_server::GetMeetingTableName_obj()."_longdata` WHERE meetingid_bigint=0";
             $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( ));
             if (is_array($rows) && count($rows)) {
                 foreach ($rows as $row) {
                     $key = $row['key'];
                     $ret[$key] = $key;
                 }
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_meeting::GetAllMeetingKeys()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
         $ret['published'] = 'published';    // The last field is always the published flag.
         return $ret;
     }
static GetAllValuesForKey ($inKey) static
Returns an array of values for the given key.
Returns
an array of strings, with the key being the same as the value. NOTE: This contains ALL possible keys.
Exceptions
a PDOException if there is a problem.
Parameters
$inKey The key to get all the values for.
Definition at line 697 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\GetMeetingTableName_obj(), and c_comdef_dbsingleton\preparedQuery().
Referenced by parse_redirect().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         try {
             $rows = null;
             switch (strtolower(trim($inKey))) {
                 case 'shared_group_id_bigint':
                 case 'email_contact':
                 case 'distance_in_km':
                 case 'distance_in_miles':
                 case 'published':
                     break;
                 case 'weekday_tinyint':
                 case 'id_bigint':
                 case 'worldid_mixed':
                 case 'service_body_bigint':
                 case 'start_time':
                 case 'duration_time':
                 case 'time_zone':
                 case 'formats':
                 case 'lang_enum':
                 case 'longitude':
                 case 'latitude':
                     $inKey = strtolower(trim($inKey));
                     $sql = "SELECT `$inKey`,`id_bigint`,`published` FROM `".c_comdef_server::GetMeetingTableName_obj()."_main` WHERE (`id_bigint` > 0) AND (`published`=1) ORDER BY ?";
                     $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $inKey ));
                     break;
                 default:
                     $temp = self::GetDataTableTemplate();
                     if (isset($temp[$inKey]) && ($temp[$inKey]['visibility'] != 1)) {
                         $sql = "SELECT ".c_comdef_server::GetMeetingTableName_obj()."_main.published,".c_comdef_server::GetMeetingTableName_obj()."_data.meetingid_bigint,".c_comdef_server::GetMeetingTableName_obj()."_data.data_string,".c_comdef_server::GetMeetingTableName_obj()."_data.data_bigint,".c_comdef_server::GetMeetingTableName_obj()."_data.data_double FROM `".c_comdef_server::GetMeetingTableName_obj()."_data` INNER JOIN ".c_comdef_server::GetMeetingTableName_obj()."_main ON ".c_comdef_server::GetMeetingTableName_obj()."_main.id_bigint=".c_comdef_server::GetMeetingTableName_obj()."_data.meetingid_bigint WHERE (`key`=?) AND (`meetingid_bigint`>0) AND (".c_comdef_server::GetMeetingTableName_obj()."_main.published=1) ORDER BY ".c_comdef_server::GetMeetingTableName_obj()."_data.data_double, ".c_comdef_server::GetMeetingTableName_obj()."_data.data_bigint,".c_comdef_server::GetMeetingTableName_obj()."_data.data_string";
                     } else {
                         $temp = self::GetLongDataTableTemplate();
                         if (isset($temp[$inKey]) && ($temp[$inKey]['visibility'] != 1)) {
                             $sql = "SELECT ".c_comdef_server::GetMeetingTableName_obj()."_main.published,".c_comdef_server::GetMeetingTableName_obj()."_longdata.data_longtext,".c_comdef_server::GetMeetingTableName_obj()."_longdata.data_blob FROM `".c_comdef_server::GetMeetingTableName_obj()."_longdata` INNER JOIN ".c_comdef_server::GetMeetingTableName_obj()."_main ON ".c_comdef_server::GetMeetingTableName_obj()."_main.id_bigint=".c_comdef_server::GetMeetingTableName_obj()."_longdata.meetingid_bigint WHERE (`key`=?) AND (`meetingid_bigint`>0) AND (".c_comdef_server::GetMeetingTableName_obj()."_main.published=1)";
                         }
                     }
                     $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $inKey ));
                     break;
             }
             if (is_array($rows) && count($rows)) {
                 foreach ($rows as $row) {
                     if (isset($row['published']) && $row['published']) {
                         $id = (isset($row['id_bigint']) && intval($row['id_bigint'])) ? intval($row['id_bigint']) : null;
                         if (!$id) {
                             $id = (isset($row['meetingid_bigint']) && intval($row['meetingid_bigint'])) ? intval($row['meetingid_bigint']) : null;
                         }
                         $value = null;
                         if (isset($row[$inKey])) {
                             $value = $row[$inKey];
                             if ($inKey == 'weekday_tinyint') {
                                 $value = intval($value) + 1;
                             }
                             if ($inKey == 'formats') {
                                 $value = explode(',', $value);
                                 asort($value);
                                 $value = implode("\t", $value);
                             }
                         }
                         if (!$value && isset($row['data_string']) && trim($row['data_string'])) {
                             $value = str_replace(',', '&APOS&', trim($row['data_string']));
                         }
                         if (!$value && isset($row['data_bigint'])) {
                             $value = intval($row['data_bigint']);
                         }
                         if (!$value && isset($row['data_double'])) {
                             $value = floatval($row['data_double']);
                         }
                         if (!$value && isset($row['data_longtext'])) {
                             $value = floatval($row['data_longtext']);
                         }
                         if (!$value && isset($row['data_blob'])) {
                             $value = floatval($row['data_blob']);
                         }
                         if (!$ret) {
                             $ret = array();
                             $ret['NULL'] = '';
                         }
                         if ($value) {
                             $ids = null;
                             if (isset($ret[$value])) {
                                 $ids = explode('\t', $ret[$value]);
                                 $ids[] = $id;
                             } else {
                                 $ids = array ( $id );
                             }
                             $ret[$value] = implode('\t', $ids);
                         } else {
                             $ids = null;
                             if (isset($ret['NULL'])) {
                                 $ids = explode('\t', $ret['NULL']);
                                 $ids[] = $id;
                             } else {
                                 $ids = array ( $id );
                             }
                             $ret['NULL'] = trim(implode('\t', $ids));
                         }
                     }
                 }
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_meeting::GetAllMeetingValues()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
         if (!$ret['NULL']) {
             unset($ret['NULL']);
         }
         return $ret;
     }
GetContactEmail ($in_recursive = false)
Get the contact email for this meeting. If $in_recursive is false, then it simply looks at this meeting's Service Body.
Returns
a string, which is the contact email for this meeting
Parameters
$in_recursive If this is true, then the function will return a recursive result. Default is false.
Definition at line 1707 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = trim($this->GetEmailContact());
         if (!$ret) {
             $service_body = $this->GetServiceBodyObj();
             if ($service_body instanceof c_comdef_service_body) {
                 $ret = $service_body->GetContactEmail($in_recursive);
             }
         }
         return $ret;
     }
static GetDataTableTemplate () static
Returns an array that provides a template for the data table values (the optional/additional values).
Returns
an array with all of the _data values.
Exceptions
a PDOException if there is a problem.
Definition at line 905 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $ret, and c_comdef_dbsingleton\preparedQuery().
Referenced by c_comdef_admin_main_console\__construct(), c_comdef_admin_xml_handler\process_get_field_templates(), c_comdef_admin_xml_handler\process_meeting_modify(), c_comdef_admin_ajax_handler\SetMeetingDataValues(), and SetUpSearch().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = array();
         try {
             $sql = "SELECT * FROM `".c_comdef_server::GetMeetingTableName_obj()."_data` WHERE meetingid_bigint=0";
             $rows = c_comdef_dbsingleton::preparedQuery($sql, array());
             foreach ($rows as $row) {
                 $ret[$row['key']]['key'] = $row['key'];
                 $ret[$row['key']]['field_prompt'] = $row['field_prompt'];
                 $ret[$row['key']]['visibility'] = $row['visibility'];
                 $ret[$row['key']]['lang_enum'] = $row['lang_enum'];
                 if ($row['data_string']) {
                     $ret[$row['key']]['value'] = $row['data_string'];
                 } elseif ($row['data_bigint']) {
                     $ret[$row['key']]['value'] = $row['data_bigint'];
                 } elseif ($row['data_double']) {
                     $ret[$row['key']]['value'] = $row['data_double'];
                 } else {
                     $ret[$row['key']]['value'] = null;
                 }
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_meeting::GetDataTableTemplate()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
         return $ret;
     }
GetEmailContact ()
Get this meeting's Email Contact Address.
Returns
a string, which is the contact email.
Definition at line 1241 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_my_meeting_data['email_contact'];
     }
static GetFullTemplate () static
Returns an array that provides a template for all tables.
Returns
an array with all of the values.
Definition at line 840 of file c_comdef_meeting.class.php.
References $ret.
Referenced by GetServerInfo(), and parse_redirect().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $main = self::GetMainDataTemplate();
         $data = self::GetDataTableTemplate();
         $longData = self::GetLongDataTableTemplate();
         $ret = array_merge($main, $data);
         if (isset($longData) && is_array($longData) && count($longData)) {
             $ret = array_merge($ret, $longData);
         }
         return $ret;
     }
GetID ()
Accessor - Returns the user ID as an integer.
Returns
an integer, containing the user ID.
Definition at line 1189 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = 0;
         if (isset($this->_my_meeting_data['id_bigint'])) {
             $ret = $this->_my_meeting_data['id_bigint'];
         }
         return $ret;
     }
static GetLongDataTableTemplate ($in_lang_enum = null) static
Returns an array that provides a template for the long data table values (the optional/additional values).
Returns
an array with all of the _longdata values.
Exceptions
a PDOException if there is a problem.
Parameters
$in_lang_enum The language to use. If not given the server default will be used.
Definition at line 951 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\GetServer(), and c_comdef_dbsingleton\preparedQuery().
Referenced by c_comdef_admin_main_console\__construct(), c_comdef_admin_xml_handler\process_get_field_templates(), c_comdef_admin_xml_handler\process_meeting_modify(), and c_comdef_admin_ajax_handler\SetMeetingDataValues().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = array();
         if (!$in_lang_enum) {
             $in_lang_enum = c_comdef_server::GetServer()->GetLocalLang();
         }
         // Should never happen.
         if (!$in_lang_enum) {
             $in_lang_enum = "en";
         }
         try {
             $sql = "SELECT * FROM `".c_comdef_server::GetMeetingTableName_obj()."_longdata` WHERE meetingid_bigint=0 AND lang_enum=?";
             $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $in_lang_enum ));
             foreach ($rows as $row) {
                 $ret[$row['key']]['key'] = $row['key'];
                 $ret[$row['key']]['field_prompt'] = $row['field_prompt'];
                 $ret[$row['key']]['lang_enum'] = $row['lang_enum'];
                 $ret[$row['key']]['visibility'] = $row['visibility'];
                 if ($row['data_longtext']) {
                     $ret[$row['key']]['value'] = $row['data_longtext'];
                 } elseif ($row['data_blob']) {
                     $ret[$row['key']]['value'] = $row['data_blob'];
                 } else {
                     $ret[$row['key']]['value'] = null;
                 }
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_meeting::GetDataTableTemplate()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
         return $ret;
     }
static GetMainDataTemplate () static
Returns an array that provides a template for the main table values (the standard values).
Returns
an array with all of the _main values.
Definition at line 862 of file c_comdef_meeting.class.php.
References $comdef_global_language, $ret, and c_comdef_server\GetLocalStrings().
Referenced by c_comdef_admin_xml_handler\process_get_field_templates().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         global $comdef_global_language;
         $localized_strings = c_comdef_server::GetLocalStrings();
         $ret = array();
         $ret['id_bigint']['key'] = 'id_bigint';
         $ret['worldid_mixed']['key'] = 'worldid_mixed';
         $ret['shared_group_id_bigint']['key'] = 'shared_group_id_bigint';
         $ret['service_body_bigint']['key'] = 'service_body_bigint';
         $ret['weekday_tinyint']['key'] = 'weekday_tinyint';
         $ret['start_time']['key'] = 'start_time';
         $ret['duration_time']['key'] = 'duration_time';
         $ret['time_zone']['key'] = 'time_zone';
         $ret['formats']['key'] = 'formats';
         $ret['lang_enum']['key'] = 'lang_enum';
         $ret['longitude']['key'] = 'longitude';
         $ret['latitude']['key'] = 'latitude';
         $ret['published']['key'] = 'published';
         $ret['email_contact']['key'] = 'email_contact';
         // Everything gets a lang_enum (determined by global server setting).
         // Almost all are visibility 0 (everyone can see).
         foreach ($ret as &$elem) {
             $elem['visibility'] = ($elem['key'] == 'email_contact') ? 1 : 0;    // Email contact is hidden.
             $elem['lang_enum'] = $comdef_global_language;
             $elem['field_prompt'] = $localized_strings['comdef_server_admin_strings']['main_prompts'][$elem['key']];
         }
         return $ret;
     }
GetMeetingAddressString ($in_list = false)
Get this meeting's Address in the string format specified for this server.
Returns
a string, containing the meeting's address in easily-readable form.
Parameters
$in_list If this is true, then the version returned will be for the list display. Default is false (The More Details display).
Definition at line 1428 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         $builder = self::GetAddressDataItemBuilder($in_list);    // Get the parsed address format builder.
         if (is_array($builder) && count($builder)) {
             foreach ($builder as $element_ar) {
                 if (trim($this->GetMeetingDataValue($element_ar['key']))) {
                     $ret .= $element_ar['prefix'];
                     $ret .= trim($this->GetMeetingDataValue($element_ar['key']));
                     $ret .= $element_ar['suffix'];
                 }
             }
         }
         return $ret;
     }
& GetMeetingData ()
Returns a reference to the internal meeting data.
Returns
a reference to the internal array, containing the meeting data.
Definition at line 1024 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_my_meeting_data;
     }
GetMeetingDataKeys ()
Returns a list of the available keys in this meeting.
Returns
an array of strings, with each one being a key.
Definition at line 1036 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = array();
         foreach ($this->_my_meeting_data as $key => &$value) {
             array_push($ret, $key);
         }
         return $ret;
     }
GetMeetingDataPrompt ($in_key)
Returns the internal meeting data string prompt.
Returns
a string. Null if the element is not there.
Parameters
$in_key A string. This is the key in the data array.
Definition at line 1102 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         if (isset($this->_my_meeting_data[$in_key])) {
             $ret = $this->_my_meeting_data[$in_key];
             if (is_array($ret) && isset($ret['prompt'])) {
                 $ret = $ret['prompt'] ;
             } else {
                 $ret = $in_key;
             }
         }
         return $ret;
     }
GetMeetingDataValue ($in_key)
Returns a reference to the internal meeting data.
Returns
a reference to the value of the requested element. Null if the element is not there.
Parameters
$in_key A string. This is the key in the data array.
Definition at line 1054 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = null;
         if (isset($this->_my_meeting_data[$in_key])) {
             if (is_array($this->_my_meeting_data[$in_key]) && isset($this->_my_meeting_data[$in_key]['value'])) {
                 if (isset($this->_my_meeting_data[$in_key]['visibility']) && ($this->_my_meeting_data[$in_key]['visibility'] == _VISIBILITY_NONE_) && !$this->UserCanObserve()) {
                     $ret = null;
                 } else {
                     $ret = $this->_my_meeting_data[$in_key]['value'];
                 }
             } else {
                 $ret = $this->_my_meeting_data[$in_key];
             }
         }
         return $ret;
     }
GetMeetingLang ()
Get this meeting's Language Enum.
Returns
a string, containing the meeting's language.
Definition at line 1416 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_my_meeting_data['lang_enum'];
     }
GetServiceBodyID ()
Get this meeting's Service Body ID.
Returns
an integer, which is the ID of the Service Body for this meeting.
Definition at line 1275 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_my_meeting_data['service_body_bigint'];
     }
GetServiceBodyName ()
Get this meeting's Service Body name, as a string.
Returns
a reference to an instance of c_comdef_service_body, which is the Service Body object for this meeting.
Definition at line 1316 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = $this->_my_meeting_data['service_body_bigint'];
         $sb = $this->GetServiceBodyObj();
         if ($sb instanceof c_comdef_service_body) {
             $ret = $sb->GetLocalName();
         }
         return $ret;
     }
GetServiceBodyObj ()
Get this meeting's Service Body, as a reference to an object.
Returns
a reference to an instance of c_comdef_service_body, which is the Service Body object for this meeting.
Definition at line 1304 of file c_comdef_meeting.class.php.
References c_comdef_server\GetServiceBodyByIDObj().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return c_comdef_server::GetServiceBodyByIDObj($this->GetServiceBodyID());
     }
GetWorldID ()
Get this meeting's world_id.
Definition at line 1216 of file c_comdef_meeting.class.php.
     {
         if (isset($this->_my_meeting_data['worldid_mixed'])) {
             return $this->_my_meeting_data['worldid_mixed'];
         } else {
             return '';
         }
     }
IsCopy ()
Accessor - Reflects the meeting's status as a duplicate of another.
Returns
a boolean, true if the meeting is a duplicate.
Definition at line 1140 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return (isset($this->_my_meeting_data['copy']) );
     }
IsCopyOf ()
Accessor - Reflects the meeting's status as a duplicate of another.
Returns
an integer, if the meeting is a duplicate, it is the ID of the meeting it copies.
Definition at line 1152 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return (intval($this->_my_meeting_data['copy']) );
     }
IsItemHidden ($in_key)
Returns whether or not a data item is hidden.
Returns
a boolean. True, if the data item is hidden from normal users.
Parameters
$in_key A string. This is the key in the data array.
Definition at line 1081 of file c_comdef_meeting.class.php.
References $ret, and _VISIBILITY_NONE_.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = ($in_key == 'email_contact');
         if (!$ret && isset($this->_my_meeting_data[$in_key])) {
             if (is_array($this->_my_meeting_data[$in_key]) && isset($this->_my_meeting_data[$in_key]['value'])) {
                 $ret = (isset($this->_my_meeting_data[$in_key]['visibility']) && ($this->_my_meeting_data[$in_key]['visibility'] == _VISIBILITY_NONE_));
             }
         }
         return $ret;
     }
IsPublished ()
Accessor - Reflects the meeting's published status.
Returns
a boolean, true if the meeting is published.
Definition at line 1164 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_my_meeting_data['published'];
     }
IsValidMeeting ()
Accessor - Returns true if the meeting data is valid.
Returns
a boolean, true if the meeting is valid (has data).
Definition at line 1126 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         list ( $main_table_values, $data_table_values, $longdata_table_values ) = $this->ReduceToArrays();
         return ( isset($main_table_values['longitude']) && isset($main_table_values['latitude']) && is_array($data_table_values) && (count($data_table_values) > 0));
     }
static process_meeting_row ($row, $data_rows = null, $longdata_rows = null) static
This processes the data retrieved from a single main table meeting. It will look up the corollary data in the data and longdata tables, and will consolidate it into an atomic array. It will also return c_comdef_format objects for the formats in the server language.
Returns
an array of data that can be used as the data for the meeting object.
Parameters
$row One row of meeting data, fresh from the database.
$data_rows These are used to unserialize the object, which bypasses the database. Optional. If non-null, this should be an array of data table values
$longdata_rows Optional. If non-null, this should be an array of longdata table values
Definition at line 1604 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $meeting_id, c_comdef_server\GetServer(), and c_comdef_dbsingleton\preparedQuery().
Referenced by c_comdef_server\GetMeetingsFromSQL(), and c_comdef_server\GetOneMeeting().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         try {
             // The weekday is kept on the server as zero-based, but we keep it 1-based in our implementation.
             $row['weekday_tinyint'] = $row['weekday_tinyint'] + 1;
             $meeting_id = $row['id_bigint'];
             $meeting_row = $row;
             // However, we do one thing differently: We split the formats array, so it is in multiple elements. That'll make it easier to handle later.
             // We also actually assign a reference to the localized format object itself to the array.
             $meeting_row['formats'] = explode(",", $meeting_row['formats']);
             // What we do here is assign the format object to the version for the language of the meeting (not necessarily the server).
             // The formats array will use the format codes as keys, so we can use these to access other localizations.
             $new_formats = array();
             $my_formats = c_comdef_server::GetServer()->GetFormatsObj();
             foreach ($meeting_row['formats'] as $format_id) {
                 $new_formats[$format_id] = $my_formats->GetFormatBySharedIDCodeAndLanguage($format_id, $row['lang_enum']);
             }
             $meeting_row['formats'] = $new_formats;
             // If the row was not already supplied, we fetch it ourselves.
             if (null == $data_rows) {
                 // We do two lookups, because a fancy-ass JOIN takes FOR-EVER. The performance is AWFUL.
                 // 99% of the time, the longdata table won't have anything in it, so we shouldn't slow
                 // down the regular data table to include a table that barely ever has anything.
                 // This has the added advantage of allowing implementations to override the main data, and
                 // to allow data in the longdata table to override the regular table.
                 $sql = "SELECT * FROM `".c_comdef_server::GetMeetingTableName_Obj()."_data` WHERE ".c_comdef_server::GetMeetingTableName_Obj()."_data.meetingid_bigint=?";
                 $data_rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $meeting_id ));
             }
             if (is_array($data_rows) && count($data_rows)) {
                 foreach ($data_rows as $data_row) {
                     $key = $data_row['key'];
                     if (trim($key)) {
                         if (isset($data_row['data_string']) && (null != $data_row['data_string'])) {
                             $meeting_row[$key]['value'] = stripslashes(strval($data_row['data_string']));
                         } elseif (isset($data_row['data_bigint']) && ( null != $data_row['data_bigint'] )) {
                             $meeting_row[$key]['value'] = intval($data_row['data_bigint']);
                         } elseif (isset($data_row['data_double']) && ( null != $data_row['data_double'] )) {
                             $meeting_row[$key]['value'] = floatval($data_row['data_double']);
                         }
                         // Only set these if we have data.
                         if (isset($meeting_row[$key]['value'])) {
                             $meeting_row[$key]['longdata'] = false;
                             $meeting_row[$key]['prompt'] = $data_row['field_prompt'];
                             $meeting_row[$key]['lang'] = $data_row['lang_enum'];
                             $meeting_row[$key]['visibility'] = isset($data_row['visibility']) ? $data_row['visibility'] : 0;
                         }
                     }
                 }
             }
             // If the row was not already supplied, we fetch it ourselves.
             if (null == $longdata_rows) {
                 $sql = "SELECT * FROM `".c_comdef_server::GetMeetingTableName_Obj()."_longdata` WHERE ".c_comdef_server::GetMeetingTableName_Obj()."_longdata.meetingid_bigint=?";
                 $longdata_rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $meeting_id ));
             }
             if (is_array($longdata_rows) && count($longdata_rows)) {
                 foreach ($longdata_rows as $longdata_row) {
                     $key = $longdata_row['key'];
                     if (trim($key) && ((null != $longdata_row['data_blob']) || (null != $longdata_row['data_longtext']))) {
                         $meeting_row[$key]['longdata'] = true;
                         $meeting_row[$key]['value'] = (null != $longdata_row['data_blob']) ? $longdata_row['data_blob'] : stripslashes($longdata_row['data_longtext']);
                         $meeting_row[$key]['prompt'] = $longdata_row['field_prompt'];
                         $meeting_row[$key]['lang'] = $longdata_row['lang_enum'];
                         $meeting_row[$key]['visibility'] = $longdata_row['visibility'];
                     }
                 }
             }
             // At this point, we have all the data for this one meeting, culled from its three tables and aggregated into an array.
             return $meeting_row;
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_meeting::process_meeting_row()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
     }
ReduceToArrays ()
Returns the object, in 3 storable arrays.
This "unwinds" the object's central data, turning it from a single compound array, with object references, into 3 standalone arrays.
Returns
an array, containing 3 arrays; one for each table.
Definition at line 66 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         // We first see whether this is a new instance or an existing one. A new instance will have no ID.
         $is_update = ( isset($this->_my_meeting_data['id_bigint']) && (0 < intval($this->_my_meeting_data['id_bigint']) ) );
         // We now set up values for the three tables: The main one, the extra data one, and the long data one.
         $main_table_values = array();
         $data_table_values = array();
         $longdata_table_values = array();
         // If this is a new meeting, we null it out so that the db will auto increment the value
         if (!$is_update) {
             $this->_my_meeting_data['id_bigint'] = null;
         }
         // Load the main table first.
         $main_table_values['id_bigint'] = $this->_my_meeting_data['id_bigint'];
         if (isset($this->_my_meeting_data['email_contact'])) {
             $main_table_values['email_contact'] = $this->_my_meeting_data['email_contact'];
         } else {
             $main_table_values['email_contact'] = null;
         }
         if (isset($this->_my_meeting_data['worldid_mixed'])) {
             $main_table_values['worldid_mixed'] = $this->_my_meeting_data['worldid_mixed'];
         } else {
             $main_table_values['worldid_mixed'] = null;
         }
         if (isset($this->_my_meeting_data['service_body_bigint'])) {
             $main_table_values['service_body_bigint'] = $this->_my_meeting_data['service_body_bigint'];
         } else {
             $main_table_values['service_body_bigint'] = null;
         }
         if (isset($this->_my_meeting_data['weekday_tinyint'])) {
             $main_table_values['weekday_tinyint'] = $this->_my_meeting_data['weekday_tinyint'] - 1;
         } else {
             $main_table_values['weekday_tinyint'] = null;
         }
         if (isset($this->_my_meeting_data['start_time'])) {
             $main_table_values['start_time'] = $this->_my_meeting_data['start_time'];
         } else {
             $main_table_values['start_time'] = null;
         }
         if (isset($this->_my_meeting_data['lang_enum'])) {
             $main_table_values['lang_enum'] = $this->_my_meeting_data['lang_enum'];
         } else {
             $main_table_values['lang_enum'] = "en"; // Should never happen.
         }
         if (isset($this->_my_meeting_data['duration_time'])) {
             $main_table_values['duration_time'] = $this->_my_meeting_data['duration_time'];
         } else {
             $main_table_values['duration_time'] = null;
         }
         if (isset($this->_my_meeting_data['time_zone'])) {
             $main_table_values['time_zone'] = $this->_my_meeting_data['time_zone'];
         } else {
             $main_table_values['time_zone'] = null;
         }
         if (isset($this->_my_meeting_data['longitude'])) {
             $main_table_values['longitude'] = $this->_my_meeting_data['longitude'];
         } else {
             $main_table_values['longitude'] = null;
         }
         if (isset($this->_my_meeting_data['latitude'])) {
             $main_table_values['latitude'] = $this->_my_meeting_data['latitude'];
         } else {
             $main_table_values['latitude'] = null;
         }
         if (isset($this->_my_meeting_data['published'])) {
             $main_table_values['published'] = $this->_my_meeting_data['published'];
         } else {
             $main_table_values['published'] = 0;
         }
         // Now, we "unwind" the formats. Remember that we made the formats into an array, and replaced the values with objects, so we just use the keys here.
         $main_table_values['formats'] = "";
         if (isset($this->_my_meeting_data['formats']) && is_array($this->_my_meeting_data['formats']) && count($this->_my_meeting_data['formats'])) {
             foreach ($this->_my_meeting_data['formats'] as $key => $value2) {
                 if ($main_table_values['formats']) {
                     $main_table_values['formats'] .= ",";
                 }
                 $main_table_values['formats'] .= $key;
             }
         }
         // Okay, that does it for the main table. Time to do the two data tables. The way we do that is very simple: We just measure how many bytes are in the data.
         // Anything over 255 characters in length becomes a member of the longdata table.
         foreach ($this->_my_meeting_data as $key => $value2) {
             // We ignore the values in the main table.
             switch ($key) {
                 case 'published':
                 case 'id_bigint':
                 case 'worldid_mixed':
                 case 'service_body_bigint':
                 case 'weekday_tinyint':
                 case 'start_time':
                 case 'lang_enum':
                 case 'duration_time':
                 case 'time_zone':
                 case 'formats':
                 case 'longitude':
                 case 'latitude':
                 case 'distance_in_km':
                 case 'distance_in_miles':
                 case 'email_contact':
                     break;
                 // Everything else goes into one of the other tables.
                 default:
                     $data_table_value['data_bigint'] = null;
                     unset($data_table_value['data_bigint']);
                     $data_table_value['data_double'] = null;
                     unset($data_table_value['data_double']);
                     $longdata_table_value['data_blob'] = null;
                     unset($longdata_table_value['data_blob']);
                     if (isset($this->_my_meeting_data[$key]['value']) && ( null != $this->_my_meeting_data[$key]['value'] )) {
                         $val = null;
                         $val_key = null;
                         // We reference the correct table for our operation.
                         if (is_int($this->_my_meeting_data[$key]['value'])) {
                             $val_key = 'data_bigint';
                             $val = intval($this->_my_meeting_data[$key]['value']);
                         } elseif (is_float($this->_my_meeting_data[$key]['value'])) {
                             $val_key = 'data_double';
                             $val = floatval($this->_my_meeting_data[$key]['value']);
                         } else {
                             $datalen = strlen($this->_my_meeting_data[$key]['value']);
                             if ($datalen) {
                                 // We use the correct table for our operation.
                                 if ($datalen > 255) {
                                     $longdata_table_value['meetingid_bigint'] = $main_table_values['id_bigint'];
                                     $longdata_table_value['lang_enum'] = $this->_my_meeting_data['lang_enum'];
                                     $longdata_table_value['field_prompt'] = $this->_my_meeting_data[$key]['prompt'];
                                     $longdata_table_value['visibility'] = $this->_my_meeting_data[$key]['visibility'];
                                     $longdata_table_value['key'] = $key;
                                     // We reference the data, as it may be pretty long.
                                     $longdata_table_value['data_blob'] = $this->_my_meeting_data[$key]['value'];
                                     $val = null;
                                     array_push($longdata_table_values, $longdata_table_value);
                                 } else {
                                     $val_key = 'data_string';
                                     $val = stripslashes($this->_my_meeting_data[$key]['value']);
                                 }
                             }
                         }
                         if (null != $val) {
                             $data_table_value['meetingid_bigint'] = $main_table_values['id_bigint'];
                             $data_table_value['lang_enum'] = $this->_my_meeting_data['lang_enum'];
                             $data_table_value['field_prompt'] = $this->_my_meeting_data[$key]['prompt'];
                             $data_table_value['visibility'] = $this->_my_meeting_data[$key]['visibility'];
                             $data_table_value['key'] = $key;
                             $data_table_value[$val_key] = $val;
                             array_push($data_table_values, $data_table_value);
                         }
                     }
                     break;
             }
         }
         $ret_array = array ();
         array_push($ret_array, $main_table_values);
         array_push($ret_array, $data_table_values);
         array_push($ret_array, $longdata_table_values);
         return $ret_array;
     }
RemoveFormat ($in_format)
Remove a format from the meeting (by code).
Given an integer, representing the format code, it will remove it from the meeting.
Returns
true if successful, and false if the format was not there.
Parameters
$in_format An integer, containing the format to be removed.
Definition at line 1485 of file c_comdef_meeting.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $myData = $this->GetMeetingData();
         if (isset($myData['formats'][$in_format])) {
             $myData['formats'][$in_format] = null;  // Make sure we remove the reference to the object.
             unset($myData['formats'][$in_format]);
             return true;
         }
         return false;
     }
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 502 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, and c_comdef_dbsingleton\preparedQuery().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         try {
             $sql = "SELECT * FROM `".c_comdef_server::GetMeetingTableName_obj()."_main` WHERE id_bigint=? LIMIT 1";
             $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $this->GetID() ));
             if (is_array($rows) && count($rows)) {
                 foreach ($rows as $row) {
                     $meeting_row = self::process_meeting_row($row);
                     $this->_my_meeting_data = null;
                     // We set this as our data.
                     $this->_my_meeting_data = $meeting_row;
                 }
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_meeting::RestoreFromDB()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
     }
SerializeObject ()
Returns a storable serialization of the object, as a string.
This is only used for the changes, as the serialized string may not be easily searched.
Returns
an array, containing the 3 component strings, each one a table array, in serialized form.
Implements i_comdef_serialized.
Definition at line 1559 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         list ( $main_table_values, $data_table_values, $longdata_table_values ) = $this->ReduceToArrays();
         $ret = serialize(array (  'main_table_values' => serialize($main_table_values),
                         'data_table_values' => serialize($data_table_values),
                         'longdata_table_values' => serialize($longdata_table_values) ));
         return $ret;
     }
SetEmailContact ($in_email_contact)
Set this meeting's Email Contact Address This "vets" the email address, to ensure it has the appropriate structure. It won't set the address if it is not the appropriate structure.
Returns
a boolean, which is true if the address was set correctly.
Parameters
$in_email_contact A string. The contact email address.
Definition at line 1255 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         if (preg_match('#^(?:[a-zA-Z0-9_\'^&amp;/+-])+(?:\.(?:[a-zA-Z0-9_\'^&amp;/+-])+)*@(?:(?:\[?(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?))\.){3}(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\]?)|(?:[a-zA-Z0-9-]+\.)+(?:[a-zA-Z]){2,}\.?)$#', $in_email_contact)) {
             $this->_my_meeting_data['email_contact'] = $in_email_contact;
             $ret = true;
         }
         return $ret;
     }
SetMeetingID ($in_meeting_id_bigint)
Set this meeting's ID.
Parameters
$in_meeting_id_bigint An integer, with the meeting's new ID.
Definition at line 1205 of file c_comdef_meeting.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_my_meeting_data['id_bigint'] = intval($in_meeting_id_bigint);
     }
SetPublished ($in_published)
Accessor - Sets the meeting's published status.
Parameters
$in_published A boolean. True if the meeting is published.
Definition at line 1174 of file c_comdef_meeting.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if (!$this->IsCopy()) { // Can't publish copies.
             $this->_my_meeting_data['published'] = (intval($in_published) != 0) ? 1 : 0;
         }
     }
SetServiceBodyID ($in_service_body_id)
Set this meeting's Service Body ID.
Returns
an integer, which is the previous ID of the Service Body for this meeting.
Parameters
$in_service_body_id An integer, the ID of the new Service Body for this meeting.
Definition at line 1287 of file c_comdef_meeting.class.php.
References $ret.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = $this->_my_meeting_data['service_body_bigint'];
         $this->_my_meeting_data['service_body_bigint'] = intval($in_service_body_id);
         return $ret;
     }
SetWorldID ($new_world_id)
Set this meeting's world_id.
Definition at line 1229 of file c_comdef_meeting.class.php.
       {
         $this->_my_meeting_data['worldid_mixed'] = $new_world_id;
     }
static UnserializeObject ($in_parent, $serialized_array) static
This takes a serialized object, and instantiates a new object from it.
Returns
a new instance of c_comdef_meeting, set up according to the serialized data passed in.
Parameters
$in_parent The parent object.
$serialized_array String containing 3 sequential arrays, each with the serialized data.
Implements i_comdef_serialized.
Definition at line 1579 of file c_comdef_meeting.class.php.
Referenced by c_comdef_change\GetAfterObject(), and c_comdef_change\GetBeforeObject().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $serialized_array = unserialize($serialized_array);
         $main_table_values = unserialize($serialized_array['main_table_values']);
         $data_table_values = unserialize($serialized_array['data_table_values']);
         $longdata_table_values = unserialize($serialized_array['longdata_table_values']);
         $my_data = self::process_meeting_row($main_table_values, $data_table_values, $longdata_table_values);
         $new_meeting = new c_comdef_meeting($in_parent, $my_data);
         return $new_meeting;
     }
UpdateToDB ($is_rollback = false)
Updates the DB to the current values of this instance. (replacing current values of the DB).
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
We give the prepared statement a token, that will be filled by a value.
We give the value by declaring an associative array element with the token name.
We give the prepared statement a token, that will be filled by a value.
We give the value by declaring an associative array element with the token name.
We give the prepared statement a token, that will be filled by a value.
We give the value by declaring an associative array element with the token name.
Parameters
$is_rollback If true, this is a rollback operation.
Definition at line 246 of file c_comdef_meeting.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\AddNewChange(), c_comdef_server\GetCurrentUserObj(), c_comdef_server\GetServer(), c_comdef_dbsingleton\lastInsertId(), and c_comdef_dbsingleton\preparedExec().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             // We take a snapshot of the meeting as it currently sits in the database as a "before" image.
             $before = null;
             $before_id = null;
             $before_lang = null;
             $service_body_id = null;
             $before_obj = c_comdef_server::GetServer()->GetOneMeeting($this->GetID());
             if ($before_obj instanceof c_comdef_meeting) {
                 $service_body_id = $before_obj->GetServiceBodyID();
                 $before = $before_obj->SerializeObject();
                 $before_id = $before_obj->GetID();
                 $before_lang = $before_obj->GetLocalLang();
                 $before_obj = null;
             }
             if (null == $service_body_id) {
                 $service_body_id = $this->GetServiceBodyID();
             }
             try {
                 // We now set up values for the three tables: The main one, the extra data one, and the long data one.
                 list ( $main_table_values, $data_table_values, $longdata_table_values ) = $this->ReduceToArrays();
                 // Okay, we have our three rows. Time to send them to the database.
                 if (is_array($main_table_values)  && count($main_table_values)) {
                     // The first thing we do is delete the current entry. We'll insert a new one.
                     $this->DeleteFromDB_NoRecord();
                     $first = true;
                     $updateSQL = "INSERT INTO `".c_comdef_server::GetMeetingTableName_obj()."_main` (";
                     foreach ($main_table_values as $key => $value) {
                         if (!$first) {
                             $updateSQL .= ",";
                         } else {
                             $first = false;
                         }
                         $updateSQL .= "`$key`";
                     }
                     $first = true;
                     $vals = array();
                     $updateSQL .= ") VALUES (";
                     foreach ($main_table_values as $key => $value) {
                         if (!$first) {
                             $updateSQL .= ",";
                         } else {
                             $first = false;
                         }
                         /// We give the prepared statement a token, that will be filled by a value.
                         $updateSQL .= ":$key";
                         /// We give the value by declaring an associative array element with the token name.
                         $vals[":$key"] = $value;
                     }
                     $updateSQL .= ")";
                     c_comdef_dbsingleton::preparedExec($updateSQL, $vals);
                     if (is_null($this->_my_meeting_data['id_bigint'])) {
                         // This was a new meeting, need to get the generated id
                         $newMeetingId = intval(c_comdef_dbsingleton::lastInsertId());
                         $this->_my_meeting_data['id_bigint'] = $newMeetingId;
                         list ( $main_table_values, $data_table_values, $longdata_table_values ) = $this->ReduceToArrays();
                     }
                     if (is_array($data_table_values)  && count($data_table_values)) {
                         foreach ($data_table_values as $data_table_value) {
                             $first = true;
                             $updateSQL = "INSERT INTO `".c_comdef_server::GetMeetingTableName_obj()."_data` (";
                             foreach ($data_table_value as $key => $value) {
                                 if (!$first) {
                                     $updateSQL .= ",";
                                 } else {
                                     $first = false;
                                 }
                                 $updateSQL .= "`$key`";
                             }
                             $first = true;
                             $vals = array();
                             $updateSQL .= ") VALUES (";
                             foreach ($data_table_value as $key => $value) {
                                 // Just in case some dork wants to change the meeting ID (BAD idea).
                                 if ($key == 'meetingid_bigint') {
                                     $value = $main_table_values['id_bigint'];
                                 }
                                 if (!$first) {
                                     $updateSQL .= ",";
                                 } else {
                                     $first = false;
                                 }
                                 /// We give the prepared statement a token, that will be filled by a value.
                                 $updateSQL .= ":$key";
                                 /// We give the value by declaring an associative array element with the token name.
                                 $vals[":$key"] = $value;
                             }
                             $updateSQL .= ")";
                             c_comdef_dbsingleton::preparedExec($updateSQL, $vals);
                         }
                     }
                     if (is_array($longdata_table_values)  && count($longdata_table_values)) {
                         foreach ($longdata_table_values as $longdata_table_value) {
                             $first = true;
                             $updateSQL = "INSERT INTO `".c_comdef_server::GetMeetingTableName_obj()."_longdata` (";
                             foreach ($longdata_table_value as $key => $value) {
                                 // Just in case some dork wants to change the meeting ID (BAD idea).
                                 if ($key == 'meetingid_bigint') {
                                     $value = $main_table_values['id_bigint'];
                                 }
                                 if (!$first) {
                                     $updateSQL .= ",";
                                 } else {
                                     $first = false;
                                 }
                                 $updateSQL .= "`$key`";
                             }
                             $first = true;
                             $vals = array();
                             $updateSQL .= ") VALUES (";
                             foreach ($longdata_table_value as $key => $value) {
                                 if (!$first) {
                                     $updateSQL .= ",";
                                 } else {
                                     $first = false;
                                 }
                                 /// We give the prepared statement a token, that will be filled by a value.
                                 $updateSQL .= ":$key";
                                 /// We give the value by declaring an associative array element with the token name.
                                 $vals[":$key"] = $value;
                             }
                             $updateSQL .= ")";
                             c_comdef_dbsingleton::preparedExec($updateSQL, $vals);
                         }
                     }
                     $after = $this->SerializeObject();
                     $after_id = $this->GetID();
                     $after_lang = $this->GetLocalLang();
                     $cType = (true == $is_rollback) ? 'comdef_change_type_rollback' : ((null != $before) ? 'comdef_change_type_change' : 'comdef_change_type_new');
                     c_comdef_server::AddNewChange($user->GetID(), $cType, $service_body_id, $before, $after, 'c_comdef_meeting', $before_id, $after_id, $before_lang, $after_lang);
                     $ret = true;
                 }
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_meeting::UpdateToDB()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
UserCanEdit ($in_user_object = null)
Test to see if a user is allowed to edit an instance (change the data).
Returns
true, if the user is allowed to edit, false, otherwise.
Parameters
$in_user_object A reference to a c_comdef_user object, for the user to be validated. If null, or not supplied, the server current user is tested.
Implements i_comdef_auth.
Definition at line 1730 of file c_comdef_meeting.class.php.
References $ret, _USER_LEVEL_DISABLED, _USER_LEVEL_EDITOR, _USER_LEVEL_SERVER_ADMIN, _USER_LEVEL_SERVICE_BODY_ADMIN, c_comdef_server\GetCurrentUserObj(), c_comdef_server\GetServer(), c_comdef_server\GetServiceBodyByIDObj(), and c_comdef_server\IsUserServerAdmin().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         // We load the server user if one wasn't supplied.
         if (null == $in_user_object) {
             $in_user_object = c_comdef_server::GetCurrentUserObj();
         }
         // If it isn't a user object, we fail right there.
         if ($in_user_object instanceof c_comdef_user) {
             $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
             if (($in_user_object->GetUserLevel() != _USER_LEVEL_SERVER_ADMIN) && ($in_user_object->GetUserLevel() != _USER_LEVEL_DISABLED) && (($in_user_object->GetUserLevel() == _USER_LEVEL_EDITOR) || ($in_user_object->GetUserLevel() == _USER_LEVEL_SERVICE_BODY_ADMIN))) {
                 // If there is an existing object, then we can't make changes unless it's allowed in the existing object.
                 $current_obj = c_comdef_server::GetServer()->GetOneMeeting($this->GetID());
                 // If there is no current object, then we are a new meeting.
                 if (null == $current_obj) {
                     $current_obj = $this;
                 } else {
                     // We clone, in case changes have been made, and we don't want to screw them up.
                     $current_obj = clone $current_obj;
                     // Otherwise, block dope fiends.
                     $current_obj->RestoreFromDB();
                 }
                 if ($current_obj instanceof c_comdef_meeting) {
                     $my_service_body = c_comdef_server::GetServiceBodyByIDObj($current_obj->GetServiceBodyID());
                     if ($in_user_object->GetUserLevel() == _USER_LEVEL_EDITOR) {
                         // Regular meeting list editors can't change published objects. They also can only edit meetings in the exact Service Body to which they are assigned.
                         $ret = ($my_service_body instanceof c_comdef_service_body) && $my_service_body->IsUserInServiceBody($in_user_object) && !$this->IsPublished();
                     } elseif (($my_service_body instanceof c_comdef_service_body) && $my_service_body->IsUserInServiceBodyHierarchy($in_user_object)) {
                         $ret = true;
                     }
                 }
             } elseif (c_comdef_server::IsUserServerAdmin()) {
                 $ret = true;
             }
         }
         return $ret;
     }
UserCanObserve ($in_user_object = null)
Test to see if a user is allowed to observe an instance (view the data).
Returns
true, if the user is allowed to observe, false, otherwise.
Parameters
$in_user_object A reference to a c_comdef_user object, for the user to be validated. If null, or not supplied, the server current user is tested.
Definition at line 1783 of file c_comdef_meeting.class.php.
References $ret, _USER_LEVEL_OBSERVER, _USER_LEVEL_SERVER_ADMIN, _USER_LEVEL_SERVICE_BODY_ADMIN, c_comdef_server\GetCurrentUserObj(), c_comdef_server\GetServer(), and c_comdef_server\GetServiceBodyByIDObj().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         // We load the server user if one wasn't supplied.
         if (null == $in_user_object) {
             $in_user_object = c_comdef_server::GetCurrentUserObj();
         }
         // If it isn't a user object, we fail right there.
         if ($in_user_object instanceof c_comdef_user) {
             $in_user_object->RestoreFromDB();   // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
             if (($in_user_object->GetUserLevel() == _USER_LEVEL_OBSERVER) || ($in_user_object->GetUserLevel() == _USER_LEVEL_SERVICE_BODY_ADMIN) || ($in_user_object->GetUserLevel() == _USER_LEVEL_SERVER_ADMIN)) {
                 // If there is an existing object, then we can't make changes unless it's allowed in the existing object.
                 $current_obj = c_comdef_server::GetServer()->GetOneMeeting($this->GetID());
                 // If there is no current object, then we are a new meeting.
                 if (null == $current_obj) {
                     $current_obj = $this;
                 } else {
                     // We clone, in case changes have been made, and we don't want to screw them up.
                     $current_obj = clone $current_obj;
                     // Otherwise, block dope fiends.
                     $current_obj->RestoreFromDB();
                 }
                 if ($current_obj instanceof c_comdef_meeting) {
                     $my_service_body = c_comdef_server::GetServiceBodyByIDObj($current_obj->GetServiceBodyID());
                     if (($my_service_body instanceof c_comdef_service_body) && $my_service_body->UserCanObserve($in_user_object)) {
                         $ret = true;
                     }
                 }
             }
         }
         return $ret;
     }
Member Data Documentation
$_my_meeting_data = null private
This is the data for this meeting.
Definition at line 55 of file c_comdef_meeting.class.php.
The documentation for this class was generated from the following file:
/home/travis/build/bmlt-enabled/bmlt-root-server/main_server/server/classes/c_comdef_meeting.class.php