BMLT Root Server: /home/travis/build/bmlt-enabled/bmlt-root-server/main_server/client_interface/json/GetLangs.php File Reference
GetLangs.php File Reference
Returns a JSON response, containing all the Language enumss and names. *.
Variables
defined('BMLT_EXEC') or define('BMLT_EXEC' true
$file_dir = str_replace('/client_interface/json', '', dirname(__FILE__)).'/server/c_comdef_server.class.php'
$server = c_comdef_server::MakeServer()
$ret = null
if($server instanceof c_comdef_server) else
Detailed Description
Returns a JSON response, containing all the Language enumss and names. *.
This file is part of the Basic Meeting List Toolbox (BMLT).
Find out more at: https://bmlt.app
BMLT is free software: you can redistribute it and/or modify it under the terms of the MIT License.
BMLT is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the MIT License for more details.
You should have received a copy of the MIT License along with this code. If not, see https://opensource.org/licenses/MIT.
Definition in file GetLangs.php.
Variable Documentation
$file_dir = str_replace('/client_interface/json', '', dirname(__FILE__)).'/server/c_comdef_server.class.php'
Definition at line 23 of file GetLangs.php.
$ret = null
Definition at line 26 of file GetLangs.php.
$server = c_comdef_server::MakeServer()
Definition at line 25 of file GetLangs.php.
Referenced by BMLT_FuncNAWSReturnDirections(), BMLT_FuncNAWSReturnFormat(), BMLT_FuncNAWSReturnFormat1(), BMLT_FuncNAWSReturnFormat2(), BMLT_FuncNAWSReturnFormat3(), BMLT_FuncNAWSReturnFormat4(), BMLT_FuncNAWSReturnFormat5(), BMLT_FuncNAWSReturnLanguage1(), BMLT_FuncNAWSReturnLastMeetingChangeTime(), BMLT_FuncNAWSReturnMeetingNAWSID(), BMLT_FuncNAWSReturnMeetingServiceBodyName(), BMLT_FuncNAWSReturnMeetingServiceBodyNAWSID(), BMLT_FuncNAWSReturnMeetingTown(), BMLT_FuncNAWSReturnNonNawsFormats(), BMLT_FuncNAWSReturnOpenOrClosed(), BMLT_FuncNAWSReturnPublishedStatus(), BMLT_FuncNAWSReturnTime(), BMLT_FuncNAWSReturnWeekday(), BMLT_FuncNAWSReturnWheelchair(), bmlt_populate_format_dictionary(), c_comdef_admin_bar(), GetChildServiceBodies(), GetFormats(), c_comdef_server\GetLocalStrings(), GetServiceBodies(), c_comdef_server\GetServiceBodyByIDObj(), c_comdef_server\GetServiceBodyHierarchyIDs(), c_comdef_service_body\IsOwnedBy(), parse_redirect(), c_comdef_admin_xml_handler\process_meeting_search(), ReturnNAWSDeletedMeetings(), ReturnNAWSFormatCSV(), c_comdef_user\SetNewPassword(), and whitespace_warnings().
if ($server instanceof c_comdef_server) else
Initial value:
{
    echo ( 'No Server' )
Definition at line 64 of file GetLangs.php.
defined ('BMLT_EXEC') or define('BMLT_EXEC' true
Definition at line 22 of file GetLangs.php.