BMLT Root Server: c_comdef_user Class Reference
c_comdef_user Class Reference
This class handles BMLT users. One instance is created for each user on the server.
Public Member Functions
UpdateToDB ($is_rollback=false, $new_login=null, $new_pass=null)
Updates or adds this instance to the database.
DeleteFromDB_NoRecord ()
Deletes this instance from the database without creating a change record.
DeleteFromDB ()
Deletes this instance from the database, and creates a change record.
ResetChildUsers ()
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
__construct ($in_parent_obj, $in_id_bigint, $in_user_level_tinyint, $in_email_address_string, $in_login_string, $in_password_string, $in_lang_enum, $in_name_string, $in_description_string, $in_owner_id_bigint=-1, $in_last_access=null)
The initial setup call for the class. If you send in values, the object will set itself up to use them.
IsEnabled ()
Returns true if the user is enabled (levels 1-3)
GetID ()
Accessor - Returns the user ID as an integer.
SetID ($in_user_id_bigint)
Accessor - Sets the user ID as an integer.
GetOwnerID ()
Accessor - Gets the owner ID as an integer.
SetOwnerID ($in_owner_id_bigint)
Accessor - Sets the owner ID as an integer.
GetUserLevel ()
Accessor - Returns the user level as an integer.
SetUserLevel ($in_user_level_tinyint)
Accessor - Sets the user level. Attempts to set the user level to 1 for users other than User 1 will fail.
GetEmailAddress ()
Accessor - Returns the user email address.
SetEmailAddress ($in_email_address_string)
Accessor - Sets the user email address.
GetLogin ()
Accessor - Returns the user login.
SetLogin ($in_login_string)
Accessor - Sets the userlogin.
IsUser ($in_login_string, $in_password_string, $in_pw_raw=false)
See if this is the given user by login and password.
GetPassword ()
Accessor - Returns the user password, in encrypted form.
SetPassword ($in_password_string)
Accessor - Sets the password, as an encrypted string.
SetNewPassword ($in_password_unencrypted_string)
Accessor - Sets the password, encrypting it.
GetLastAccess ()
Accessor - Gets the last access time.
SetLastAccess ($in_time=null)
Simply sets the last access time to now.
SerializeObject ()
Returns a storable serialization of the object, as a string.
UserCanEdit ($in_user_object=null)
Test to see if a user is allowed to edit an instance (change the data).
Public Member Functions inherited from t_comdef_local_type
SetLocalLang ($in_lang_enum=null)
Sets the language.
GetLocalLang ()
Returns a reference to the local language setting.
SetLocalName ($in_name_string)
Accessor -Sets the _local_type_name_string data member.
GetLocalName ()
Accessor -Returns a reference to the _local_type_name_string data member.
SetLocalDescription ($in_description_string)
Accessor -Sets the _local_type_desc_string data member.
GetLocalDescription ()
Accessor -Returns a reference to the _local_type_desc_string data member.
Public Member Functions inherited from t_local_id_class
SetParentObj ($in_parent_obj)
Sets the object's "parent" (Container) object, as a reference.
GetParentObj ()
Returns a reference to the object's container.
Public Member Functions inherited from i_comdef_db_stored
UpdateToDB ()
This causes the object to update the database to its current state.
Static Public Member Functions
static UnserializeObject ($in_parent, $serialized_string)
This takes the serialized table, and instantiates a new object from it.
Private Attributes
$_id_bigint = null
An integer, containing the unique ID of this user.
$_user_level_tinyint = null
An integer, containing the user level.
$_email_address_string = null
A string, containing the user's email address.
$_login_string = null
A string, containing the user's login ID.
$_password_string = null
A string, containing the user's encrypted password.
$_last_access = null
A time date, indicating the last time the user was active. This will be useful for administration.
$_owner_id_bigint = -1
An integer containing the id of the user that owns this user.
Detailed Description
This class handles BMLT users. One instance is created for each user on the server.
Definition at line 40 of file c_comdef_user.class.php.
Constructor & Destructor Documentation
__construct()
__construct ($in_parent_obj, $in_id_bigint, $in_user_level_tinyint, $in_email_address_string, $in_login_string, $in_password_string, $in_lang_enum, $in_name_string, $in_description_string, $in_owner_id_bigint = -1, $in_last_access = null)
The initial setup call for the class. If you send in values, the object will set itself up to use them.
Parameters
$in_parent_obj A reference to the parent object for this object
$in_id_bigint Integer. The ID of the user
$in_email_address_string A string, containing the user's email address.
$in_login_string A string, containing the user's login.
$in_password_string A string, containing the user's password, in encrypted form.
$in_lang_enum An enum/string, with the user's language.
$in_name_string A string, containing the readble name for the user.
$in_description_string A string, containing a description of the user.
$in_owner_id_bigint An integer containing the id of the user that owns this user.
$in_last_access An epoch time, indicating the last access of this user (Optional).
Definition at line 336 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         // Set the four inherited values.
         $this->SetParentObj($in_parent_obj);
         $this->SetLocalLang($in_lang_enum);
         $this->SetLocalName($in_name_string);
         $this->SetLocalDescription($in_description_string);
         // Set the local values.
         $this->_id_bigint = $in_id_bigint;
         $this->_user_level_tinyint = $in_user_level_tinyint;
         $this->_email_address_string = $in_email_address_string;
         $this->_login_string = $in_login_string;
         $this->_password_string = $in_password_string;
         $this->_owner_id_bigint = $in_owner_id_bigint;
         $this->_last_access = $in_last_access;
     }
Member Function Documentation
DeleteFromDB()
DeleteFromDB ()
Deletes this instance from the database, and creates a change record.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 236 of file c_comdef_user.class.php.
References $ret, c_comdef_server\AddNewChange(), c_comdef_server\GetCurrentUserObj(), and c_comdef_server\GetOneUser().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $user = c_comdef_server::GetCurrentUserObj();
         if ($this->UserCanEdit($user)) {
             // We take a snapshot of the user as it currently sits in the database as a "before" image.
             $before = null;
             $before_id = null;
             $before_lang = null;
             $before_obj = c_comdef_server::GetOneUser($this->GetID());
             if ($before_obj instanceof c_comdef_user) {
                 $before = $before_obj->SerializeObject();
                 $before_id = $before_obj->GetID();
                 $before_lang = $before_obj->GetLocalLang();
                 $before_obj = null;
             }
             $ret = $this->DeleteFromDB_NoRecord();
             if ($ret) {
                 c_comdef_server::AddNewChange($user->GetID(), 'comdef_change_type_delete', $this->GetID(), $before, null, 'c_comdef_user', $before_id, null, $before_lang, null);
             }
         }
         return $ret;
     }
DeleteFromDB_NoRecord()
DeleteFromDB_NoRecord ()
Deletes this instance from the database without creating a change record.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Definition at line 204 of file c_comdef_user.class.php.
References $_COMDEF_DEBUG, $ret, and c_comdef_dbsingleton\preparedExec().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         if ($this->UserCanEdit()) {
             try {
                 $sql = "DELETE FROM `".c_comdef_server::GetUserTableName_obj()."` WHERE id_bigint=?";
                 c_comdef_dbsingleton::preparedExec($sql, array ( $this->GetID() ));
                 $ret = true;
             } catch (Exception $ex) {
                 global  $_COMDEF_DEBUG;
                 if ($_COMDEF_DEBUG) {
                     echo "Exception Thrown in c_comdef_user::DeleteFromDB()!<br />";
                     var_dump($ex);
                 }
                 throw ( $ex );
             }
         }
         return $ret;
     }
GetEmailAddress()
GetEmailAddress ()
Accessor - Returns the user email address.
Returns
a string, containing the user email address.
Definition at line 531 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_email_address_string;
     }
GetID()
GetID ()
Accessor - Returns the user ID as an integer.
Returns
an integer, containing the user ID.
Definition at line 409 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_id_bigint;
     }
GetLastAccess()
GetLastAccess ()
Accessor - Gets the last access time.
Returns
an epoch time that contains the last access time.
Definition at line 689 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_last_access;
     }
GetLogin()
GetLogin ()
Accessor - Returns the user login.
Returns
a string, containing the user login.
Definition at line 554 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_login_string;
     }
GetOwnerID()
GetOwnerID ()
Accessor - Gets the owner ID as an integer.
Definition at line 430 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_owner_id_bigint;
     }
GetPassword()
GetPassword ()
Accessor - Returns the user password, in encrypted form.
Returns
a string, containing the user password, as an encrypted hash.
Definition at line 636 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return $this->_password_string;
     }
GetUserLevel()
GetUserLevel ()
Accessor - Returns the user level as an integer.
Returns
an integer, containing the user level. Values:
(1) Server Administrator -There can only be one. The user ID is always 1. This administrator can edit all aspects of the server.
(2) Service Body Administrator -There can only be one per Service Body A Service Body Administrator can edit all meetings from the Service Body that assigns the user as its administrator. This user can also assign other Service Body Administrators or Editors as users able to edit meetings belonging to the Service Body. A Service Body Administrator can also edit Service Body information. NOTE: A Service Body Administrator only has extra rights when assigned to a specific Service Body. If assigned as an Editor on another Service Body, they do not have rights beyond those of an Editor.
(3) Editor -There can be many. An Editor is assigned by a Service Body Administrator to edit meetings for that Service Body. They can only edit meetings; not users or Service Bodies. Making a user an editor (or a Service Body Administrator) doesn't automatically give them any rights. They must first be assigned to a Service Body, either by the Server Administrator (Service Body Administrators), or by a Service Body Administrator (Editors).
(4) User Disabled.
(5) Observer -User can see private data in meetings for which it is authorized.
Definition at line 475 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         // We reload ourselves from the database first, just to avoid shenanigans...
         $this->RestoreFromDB();
         return $this->_user_level_tinyint;
     }
IsEnabled()
IsEnabled ()
Returns true if the user is enabled (levels 1-3)
Returns
a Boolean. true if enabled, false if not.
Definition at line 397 of file c_comdef_user.class.php.
References _USER_LEVEL_DISABLED.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         return ($this->_user_level_tinyint > 0) && ($this->_user_level_tinyint != _USER_LEVEL_DISABLED);
     }
IsUser()
IsUser ($in_login_string, $in_password_string, $in_pw_raw = false)
See if this is the given user by login and password.
The login is case-insensitive, but the password is not.
Returns
true, if so, false if not.
Parameters
$in_login_string A string, containing the user's login.
$in_password_string A string, containing the user's password, in encrypted form, or unencrypted, if $in_pw_raw is true.
$in_pw_raw A Boolean, true if the password has not been encrypted.
Definition at line 612 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $login_match = (strcasecmp($in_login_string, $this->GetLogin()) == 0);
         // See if we need to encrypt the password.
         if ($in_pw_raw) {
             $password_match = password_verify($in_password_string, $this->GetPassword());
         } else {
             $password_match = hash_equals($this->GetPassword(), $in_password_string);
         }
         return $login_match && $password_match;
     }
ResetChildUsers()
ResetChildUsers ()
Definition at line 268 of file c_comdef_user.class.php.
References $_COMDEF_DEBUG, $ret, and c_comdef_dbsingleton\preparedExec().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         try {
             $sql = "UPDATE `".c_comdef_server::GetUserTableName_obj()."` SET owner_id_bigint=-1 WHERE owner_id_bigint=?";
             c_comdef_dbsingleton::preparedExec($sql, array ( $this->GetID() ));
             $ret = true;
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_user::ResetChildUsers()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
         return $ret;
     }
RestoreFromDB()
RestoreFromDB ()
Updates this instance to the current values in the DB (replacing current values of the instance).
Exceptions
a PDOException if there is a problem.
Implements i_comdef_db_stored.
Definition at line 297 of file c_comdef_user.class.php.
References $_COMDEF_DEBUG, and c_comdef_dbsingleton\preparedQuery().
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         try {
             if ($this->GetID()) {
                 $sql = "SELECT * FROM `".c_comdef_server::GetUserTableName_obj()."` WHERE id_bigint=? LIMIT 1";
                 $rows = c_comdef_dbsingleton::preparedQuery($sql, array ( $this->GetID() ));
                 if (is_array($rows) && count($rows)) {
                     $this->_user_level_tinyint = $rows[0]['user_level_tinyint'];
                     $this->_email_address_string = $rows[0]['email_address_string'];
                     $this->_login_string = $rows[0]['login_string'];
                     $this->_password_string = $rows[0]['password_string'];
                     $this->_owner_id_bigint = $rows[0]['owner_id_bigint'];
                     $time = explode(" ", $rows[0]['last_access_datetime']);
                     $t0 = explode("-", $time[0]);
                     $t1 = explode(":", $time[1]);
                     $this->_last_access = mktime($t1[0], $t1[1], $t1[2], $t0[1], $t0[2], $t0[0]);
                     $this->SetLocalName($rows[0]['name_string']);
                     $this->SetLocalDescription($rows[0]['description_string']);
                     $this->SetLocalLang($rows[0]['lang_enum']);
                 }
             }
         } catch (Exception $ex) {
             global  $_COMDEF_DEBUG;
             if ($_COMDEF_DEBUG) {
                 echo "Exception Thrown in c_comdef_user::RestoreFromDB()!<br />";
                 var_dump($ex);
             }
             throw ( $ex );
         }
     }
SerializeObject()
SerializeObject ()
Returns a storable serialization of the object, as a string.
This is only used for the changes, as the serialized string may not be easily searched.
Returns
a string, containing the table array, in serialized form.
Implements i_comdef_serialized.
Definition at line 715 of file c_comdef_user.class.php.
     {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $serialize_array = array(
                                 $this->_id_bigint,
                                 $this->_user_level_tinyint,
                                 $this->_email_address_string,
                                 $this->_login_string,
                                 $this->_password_string,
                                 $this->_last_access,
                                 $this->GetLocalName(),
                                 $this->GetLocalDescription(),
                                 $this->_owner_id_bigint,
                                 $this->GetLocalLang()
                                 );
         return serialize($serialize_array);
     }
SetEmailAddress()
SetEmailAddress ($in_email_address_string)
Accessor - Sets the user email address.
Parameters
$in_email_address_string A string, containing the user's email address.
Definition at line 541 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_email_address_string = $in_email_address_string;
     }
SetID()
SetID ($in_user_id_bigint)
Accessor - Sets the user ID as an integer.
Parameters
$in_user_id_bigint An integer, with the user ID.
Definition at line 419 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_id_bigint = $in_user_id_bigint;
     }
SetLastAccess()
SetLastAccess ($in_time = null)
Simply sets the last access time to now.
Parameters
$in_time An epoch time. If not provided, now is used.
Definition at line 699 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_last_access = (null != $in_time) ? $in_time : time();
     }
SetLogin()
SetLogin ($in_login_string)
Accessor - Sets the userlogin.
Returns
true if successful, and false if not.
Parameters
$in_login_string A string, containing the user's login.
Definition at line 566 of file c_comdef_user.class.php.
References $ret, and c_comdef_server\GetServer().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         if ($in_login_string) {
             $users_obj = c_comdef_server::GetServer()->GetServerUsersObj();
             // We are not allowed to select a login that is already in use. The comparison
             // is case-insensitive.
             if ($users_obj instanceof c_comdef_users) {
                 $obj_array = $users_obj->GetUsersArray();
                 if (is_array($obj_array)) {
                     $ret = true;
                     foreach ($obj_array as $one_user) {
                         // We don't worry if this is our own object.
                         if ($one_user->GetID() != $this->GetID()) {
                             if (strtolower($one_user->GetLogin()) == strtolower($in_login_string)) {
                                 $ret = false;
                                 break;
                             }
                         }
                     }
                     // If we went through without a match, we change the login.
                     if ($ret) {
                         $this->_login_string = $in_login_string;
                     }
                 }
             }
         }
         return $ret;
     }
SetNewPassword()
SetNewPassword ($in_password_unencrypted_string)
Accessor - Sets the password, encrypting it.
Returns
a string, containing the encrypted password. Returns null if none was provided.
Parameters
$in_password_unencrypted_string A string, containing the user's password, in unencrypted form.
Definition at line 663 of file c_comdef_user.class.php.
References $server, FullCrypt(), and c_comdef_server\GetServer().
Referenced by c_comdef_admin_ajax_handler\HandleUserCreate().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if (trim($in_password_unencrypted_string)) {
             $server = c_comdef_server::GetServer();
             $strings = $server->GetLocalStrings();
             $min_pw_len = $strings['min_pw_len'];
             if ($min_pw_len <= strlen(trim($in_password_unencrypted_string))) {
                 $this->SetPassword(FullCrypt(trim($in_password_unencrypted_string)), $this->GetPassword());
                 return $this->GetPassword();
             } else {
                 return null;
             }
         } else {
             return null;
         }
     }
SetOwnerID()
SetOwnerID ($in_owner_id_bigint)
Accessor - Sets the owner ID as an integer.
Definition at line 440 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $this->_owner_id_bigint = $in_owner_id_bigint;
     }
SetPassword()
SetPassword ($in_password_string)
Accessor - Sets the password, as an encrypted string.
Parameters
$in_password_string A string, containing the user's password, in encrypted form.
Definition at line 646 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if (trim($in_password_string)) {
             $this->_password_string = trim($in_password_string);
         } else {
             return null;
         }
     }
SetUserLevel()
SetUserLevel ($in_user_level_tinyint)
Accessor - Sets the user level. Attempts to set the user level to 1 for users other than User 1 will fail.
Returns
true if successful, false otherwise.
Definition at line 490 of file c_comdef_user.class.php.
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         if (($this->_user_level_tinyint == 1) && ($this->_id_bigint > 1)) {
             return false;
         } else {
             $this->_user_level_tinyint = $in_user_level_tinyint;
             return true;
         }
     }
UnserializeObject()
static UnserializeObject ($in_parent, $serialized_string) static
This takes the serialized table, and instantiates a new object from it.
Returns
a new instance of c_comdef_user, set up according to the serialized data passed in.
Parameters
$in_parent The parent object.
$serialized_string A string containing the serialized data.
Implements i_comdef_serialized.
Definition at line 742 of file c_comdef_user.class.php.
Referenced by c_comdef_change\GetAfterObject(), and c_comdef_change\GetBeforeObject().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         list (  $_id_bigint,
                 $_user_level_tinyint,
                 $_email_address_string,
                 $_login_string,
                 $_password_string,
                 $_last_access,
                 $_local_name,
                 $_local_description,
                 $_owner_id_bigint,
                 $_local_lang ) = unserialize($serialized_string);
         return new c_comdef_user($in_parent, $_id_bigint, $_user_level_tinyint, $_email_address_string, $_login_string, $_password_string, $_local_lang, $_local_name, $_local_description, $_owner_id_bigint, $_last_access);
     }
UpdateToDB()
UpdateToDB ($is_rollback = false, $new_login = null, $new_pass = null)
Updates or adds this instance to the database.
Returns
true if successful, false, otherwise.
Exceptions
a PDOException if there is a problem.
Parameters
$is_rollback If true, this is a rollback operation.
$new_login This is a new login (Due to the self-checking, we can't set our own login before this). If it is null, no new password will be set.
$new_pass This is a new password (Due to the self-checking, we can't set our own pass before this). If it is null, no new password will be set.
Definition at line 99 of file c_comdef_user.class.php.
References $_COMDEF_DEBUG, $ret, c_comdef_server\AddNewChange(), c_comdef_server\GetCurrentUserObj(), c_comdef_server\GetOneUser(), c_comdef_dbsingleton\preparedExec(), and c_comdef_dbsingleton\preparedQuery().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         $cur_user = c_comdef_server::GetCurrentUserObj();
         if ($cur_user instanceof c_comdef_user) {
             $cur_user_clone = clone ( $cur_user );  // This little dance is to make sure that the live object wasn't changed.
             $cur_user_clone->RestoreFromDB();
             if ($cur_user_clone->UserCanEdit($cur_user)) {
                 // We take a snapshot of the user as it currently sits in the database as a "before" image.
                 $before = null;
                 $before_id = null;
                 $before_lang = null;
                 $before_obj = c_comdef_server::GetOneUser($this->GetID());
                 if ($before_obj instanceof c_comdef_user) {
                     $before_obj_clone = clone $before_obj;
                     $before_obj_clone->RestoreFromDB();
                     $before = $before_obj_clone->SerializeObject();
                     $before_id = $before_obj_clone->GetID();
                     $before_lang = $before_obj_clone->GetLocalLang();
                     $before_obj_clone = null;
                 }
                 $this->DeleteFromDB_NoRecord();
                 try {
                     $update = array();
                     if ($this->_id_bigint) {
                         array_push($update, $this->_id_bigint);
                     }
                     array_push($update, $this->_user_level_tinyint);
                     array_push($update, $this->_email_address_string);
                     if (null != $new_login) {
                         $this->SetLogin($new_login);
                     }
                     array_push($update, $this->_login_string);
                     if (null != $new_pass) {
                         $this->SetNewPassword($new_pass);
                     }
                     array_push($update, $this->GetPassword());
                     array_push($update, date("Y-m-d H:i:s", $this->_last_access));
                     array_push($update, $this->GetLocalName());
                     array_push($update, $this->GetLocalDescription());
                     array_push($update, $this->GetLocalLang());
                     array_push($update, $this->GetOwnerID());
                     $sql = "INSERT INTO `".c_comdef_server::GetUserTableName_obj()."` (";
                     if ($this->_id_bigint) {
                         $sql .= "`id_bigint`,";
                     }
                     $sql .= "`user_level_tinyint`,`email_address_string`,`login_string`,`password_string`,`last_access_datetime`,`name_string`,`description_string`,`lang_enum`, `owner_id_bigint`) VALUES (";
                     if ($this->_id_bigint) {
                         $sql .= "?,";
                     }
                     $sql .= "?,?,?,?,?,?,?,?,?)";
                     c_comdef_dbsingleton::preparedExec($sql, $update);
                     // If this is a new user, then we'll need to fetch the ID.
                     if (!$this->_id_bigint) {
                         $sql = "SELECT LAST_INSERT_ID()";
                         $rows = c_comdef_dbsingleton::preparedQuery($sql);
                         if (is_array($rows) && count($rows)) {
                             $this->_id_bigint = intval($rows[0]['last_insert_id()']);
                         }
                     }
                     $after = $this->SerializeObject();
                     $after_id = $this->GetID();
                     $after_lang = $this->GetLocalLang();
                     $cType = (true == $is_rollback) ? 'comdef_change_type_rollback' : ((null != $before) ? 'comdef_change_type_change' : 'comdef_change_type_new');
                     c_comdef_server::AddNewChange($cur_user->GetID(), $cType, null, $before, $after, 'c_comdef_user', $before_id, $after_id, $before_lang, $after_lang);
                     $ret = true;
                 } catch (Exception $ex) {
                     global  $_COMDEF_DEBUG;
                     if ($_COMDEF_DEBUG) {
                         echo "Exception Thrown in c_comdef_user::UpdateToDB()!<br />";
                         var_dump($ex);
                     }
                     throw ( $ex );
                 }
             }
         }
         return $ret;
     }
UserCanEdit()
UserCanEdit ($in_user_object = null)
Test to see if a user is allowed to edit an instance (change the data).
Returns
true, if the user is allowed to edit, false, otherwise.
Parameters
$in_user_object A reference to a c_comdef_user object, for the user to be validated. If null, or not supplied, the server current user is tested.
Implements i_comdef_auth.
Definition at line 767 of file c_comdef_user.class.php.
References $ret, _USER_LEVEL_DISABLED, _USER_LEVEL_OBSERVER, c_comdef_server\GetCurrentUserObj(), c_comdef_server\IsUserServerAdmin(), and c_comdef_server\IsUserServiceBodyAdmin().
       {
         // phpcs:enable PSR1.Methods.CamelCapsMethodName.NotCamelCaps
         $ret = false;
         // We load the server user if one wasn't supplied.
         if (null == $in_user_object) {
             $in_user_object = c_comdef_server::GetCurrentUserObj();
         }
         // We clone, in case changes have been made, and we don't want to screw them up.
         $in_user_clone = clone $in_user_object;
         // If it isn't a user object, we fail right there.
         if ($in_user_clone instanceof c_comdef_user) {
             $in_user_clone->RestoreFromDB();    // The reason you do this, is to ensure that the user wasn't modified "live." It's a security precaution.
             // Server admins can edit users. Service body administrators can edit users they own. Any user can edit itself.
             if ($in_user_clone->GetUserLevel() == _USER_LEVEL_DISABLED) {
                 return false;
             }
             if ($in_user_clone->GetUserLevel() == _USER_LEVEL_OBSERVER) {
                 return false;
             }
             if ($in_user_clone->GetID() == $this->GetID()) {
                 return true;
             }
             if (c_comdef_server::IsUserServerAdmin()) {
                 return true;
             }
             if (c_comdef_server::IsUserServiceBodyAdmin() && $this->GetOwnerID() == c_comdef_server::GetCurrentUserObj()->GetID()) {
                 return true;
             }
             $in_user_clone = null;
         }
         return $ret;
     }
Member Data Documentation
$_email_address_string
$_email_address_string = null private
A string, containing the user's email address.
Definition at line 77 of file c_comdef_user.class.php.
$_id_bigint
$_id_bigint = null private
An integer, containing the unique ID of this user.
Definition at line 45 of file c_comdef_user.class.php.
$_last_access
$_last_access = null private
A time date, indicating the last time the user was active. This will be useful for administration.
Definition at line 86 of file c_comdef_user.class.php.
$_login_string
$_login_string = null private
A string, containing the user's login ID.
Definition at line 80 of file c_comdef_user.class.php.
$_owner_id_bigint
$_owner_id_bigint = -1 private
An integer containing the id of the user that owns this user.
Definition at line 89 of file c_comdef_user.class.php.
$_password_string
$_password_string = null private
A string, containing the user's encrypted password.
Definition at line 83 of file c_comdef_user.class.php.
$_user_level_tinyint
$_user_level_tinyint = null private
An integer, containing the user level.
Values:
(1) Server Administrator -There can only be one. The user ID is always 1. This administrator can edit all aspects of the server.
(2) Service Body Administrator -There can only be one per Service Body A Service Body Administrator can edit all meetings from the Service Body that assigns the user as its administrator. This user can also assign other Service Body Administrators or Editors as users able to edit meetings belonging to the Service Body. A Service Body Administrator can also edit Service Body information. NOTE: A Service Body Administrator only has extra rights when assigned to a specific Service Body. If assigned as an Editor on another Service Body, they do not have rights beyond those of an Editor.
(3) Editor -There can be many. An Editor is assigned by a Service Body Administrator to edit meetings for that Service Body. They can only edit meetings; not users or Service Bodies. Making a user an editor (or a Service Body Administrator) doesn't automatically give them any rights. They must first be assigned to a Service Body, either by the Server Administrator (Service Body Administrators), or by a Service Body Administrator (Editors).
(4) User Disabled.
(5) Observer -There can be many. This user cannot make changes, but can see visibility 0 data items in meetings for the Service bodies to which it has been attached..
Definition at line 74 of file c_comdef_user.class.php.
The documentation for this class was generated from the following file:
/Volumes/Development/webroot/web_projects/BMLT-Root-Server/main_server/server/classes/c_comdef_user.class.php