INSERT INTO `%%PREFIX%%_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'B', NULL, 'BEG', 'fr', 'Débutants', 'Cette réunion est axée sur les besoins des nouveaux membres de NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'fr', 'bilingue', 'Cette réunion peut aider les personnes qui parlent l\'anglais et une autre langue.', 'FC3'),
(3, 'BT', NULL, 'BT', 'fr', 'Texte de Base', 'Cette réunion est axée sur la discussion du texte de base de Narcotiques Anonymes.', 'FC1'),
(4, 'C', NULL, 'CLOSED', 'fr', 'Fermée', 'Cette réunion est fermée aux non-toxicomanes. Vous pouvez y assister que si vous pensez que vous pouvez avoir un problème avec l\'abus de drogues.', 'O'),
(5, 'CH', NULL, NULL, 'fr', 'Fermé durant les jours fériés.', 'Cette réunion a lieu dans une local qui est généralement fermé durant les jours fériés.', 'FC3'),
(6, 'CL', NULL, 'CAN', 'fr', 'Chandelle', 'Cette réunion se déroule à la chandelle.', 'FC2'),
(7, 'CS', NULL, '', 'fr', 'Enfants sous Supervision', 'Les enfants bien élevés sont les bienvenus et supervisés.', 'FC3'),
(8, 'D', NULL, 'DISC', 'fr', 'Discussion', 'Cette réunion invite tous les participants à la discussion.', 'FC1'),
(10, 'GL', NULL, 'GL', 'fr', 'Gais, lesbiennes, transsexuel(le)s, bisexuel(le)s', 'Cette réunion est axée sur les besoins des membres gais, lesbiennes, transsexuel(le)s et bisexuel(le)s de NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'fr', 'Chroniques', 'Cette réunion est axée sur les besoins des membres de NA comportant des troubles de maladies chroniques.', 'FC1'),
(12, 'IP', NULL, 'IP', 'fr', 'Brochures', 'Cette réunion est axée sur la discussion d\'une ou plusieurs brochures.', 'FC1'),
(13, 'IW', NULL, 'IW', 'fr', 'Ça marche, Comment et Pourquoi', 'Cette session met l\'accent sur la discussion de texte Ça marche, Comment et Pourquoi.', 'FC1'),
(14, 'JT', NULL, 'JFT', 'fr', 'Juste pour aujourd\'hui', 'Cette session met l\'accent sur la discussion du texte Juste pour aujourd\'hui.', 'FC1'),
(15, 'M', NULL, 'M', 'fr', 'Hommes', 'Cette réunion est destinée à être assisté par seulement que des hommes.', 'FC3'),
(16, 'NC', NULL, NULL, 'fr', 'Pas d\'enfant', 'S\'il vous plaît, ne pas amener les enfants à cette réunion.', 'FC3'),
(17, 'O', NULL, 'OPEN', 'fr', 'Ouvert', 'Cette réunion est ouverte aux toxicomanes et non-toxicomanes de même. Tous sont les bienvenus.', 'O'),
(18, 'Pi', NULL, NULL, 'fr', 'À la pige', 'Cette réunion a un format de discussion est que chaque personne qui discute invite la personne suivante à discuter.', 'FC1'),
(19, 'RF', NULL, 'VAR', 'fr', 'Format varié', 'Cette réunion a un format qui varie à toutes les réunions.', 'FC1'),
(20, 'Rr', NULL, NULL, 'fr', 'À la ronde', 'Cette réunion a un ordre de partage fixe (généralement un cercle).', 'FC1'),
(21, 'SC', NULL, NULL, 'fr', 'Caméra de surveillance', 'Cette réunion se tient dans un emplacement qui a des caméras de surveillance.', 'FC2'),
(22, 'SD', NULL, 'SPK', 'fr', 'Partage et ouvert', 'Cette réunion a un conférencier, puis ouvert au public.', 'FC1'),
(23, 'SG', NULL, 'SWG', 'fr', 'Guides des Étapes', 'Cette réunion est axée sur la discussion sur le Guide des Étapes.', 'FC1'),
(24, 'SL', NULL, NULL, 'fr', 'Malentendants', 'Cette rencontre permet l\'interprète pour les personnes malentendantes.', 'FC2'),
(26, 'So', NULL, 'SPK', 'fr', 'Partage seulement', 'Cette réunion a seulement un conférencier. Les autres participants ne participent pas à la discussion.', 'FC1'),
(27, 'St', NULL, 'STEP', 'fr', 'Étapes NA', 'Cette réunion est axée sur la discussion des Douze Étapes de NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'fr', 'Discussion chronométrée', 'Cette réunion a une durée de discussion  limitée par une minuterie pour chaque personne.', 'FC1'),
(29, 'To', NULL, 'TOP', 'fr', 'Thématique', 'Cette réunion est basée sur un thème choisi par la personne qui anime ou la conscience de groupe.', 'FC1'),
(30, 'Tr', NULL, 'TRAD', 'fr', 'Traditions', 'Cette réunion est axée sur la discussion des Douze Traditions de NA.', 'FC1'),
(31, 'TW', NULL, 'TRAD', 'fr', 'Atelier sur les traditions', 'Cette réunion est une discussion détaillée d\'une ou de plusieurs des Douze Traditions de NA', 'FC1'),
(32, 'W', NULL, 'W', 'fr', 'Femmes', 'Seulement les femmes sont admises.', 'FC3'),
(33, 'WC', NULL, 'WCHR', 'fr', 'Fauteuil Roulant', 'Cette réunion est accessible en fauteuil roulant.', 'FC2'),
(34, 'YP', NULL, 'Y', 'fr', 'Jeunes', 'Cette réunion est axée sur les besoins des plus jeunes membres de NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'fr', 'Marathon', 'Il n\'y a pas de durée fixe. Cette réunion se poursuit jusqu\'à ce que chaque membre a eu l\'occasion de partager.', 'FC1'),
(36, 'BK', NULL, 'LIT', 'fr', 'Études de livres NA', 'Livres  N.A. Approuvés', 'FC1'),
(37, 'NS', NULL, 'NS', 'fr', 'Non-fumeurs', 'Fumer n\'est pas permis à cette réunion.', 'FC1'),
(38, 'Ag', NULL, NULL, 'fr', 'Agnostique', 'Destiné aux personnes ayant divers degrés de la foi.', 'FC1'),
(39, 'FD', NULL, NULL, 'fr', 'Cinq et dix', 'Discussion de la cinquième étape et la dixième étape.', 'FC1'),
(40, 'AB', NULL, 'QA', 'fr', 'Panier', 'Un sujet est choisi parmi les suggestions placées dans un panier.', 'FC1'),
(41, 'ME', NULL, 'MED', 'fr', 'Méditation', 'Cette réunion encourage ses participants à s\'engager dans la méditation tranquille.', 'FC1'),
(42, 'RA', NULL, 'RA', 'fr', 'Accés limités', 'Cet emplacement impose des restrictions sur les participants.', 'FC3'),
(43, 'QA', NULL, 'QA', 'fr', 'Questions et Réponses', 'Les participants peuvent poser des questions et attendre des réponses des membres du groupe.', 'FC1'),
(44, 'CW', NULL, 'CW', 'fr', 'Enfants bienvenus', 'Les enfants sont les bienvenus à cette réunion.', 'FC3'),
(45, 'CP', NULL, 'CPT', 'fr', 'Concepts', 'Cette réunion est axée sur la discussion des douze concepts de NA.', 'FC1'),
(46, 'Finlandais', NULL, NULL, 'fr', 'Finlandais', 'Cette réunion se déroule en langue finlandaisè', 'FC3'),
(47, 'ENG', NULL, NULL, 'fr', 'Anglais', 'Cette réunion se déroule de langues anglais.', 'FC3'),
(54, 'VM', NULL, 'VM', 'fr', 'Virtual Meeting', 'Meets Virtually', 'FC2'),
(55, 'TC', NULL, 'TC', 'fr', 'Temporarily Closed', 'Facility is Temporarily Closed', 'O'),
(56, 'HY', NULL,  'HYBR', 'fr', 'Hybrid Meeting', 'Meets Virtually and In-person', 'FC2');
