INSERT INTO `%%PREFIX%%_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'B', NULL, 'BEG', 'pl', 'Nowoprzybyli', 'Mityng koncentruje się na potrzebach nowyh członków NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'pl', 'Wielojęzykowość', 'Na tym mityngu mogą uczęszczać osoby posługujące się językiem angielskim i innymi.', 'FC3'),
(3, 'BT', NULL, 'BT', 'pl', 'Tekst Podstawowy', 'Mityng koncentruje się na dyskusjach o Tekście Podstawowym Anonimowych Narkomanów.', 'FC1'),
(4, 'C', NULL, 'CLOSED', 'pl', 'Mityng zamknięty', 'Mityng zamknięty. Wyłącznie dla osób uzależnionych i tych, które chcą przestać brać.', 'O'),
(5, 'CH', NULL, 'CH', 'pl', 'Zamknięty w święta', 'Mityng odbywa się w miejscu, które zwykle jest zamknięte w dni wolne od pracy/wakacje.', 'FC3'),
(6, 'CL', NULL, 'CAN', 'pl', 'Świeczka', 'Ten mityng odbywa się przy blasku świecy.', 'FC2'),
(7, 'CS', NULL, '', 'pl', 'Dzieci pod opieką', 'Dzieci uzależnionych mile widziane pod warunkiem odpowiedniego zachowania.', 'FC3'),
(8, 'D', NULL, 'DISC', 'pl', 'Dyskusja', 'Mityng dla wszystkich chętnych.', 'FC1'),
(9, 'ES', NULL, 'LANG', 'pl', 'Hiszpański', 'Mityng odbywa się w języku hiszpańskim.', 'FC3'),
(10, 'GL', NULL, 'GL', 'pl', 'LGBTQ', 'Mityng koncentruje się na członkach wspólnoty należących do społeczności LGBT.', 'FC3'),
(11, 'IL', NULL, NULL, 'pl', 'Choroba', 'Mityng koncentruje się na potrzebach przewlekle chorych członków NA.', 'FC1'),
(12, 'IP', NULL, 'IP', 'pl', 'Broszura Informacyjna', 'Mityng koncentruje się na dyskusji nad jedną z Broszur Międzynarodowych.', 'FC1'),
(13, 'IW', NULL, 'IW', 'pl', 'To Działa - Jak i Dlaczego', 'Mityng koncentruje się na dyskusji nad tekstem z "To Działa - Jak i Dlaczego".', 'FC1'),
(14, 'JT', NULL, 'JFT', 'pl', 'Właśnie Dzisiaj', 'Mityng koncentruje się na dyskusji nad tekstem z "Właśnie dzisiaj".', 'FC1'),
(15, 'M', NULL, 'M', 'pl', 'Mężczyźni', 'Mityng wyłącznie dla mężczyzn.', 'FC3'),
(16, 'NC', NULL, 'NC', 'pl', 'Bez Dzieci', 'Prosimy, by nie przyprowadzać dzieci na ten mityng.', 'FC3'),
(17, 'O', NULL, 'OPEN', 'pl', 'Otwarty', 'Mityng otwarty dla uzależnionych i nieuzależnionych. Wszyscy są mile widziani.', 'O'),
(18, 'Pi', NULL, NULL, 'pl', 'Pitch', 'Na tym mityngu obowiązuje format, w którym osoba, dzieląca się doświadczeniem, wybiera kolejną osobę.', 'FC1'),
(19, 'RF', NULL, 'VAR', 'pl', 'Zmienny format', 'Format tego mityngu zmienia się co mityng.', 'FC1'),
(20, 'Rr', NULL, NULL, 'pl', 'Round Robin', 'Na tym mityngu jest ustalona kolejność dzielenia się doświadczeniem (zwykle w koło)', 'FC1'),
(21, 'SC', NULL, NULL, 'pl', 'Kamery bezpieczeństwa', 'Mityng odbywa się w miejscu, w którym zamontowane są kamery bezpieczeństwa.', 'FC2'),
(22, 'SD', NULL, 'SPK', 'pl', 'Spikerka/dyskusja', 'Mityng rozpoczynany jest wypowiedzią spikera, a następnie jest otwarty do dzielenia się przez resztę uczestników.', 'FC1'),
(23, 'SG', NULL, 'SWG', 'pl', 'Przewodnik pracy nad Krokami', 'Mityng koncentruje się na dyskusji nad tekstem z "Przewodnika do pracy nad Krokami".', 'FC1'),
(24, 'SL', NULL, NULL, 'pl', 'ASL', 'W tym mityngu bierze udział tłumacz języka migowego dla osób niesłyszących.', 'FC2'),
(26, 'So', NULL, 'SPK', 'pl', 'Tylko spikerka', 'Mityng składa się tylko z wypowiedzi spikera. Inni uczestnicy nie dzielą się doświadczeniem.', 'FC1'),
(27, 'St', NULL, 'STEP', 'pl', 'Kroki', 'Mityng koncentruje się na dyskusji nad Dwunastoma Krokami Anonimowych Narkomanów.', 'FC1'),
(28, 'Ti', NULL, NULL, 'pl', 'Licznik czasu', 'Na tym mitngu czas wypowiedzi jest kontrolowany przez licznik czasu.', 'FC1'),
(29, 'To', NULL, 'TOP', 'pl', 'Dowolny temat', 'Temat tego mityngu jest wybierany przez spikera lub przez sumienie grupy.', 'FC1'),
(30, 'Tr', NULL, 'TRAD', 'pl', 'Tradycje', 'Mityng koncentruje się na dyskusji nad Dwunastoma Tradycjami NA.', 'FC1'),
(31, 'TW', NULL, 'TRAD', 'pl', 'Warsztaty z tradycji', 'Mityng koncentruje się na wnikliwej analizje jednej lub wielu z Dwunastu Tradycji Anonimowych Narkomanów', 'FC1'),
(32, 'W', NULL, 'W', 'pl', 'Kobiety', 'Mityng przeznaczony jedynie dla kobiet.', 'FC3'),
(33, 'WC', NULL, 'WCHR', 'pl', 'Wózki inwalidzkie', 'Mityng wyposażony w łatwy dostęp dla wózków inwalidzkich.', 'FC2'),
(34, 'YP', NULL, 'Y', 'pl', 'Młodzi ludzie', 'Mityng koncentruje się na dyskusjach nad potrzebami najmłodszych członków NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'pl', 'Bez końca', 'Mityng bez ustalonej długości. Trwa tak długo, jak długo są na nim uczestnicy.', 'FC1'),
(36, 'BK', NULL, 'LIT', 'pl', 'Analiza książek', 'Analiza oficjalnych książek Anonimowych Narkomanów', 'FC1'),
(37, 'NS', NULL, 'NS', 'pl', 'Zakac palenia', 'Palenie w trakcie tego mityngu jest zabronione.', 'FC1'),
(38, 'Ag', NULL, NULL, 'pl', 'Agnostycy', 'Mityng dla ludzi o zróżnicowanych stopniach wiary.', 'FC1'),
(39, 'FD', NULL, NULL, 'pl', 'Piąty i dziesiąty krok', 'Dyskusja nad piątym i dziesiątym krokiem Anonimowych Narkomanów', 'FC1'),
(40, 'AB', NULL, 'QA', 'pl', 'Temat z koszyka', 'Temat mityngu wybierany jest spośród zaproponowanych niejawnie przez grupę.', 'FC1'),
(41, 'ME', NULL, 'MED', 'pl', 'Medytacja', 'Uczestnicy tego mityngu zachęcani są do wzięcia udziału w cichej medytacji.', 'FC1'),
(42, 'RA', NULL, 'RA', 'pl', 'Ograniczone uczestnictwo', 'Miejsce odbywania się mityngu nakłada ograniczenia na to, kto może wziąć udział w mityngu.', 'FC3'),
(43, 'QA', NULL, 'QA', 'pl', 'Pytania i odpowiedzi', 'Uczestnicy mogą zadawać pytania i oczekiwać odpowiedzi od innych uczestników.', 'FC1'),
(44, 'CW', NULL, 'CW', 'pl', 'Dzieci mile widziane', 'Dzieci są mile widziane.', 'FC3'),
(45, 'CP', NULL, 'CPT', 'pl', 'Koncepcje', 'Mityng koncentruje się na dyskusji nad Dwunastoma Koncepcjami Anonimowych Narkomanów.', 'FC1'),
(46, 'FIN', NULL, NULL, 'pl', 'Fiński', 'Mityng odbywa się w języku fińskim', 'FC3'),
(47, 'ENG', NULL, NULL, 'pl', 'Anglojęzyczny', 'Mityng odbywa się w języku angielskim.', 'FC3'),
(48, 'PER', NULL, NULL, 'pl', 'Perski', 'Mityng odbywa się w języku perskim', 'FC1'),
(49, 'L/R', NULL, NULL, 'pl', 'Litewski/rosyjski', 'Mityng odbywa się w języku litewskim/rosyjskim', 'FC1'),
(50, 'WEB', NULL, NULL, 'pl', 'Mityng onlina', 'Mityng odbywa się on-line.', 'FC2'),
(51, 'LC', NULL, 'LC', 'pl', 'Życie w czystości', 'Mityng koncentruje się na dyskusji nad tekstem z "Życie w czystości: Podróż trwa nadal".', 'FC1'),
(52, 'GP', NULL, 'GP', 'pl', 'Guiding Principles', 'Mityng koncentruje się na dyskusji nad tekstem z "Guiding Principles - The Spirit of Our Traditions".', 'FC1'),
(53, 'VM', NULL, 'VM', 'pl', 'Virtual Meeting', 'This is a meeting that meets online.', 'FC2'),
(54, 'TC', NULL, 'TC', 'pl', 'Temporarily Closed', '**** Temporarily Closed ****', 'O');