INSERT INTO `%%PREFIX%%_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'B', NULL, NULL, 'en', 'Beginners', 'This meeting is focused on the needs of new members of NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'en', 'Bi-Lingual', 'This Meeting can be attended by speakers of English and another language.', 'FC3'),
(3, 'BT', NULL, NULL, 'en', 'Basic Text', 'This meeting is focused on discussion of the Basic Text of Narcotics Anonymous.', 'FC1'),
(4, 'C', NULL, NULL, 'en', 'Closed', 'This meeting is closed to non-addicts. You should attend only if you believe that you may have a problem with substance abuse.', 'FC3'),
(5, 'CH', NULL, NULL, 'en', 'Closed Holidays', 'This meeting gathers in a facility that is usually closed on holidays.', 'FC3'),
(6, 'CL', NULL, NULL, 'en', 'Candlelight', 'This meeting is held by candlelight.', 'FC2'),
(7, 'CS', NULL, NULL, 'en', 'Children under Supervision', 'Well-behaved, supervised children are welcome.', 'FC3'),
(8, 'D', NULL, NULL, 'en', 'Discussion', 'This meeting invites participation by all attendees.', 'FC1'),
(9, 'ES', NULL, NULL, 'en', 'Espanol', 'This meeting can be attended by speakers of Spanish.', 'FC3'),
(10, 'GL', NULL, NULL, 'en', 'Gay/Lesbian/Transgender', 'This meeting is focused on the needs of gay, lesbian and transgender members of NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'en', 'Illness', 'This meeting is focused on the needs of NA members with chronic illness.', 'FC1'),
(12, 'IP', NULL, NULL, 'en', 'Informational Pamphlet', 'This meeting is focused on discussion of one or more Informational Pamphlets.', 'FC1'),
(13, 'IW', NULL, NULL, 'en', 'It Works -How and Why', 'This meeting is focused on discussion of the It Works -How and Why text.', 'FC1'),
(14, 'JT', NULL, NULL, 'en', 'Just for Today', 'This meeting is focused on discussion of the Just For Today text.', 'FC1'),
(15, 'M', NULL, NULL, 'en', 'Men', 'This meeting is meant to be attended by men only.', 'FC3'),
(16, 'NC', NULL, NULL, 'en', 'No Children', 'Please do not bring children to this meeting.', 'FC3'),
(17, 'O', NULL, NULL, 'en', 'Open', 'This meeting is open to addicts and non-addicts alike. All are welcome.', 'FC3'),
(18, 'Pi', NULL, NULL, 'en', 'Pitch', 'This meeting has a format that consists of each person who shares picking the next person.', 'FC1'),
(19, 'RF', NULL, NULL, 'en', 'Rotating Format', 'This meeting has a format that changes for each meeting.', 'FC1'),
(20, 'Rr', NULL, NULL, 'en', 'Round Robin', 'This meeting has a fixed sharing order (usually a circle.)', 'FC1'),
(21, 'SC', NULL, NULL, 'en', 'Surveillance Cameras', 'This meeting is held in a facility that has surveillance cameras.', 'FC2'),
(22, 'SD', NULL, NULL, 'en', 'Speaker/Discussion', 'This meeting is lead by a speaker, then opened for participation by attendees.', 'FC1'),
(23, 'SG', NULL, NULL, 'en', 'Step Working Guide', 'This meeting is focused on discussion of the Step Working Guide text.', 'FC1'),
(24, 'SL', NULL, NULL, 'en', 'ASL', 'This meeting provides an American Sign Language (ASL) interpreter for the deaf.', 'FC2'),
(25, 'Sm', NULL, NULL, 'en', 'Smoking Permitted', 'Smoking (of tobacco) is permitted at this meeting.', 'FC2'),
(26, 'So', NULL, NULL, 'en', 'Speaker Only', 'This meeting is a speaker-only meeting. Other attendees do not participate in the discussion.', 'FC1'),
(27, 'St', NULL, NULL, 'en', 'Step', 'This meeting is focused on discussion of the Twelve Steps of NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'en', 'Timer', 'This meeting has sharing time limited by a timer.', 'FC1'),
(29, 'To', NULL, NULL, 'en', 'Topic', 'This meeting is based upon a topic chosen by a speaker or by group conscience.', 'FC1'),
(30, 'Tr', NULL, NULL, 'en', 'Tradition', 'This meeting is focused on discussion of the Twelve Traditions of NA.', 'FC1'),
(31, 'TW', NULL, NULL, 'en', 'Traditions Workshop', 'This meeting engages in detailed discussion of one or more of the Twelve Traditions of N.A.', 'FC1'),
(32, 'W', NULL, NULL, 'en', 'Women', 'This meeting is meant to be attended by women only.', 'FC3'),
(33, 'WC', NULL, NULL, 'en', 'Wheelchair', 'This meeting is wheelchair accessible.', 'FC2'),
(34, 'YP', NULL, NULL, 'en', 'Young People', 'This meeting is focused on the needs of younger members of NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'en', 'Open-Ended', 'No fixed duration. The meeting continues until everyone present has had a chance to share.', 'FC1'),
(36, 'BK', NULL, NULL, 'en', 'Book Study', 'Approved N.A. Books', 'FC1'),
(37, 'NS', NULL, NULL, 'en', 'No Smoking', 'Smoking is not allowed at this meeting.', 'FC1'),
(38, 'Ag', NULL, NULL, 'en', 'Agnostic', 'Intended for people with varying degrees of Faith.', 'FC1'),
(39, 'FD', NULL, NULL, 'en', 'Five and Dime', 'Discussion of the Fifth Step and the Tenth Step', 'FC1'),
(40, 'AB', NULL, NULL, 'en', 'Ask-It-Basket', 'A topic is chosen from suggestions placed into a basket.', 'FC1'),
(41, 'ME', NULL, NULL, 'en', 'Meditation', 'This meeting encourages its participants to engage in quiet meditation.', 'FC1'),
(42, 'RA', NULL, NULL, 'en', 'Restricted Attendance', 'This facility places restrictions on attendees.', 'FC3'),
(43, 'QA', NULL, NULL, 'en', 'Question and Answer', 'Attendees may ask questions and expect answers from Group members.', 'FC1'),
(44, 'CW', NULL, NULL, 'en', 'Children Welcome', 'Children are welcome at this meeting.', 'FC3'),
(45, 'CP', NULL, NULL, 'en', 'Concepts', 'This meeting is focused on discussion of the twelve concepts of NA.', 'FC1'),
(46, 'FIN', NULL, NULL, 'en', 'Finish', 'finish speaking meeting', 'FC3'),
(47, 'ENG', NULL, NULL, 'en', 'English speaking', 'This Meeting can be attended by speakers of English.', 'FC3'),
(48, 'PER', NULL, NULL, 'en', 'Persian', 'Persian speeking meeting', 'FC1'),
(50, 'WEB', NULL, NULL, 'en', 'Online Meeting', 'This is a meeting that gathers on the Internet.', 'FC2'),

(1, 'B', NULL, NULL, 'es', 'Para el recién llegado', 'Esta reunión se centra en las necesidades de los nuevos miembros de NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'es', 'Bilingüe', 'Esta reunión se pueden asistir personas de que hablen inglés y otro idioma.', 'FC3'),
(3, 'BT', NULL, NULL, 'es', 'Texto Básico', 'Esta reunión se centra en la discusión del texto básico de Narcóticos Anónimos.', 'FC1'),
(4, 'C', NULL, NULL, 'es', 'Cerrado', 'Esta reunión está cerrada a los no adictos. Usted debe asistir solamente si cree que puede tener un problema con abuso de drogas.', 'FC3'),
(5, 'CH', NULL, NULL, 'es', 'Cerrado en Días de fiesta', 'Esta reunión tiene lugar en una localidad que esta generalmente cerrada los días de fiesta.', 'FC3'),
(6, 'CL', NULL, NULL, 'es', 'Luz de vela', 'Esta reunión se celebra a luz de vela.', 'FC2'),
(7, 'CS', NULL, NULL, 'es', 'Niños bajo Supervisión', 'Los niños de buen comportamiento y supervisados son bienvenidos.', 'FC3'),
(8, 'D', NULL, NULL, 'es', 'Discusión', 'Esta reunión invita la participación de todos los asistentes.', 'FC1'),
(9, 'ES', NULL, NULL, 'es', 'Español', 'A esta reunión pueden asistir personas que hablen español.', 'FC3'),
(10, 'GL', NULL, NULL, 'es', 'Gay/Lesbiana', 'Esta reunión se centra en las necesidades de miembros gay y lesbianas de NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'es', 'Enfermedad', 'Esta reunión se centra en las necesidades de los miembros de NA con enfermedades crónicas.', 'FC1'),
(12, 'IP', NULL, NULL, 'es', 'Folleto Informativo', 'Esta reunión se centra en la discusión de unos o más folletos informativos.', 'FC1'),
(13, 'IW', NULL, NULL, 'es', 'Functiona - Cómo y Porqué', 'Esta reunión se centra en la discusión del texto Funciona - Cómo y Porqué.', 'FC1'),
(14, 'JT', NULL, NULL, 'es', 'Solo por Hoy', 'Esta reunión se centra en la discusión del texto Solo por Hoy.', 'FC1'),
(15, 'M', NULL, NULL, 'es', 'Hombres', 'A esta reunión se supone que aistan hombres solamente.', 'FC3'),
(16, 'NC', NULL, NULL, 'es', 'No niños', 'Por favor no traer niños a esta reunión.', 'FC3'),
(17, 'O', NULL, NULL, 'es', 'Abierta', 'Esta reunión está abierta a los adictos y a los no adictos por igual. Todos son bienvenidos.', 'FC3'),
(18, 'Pi', NULL, NULL, 'es', 'Echada', 'Esta reunión tiene un formato que consiste en que cada persona que comparta escoja a la persona siguiente.', 'FC1'),
(19, 'RF', NULL, NULL, 'es', 'Formato que Rota', 'Esta reunión tiene un formato que cambia para cada reunión.', 'FC1'),
(20, 'Rr', NULL, NULL, 'es', 'Round Robin', 'Esta reunión tiene un orden fijo de compartir (generalmente un círculo).', 'FC1'),
(21, 'SC', NULL, NULL, 'es', 'Cámaras de Vigilancia', 'Esta reunión se celebra en una localidad que tenga cámaras de vigilancia.', 'FC2'),
(22, 'SD', NULL, NULL, 'es', 'Orador/Discusión', 'Esta reunión es conducida por un orador, después es abierta para la participación de los asistentes.', 'FC1'),
(23, 'SG', NULL, NULL, 'es', 'Guia Para Trabajar los Pasos', 'Esta reunión se centra en la discusión del texto Guia Para Trabajar los Pasos.', 'FC1'),
(24, 'SL', NULL, NULL, 'es', 'ASL', 'Esta reunión proporciona intérprete (ASL) para los sordos.', 'FC2'),
(25, 'Sm', NULL, NULL, 'es', 'Permitido Fumar', 'El fumar (tabaco) es permitido en esta reunión.', 'FC2'),
(26, 'So', NULL, NULL, 'es', 'Solamente Orador', 'Esta reunión es de orador solamente. Otros asistentes no participan en la discusión.', 'FC1'),
(27, 'St', NULL, NULL, 'es', 'Paso', 'Esta reunión se centra en la discusión de los doce pasos de NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'es', 'Contador de Tiempo', 'Esta reunión tiene el tiempo de compartir limitado por un contador de tiempo.', 'FC1'),
(29, 'To', NULL, NULL, 'es', 'Tema', 'Esta reunión se basa en un tema elegido por el orador o por la conciencia del grupo.', 'FC1'),
(30, 'Tr', NULL, NULL, 'es', 'Tradición', 'Esta reunión se centra en la discusión de las Doce Tradiciones de NA.', 'FC1'),
(31, 'TW', NULL, NULL, 'es', 'Taller de las Tradiciones', 'Esta reunión consiste en la discusión detallada de una o más de las Doce Tradiciones de N.A.', 'FC1'),
(32, 'W', NULL, NULL, 'es', 'Mujeres', 'A esta reunión se supone que asistan mujeres solamente.', 'FC3'),
(33, 'WC', NULL, NULL, 'es', 'Silla de Ruedas', 'Esta reunión es accesible por silla de ruedas.', 'FC2'),
(34, 'YP', NULL, NULL, 'es', 'Jovenes', 'Esta reunión se centra en las necesidades de los miembros más jóvenes de NA.', 'FC1'),
(35, 'OE', NULL, NULL, 'es', 'Sin Tiempo Fijo', 'No tiene tiempo fijo. Esta reunión continua hasta que cada miembro haya tenido la oportunidad de compartir.', 'FC1'),

(4, 'S', NULL, NULL, 'sv', 'Slutet möte', 'Slutet möte är för de individer som identifierar sig som beroende eller för de som är osäkra och tror att de kanske har drogproblem.', 'FC3'),
(9, 'ESP', NULL, NULL, 'sv', 'Spanska', 'Spansktalande möte', 'FC3'),
(15, 'M', NULL, NULL, 'sv', 'Mansmöte', 'Detta möte är endast öppet för män.', 'FC3'),
(17, 'Ö', NULL, NULL, 'sv', 'Öppet möte', 'Ett öppet möte är ett NA-möte där vem som helst som är intresserad av hur vi har funnit tillfrisknande från beroendesjukdomen kan närvara.', 'FC3'),
(32, 'K', NULL, NULL, 'sv', 'Kvinnomöte', 'Detta möte är endast öppet för kvinnor.', 'FC3'),
(33, 'RL', NULL, NULL, 'sv', 'Rullstolsvänlig lokal', 'Detta möte är tillgängligt för rullstolsbundna.', 'FC2'),
(47, 'ENG', NULL, NULL, 'sv', 'Engelska', 'Engelsktalande möte', 'FC3'),
(48, 'PER', NULL, NULL, 'sv', 'Persiskt', 'Persiskt möte', 'FC1'),
(49, 'L/R', NULL, NULL, 'sv', 'Lithuanian/Russian', 'Lithuanian/Russian Speaking Meeting', 'FC1'),
(50, 'WEB', NULL, NULL, 'sv', 'Online m?te', 'M?te p? internet.', 'FC2'),

(1, 'B', NULL, NULL, 'fr', 'Débutants', 'Cette réunion est axée sur les besoins des nouveaux membres de NA.\r\n', 'FC3'),
(2, 'BL', NULL, NULL, 'fr', 'bilingue', 'Cette réunion peut aider les personnes qui parlent l''anglais et une autre langue.', 'FC3'),
(3, 'BT', NULL, NULL, 'fr', 'Texte de Base', 'Cette réunion est axée sur la discussion du texte de base de Narcotiques Anonymes.', 'FC1'),
(4, 'C', NULL, NULL, 'fr', 'Fermée', 'Cette réunion est fermée aux non-toxicomanes. Vous pouvez y assister que si vous pensez que vous pouvez avoir un problème avec l''abus de drogues.', 'FC3'),
(5, 'CH', NULL, NULL, 'fr', 'Fermé durant les jours fériés.', 'Cette réunion a lieu dans une local qui est généralement fermé durant les jours fériés.', 'FC3'),
(6, 'CL', NULL, NULL, 'fr', 'Chandelle', 'Cette réunion se déroule à la chandelle.', 'FC2'),
(7, 'CS', NULL, NULL, 'fr', 'Enfants sous Supervision', 'Les enfants bien élevés sont les bienvenus et supervisés.', 'FC3'),
(8, 'D', NULL, NULL, 'fr', 'Discussion', 'Cette réunion invite tous les participants à la discussion.', 'FC1'),
(10, 'GL', NULL, NULL, 'fr', 'Gais, lesbiennes, transsexuel(le)s, bisexuel(le)s', 'Cette réunion est axée sur les besoins des membres gais, lesbiennes, transsexuel(le)s et bisexuel(le)s de NA.\r\n', 'FC3'),
(11, 'IL', NULL, NULL, 'fr', 'Chroniques', 'Cette réunion est axée sur les besoins des membres de NA comportant des troubles de maladies chroniques.', 'FC1'),
(12, 'IP', NULL, NULL, 'fr', 'Brochures', 'Cette réunion est axée sur la discussion d''une ou plusieurs brochures.', 'FC1'),
(13, 'IW', NULL, NULL, 'fr', 'Ça marche, Comment et Pourquoi', 'Cette session met l''accent sur la discussion de texte Ça marche, Comment et Pourquoi.', 'FC1'),
(14, 'JT', NULL, NULL, 'fr', 'Juste pour aujourd''hui', 'Cette session met l''accent sur la discussion du texte Juste pour aujourd''hui.', 'FC1'),
(15, 'M', NULL, NULL, 'fr', 'Hommes', 'Cette réunion est destinée à être assisté par seulement que des hommes.', 'FC3'),
(16, 'NC', NULL, NULL, 'fr', 'Pas d''enfant', 'S''il vous plaît, ne pas amener les enfants à cette réunion.', 'FC3'),
(17, 'O', NULL, NULL, 'fr', 'Ouvert', 'Cette réunion est ouverte aux toxicomanes et non-toxicomanes de même. Tous sont les bienvenus.', 'FC3'),
(18, 'Pi', NULL, NULL, 'fr', 'À la pige\r\n', 'Cette réunion a un format de discussion est que chaque personne qui discute invite la personne suivante à discuter.', 'FC1'),
(19, 'RF', NULL, NULL, 'fr', 'Format varié', 'Cette réunion a un format qui varie à toutes les réunions.', 'FC1'),
(20, 'Rr', NULL, NULL, 'fr', 'À la ronde', 'Cette réunion a un ordre de partage fixe (généralement un cercle).', 'FC1'),
(21, 'SC', NULL, NULL, 'fr', 'Caméra de surveillance', 'Cette réunion se tient dans un emplacement qui a des caméras de surveillance.', 'FC2'),
(22, 'SD', NULL, NULL, 'fr', 'Partage et ouvert', 'Cette réunion a un conférencier, puis ouvert au public.', 'FC1'),
(23, 'SG', NULL, NULL, 'fr', 'Guides des Étapes', 'Cette réunion est axée sur la discussion sur le Guide des Étapes.', 'FC1'),
(24, 'SL', NULL, NULL, 'fr', 'Malentendants', 'Cette rencontre permet l''interprète pour les personnes malentendantes.', 'FC2'),
(26, 'So', NULL, NULL, 'fr', 'Partage seulement', 'Cette réunion a seulement un conférencier. Les autres participants ne participent pas à la discussion.', 'FC1'),
(27, 'St', NULL, NULL, 'fr', 'Étapes NA', 'Cette réunion est axée sur la discussion des Douze Étapes de NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'fr', 'Discussion chronométrée', 'Cette réunion a une durée de discussion  limitée par une minuterie pour chaque personne.', 'FC1'),
(29, 'To', NULL, NULL, 'fr', 'Thématique', 'Cette réunion est basée sur un thème choisi par la personne qui anime ou la conscience de groupe.', 'FC1'),
(30, 'Tr', NULL, NULL, 'fr', 'Traditions', 'Cette réunion est axée sur la discussion des Douze Traditions de NA.', 'FC1'),
(31, 'TW', NULL, NULL, 'fr', 'Atelier sur les traditions', 'Cette réunion est une discussion détaillée d''une ou de plusieurs des Douze Traditions de NA\r\n', 'FC1'),
(32, 'W', NULL, NULL, 'fr', 'Femmes', 'Seulement les femmes sont admises.', 'FC3'),
(33, 'WC', NULL, NULL, 'fr', 'Fauteuil Roulant', 'Cette réunion est accessible en fauteuil roulant.', 'FC2'),
(34, 'YP', NULL, NULL, 'fr', 'Jeunes', 'Cette réunion est axée sur les besoins des plus jeunes membres de NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'fr', 'Marathon', 'Il n''y a pas de durée fixe. Cette réunion se poursuit jusqu''à ce que chaque membre a eu l''occasion de partager.', 'FC1'),
(36, 'BK', NULL, NULL, 'fr', 'Études de livres NA', 'Livres  N.A. Approuvés', 'FC1'),
(37, 'NS', NULL, NULL, 'fr', 'Non-fumeurs', 'Fumer n''est pas permis à cette réunion.', 'FC1'),
(38, 'Ag', NULL, NULL, 'fr', 'Agnostique', 'Destiné aux personnes ayant divers degrés de la foi.', 'FC1'),
(39, 'FD', NULL, NULL, 'fr', 'Cinq et dix', 'Discussion de la cinquième étape et la dixième étape.', 'FC1'),
(40, 'AB', NULL, NULL, 'fr', 'Panier', 'Un sujet est choisi parmi les suggestions placées dans un panier.', 'FC1'),
(41, 'ME', NULL, NULL, 'fr', 'Méditation', 'Cette réunion encourage ses participants à s''engager dans la méditation tranquille.', 'FC1'),
(42, 'RA', NULL, NULL, 'fr', 'Accés limités', 'Cet emplacement impose des restrictions sur les participants.', 'FC3'),
(43, 'QA', NULL, NULL, 'fr', 'Questions et Réponses', 'Les participants peuvent poser des questions et attendre des réponses des membres du groupe.', 'FC1'),
(44, 'CW', NULL, NULL, 'fr', 'Enfants bienvenus', 'Les enfants sont les bienvenus à cette réunion.', 'FC3'),
(45, 'CP', NULL, NULL, 'fr', 'Concepts', 'Cette réunion est axée sur la discussion des douze concepts de NA.', 'FC1'),
(46, 'Finlandais', NULL, NULL, 'fr', 'Finlandais', 'Cette réunion se déroule en langue finlandaisè', 'FC3'),
(47, 'ENG', NULL, NULL, 'fr', 'Anglais', 'Cette réunion se déroule de langues anglais.', 'FC3'),
(50, 'WEB', NULL, NULL, 'fr', 'Internet', 'Il s''agit d''une réunion qui se déroule sur Internet.', 'FC2');
