INSERT INTO `%%PREFIX%%_comdef_meetings_data` (`meetingid_bigint`, `key`, `field_prompt`, `lang_enum`, `visibility`, `data_string`, `data_bigint`, `data_double`) VALUES
(0, 'meeting_name', 'Meeting Name', 'en', NULL, 'Meeting Name', NULL, NULL),
(0, 'location_text', 'Location Name', 'en', NULL, 'Location Name', NULL, NULL),
(0, 'location_info', 'Additional Location Information', 'en', NULL, 'Additional Location Information', NULL, NULL),
(0, 'location_street', 'Street Address', 'en', NULL, 'Street Address', NULL, NULL),
(0, 'location_city_subsection', 'Borough', 'en', NULL, 'Borough', NULL, NULL),
(0, 'location_neighborhood', 'Neighborhood', 'en', NULL, 'Neighborhood', NULL, NULL),
(0, 'location_municipality', 'Town', 'en', NULL, 'Town', NULL, NULL),
(0, 'location_sub_province', 'County', 'en', NULL, 'County', NULL, NULL),
(0, 'location_province', 'State', 'en', NULL, 'State', NULL, NULL),
(0, 'location_postal_code_1', 'Zip Code', 'en', NULL, NULL, 0, NULL),
(0, 'location_nation', 'Nation', 'en', NULL, 'Nation', NULL, NULL),
(0, 'comments', 'Comments', 'en', NULL, 'Comments', NULL, NULL),
(0, 'train_lines', 'Train Lines', 'en', NULL, NULL, NULL, NULL),
(0, 'bus_lines', 'Bus Lines', 'en', NULL, NULL, NULL, NULL),
(0, 'contact_phone_2', 'Contact 2 Phone', 'en', 1, 'Contact 2 Phone', NULL, NULL),
(0, 'contact_email_2', 'Contact 2 Email', 'en', 1, 'Contact 2 Email', NULL, NULL),
(0, 'contact_name_2', 'Contact 2 Name', 'en', 1, 'Contact 2 Name', NULL, NULL),
(0, 'contact_phone_1', 'Contact 1 Phone', 'en', 1, 'Contact 1 Phone', NULL, NULL),
(0, 'contact_email_1', 'Contact 1 Email', 'en', 1, 'Contact 1 Email', NULL, NULL),
(0, 'contact_name_1', 'Contact 1 Name', 'en', 1, 'Contact 1 Name', NULL, NULL)
(0, 'phone_meeting_link', 'Phone Link', 'en', NULL, NULL, NULL, NULL),
(0, 'virtual_meeting_link', 'Virtual Link', 'en', NULL, NULL, NULL, NULL);
