INSERT INTO `%%PREFIX%%_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'B', NULL, 'BEG', 'en', 'Beginners', 'This meeting is focused on the needs of new members of NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'en', 'Bi-Lingual', 'This Meeting can be attended by speakers of English and another language.', 'FC3'),
(3, 'BT', NULL, 'BT', 'en', 'Basic Text', 'This meeting is focused on discussion of the Basic Text of Narcotics Anonymous.', 'FC1'),
(4, 'C', NULL, 'CLOSED', 'en', 'Closed', 'This meeting is closed to non-addicts. You should attend only if you believe that you may have a problem with substance abuse.', 'O'),
(5, 'CH', NULL, 'CH', 'en', 'Closed Holidays', 'This meeting gathers in a facility that is usually closed on holidays.', 'FC3'),
(6, 'CL', NULL, 'CAN', 'en', 'Candlelight', 'This meeting is held by candlelight.', 'FC2'),
(7, 'CS', NULL, '', 'en', 'Children under Supervision', 'Well-behaved, supervised children are welcome.', 'FC3'),
(8, 'D', NULL, 'DISC', 'en', 'Discussion', 'This meeting invites participation by all attendees.', 'FC1'),
(9, 'ES', NULL, 'LANG', 'en', 'Español', 'This meeting is conducted in Spanish.', 'FC3'),
(10, 'GL', NULL, 'GL', 'en', 'Gay/Lesbian/Transgender', 'This meeting is focused on the needs of gay, lesbian and transgender members of NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'en', 'Illness', 'This meeting is focused on the needs of NA members with chronic illness.', 'FC1'),
(12, 'IP', NULL, 'IP', 'en', 'Informational Pamphlet', 'This meeting is focused on discussion of one or more Informational Pamphlets.', 'FC1'),
(13, 'IW', NULL, 'IW', 'en', 'It Works -How and Why', 'This meeting is focused on discussion of the It Works -How and Why text.', 'FC1'),
(14, 'JT', NULL, 'JFT', 'en', 'Just for Today', 'This meeting is focused on discussion of the Just For Today text.', 'FC1'),
(15, 'M', NULL, 'M', 'en', 'Men', 'This meeting is meant to be attended by men only.', 'FC3'),
(16, 'NC', NULL, 'NC', 'en', 'No Children', 'Please do not bring children to this meeting.', 'FC3'),
(17, 'O', NULL, 'OPEN', 'en', 'Open', 'This meeting is open to addicts and non-addicts alike. All are welcome.', 'O'),
(18, 'Pi', NULL, NULL, 'en', 'Pitch', 'This meeting has a format that consists of each person who shares picking the next person.', 'FC1'),
(19, 'RF', NULL, 'VAR', 'en', 'Rotating Format', 'This meeting has a format that changes for each meeting.', 'FC1'),
(20, 'Rr', NULL, NULL, 'en', 'Round Robin', 'This meeting has a fixed sharing order (usually a circle.)', 'FC1'),
(21, 'SC', NULL, NULL, 'en', 'Surveillance Cameras', 'This meeting is held in a facility that has surveillance cameras.', 'FC2'),
(22, 'SD', NULL, 'SPK', 'en', 'Speaker/Discussion', 'This meeting is lead by a speaker, then opened for participation by attendees.', 'FC1'),
(23, 'SG', NULL, 'SWG', 'en', 'Step Working Guide', 'This meeting is focused on discussion of the Step Working Guide text.', 'FC1'),
(24, 'SL', NULL, NULL, 'en', 'ASL', 'This meeting provides an American Sign Language (ASL) interpreter for the deaf.', 'FC2'),
(26, 'So', NULL, 'SPK', 'en', 'Speaker Only', 'This meeting is a speaker-only meeting. Other attendees do not participate in the discussion.', 'FC1'),
(27, 'St', NULL, 'STEP', 'en', 'Step', 'This meeting is focused on discussion of the Twelve Steps of NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'en', 'Timer', 'This meeting has sharing time limited by a timer.', 'FC1'),
(29, 'To', NULL, 'TOP', 'en', 'Topic', 'This meeting is based upon a topic chosen by a speaker or by group conscience.', 'FC1'),
(30, 'Tr', NULL, 'TRAD', 'en', 'Tradition', 'This meeting is focused on discussion of the Twelve Traditions of NA.', 'FC1'),
(31, 'TW', NULL, 'TRAD', 'en', 'Traditions Workshop', 'This meeting engages in detailed discussion of one or more of the Twelve Traditions of N.A.', 'FC1'),
(32, 'W', NULL, 'W', 'en', 'Women', 'This meeting is meant to be attended by women only.', 'FC3'),
(33, 'WC', NULL, 'WCHR', 'en', 'Wheelchair', 'This meeting is wheelchair accessible.', 'FC2'),
(34, 'YP', NULL, 'Y', 'en', 'Young People', 'This meeting is focused on the needs of younger members of NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'en', 'Open-Ended', 'No fixed duration. The meeting continues until everyone present has had a chance to share.', 'FC1'),
(36, 'BK', NULL, 'LIT', 'en', 'Book Study', 'Approved N.A. Books', 'FC1'),
(37, 'NS', NULL, 'NS', 'en', 'No Smoking', 'Smoking is not allowed at this meeting.', 'FC1'),
(38, 'Ag', NULL, NULL, 'en', 'Agnostic', 'Intended for people with varying degrees of Faith.', 'FC1'),
(39, 'FD', NULL, NULL, 'en', 'Five and Dime', 'Discussion of the Fifth Step and the Tenth Step', 'FC1'),
(40, 'AB', NULL, 'QA', 'en', 'Ask-It-Basket', 'A topic is chosen from suggestions placed into a basket.', 'FC1'),
(41, 'ME', NULL, 'MED', 'en', 'Meditation', 'This meeting encourages its participants to engage in quiet meditation.', 'FC1'),
(42, 'RA', NULL, 'RA', 'en', 'Restricted Attendance', 'This facility places restrictions on attendees.', 'FC3'),
(43, 'QA', NULL, 'QA', 'en', 'Question and Answer', 'Attendees may ask questions and expect answers from Group members.', 'FC1'),
(44, 'CW', NULL, 'CW', 'en', 'Children Welcome', 'Children are welcome at this meeting.', 'FC3'),
(45, 'CP', NULL, 'CPT', 'en', 'Concepts', 'This meeting is focused on discussion of the twelve concepts of NA.', 'FC1'),
(46, 'FIN', NULL, NULL, 'en', 'Finnish', 'finnish speaking meeting', 'FC3'),
(47, 'ENG', NULL, NULL, 'en', 'English speaking', 'This Meeting can be attended by speakers of English.', 'FC3'),
(48, 'PER', NULL, NULL, 'en', 'Persian', 'Persian speeking meeting', 'FC1'),
(49, 'L/R', NULL, NULL, 'en', 'Lithuanian/Russian', 'Lithuanian/Russian Speaking Meeting', 'FC1'),
(50, 'WEB', NULL, NULL, 'en', 'Online Meeting', 'This is a meeting that gathers on the Internet.', 'FC2'),
(51, 'LC', NULL, 'LC', 'en', 'Living Clean', 'This is a discussion of the NA book Living Clean -The Journey Continues.', 'FC1'),
(52, 'GP', NULL, 'GP', 'en', 'Guiding Principles', 'This is a discussion of the NA book Guiding Principles - The Spirit of Our Traditions.', 'FC1'),
(54, 'VM', NULL, 'VM', 'en', 'Virtual Meeting', 'This is a meeting that meets online.', 'FC2'),
(55, 'TC', NULL, 'TC', 'en', 'Temporarily Closed', '**** Temporarily Closed ****', 'O');
