INSERT INTO `%%PREFIX%%_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'B', NULL, 'BEG', 'en', 'Beginners', 'This meeting is focused on the needs of new members of NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'en', 'Bi-Lingual', 'This Meeting can be attended by speakers of English and another language.', 'FC3'),
(3, 'BT', NULL, 'BT', 'en', 'Basic Text', 'This meeting is focused on discussion of the Basic Text of Narcotics Anonymous.', 'FC1'),
(4, 'C', NULL, 'CLOSED', 'en', 'Closed', 'This meeting is closed to non-addicts. You should attend only if you believe that you may have a problem with substance abuse.', 'O'),
(5, 'CH', NULL, NULL, 'en', 'Closed Holidays', 'This meeting gathers in a facility that is usually closed on holidays.', 'FC3'),
(6, 'CL', NULL, 'CAN', 'en', 'Candlelight', 'This meeting is held by candlelight.', 'FC2'),
(7, 'CS', NULL, '', 'en', 'Children under Supervision', 'Well-behaved, supervised children are welcome.', 'FC3'),
(8, 'D', NULL, 'DISC', 'en', 'Discussion', 'This meeting invites participation by all attendees.', 'FC1'),
(9, 'ES', NULL, 'LANG', 'en', 'Español', 'This meeting is conducted in Spanish.', 'FC3'),
(10, 'GL', NULL, 'GL', 'en', 'Gay/Lesbian/Transgender', 'This meeting is focused on the needs of gay, lesbian and transgender members of NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'en', 'Illness', 'This meeting is focused on the needs of NA members with chronic illness.', 'FC1'),
(12, 'IP', NULL, 'IP', 'en', 'Informational Pamphlet', 'This meeting is focused on discussion of one or more Informational Pamphlets.', 'FC1'),
(13, 'IW', NULL, 'IW', 'en', 'It Works -How and Why', 'This meeting is focused on discussion of the It Works -How and Why text.', 'FC1'),
(14, 'JT', NULL, 'JFT', 'en', 'Just for Today', 'This meeting is focused on discussion of the Just For Today text.', 'FC1'),
(15, 'M', NULL, 'M', 'en', 'Men', 'This meeting is meant to be attended by men only.', 'FC3'),
(16, 'NC', NULL, NULL, 'en', 'No Children', 'Please do not bring children to this meeting.', 'FC3'),
(17, 'O', NULL, 'OPEN', 'en', 'Open', 'This meeting is open to addicts and non-addicts alike. All are welcome.', 'O'),
(18, 'Pi', NULL, NULL, 'en', 'Pitch', 'This meeting has a format that consists of each person who shares picking the next person.', 'FC1'),
(19, 'RF', NULL, 'VAR', 'en', 'Rotating Format', 'This meeting has a format that changes for each meeting.', 'FC1'),
(20, 'Rr', NULL, NULL, 'en', 'Round Robin', 'This meeting has a fixed sharing order (usually a circle.)', 'FC1'),
(21, 'SC', NULL, NULL, 'en', 'Surveillance Cameras', 'This meeting is held in a facility that has surveillance cameras.', 'FC2'),
(22, 'SD', NULL, 'SPK', 'en', 'Speaker/Discussion', 'This meeting is lead by a speaker, then opened for participation by attendees.', 'FC1'),
(23, 'SG', NULL, 'SWG', 'en', 'Step Working Guide', 'This meeting is focused on discussion of the Step Working Guide text.', 'FC1'),
(24, 'SL', NULL, NULL, 'en', 'ASL', 'This meeting provides an American Sign Language (ASL) interpreter for the deaf.', 'FC2'),
(26, 'So', NULL, 'SPK', 'en', 'Speaker Only', 'This meeting is a speaker-only meeting. Other attendees do not participate in the discussion.', 'FC1'),
(27, 'St', NULL, 'STEP', 'en', 'Step', 'This meeting is focused on discussion of the Twelve Steps of NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'en', 'Timer', 'This meeting has sharing time limited by a timer.', 'FC1'),
(29, 'To', NULL, 'TOP', 'en', 'Topic', 'This meeting is based upon a topic chosen by a speaker or by group conscience.', 'FC1'),
(30, 'Tr', NULL, 'TRAD', 'en', 'Tradition', 'This meeting is focused on discussion of the Twelve Traditions of NA.', 'FC1'),
(31, 'TW', NULL, 'TRAD', 'en', 'Traditions Workshop', 'This meeting engages in detailed discussion of one or more of the Twelve Traditions of N.A.', 'FC1'),
(32, 'W', NULL, 'W', 'en', 'Women', 'This meeting is meant to be attended by women only.', 'FC3'),
(33, 'WC', NULL, 'WCHR', 'en', 'Wheelchair', 'This meeting is wheelchair accessible.', 'FC2'),
(34, 'YP', NULL, 'Y', 'en', 'Young People', 'This meeting is focused on the needs of younger members of NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'en', 'Open-Ended', 'No fixed duration. The meeting continues until everyone present has had a chance to share.', 'FC1'),
(36, 'BK', NULL, 'LIT', 'en', 'Book Study', 'Approved N.A. Books', 'FC1'),
(37, 'NS', NULL, NULL, 'en', 'No Smoking', 'Smoking is not allowed at this meeting.', 'FC1'),
(38, 'Ag', NULL, NULL, 'en', 'Agnostic', 'Intended for people with varying degrees of Faith.', 'FC1'),
(39, 'FD', NULL, NULL, 'en', 'Five and Dime', 'Discussion of the Fifth Step and the Tenth Step', 'FC1'),
(40, 'AB', NULL, 'QA', 'en', 'Ask-It-Basket', 'A topic is chosen from suggestions placed into a basket.', 'FC1'),
(41, 'ME', NULL, 'MED', 'en', 'Meditation', 'This meeting encourages its participants to engage in quiet meditation.', 'FC1'),
(42, 'RA', NULL, 'RA', 'en', 'Restricted Attendance', 'This facility places restrictions on attendees.', 'FC3'),
(43, 'QA', NULL, 'QA', 'en', 'Question and Answer', 'Attendees may ask questions and expect answers from Group members.', 'FC1'),
(44, 'CW', NULL, 'CW', 'en', 'Children Welcome', 'Children are welcome at this meeting.', 'FC3'),
(45, 'CP', NULL, 'CPT', 'en', 'Concepts', 'This meeting is focused on discussion of the twelve concepts of NA.', 'FC1'),
(46, 'FIN', NULL, NULL, 'en', 'Finnish', 'finnish speaking meeting', 'FC3'),
(47, 'ENG', NULL, NULL, 'en', 'English speaking', 'This Meeting can be attended by speakers of English.', 'FC3'),
(48, 'PER', NULL, NULL, 'en', 'Persian', 'Persian speeking meeting', 'FC1'),
(49, 'L/R', NULL, NULL, 'en', 'Lithuanian/Russian', 'Lithuanian/Russian Speaking Meeting', 'FC1'),
(50, 'WEB', NULL, NULL, 'en', 'Online Meeting', 'This is a meeting that gathers on the Internet.', 'FC2'),
(51, 'LC', NULL, 'LC', 'en', 'Living Clean', 'This is a discussion of the NA book Living Clean -The Journey Continues.', NULL),
(1, 'B', NULL, 'BEG', 'es', 'Para el recién llegado', 'Esta reunión se centra en las necesidades de los nuevos miembros de NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'es', 'Bilingüe', 'Esta reunión se pueden asistir personas de que hablen inglés y otro idioma.', 'FC3'),
(3, 'BT', NULL, 'BT', 'es', 'Texto Básico', 'Esta reunión se centra en la discusión del texto básico de Narcóticos Anónimos.', 'FC1'),
(4, 'C', NULL, 'CLOSED', 'es', 'Cerrado', 'Esta reunión está cerrada a los no adictos. Usted debe asistir solamente si cree que puede tener un problema con abuso de drogas.', 'O'),
(5, 'CH', NULL, NULL, 'es', 'Cerrado en Días de fiesta', 'Esta reunión tiene lugar en una localidad que esta generalmente cerrada los días de fiesta.', 'FC3'),
(6, 'CL', NULL, 'CAN', 'es', 'Luz de vela', 'Esta reunión se celebra a luz de vela.', 'FC2'),
(7, 'CS', NULL, '', 'es', 'Niños bajo Supervisión', 'Los niños de buen comportamiento y supervisados son bienvenidos.', 'FC3'),
(8, 'D', NULL, 'DISC', 'es', 'Discusión', 'Esta reunión invita la participación de todos los asistentes.', 'FC1'),
(10, 'GL', NULL, 'GL', 'es', 'Gay/Lesbiana', 'Esta reunión se centra en las necesidades de miembros gay y lesbianas de NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'es', 'Enfermedad', 'Esta reunión se centra en las necesidades de los miembros de NA con enfermedades crónicas.', 'FC1'),
(12, 'IP', NULL, 'IP', 'es', 'Folleto Informativo', 'Esta reunión se centra en la discusión de unos o más folletos informativos.', 'FC1'),
(13, 'IW', NULL, 'IW', 'es', 'Functiona - Cómo y Porqué', 'Esta reunión se centra en la discusión del texto Funciona - Cómo y Porqué.', 'FC1'),
(14, 'JT', NULL, 'JFT', 'es', 'Solo por Hoy', 'Esta reunión se centra en la discusión del texto Solo por Hoy.', 'FC1'),
(15, 'M', NULL, 'M', 'es', 'Hombres', 'A esta reunión se supone que aistan hombres solamente.', 'FC3'),
(16, 'NC', NULL, NULL, 'es', 'No niños', 'Por favor no traer niños a esta reunión.', 'FC3'),
(17, 'O', NULL, 'OPEN', 'es', 'Abierta', 'Esta reunión está abierta a los adictos y a los no adictos por igual. Todos son bienvenidos.', 'O'),
(18, 'Pi', NULL, NULL, 'es', 'Echada', 'Esta reunión tiene un formato que consiste en que cada persona que comparta escoja a la persona siguiente.', 'FC1'),
(19, 'RF', NULL, 'VAR', 'es', 'Formato que Rota', 'Esta reunión tiene un formato que cambia para cada reunión.', 'FC1'),
(20, 'Rr', NULL, NULL, 'es', 'Round Robin', 'Esta reunión tiene un orden fijo de compartir (generalmente un círculo).', 'FC1'),
(21, 'SC', NULL, NULL, 'es', 'Cámaras de Vigilancia', 'Esta reunión se celebra en una localidad que tenga cámaras de vigilancia.', 'FC2'),
(22, 'SD', NULL, 'SPK', 'es', 'Orador/Discusión', 'Esta reunión es conducida por un orador, después es abierta para la participación de los asistentes.', 'FC1'),
(23, 'SG', NULL, 'SWG', 'es', 'Guia Para Trabajar los Pasos', 'Esta reunión se centra en la discusión del texto Guia Para Trabajar los Pasos.', 'FC1'),
(24, 'SL', NULL, NULL, 'es', 'ASL', 'Esta reunión proporciona intérprete (ASL) para los sordos.', 'FC2'),
(26, 'So', NULL, 'SPK', 'es', 'Solamente Orador', 'Esta reunión es de orador solamente. Otros asistentes no participan en la discusión.', 'FC1'),
(27, 'St', NULL, 'STEP', 'es', 'Paso', 'Esta reunión se centra en la discusión de los doce pasos de NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'es', 'Contador de Tiempo', 'Esta reunión tiene el tiempo de compartir limitado por un contador de tiempo.', 'FC1'),
(29, 'To', NULL, 'TOP', 'es', 'Tema', 'Esta reunión se basa en un tema elegido por el orador o por la conciencia del grupo.', 'FC1'),
(30, 'Tr', NULL, 'TRAD', 'es', 'Tradición', 'Esta reunión se centra en la discusión de las Doce Tradiciones de NA.', 'FC1'),
(31, 'TW', NULL, 'TRAD', 'es', 'Taller de las Tradiciones', 'Esta reunión consiste en la discusión detallada de una o más de las Doce Tradiciones de N.A.', 'FC1'),
(32, 'W', NULL, 'W', 'es', 'Mujeres', 'A esta reunión se supone que asistan mujeres solamente.', 'FC3'),
(33, 'WC', NULL, 'WCHR', 'es', 'Silla de Ruedas', 'Esta reunión es accesible por silla de ruedas.', 'FC2'),
(34, 'YP', NULL, 'Y', 'es', 'Jovenes', 'Esta reunión se centra en las necesidades de los miembros más jóvenes de NA.', 'FC3'),
(4, 'S', NULL, 'CLOSED', 'sv', 'Slutet möte', 'Ett slutet NA möte är för de individer som identifierar sig som beroende eller för de som är osäkra och tror att de kanske har drogproblem.', 'FC3'),
(15, 'M', NULL, 'M', 'sv', 'Mansmöte', 'Detta möte är endast öppet för män.', 'FC3'),
(17, 'Ö', NULL, 'OPEN', 'sv', 'Öppet möte', 'Ett öppet möte är ett NA-möte där vem som helst som är intresserad av hur vi har funnit tillfrisknande från beroendesjukdomen kan närvara.', 'FC3'),
(35, 'OE', NULL, NULL, 'es', 'Sin Tiempo Fijo', 'No tiene tiempo fijo. Esta reunión continua hasta que cada miembro haya tenido la oportunidad de compartir.', 'FC1'),
(47, 'ENG', NULL, NULL, 'sv', 'Engelska', 'Engelsktalande möte', 'FC3'),
(48, 'PER', NULL, NULL, 'sv', 'Persiskt', 'Persiskt möte', 'FC1'),
(32, 'K', NULL, 'W', 'sv', 'Kvinnomöte', 'Detta möte är endast öppet för kvinnor.', 'FC3'),
(33, 'RL', NULL, 'WCHR', 'sv', 'Rullstolsvänlig lokal', 'Detta möte är tillgängligt för rullstolsbundna.', 'FC2'),
(47, 'ENG', NULL, NULL, 'sv', 'Engelska', 'Engelsktalande möte', 'FC3'),
(1, 'B', NULL, 'BEG', 'fr', 'Débutants', 'Cette réunion est axée sur les besoins des nouveaux membres de NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'fr', 'bilingue', 'Cette réunion peut aider les personnes qui parlent l\'anglais et une autre langue.', 'FC3'),
(3, 'BT', NULL, 'BT', 'fr', 'Texte de Base', 'Cette réunion est axée sur la discussion du texte de base de Narcotiques Anonymes.', 'FC1'),
(4, 'C', NULL, 'CLOSED', 'fr', 'Fermée', 'Cette réunion est fermée aux non-toxicomanes. Vous pouvez y assister que si vous pensez que vous pouvez avoir un problème avec l\'abus de drogues.', 'O'),
(5, 'CH', NULL, NULL, 'fr', 'Fermé durant les jours fériés.', 'Cette réunion a lieu dans une local qui est généralement fermé durant les jours fériés.', 'FC3'),
(6, 'CL', NULL, 'CAN', 'fr', 'Chandelle', 'Cette réunion se déroule à la chandelle.', 'FC2'),
(7, 'CS', NULL, '', 'fr', 'Enfants sous Supervision', 'Les enfants bien élevés sont les bienvenus et supervisés.', 'FC3'),
(8, 'D', NULL, 'DISC', 'fr', 'Discussion', 'Cette réunion invite tous les participants à la discussion.', 'FC1'),
(10, 'GL', NULL, 'GL', 'fr', 'Gais, lesbiennes, transsexuel(le)s, bisexuel(le)s', 'Cette réunion est axée sur les besoins des membres gais, lesbiennes, transsexuel(le)s et bisexuel(le)s de NA.', 'FC3'),
(11, 'IL', NULL, NULL, 'fr', 'Chroniques', 'Cette réunion est axée sur les besoins des membres de NA comportant des troubles de maladies chroniques.', 'FC1'),
(12, 'IP', NULL, 'IP', 'fr', 'Brochures', 'Cette réunion est axée sur la discussion d\'une ou plusieurs brochures.', 'FC1'),
(13, 'IW', NULL, 'IW', 'fr', 'Ça marche, Comment et Pourquoi', 'Cette session met l\'accent sur la discussion de texte Ça marche, Comment et Pourquoi.', 'FC1'),
(14, 'JT', NULL, 'JFT', 'fr', 'Juste pour aujourd\'hui', 'Cette session met l\'accent sur la discussion du texte Juste pour aujourd\'hui.', 'FC1'),
(15, 'M', NULL, 'M', 'fr', 'Hommes', 'Cette réunion est destinée à être assisté par seulement que des hommes.', 'FC3'),
(16, 'NC', NULL, NULL, 'fr', 'Pas d\'enfant', 'S\'il vous plaît, ne pas amener les enfants à cette réunion.', 'FC3'),
(17, 'O', NULL, 'OPEN', 'fr', 'Ouvert', 'Cette réunion est ouverte aux toxicomanes et non-toxicomanes de même. Tous sont les bienvenus.', 'O'),
(18, 'Pi', NULL, NULL, 'fr', 'À la pige', 'Cette réunion a un format de discussion est que chaque personne qui discute invite la personne suivante à discuter.', 'FC1'),
(19, 'RF', NULL, 'VAR', 'fr', 'Format varié', 'Cette réunion a un format qui varie à toutes les réunions.', 'FC1'),
(20, 'Rr', NULL, NULL, 'fr', 'À la ronde', 'Cette réunion a un ordre de partage fixe (généralement un cercle).', 'FC1'),
(21, 'SC', NULL, NULL, 'fr', 'Caméra de surveillance', 'Cette réunion se tient dans un emplacement qui a des caméras de surveillance.', 'FC2'),
(22, 'SD', NULL, 'SPK', 'fr', 'Partage et ouvert', 'Cette réunion a un conférencier, puis ouvert au public.', 'FC1'),
(23, 'SG', NULL, 'SWG', 'fr', 'Guides des Étapes', 'Cette réunion est axée sur la discussion sur le Guide des Étapes.', 'FC1'),
(24, 'SL', NULL, NULL, 'fr', 'Malentendants', 'Cette rencontre permet l\'interprète pour les personnes malentendantes.', 'FC2'),
(26, 'So', NULL, 'SPK', 'fr', 'Partage seulement', 'Cette réunion a seulement un conférencier. Les autres participants ne participent pas à la discussion.', 'FC1'),
(27, 'St', NULL, 'STEP', 'fr', 'Étapes NA', 'Cette réunion est axée sur la discussion des Douze Étapes de NA.', 'FC1'),
(28, 'Ti', NULL, NULL, 'fr', 'Discussion chronométrée', 'Cette réunion a une durée de discussion  limitée par une minuterie pour chaque personne.', 'FC1'),
(29, 'To', NULL, 'TOP', 'fr', 'Thématique', 'Cette réunion est basée sur un thème choisi par la personne qui anime ou la conscience de groupe.', 'FC1'),
(30, 'Tr', NULL, 'TRAD', 'fr', 'Traditions', 'Cette réunion est axée sur la discussion des Douze Traditions de NA.', 'FC1'),
(31, 'TW', NULL, 'TRAD', 'fr', 'Atelier sur les traditions', 'Cette réunion est une discussion détaillée d\'une ou de plusieurs des Douze Traditions de NA', 'FC1'),
(32, 'W', NULL, 'W', 'fr', 'Femmes', 'Seulement les femmes sont admises.', 'FC3'),
(33, 'WC', NULL, 'WCHR', 'fr', 'Fauteuil Roulant', 'Cette réunion est accessible en fauteuil roulant.', 'FC2'),
(34, 'YP', NULL, 'Y', 'fr', 'Jeunes', 'Cette réunion est axée sur les besoins des plus jeunes membres de NA.', 'FC3'),
(35, 'OE', NULL, NULL, 'fr', 'Marathon', 'Il n\'y a pas de durée fixe. Cette réunion se poursuit jusqu\'à ce que chaque membre a eu l\'occasion de partager.', 'FC1'),
(36, 'BK', NULL, 'LIT', 'fr', 'Études de livres NA', 'Livres  N.A. Approuvés', 'FC1'),
(37, 'NS', NULL, NULL, 'fr', 'Non-fumeurs', 'Fumer n\'est pas permis à cette réunion.', 'FC1'),
(38, 'Ag', NULL, NULL, 'fr', 'Agnostique', 'Destiné aux personnes ayant divers degrés de la foi.', 'FC1'),
(39, 'FD', NULL, NULL, 'fr', 'Cinq et dix', 'Discussion de la cinquième étape et la dixième étape.', 'FC1'),
(40, 'AB', NULL, 'QA', 'fr', 'Panier', 'Un sujet est choisi parmi les suggestions placées dans un panier.', 'FC1'),
(41, 'ME', NULL, 'MED', 'fr', 'Méditation', 'Cette réunion encourage ses participants à s\'engager dans la méditation tranquille.', 'FC1'),
(42, 'RA', NULL, 'RA', 'fr', 'Accés limités', 'Cet emplacement impose des restrictions sur les participants.', 'FC3'),
(43, 'QA', NULL, 'QA', 'fr', 'Questions et Réponses', 'Les participants peuvent poser des questions et attendre des réponses des membres du groupe.', 'FC1'),
(44, 'CW', NULL, 'CW', 'fr', 'Enfants bienvenus', 'Les enfants sont les bienvenus à cette réunion.', 'FC3'),
(45, 'CP', NULL, 'CPT', 'fr', 'Concepts', 'Cette réunion est axée sur la discussion des douze concepts de NA.', 'FC1'),
(46, 'Finlandais', NULL, NULL, 'fr', 'Finlandais', 'Cette réunion se déroule en langue finlandaisè', 'FC3'),
(47, 'ENG', NULL, NULL, 'fr', 'Anglais', 'Cette réunion se déroule de langues anglais.', 'FC3'),
(50, 'WEB', NULL, NULL, 'fr', 'Internet', 'Il s\'agit d\'une réunion qui se déroule sur Internet.', 'FC2'),
(1, 'NV', NULL, NULL, 'it', 'Nuovi venuti', 'Riunione concentrata principalmente sulle necessità dei nuovi membri di NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'it', 'Bilingue', 'Questa riunione può essere frequentata da membri che parlano italiano e/o inglese.', 'FC3'),
(3, 'TB', NULL, NULL, 'it', 'Testo base', 'Riunione concentrata sulla discussione del testo base di NA.', 'FC1'),
(4, 'Ch.', NULL, NULL, 'it', 'Chiusa', 'Riunione chiusa ai non dipendenti. Dovrebbe frequentarla soltanto chi crede di avere un problema con le sostanze d\'abuso.', 'O'),
(5, 'SF', NULL, NULL, 'it', 'Sospesa nei giorni festivi', 'Questa riunione si tiene in locali che di solito sono chiusi nei giorni festivi e di vacanza.', 'FC3'),
(6, 'LC', NULL, NULL, 'it', 'Lume di candela', 'Questa riunione si tiene a lume di candela per favorire la meditazione.', 'FC2'),
(7, 'BS', NULL, NULL, 'it', 'Bambini sotto supervisione', 'Sono ammessi bambini senza problemi di comportamento e sotto supervisione.', 'FC3'),
(8, 'Disc.', NULL, NULL, 'it', 'Discussione', 'Tutti i partecipanti sono invitati a condividere.', 'FC1'),
(9, 'IT', NULL, NULL, 'it', 'Italiano', 'Riunione in lingua italiana.', 'FC3'),
(14, 'SPO', NULL, NULL, 'it', 'Solo per oggi', 'Riunione in cui si discutono i temi delle meditazioni quotidiane del libro "Solo per oggi".', 'FC1'),
(15, 'U', NULL, NULL, 'it', 'Uomini', 'Riunioni per soli uomini.', 'FC3'),
(17, 'Ap.', NULL, NULL, 'it', 'Aperta', 'Riunione aperta ai non dipendenti. Parenti, amici, professionisti e altri membri della società, sono benvenuti.', 'O'),
(23, 'GLP', NULL, NULL, 'it', 'Guida al lavoro sui passi', 'Riunione basata sulla discussione della Guida al lavoro sui Dodici passi di NA.', 'FC1'),
(28, 'Temp.', NULL, NULL, 'it', 'Condivisioni temporizzate', 'In queste riunioni il tempo di condivisione è limitato da un cronometro.', 'FC1'),
(27, 'P', NULL, NULL, 'it', 'Passi', 'Riunione di discussione sui Dodici passi.', 'FC1'),
(29, 'Arg.', NULL, NULL, 'it', 'Riunioni a tema', 'Queste riunioni si basano su un argomento prescelto.', 'FC1'),
(30, 'T', NULL, NULL, 'it', 'Tradizioni', 'Riunione di discussione sulle Dodici tradizioni.', 'FC1'),
(31, 'TW', NULL, NULL, 'it', 'Workshop sulle Dodici tradizioni', 'Riunioni in cui si discute dettagliatamente su una o più delle Dodici tradizioni.', 'FC1'),
(32, 'D', NULL, NULL, 'it', 'Donne', 'Riunione solo donne.', 'FC3'),
(33, 'SR', NULL, NULL, 'it', 'Sedia a rotelle', 'Riunione accessibile per chi ha la sedia a rotelle.', 'FC2'),
(35, 'M', NULL, NULL, 'it', 'Maratona', 'Durata non prestabilita. La riunione prosegue finché tutti i presenti hanno da condividere.', 'FC1'),
(37, 'NF', NULL, NULL, 'it', 'Non fumatori', 'In queste riunioni non è consentito fumare.', 'FC1'),
(40, 'TS', NULL, NULL, 'it', 'Tema a sorpresa', 'L\'argomento su cui condividere è scritto su un biglietto o altro supporto (es. un bastoncino di legno) ed estratto a caso da ciascun membro.', 'FC1'),
(42, 'M', NULL, NULL, 'it', 'Meditazione', 'In questa riunione sono poste restrizioni alle modalità di partecipazione.', 'FC3'),
(43, 'D/R', NULL, NULL, 'it', 'Domande e risposteq', 'I partecipanti possono fare domande e attenderne la risposta dagli altri membri del gruppo.', 'FC1'),
(44, 'Ba', NULL, NULL, 'it', 'Bambini', 'I bambini sono benvenuti in queste riunioni.', 'FC3'),
(45, 'C', NULL, NULL, 'it', 'Concetti di servizio', 'Riunioni basate sulla discussione dei Dodici concetti per il servizio in NA.', 'FC1'),
(50, 'WEB', NULL, NULL, 'it', 'Riunione online', 'Riunione che si svolge via Internet (es. Skype, Hangouts o altri sistemi tipo chat o IM in generale).', 'FC2'),
(51, 'VP', NULL, NULL, 'it', 'Vivere puliti', 'Riunioni di discussione sul libro "Vivere puliti - Il viaggio continua".', 'FC1');

