INSERT INTO `%%PREFIX%%_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'NV', NULL, NULL, 'it', 'Nuovi venuti', 'Riunione concentrata principalmente sulle necessità dei nuovi membri di NA.', 'FC3'),
(2, 'BL', NULL, 'LANG', 'it', 'Bilingue', 'Questa riunione può essere frequentata da membri che parlano italiano e/o inglese.', 'LANG'),
(3, 'TB', NULL, NULL, 'it', 'Testo base', 'Riunione concentrata sulla discussione del testo base di NA.', 'FC1'),
(4, 'Ch.', NULL, NULL, 'it', 'Chiusa', 'Riunione chiusa ai non dipendenti. Dovrebbe frequentarla soltanto chi crede di avere un problema con le sostanze d\'abuso.', 'O'),
(5, 'SF', NULL, NULL, 'it', 'Sospesa nei giorni festivi', 'Questa riunione si tiene in locali che di solito sono chiusi nei giorni festivi e di vacanza.', 'FC3'),
(6, 'LC', NULL, NULL, 'it', 'Lume di candela', 'Questa riunione si tiene a lume di candela per favorire la meditazione.', 'FC2'),
(7, 'BS', NULL, NULL, 'it', 'Bambini sotto supervisione', 'Sono ammessi bambini senza problemi di comportamento e sotto supervisione.', 'FC3'),
(8, 'Disc.', NULL, NULL, 'it', 'Discussione', 'Tutti i partecipanti sono invitati a condividere.', 'FC1'),
(9, 'ES', NULL, 'LANG', 'it', 'Spagnolo', 'Riunione in lingua spagnolo.', 'FC3'),
(14, 'SPO', NULL, NULL, 'it', 'Solo per oggi', 'Riunione in cui si discutono i temi delle meditazioni quotidiane del libro "Solo per oggi".', 'FC1'),
(15, 'U', NULL, NULL, 'it', 'Uomini', 'Riunioni per soli uomini.', 'FC3'),
(17, 'Ap.', NULL, NULL, 'it', 'Aperta', 'Riunione aperta ai non dipendenti. Parenti, amici, professionisti e altri membri della società, sono benvenuti.', 'O'),
(23, 'GLP', NULL, NULL, 'it', 'Guida al lavoro sui passi', 'Riunione basata sulla discussione della Guida al lavoro sui Dodici passi di NA.', 'FC1'),
(28, 'Temp.', NULL, NULL, 'it', 'Condivisioni temporizzate', 'In queste riunioni il tempo di condivisione è limitato da un cronometro.', 'FC1'),
(27, 'P', NULL, NULL, 'it', 'Passi', 'Riunione di discussione sui Dodici passi.', 'FC1'),
(29, 'Arg.', NULL, NULL, 'it', 'Riunioni a tema', 'Queste riunioni si basano su un argomento prescelto.', 'FC1'),
(30, 'T', NULL, NULL, 'it', 'Tradizioni', 'Riunione di discussione sulle Dodici tradizioni.', 'FC1'),
(31, 'TW', NULL, NULL, 'it', 'Workshop sulle Dodici tradizioni', 'Riunioni in cui si discute dettagliatamente su una o più delle Dodici tradizioni.', 'FC1'),
(32, 'D', NULL, NULL, 'it', 'Donne', 'Riunione solo donne.', 'FC3'),
(33, 'SR', NULL, NULL, 'it', 'Sedia a rotelle', 'Riunione accessibile per chi ha la sedia a rotelle.', 'FC2'),
(35, 'M', NULL, NULL, 'it', 'Maratona', 'Durata non prestabilita. La riunione prosegue finché tutti i presenti hanno da condividere.', 'FC1'),
(37, 'NF', NULL, NULL, 'it', 'Non fumatori', 'In queste riunioni non è consentito fumare.', 'FC1'),
(40, 'TS', NULL, NULL, 'it', 'Tema a sorpresa', 'L\'argomento su cui condividere è scritto su un biglietto o altro supporto (es. un bastoncino di legno) ed estratto a caso da ciascun membro.', 'FC1'),
(42, 'M', NULL, NULL, 'it', 'Meditazione', 'In questa riunione sono poste restrizioni alle modalità di partecipazione.', 'FC3'),
(43, 'D/R', NULL, NULL, 'it', 'Domande e risposteq', 'I partecipanti possono fare domande e attenderne la risposta dagli altri membri del gruppo.', 'FC1'),
(44, 'Ba', NULL, NULL, 'it', 'Bambini', 'I bambini sono benvenuti in queste riunioni.', 'FC3'),
(45, 'C', NULL, NULL, 'it', 'Concetti di servizio', 'Riunioni basate sulla discussione dei Dodici concetti per il servizio in NA.', 'FC1'),
(51, 'VP', NULL, NULL, 'it', 'Vivere puliti', 'Riunioni di discussione sul libro "Vivere puliti - Il viaggio continua".', 'FC1'),
(54, 'VM', NULL, 'VM', 'it', 'Virtual Meeting', 'Meets Virtually', 'FC2'),
(55, 'TC', NULL, 'TC', 'it', 'Temporarily Closed', 'Facility is Temporarily Closed', 'FC2'),
(56, 'HY', NULL,  'HYBR', 'it', 'Hybrid Meeting', 'Meets Virtually and In-person', 'FC2');