INSERT INTO `%%PREFIX%%_comdef_formats` (`shared_id_bigint`, `key_string`, `icon_blob`, `worldid_mixed`, `lang_enum`, `name_string`, `description_string`, `format_type_enum`) VALUES
(1, 'RC', NULL, 'BEG', 'pt', 'Recém-chegados', 'Esta reunião tem foco nas necessidades de novos membros em NA.', 'FC3'),
(2, 'BL', NULL, NULL, 'pt', 'Bilíngue', 'Reunião pode acontecer em duas línguas além de Português.', 'FC3'),
(3, 'TB', NULL, 'BT', 'pt', 'Texto Básico', 'Esta reunião tem foco no debate sobre o Texto Básico de Narcóticos Anônimos.', 'FC1'),
(4, 'F', NULL, 'CLOSED', 'pt', 'Fechada', 'Esta reunião fechada para não adictos. Você deve ir apenas se acredita ter problemas com abuso de substâncias.', 'O'),
(5, 'FF', NULL, 'CH', 'pt', 'Fechada em feriados', 'Esta reunião acontece em local que geralmente é fechado em feirados.', 'FC3'),
(6, 'VL', NULL, 'CAN', 'pt', 'Luz de velas', 'Esta reunião acontece à luz de velas.', 'FC2'),
(7, 'CA', NULL, '', 'pt', 'Criança sob supervisão', 'Bem-comportadas, crianças sob supervisão são bem-vindas.', 'FC3'),
(8, 'D', NULL, 'DISC', 'pt', 'Discussão', 'Esta reunião convida a participação de todos.', 'FC1'),
(9, 'ES', NULL, 'LANG', 'pt', 'Espanhol', 'Esta reunião acontece em Espanhol.', 'FC3'),
(10, 'LGBT', NULL, 'GL', 'pt', 'LGBTQ+', 'Reunião de interesse LGBTQ+ em NA.', 'FC3'),
(11, 'DC', NULL, NULL, 'pt', 'Doença Crônica', 'Esta reunião tem foco nos interesses especiais de pessoas sofrendo de doenças crônicas.', 'FC1'),
(12, 'IP', NULL, 'PI', 'pt', 'Panfleto Informativo', 'Esta reunião tem foco na discussão sobre um ou mais IPs ou Panfletos Informativos.', 'FC1'),
(13, 'FUN', NULL, 'IW', 'pt', 'Funciona - Como e Por quê', 'Esta reunião tem foco na discussão do texto do livro Funciona - Como e Por quê.', 'FC1'),
(14, 'SPH', NULL, 'JFT', 'pt', 'Só Por Hoje', 'Esta reunião tem foco na discussão do texto do livro Só Por Hoje.', 'FC1'),
(15, 'H', NULL, 'M', 'pt', 'Homens', 'Reunião de interesse masculino em NA', 'FC3'),
(16, 'PC', NULL, 'NC', 'pt', 'Proibido crianças', 'Por gentileza não trazer crianças a essa reunião.', 'FC3'),
(17, 'A', NULL, 'OPEN', 'pt', 'Aberta', 'Esta reunião é aberta para adictos e não-adictos. Todos são bem-vindos.', 'O'),
(18, 'Ind', NULL, NULL, 'pt', 'Indicação', 'Esta reunião tem um formato que consiste que cada pessoa que partilha escolhe a próxima pessoa a partilhar.', 'FC1'),
(19, 'FR', NULL, 'VAR', 'pt', 'Formato Rotativo', 'Esta reunião muda seu formato a cada reunião.', 'FC1'),
(20, 'Rr', NULL, NULL, 'pt', 'Round Robin', 'Esta reunião tem um formato fixo de partilha (geralmente em círculo.)', 'FC1'),
(21, 'CV', NULL, NULL, 'pt', 'Câmera de vigilância', 'Esta reunião acontece em ambiente que tem câmeras de vigilância.', 'FC2'),
(22, 'TD', NULL, 'S-D', 'pt', 'Temática/Discussão', 'Esta reunião tem um orador, em seguida é aberta a participação dos membros', 'FC1'),
(23, 'EP', NULL, 'SWG', 'pt', 'Estudo de Passos', 'Esta reunião é de estudo dos passos através do Guia Para Trabalhar os Passos de NA.', 'FC1'),
(24, 'LS', NULL, NULL, 'pt', 'LSB', 'Esta reunião acontece com ajuda de intérprete de LIBRAS (Língua Brasileira de Sinais).', 'FC2'),
(26, 'TM', NULL, 'SPK', 'pt', 'Temática', 'Esta reunião é do tipo temática. Não há participação dos membros na discussão.', 'FC1'),
(27, 'PS', NULL, 'STEP', 'pt', 'Passos', 'Esta reunião é de discussão dos 12 Passos de NA.', 'FC1'),
(28, 'TP', NULL, NULL, 'pt', 'Tempo de Partilha', 'Esta reunião tem seu tempo de partilha controlado por relógio.', 'FC1'),
(29, 'To', NULL, 'TOP', 'pt', 'Tópico', 'Esta reunião é baseada em tópico escolhida por um orador ou por consciência de grupo.', 'FC1'),
(30, 'Tr', NULL, 'TRAD', 'pt', 'Tradições', 'Esta reunião tem foco em discussão das 12 Tradições de NA.', 'FC1'),
(31, 'TW', NULL, 'TRAD', 'pt', 'Workshop de Tradições', 'Esta reunião envolve uma discussão mais detalhada de uma ou mais das Tradições de N.A.', 'FC1'),
(32, 'M', NULL, 'W', 'pt', 'Mulheres', 'Reunião de interesse feminino em NA.', 'FC3'),
(33, 'CadT', NULL, 'WCHR', 'pt', 'Cadeirante Total', 'Esta reunião tem acesso total a cadeirantes.', 'FC2'),
(34, 'Jv', NULL, 'Y', 'pt', 'Jovens', 'Esta reunião tem foco nos interesses de membros jovens em NA.', 'FC3'),
(35, 'UP', NULL, NULL, 'pt', 'Último Partilhar', 'Sem duração fixa. A reunião continua até todos os presentes partilharem.', 'FC1'),
(36, 'EL', NULL, 'LIT', 'pt', 'Estudo de Literatura', 'Reunião de estudo de literaturas aprovadas de NA', 'FC1'),
(37, 'NF', NULL, 'NS', 'pt', 'Proibido Fumar', 'Não é permitido fumar nessa reunião.', 'FC1'),
(38, 'Ag', NULL, NULL, 'pt', 'Agnóstico', 'Destinada a pessoas com diferentes graus de fé.', 'FC1'),
(39, 'QD', NULL, NULL, 'pt', 'Quinto e Décimo', 'Reunião de discussão sobre o Quinto e Décimo Passos', 'FC1'),
(40, 'ST', NULL, 'QA', 'pt', 'Sorteio de Tópico', 'Um tópico é escolhido através de sugestões sorteadas.', 'FC1'),
(41, 'ME', NULL, 'MED', 'pt', 'Meditação', 'Esta reunião incentiva seus participantes a se envolverem em meditação silenciosa.', 'FC1'),
(42, 'AR', NULL, 'RA', 'pt', 'Acesso Restrito', 'Esta reunião esta em local que impõe restrição de acesso às pessoas.', 'FC3'),
(43, 'PR', NULL, 'QA', 'pt', 'Perguntas e Respostas', 'Os participantes podem fazer perguntas e esperar respostas dos membros do grupo.', 'FC1'),
(44, 'PC', NULL, 'CW', 'pt', 'Permitido Crianças', 'Crianças são bem-vindas a essa reunião.', 'FC3'),
(45, 'Con', NULL, 'CPT', 'pt', 'Conceitos', 'Esta reunião tem foco na discussão dos Doze Conceitos de NA.', 'FC1'),
(46, 'FIN', NULL, NULL, 'pt', 'Filandês', 'Reunião em língua filandesa', 'FC3'),
(47, 'ENG', NULL, NULL, 'pt', 'Inglês', 'Reunião em língua inglesa.', 'FC3'),
(48, 'PER', NULL, NULL, 'pt', 'Persa', 'Reunião em língua persa', 'FC1'),
(49, 'L/R', NULL, NULL, 'pt', 'Lituano/Russo', 'Reunião em Lituano/Russo', 'FC1'),
(51, 'VL', NULL, 'LC', 'pt', 'Vivendo Limpo', 'Esta é uma reunião de discussão do livro Vivendo Limpo-A Jornada Continua.', 'FC1'),
(52, 'GP', NULL, 'GP', 'pt', 'Guia de Princípios', 'Esta é uma reunião baseada no livro Guia de Princípios - O Espírito das Nossas Tradições .', 'FC1'),
(53, 'CadP', NULL, 'WCHR', 'pt', 'Cadeirante Parcial', 'Esta reunião tem acesso parcial a cadeirante.', 'FC2'),
(54, 'VM', NULL, 'VM', 'pt', 'Virtual Meeting', 'Meets Virtually', 'FC2'),
(55, 'TC', NULL, 'TC', 'pt', 'Temporarily Closed', 'Facility is Temporarily Closed', 'FC2'),
(56, 'HY', NULL,  'HYBR', 'pt', 'Hybrid Meeting', 'Meets Virtually and In-person', 'FC2');