name: BMLT Docker Builds

on:
  schedule:
    - cron:  '0 12 * * 0'
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Base
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./docker
          file: ./docker/Dockerfile-base
          platforms: linux/amd64,linux/arm64/v8
          tags: bmltenabled/bmlt-root-server-base:latest
          push: true

  build-db:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.2.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push DB
        uses: docker/build-push-action@v3.2.0
        with:
          context: ./docker
          file: ./docker/Dockerfile-db
          platforms: linux/amd64,linux/arm64/v8
          tags: bmltenabled/bmlt-root-server-sample-db:latest
          push: true
