name: BMLT Docker Builds

on:
  schedule:
    - cron:  '0 12 * * 0'
  workflow_dispatch:

jobs:
  build-base:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        php_version: [8.2, 8.3, 8.4]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: bmltenabled/bmlt-root-server-base
          tags: |
            type=raw,value=${{ matrix.php_version }}
            type=raw,value=latest,enable=${{ matrix.php_version == '8.2' }}
          labels: |
            org.opencontainers.image.title=BMLT Root Server Base (PHP ${{ matrix.php_version }})
            org.opencontainers.image.description=Base image for BMLT Root Server with PHP ${{ matrix.php_version }}
            org.opencontainers.image.vendor=BMLT
            org.opencontainers.image.created={{date 'YYYY-MM-DDTHH:mm:ssZ'}}
            org.opencontainers.image.version=${{ matrix.php_version }}
            php.version=${{ matrix.php_version }}

      - name: Build and push Base
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./docker
          file: ./docker/Dockerfile-base
          platforms: linux/amd64,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            PHP_VERSION=${{ matrix.php_version }}
          push: true

  build-db:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push DB
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./docker
          file: ./docker/Dockerfile-db
          platforms: linux/amd64,linux/arm64/v8
          tags: bmltenabled/bmlt-root-server-sample-db:latest
          push: true
