name: 'main'
on:
  push:
    branches: [ '3.0.0' ]

jobs:
  build-latest:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Make Root Server Build
        run: |
          make build-zip
          ZIP_FILENAME=bmlt-root-server-3.0.0-build${GITHUB_RUN_NUMBER}-${GITHUB_SHA}.zip
          echo "ZIP_FILENAME=${ZIP_FILENAME}" >> $GITHUB_ENV

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions/gh-ci-s3-artifact
          role-session-name: gh-actions
          aws-region: us-east-1

      - name: copy artifacts to s3
        run: |
          aws s3 cp build/$ZIP_FILENAME s3://${{ secrets.S3_BUCKET }}/bmlt-root-server/$ZIP_FILENAME
